### PR TITLE
#2413 Carnation display Content paragraphs 

### LINKED ISSUE #2413: News Posts only show "Image & Description" Fields in Content Area
**Issue Description:**
This issue was brought to my attention by ymcagreenville.org.  When adding any paragraph to the "Content Area" of a News Post, it doesn't actually display on the node.  The Image & Description fields show, but nothing else in the Content Area.

Using the sandbox website as an example: https://sandbox-carnation-cus.openy.org/news/learn-about-camp-terrys-history. I have only tested this in Carnation.

image

**Proposed Solution:**
`/openy_carnation/templates/node/news/node--news--full.html.twig`
Update News Posts template to print out the contents `{{ content.field_content }}` on line 100, just below the description field.  

**Notes:**
In looking further, it appears that the Blog and Events content type templates also omit the contents of "Content Area" besides the defined field.  

`./openy_carnation/templates/node/event/node--event--full.html.twig`
`./openy_carnation/templates/node/blog/node--blog--full.html.twig`

So it's possible this is not an issue, but rather a feature request.  Which is why I'm submitting it here first.  Thanks!

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: #2413

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] On Carnation: check paragraphs rendered under description field for news, blog, event CTs.
News
image
Blog
image
Event
image

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3115/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3115/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3115/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3116/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3116/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3116/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3117/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3117/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3117/

**Review by hamrant — APPROVED** [review]
Tested on http://upgrade.openy.cibox.tools/build3116 - works as expected

**Pull request merged**
