### PR TITLE
Update colors as per YMCA Brand guidelines

### PR DESCRIPTION
**Pull request by froboy**
This is not related to an open issue.

## Steps for review

- [ ] Install Open Y OR
- [ ] `drush mim --group=openy_demo_term`
- [ ] visit /admin/structure/taxonomy/manage/color/overview
- [ ] observe the colors match those of the [Brand Guidelines](https://theybrand.org/wordpress/brand-graphics-color-usage) (Login required)

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by froboy** [comment]
Related D.o issue: https://www.drupal.org/project/openy/issues/3163871

**Comment by podarok** [comment]
@froboy - what about Accessibility and upgrade path?
I remember there were issues with accessibility for the Brand colors
/cc @YMCA-GTC @ymcagtc @paige-kiecker

**Comment by froboy** [comment]
@podarok I didn't do accessibility checks as I wasn't sure how we got to these in the first place. My hangup is that the current lis uses similar/same names for brand colors but they are... different. From my own personal standpoint (as an Open Y user, not representing Y-USA), I'd say if we are able to check for compliance with these then we should stick to brand colors but only allow those that are compliant, then maybe add some clearly defined off-brand colors.

**Comment by froboy** [comment]
I've discussed this in length with the Open Y team and realize this didn't take into account a number of requirements. Closing the issue for the time being.

**Pull request closed without merging**
