### PR TITLE
[OYPD-601] Ability to edit blog title bars in CMS editor.

### PR DESCRIPTION
**Pull request by fandm**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Jira ticket

https://propeople-us.atlassian.net/browse/OYPD-601

## Steps for review

- [x] Login as admin.
- [x] Edit or add some landing page, branch and camp nodes and edit/add paragraphs: `Blog Posts Listing`, `Latest Blog Posts`, `Latest Blog Posts (branch)` and `Latest Blog Posts (camp)`.
- [x] Set the value for the new field `Title` of each paragraph.
- [x] Save changes, view the node and verify that title looks as expected.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2366 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2366 |
| Installation process | http://install.openy-dev.ffwua.com/build2366/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2366/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2366/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2366/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2366/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2366/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2366/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2366/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2367 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2367 |
| Installation process | http://install.openy-dev.ffwua.com/build2367/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2367/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2367/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2367/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2367/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2367/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2367/blogWCAG2AAhtmlcs.txt

**Review by alexschedrov — DISMISSED** [review]
Code looks good. Needs testing. @AlexNetman please test on fresh installation as well as on upgrade path.

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2367/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
On UPGRADE env those paragraphs are not having Title fields: 

image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2369 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2369 |
| Installation process | http://install.openy-dev.ffwua.com/build2369/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2369/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2369/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2369/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2369/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2369/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2369/blogWCAG2AAhtmlcs.txt

**Comment by fandm** [comment]
> On UPGRADE env those paragraphs are not having Title fields

Fixed.
@AlexNetman Also please note that `Featured Blog Posts` was not mentioned in the ticket https://propeople-us.atlassian.net/browse/OYPD-601 So I had done nothing with this paragraph.

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2369/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2372 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2372 |
| Installation process | http://install.openy-dev.ffwua.com/build2372/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2372/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2372/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2372/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2372/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2372/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2372/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2372/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@fandm Let's also add this for `Featured Blog Posts`. It seems it was missed in the original description.

**Comment by alexschedrov** [comment]
@fandm @AlexNetman turns out that `Featured blog posts` already have headline field. Ready to be tested.

**Review by AlexNetman — APPROVED** [review]

**Pull request merged**
