### PR TITLE
[OYPD-321] Behat function for filling complex fields.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-321
D.o https://www.drupal.org/node/2861346

Steps to review:
Current tests do not use this context. Documentation has been added to describe how to create tests using this context. The following examples created to test:
```
Background: Log in & create background content
  Given I am logged in as a user with the "Administrator" role
  And I create "taxonomy_term" of type "color" with key for reference:
    | KEY  | name | field_color |
    | Blue | Blue | 0000FF      |
    | Red  | Red  | FF0000      |
  And I create "paragraph" of type "small_banner" with key for reference:
    | KEY     | field_prgf_headline | field_prgf_color |
    | banner1 | Banner 1            | Blue             |
    | banner2 | Banner 2            | Red              |
  And I create "media" of type "image" with key for reference:
    | KEY     | name    | field_media_image |
    | image1  | Image 1 | gallery.png       |
  And I create large "landing_page" content:
    | KEY             | test_landing_1  | test_landing_2  |
    | title           | Test Landing 01 | Test Landing 02 |
    | field_lp_layout | one_column      | one_column      |
    | field_content   | banner1         | banner2         |
  And I create large "landing_page" content:
    | title           | Test Landing 03  |
    | field_lp_layout | one_column       |
    | field_content   | banner1, banner2 |
  And I create nodes "landing_page" content:
    | title           | field_lp_layout | field_content    |
    | Test Landing 04 | one_column      | banner1, banner2 |
    | Test Landing 05 | one_column      | banner1          |

Scenario: I find and visit Test Landing
  Given I go to "/admin/content"
  And I should see "Test Landing 03"
  And I click "Test Landing 03"
  And I should see "Banner 1"
  And I should see "Banner 2"

Scenario: I visit my new node
  Given I view a "landing_page" content:
    | title           | Test Landing         |
    | field_lp_layout | one_column           |
    | field_content   | banner1 |
  And I should see "Banner 1"

  Scenario: Branch address visibility
    When I view a "branch" content:
      | title                               | Branch Two   |
      | field_location_address:country_code | US           |
      | :address_line1                      | Main road 10 |
      | :locality                           | Seattle      |
      | :administrative_area                | WA           |
      | :postal_code                        | 98101        |
      | field_location_coordinates:lat      | 47.293433    |
      | :lng                                | -122.238717  |
      | field_location_phone                | +1234567890  |
    Then I should see "Branch Two"
    And I should see "Main road 10"
```

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build760 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build760 |
| Installation process | http://install.openy-dev.ffwua.com/build760/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/760/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build760/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build762 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build762 |
| Installation process | http://install.openy-dev.ffwua.com/build762/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/762/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build762/profiles/contrib/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Pull request merged**
