### PR TITLE
[OYPD-475] Break out class and session demo content migrations for in…

### PR DESCRIPTION
**Pull request by Kerby70**
…stall performance.

Jira https://propeople-us.atlassian.net/browse/OYPD-475
D.o https://www.drupal.org/node/2884206

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [x] PHP 7.1
- [x] Max execution time = 30
- [x] /core/install.php
- [x] Include all content migration options
- [x] No max execution error
- [x] Other ways to install still work & have demo content expected.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1354 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1354 |
| Installation process | http://install.openy-dev.ffwua.com/build1354/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1354/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1354/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1355 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1355 |
| Installation process | http://install.openy-dev.ffwua.com/build1355/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1355/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1355/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Comment by alexschedrov** [comment]
On build we have error :(
image

**Comment by Kerby70** [comment]
@Sanchiz I'm not able to replicate this error locally.

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1367 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1367 |
| Installation process | http://install.openy-dev.ffwua.com/build1367/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1367/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1367/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1370 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1370 |
| Installation process | http://install.openy-dev.ffwua.com/build1370/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1370/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1370/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1374 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1374 |
| Installation process | http://install.openy-dev.ffwua.com/build1374/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1374/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1374/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1375 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1375 |
| Installation process | http://install.openy-dev.ffwua.com/build1375/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1375/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1375/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@Kerby70 I can go through installtion now! However there are some regressions in comparison to latest demo version:
- When I openy class with Location popup paragraph
- Then click on "Edit"
- Nothing happens (assumption Location popup should be visible)
- Also when I manually remove location=% from URL, "Edit" button doesn't appear

https://www.screencast.com/t/XhPcU4hILXD3

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1386 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1386 |
| Installation process | http://install.openy-dev.ffwua.com/build1386/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1386/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1386/profiles/contrib/openy/build/reports/behat

**Pull request merged**
