### PR TITLE
[OYPD-498] Adjustments to class pages for H tag changes

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Verify changes to class pages according to OYPD-498 task.

I added the H1 tag for the page, and switch the class listing title to H2. In doing so, I chose not to adjust the CSS. Since it is main page content I think it should follow the basic style guide of how h1 and h2 is handled instead of making style overrides for just these pages. Because of that, the sub title gets a larger font. If that is really not desired, I can change it.

The attached picture shows this. The H1 is 40px, the H2 is 36px.

screen shot 2017-06-23 at 4 54 51 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1714 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1714 |
| Installation process | http://install.openy-dev.ffwua.com/build1714/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1714/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1714

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1714

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1714/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1721/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #615 of commit ddcb25e763980bda6ab6cade02dba28c94eb90e8 automatically merged.
GitHub pull request #615 of commit ddcb25e763980bda6ab6cade02dba28c94eb90e8 automatically merged.
GitHub pull request #615 of commit ddcb25e763980bda6ab6cade02dba28c94eb90e8 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git4156003884976450641.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git2636999907041788445.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/615/merge^{commit} # timeout=10
 > git branch -a --contains 3982793b531a35a9003f71c6241a7f3a9e24c223 # timeout=10
 > git rev-parse remotes/origin/pr/615/merge^{commit} # timeout=10
Checking out Revision 3982793b531a35a9003f71c6241a7f3a9e24c223 (origin/pr/615/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 3982793b531a35a9003f71c6241a7f3a9e24c223
First time build. Skipping changelog.
Waiting for the completion of SERVER_CLEANER_FIFO
SERVER_CLEANER_FIFO #84 completed. Result was SUCCESS
Build step 'Trigger/call builds on other projects' changed build result to SUCCESS
[workspace] $ /bin/sh -xe /tmp/hudson4476751333150172562.sh
+ rm -Rf /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ cp -R ../vm /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
From github.com:propeoplemd/openy_vm
   ce3ae8d..b0a8a31  master     -> origin/master
Updating ce3ae8d..b0a8a31
Fast-forward
 .../libraries/colordialog/dialogs/colordialog.css  |   20 +
 .../libraries/colordialog/dialogs/colordialog.js   |  343 +++
 docroot/libraries/colordialog/lang/af.js           |   11 +
 docroot/libraries/colordialog/lang/ar.js           |   11 +
 docroot/libraries/colordialog/lang/az.js           |   11 +
 docroot/libraries/colordialog/lang/bg.js           |   11 +
 docroot/libraries/colordialog/lang/bn.js           |   11 +
 docroot/libraries/colordialog/lang/bs.js           |   11 +
 docroot/libraries/colordialog/lang/ca.js           |   11 +
 docroot/libraries/colordialog/lang/cs.js           |   11 +
 docroot/libraries/colordialog/lang/cy.js           |   11 +
 docroot/libraries/colordialog/lang/da.js           |   11 +
 docroot/libraries/colordialog/lang/de-ch.js        |   11 +
 docroot/libraries/colordialog/lang/de.js           |   11 +
 docroot/libraries/colordialog/lang/el.js           |   11 +
 docroot/libraries/colordialog/lang/en-au.js        |   11 +
 docroot/libraries/colordialog/lang/en-ca.js        |   11 +
 docroot/libraries/colordialog/lang/en-gb.js        |   11 +
 docroot/libraries/colordialog/lang/en.js           |   11 +
 docroot/libraries/colordialog/lang/eo.js           |   11 +
 docroot/libraries/colordialog/lang/es.js           |   11 +
 docroot/libraries/colordialog/lang/et.js           |   11 +
 docroot/libraries/colordialog/lang/eu.js           |   11 +
 docroot/libraries/colordialog/lang/fa.js           |   11 +
 docroot/libraries/colordialog/lang/fi.js           |   11 +
 docroot/libraries/colordialog/lang/fo.js           |   11 +
 docroot/libraries/colordialog/lang/fr-ca.js        |   11 +
 docroot/libraries/colordialog/lang/fr.js           |   11 +
 docroot/libraries/colordialog/lang/gl.js           |   11 +
 docroot/libraries/colordialog/lang/gu.js           |   11 +
 docroot/libraries/colordialog/lang/he.js           |   11 +
 docroot/libraries/colordialog/lang/hi.js           |   11 +
 docroot/libraries/colordialog/lang/hr.js           |   11 +
 docroot/libraries/colordialog/lang/hu.js           |   11 +
 docroot/libraries/colordialog/lang/id.js           |   11 +
 docroot/libraries/colordialog/lang/is.js           |   11 +
 docroot/libraries/colordialog/lang/it.js           |   11 +
 docroot/libraries/colordialog/lang/ja.js           |   11 +
 docroot/libraries/colordialog/lang/ka.js           |   11 +
 docroot/libraries/colordialog/lang/km.js           |   11 +
 docroot/libraries/colordialog/lang/ko.js           |   11 +
 docroot/libraries/colordialog/lang/ku.js           |   11 +
 docroot/libraries/colordialog/lang/lt.js           |   11 +
 docroot/libraries/colordialog/lang/lv.js           |   11 +
 docroot/libraries/colordialog/lang/mk.js           |   11 +
 docroot/libraries/colordialog/lang/mn.js           |   11 +
 docroot/libraries/colordialog/lang/ms.js           |   11 +
 docroot/libraries/colordialog/lang/nb.js           |   11 +
 docroot/libraries/colordialog/lang/nl.js           |   11 +
 docroot/libraries/colordialog/lang/no.js           |   11 +
 docroot/libraries/colordialog/lang/oc.js           |   11 +
 docroot/libraries/colordialog/lang/pl.js           |   11 +
 docroot/libraries/colordialog/lang/pt-br.js        |   11 +
 docroot/libraries/colordialog/lang/pt.js           |   11 +
 docroot/libraries/colordialog/lang/ro.js           |   11 +
 docroot/libraries/colordialog/lang/ru.js           |   11 +
 docroot/libraries/colordialog/lang/si.js           |   11 +
 docroot/libraries/colordialog/lang/sk.js           |   11 +
 docroot/libraries/colordialog/lang/sl.js           |   11 +
 docroot/libraries/colordialog/lang/sq.js           |   11 +
 docroot/libraries/colordialog/lang/sr-latn.js      |   11 +
 docroot/libraries/colordialog/lang/sr.js           |   11 +
 docroot/libraries/colordialog/lang/sv.js           |   11 +
 docroot/libraries/colordialog/lang/th.js           |   11 +
 docroot/libraries/colordialog/lang/tr.js           |   11 +
 docroot/libraries/colordialog/lang/tt.js           |   11 +
 docroot/libraries/colordialog/lang/ug.js           |   11 +
 docroot/libraries/colordialog/lang/uk.js           |   11 +
 docroot/libraries/colordialog/lang/vi.js           |   11 +
 docroot/libraries/colordialog/lang/zh-cn.js        |   11 +
 docroot/libraries/colordialog/lang/zh.js           |   11 +
 docroot/libraries/colordialog/plugin.js            |   71 +
 docroot/libraries/glyphicons/css/config.json       |  402 ++++
 docroot/libraries/glyphicons/css/css/bootstrap.css |  819 +++++++
 .../css/fonts/glyphicons-halflings-regular.eot     |  Bin 0 -> 20127 bytes
 .../css/fonts/glyphicons-halflings-regular.svg     |  288 +++
 .../css/fonts/glyphicons-halflings-regular.ttf     |  772 +++++++
 .../css/fonts/glyphicons-halflings-regular.woff    |  Bin 0 -> 23424 bytes
 .../css/fonts/glyphicons-halflings-regular.woff2   |  Bin 0 -> 18028 bytes
 docroot/libraries/glyphicons/css/js/bootstrap.js   | 2366 ++++++++++++++++++++
 .../libraries/glyphicons/css/js/bootstrap.min.js   |   12 +
 docroot/libraries/glyphicons/css/style.css         |   13 +
 docroot/libraries/glyphicons/dialogs/glyphicons.js |  141 ++
 docroot/libraries/glyphicons/icons/glyphicons.png  |    6 +
 docroot/libraries/glyphicons/plugin.js             |   40 +
 85 files changed, 6052 insertions(+)
 create mode 100644 docroot/libraries/colordialog/dialogs/colordialog.css
 create mode 100644 docroot/libraries/colordialog/dialogs/colordialog.js
 create mode 100644 docroot/libraries/colordialog/lang/af.js
 create mode 100644 docroot/libraries/colordialog/lang/ar.js
 create mode 100644 docroot/libraries/colordialog/lang/az.js
 create mode 100644 docroot/libraries/colordialog/lang/bg.js
 create mode 100644 docroot/libraries/colordialog/lang/bn.js
 create mode 100644 docroot/libraries/colordialog/lang/bs.js
 create mode 100644 docroot/libraries/colordialog/lang/ca.js
 create mode 100644 docroot/libraries/colordialog/lang/cs.js
 create mode 100644 docroot/libraries/colordialog/lang/cy.js
 create mode 100644 docroot/libraries/colordialog/lang/da.js
 create mode 100644 docroot/libraries/colordialog/lang/de-ch.js
 create mode 100644 docroot/libraries/colordialog/lang/de.js
 create mode 100644 docroot/libraries/colordialog/lang/el.js
 create mode 100644 docroot/libraries/colordialog/lang/en-au.js
 create mode 100644 docroot/libraries/colordialog/lang/en-ca.js
 create mode 100644 docroot/libraries/colordialog/lang/en-gb.js
 create mode 100644 docroot/libraries/colordialog/lang/en.js
 create mode 100644 docroot/libraries/colordialog/lang/eo.js
 create mode 100644 docroot/libraries/colordialog/lang/es.js
 create mode 100644 docroot/libraries/colordialog/lang/et.js
 create mode 100644 docroot/libraries/colordialog/lang/eu.js
 create mode 100644 docroot/libraries/colordialog/lang/fa.js
 create mode 100644 docroot/libraries/colordialog/lang/fi.js
 create mode 100644 docroot/libraries/colordialog/lang/fo.js
 create mode 100644 docroot/libraries/colordialog/lang/fr-ca.js
 create mode 100644 docroot/libraries/colordialog/lang/fr.js
 create mode 100644 docroot/libraries/colordialog/lang/gl.js
 create mode 100644 docroot/libraries/colordialog/lang/gu.js
 create mode 100644 docroot/libraries/colordialog/lang/he.js
 create mode 100644 docroot/libraries/colordialog/lang/hi.js
 create mode 100644 docroot/libraries/colordialog/lang/hr.js
 create mode 100644 docroot/libraries/colordialog/lang/hu.js
 create mode 100644 docroot/libraries/colordialog/lang/id.js
 create mode 100644 docroot/libraries/colordialog/lang/is.js
 create mode 100644 docroot/libraries/colordialog/lang/it.js
 create mode 100644 docroot/libraries/colordialog/lang/ja.js
 create mode 100644 docroot/libraries/colordialog/lang/ka.js
 create mode 100644 docroot/libraries/colordialog/lang/km.js
 create mode 100644 docroot/libraries/colordialog/lang/ko.js
 create mode 100644 docroot/libraries/colordialog/lang/ku.js
 create mode 100644 docroot/libraries/colordialog/lang/lt.js
 create mode 100644 docroot/libraries/colordialog/lang/lv.js
 create mode 100644 docroot/libraries/colordialog/lang/mk.js
 create mode 100644 docroot/libraries/colordialog/lang/mn.js
 create mode 100644 docroot/libraries/colordialog/lang/ms.js
 create mode 100644 docroot/libraries/colordialog/lang/nb.js
 create mode 100644 docroot/libraries/colordialog/lang/nl.js
 create mode 100644 docroot/libraries/colordialog/lang/no.js
 create mode 100644 docroot/libraries/colordialog/lang/oc.js
 create mode 100644 docroot/libraries/colordialog/lang/pl.js
 create mode 100644 docroot/libraries/colordialog/lang/pt-br.js
 create mode 100644 docroot/libraries/colordialog/lang/pt.js
 create mode 100644 docroot/libraries/colordialog/lang/ro.js
 create mode 100644 docroot/libraries/colordialog/lang/ru.js
 create mode 100644 docroot/libraries/colordialog/lang/si.js
 create mode 100644 docroot/libraries/colordialog/lang/sk.js
 create mode 100644 docroot/libraries/colordialog/lang/sl.js
 create mode 100644 docroot/libraries/colordialog/lang/sq.js
 create mode 100644 docroot/libraries/colordialog/lang/sr-latn.js
 create mode 100644 docroot/libraries/colordialog/lang/sr.js
 create mode 100644 docroot/libraries/colordialog/lang/sv.js
 create mode 100644 docroot/libraries/colordialog/lang/th.js
 create mode 100644 docroot/libraries/colordialog/lang/tr.js
 create mode 100644 docroot/libraries/colordialog/lang/tt.js
 create mode 100644 docroot/libraries/colordialog/lang/ug.js
 create mode 100644 docroot/libraries/colordialog/lang/uk.js
 create mode 100644 docroot/libraries/colordialog/lang/vi.js
 create mode 100644 docroot/libraries/colordialog/lang/zh-cn.js
 create mode 100644 docroot/libraries/colordialog/lang/zh.js
 create mode 100644 docroot/libraries/colordialog/plugin.js
 create mode 100644 docroot/libraries/glyphicons/css/config.json
 create mode 100644 docroot/libraries/glyphicons/css/css/bootstrap.css
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.eot
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.svg
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.ttf
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.woff
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.woff2
 create mode 100644 docroot/libraries/glyphicons/css/js/bootstrap.js
 create mode 100644 docroot/libraries/glyphicons/css/js/bootstrap.min.js
 create mode 100644 docroot/libraries/glyphicons/css/style.css
 create mode 100644 docroot/libraries/glyphicons/dialogs/glyphicons.js
 create mode 100644 docroot/libraries/glyphicons/icons/glyphicons.png
 create mode 100644 docroot/libraries/glyphicons/plugin.js
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory1672612390642983616.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1721 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory3573078163935697486.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1721 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1721/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1721 -e drupal_folder=/var/www/build1721 -e site_url=http://openy-dev.ffwua.com/build1721 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-jnkwldelcgtpklvjrfwvtewjitvnzizy
Traceback (most recent call last):
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1498478699.35-91359751710763/file", line 2012, in <module>
    main()
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1498478699.35-91359751710763/file", line 291, in main
    changed |= recursive_set_attributes(module, file_args['path'], follow, file_args)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1498478699.35-91359751710763/file", line 132, in recursive_set_attributes
    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1498478699.35-91359751710763/file", line 1207, in set_fs_attributes_if_different
    file_args['path'], file_args['mode'], changed
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1498478699.35-91359751710763/file", line 1045, in set_mode_if_different
    path_stat = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/tmp/filey53KV5'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=3    changed=0    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1725 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1725 |
| Installation process | http://install.openy-dev.ffwua.com/build1725/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1725/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1725

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1725

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1725/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1734 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1734 |
| Installation process | http://install.openy-dev.ffwua.com/build1734/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1734/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1734

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1734

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1734/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
