### PR TITLE
[OYPD-206] Use OpenY Hours feature from YGH

### PR DESCRIPTION
**Pull request by hamrant**
jira - https://propeople-us.atlassian.net/browse/OYPD-206
drupal.org issue - https://www.drupal.org/node/2853630

**Steps for review:**
- [x] login as admin
- [x] go to /admin/content?status=All&type=branch&title=&langcode=All
- [x] edit any branch
- [x] Add Branch Hours
- [x] Check TODAY'S HOURS in header
- [x] profit

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build496

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/496/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build496/profiles/openy/build/reports/behat

**Comment by hamrant** [comment]
test this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build500

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/500/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build500/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Branch hours have been displayed in teaser. Right now there's no branch hours field in teaser.
http://openy-dev.ffwua.com/build500/locations

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build505

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/505/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build505/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Current:
image

Should be similar to:
image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build511

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/511/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build511/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build512

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/512/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build512/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
image

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
