### PR TITLE
feat: Decouple all 3 themes to Drupal.org

### LINKED ISSUE #2577: Carnation compilation errors
On attempting to compile CSS in Carnation I receive a number of errors and `npm run build` fails. I'm assuming there may be a specific version of node/npm/yarn that's required, but I can't figure it out. We should specify this in the readme.

Tested with:
- node v14.18.1 (npm v6.14.15)
- node v17.0.1 (npm v8.1.0)

Old version throws... lots of errors. New version throws this. I've also tried `npm rebuild`.

```
npm run build

> Carnation@1.0.0 build
> webpack --config webpack.build.js --debug --output-pathinfo

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/.../Projects/openy/themes/openy_themes/openy_carnation/node_modules/webpack/lib/util/createHash.js:135:53)
...
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: https://openy.atlassian.net/browse/MAINTAIN-144

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3622/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3622/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3622/

**Comment by podarok** [comment]
image

**Comment by podarok** [comment]
image

**Comment by froboy** [comment]
@podarok I'm not able to recreate this issue. I've required `"ymcatwincities/openy": "dev-dev_themes_decouple",` and I'm building my local with a full fresh install using `fin init`. Is there another process you're using to get to this point?

**Comment by podarok** [comment]
@froboy yes, I found this on upgrade path.
you should install previous version and apply updated branch on top

**Comment by podarok** [comment]
But good to know profile install not affected

**Comment by froboy** [comment]
@podarok I'm still not able to recreate the issue. Here's what I did this time around:

```
# Set up project with composer create-project and docksal
fin composer require ymcatwincities/openy:"^9.2" -W
fin init
# visit /locations and observe it works 
fin composer require ymcatwincities/openy:dev-dev_themes_decouple -W
fin drush updb # no updates necessary
fin drush cr
```

I'm running into some other errors like this, but most of the time disabling and reenabling the module resolves it.

```
Error: Class 'Drupal\openy_programs_search\DataStorage' not found in Drupal\Component\DependencyInjection\Container->createService() (line 262 of /var/www/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php)
```

I was able to resolve that issue with:
`fin drush pmu openy_programs_search && fin drush en openy_programs_search -y && fin drush cr`

Could you please send a db from your failing instance or provide more detailed repro steps. Thanks.

**Comment by froboy** [comment]
@podarok I logged into the cibox version above and was able to figure out the issue. At `admin/openy/settings/openy_map` the "Locations Map Icon" fields were not set. This somehow results in the map... breaking badly. Once I filled in the field for each section and saved the form the map displays properly. I've seen this issue on the sandbox before so i think it might be something in the install scripts. I'd recommend we split the issue off separately though as it seems like it's not related to the theme decoupling.

Map_settings___Drush_Site-Install

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3629/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3629/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3629/

**Comment by podarok** [comment]
> Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3629/

Check @froboy - it's a newer DB dump for upgrade path ( current stable Open Y ) and the map is working, pins are not

image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3630/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3630/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3630/

**Pull request merged**
