### PR TITLE
Enable snapshots on test-failure

### PR DESCRIPTION
**Pull request by AlexNetman**
With new plugin Screenshots are saved on failure automatically in /build/reports/behat/screenshots

Also on CI there was an error related to Symphony version was forced to "~3.2.8"
But drupal-extesion still require "~2.7"
https://www.drupal.org/node/2704943
https://github.com/jhedstrom/drupalextension/blob/master/composer.json
So I changed Symphony version to 2.7 in CI job "PR_BUILDER_TESTS"

PS: May be we at this point we can avoid redefining composer.json on CI level? (Because we switched to composer-builds few days ago)

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2320 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2320 |
| Installation process | http://install.openy-dev.ffwua.com/build2320/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2320/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2320/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2320/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2320/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2320/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2320/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2320/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2321 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2321 |
| Installation process | http://install.openy-dev.ffwua.com/build2321/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2321/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2321/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2321/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2321/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2321/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2321/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2321/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
OK. I found that previous run failed because CI Job has to be modified.
So I added library there http://ci.openymca.org:8080/job/PR_BUILDER_TESTS/configure

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2322 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2322 |
| Installation process | http://install.openy-dev.ffwua.com/build2322/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2322/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2322/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2322/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2322/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2322/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2322/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2322/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2323 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2323 |
| Installation process | http://install.openy-dev.ffwua.com/build2323/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2323/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2323/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2323/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2323/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2323/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2323/blogWCAG2AAhtmlcs.txt

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2327 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2327 |
| Installation process | http://install.openy-dev.ffwua.com/build2327/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2327/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2327/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2327/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2327/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2327/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2327/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2327/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2332 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2332 |
| Installation process | http://install.openy-dev.ffwua.com/build2332/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2332/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2332/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2332/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2332/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2332/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2332/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2332/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2408 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2408 |
| Installation process | http://install.openy-dev.ffwua.com/build2408/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2408/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2408/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2408/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2408/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2408/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2408/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2408/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build34 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build34 |
| Installation process | http://install.openy-dev.ffwua.com/build34/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/34/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build34/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build34/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build34/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build34/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build34/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build34/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build35 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build35 |
| Installation process | http://install.openy-dev.ffwua.com/build35/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/35/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build35/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build35/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build35/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build35/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build35/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build35/blogWCAG2AAhtmlcs.txt

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build36 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build36 |
| Installation process | http://install.openy-dev.ffwua.com/build36/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/36/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build36/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build36/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build36/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build36/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build36/blogWCAG2AAhtmlcs.txt

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build37 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build37 |
| Installation process | http://install.openy-dev.ffwua.com/build37/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/37/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build37/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build37/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build37/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build37/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build37/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build37/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build76 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build76 |
| Installation process | http://install.openy-dev.ffwua.com/build76/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/76/

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/77/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #836 of commit 654edda81d198842e0bc8b3dc9e8d8708ee77aa0 automatically merged.
GitHub pull request #836 of commit 654edda81d198842e0bc8b3dc9e8d8708ee77aa0 automatically merged.
GitHub pull request #836 of commit 654edda81d198842e0bc8b3dc9e8d8708ee77aa0 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build77/openy-profile # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7075863660051224239.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: remote: Counting objects: 6137, done.
remote: Compressing objects:   0% (1/3589)   
remote: Compressing objects:   1% (36/3589)   
remote: Compressing objects:   2% (72/3589)   
remote: Compressing objects:   3% (108/3589)   
remote: Compressing objects:   4% (144/3589)   
remote: Compressing objects:   5% (180/3589)   
remote: Compressing objects:   6% (216/3589)   
remote: Compressing objects:   7% (252/3589)   
remote: Compressing objects:   8% (288/3589)   
remote: Compressing objects:   9% (324/3589)   
remote: Compressing objects:  10% (359/3589)   
remote: Compressing objects:  11% (395/3589)   
remote: Compressing objects:  12% (431/3589)   
remote: Compressing objects:  13% (467/3589)   
remote: Compressing objects:  14% (503/3589)   
remote: Compressing objects:  15% (539/3589)   
remote: Compressing objects:  16% (575/3589)   
remote: Compressing objects:  17% (611/3589)   
remote: Compressing objects:  18% (647/3589)   
remote: Compressing objects:  19% (682/3589)   
remote: Compressing objects:  20% (718/3589)   
remote: Compressing objects:  21% (754/3589)   
remote: Compressing objects:  22% (790/3589)   
remote: Compressing objects:  23% (826/3589)   
remote: Compressing objects:  24% (862/3589)   
remote: Compressing objects:  25% (898/3589)   
remote: Compressing objects:  26% (934/3589)   
remote: Compressing objects:  27% (970/3589)   
remote: Compressing objects:  28% (1005/3589)   
remote: Compressing objects:  29% (1041/3589)   
remote: Compressing objects:  30% (1077/3589)   
remote: Compressing objects:  31% (1113/3589)   
remote: Compressing objects:  32% (1149/3589)   
remote: Compressing objects:  33% (1185/3589)   
remote: Compressing objects:  34% (1221/3589)   
remote: Compressing objects:  35% (1257/3589)   
remote: Compressing objects:  36% (1293/3589)   
remote: Compressing objects:  37% (1328/3589)   
remote: Compressing objects:  38% (1364/3589)   
remote: Compressing objects:  39% (1400/3589)   
remote: Compressing objects:  40% (1436/3589)   
remote: Compressing objects:  41% (1472/3589)   
remote: Compressing objects:  42% (1508/3589)   
remote: Compressing objects:  43% (1544/3589)   
remote: Compressing objects:  44% (1580/3589)   
remote: Compressing objects:  45% (1616/3589)   
remote: Compressing objects:  46% (1651/3589)   
remote: Compressing objects:  47% (1687/3589)   
remote: Compressing objects:  48% (1723/3589)   
remote: Compressing objects:  49% (1759/3589)   
remote: Compressing objects:  50% (1795/3589)   
remote: Compressing objects:  51% (1831/3589)   
remote: Compressing objects:  52% (1867/3589)   
remote: Compressing objects:  53% (1903/3589)   
remote: Compressing objects:  54% (1939/3589)   
remote: Compressing objects:  55% (1974/3589)   
remote: Compressing objects:  56% (2010/3589)   
remote: Compressing objects:  57% (2046/3589)   
remote: Compressing objects:  58% (2082/3589)   
remote: Compressing objects:  59% (2118/3589)   
remote: Compressing objects:  60% (2154/3589)   
remote: Compressing objects:  61% (2190/3589)   
remote: Compressing objects:  62% (2226/3589)   
remote: Compressing objects:  63% (2262/3589)   
remote: Compressing objects:  64% (2297/3589)   
remote: Compressing objects:  65% (2333/3589)   
remote: Compressing objects:  66% (2369/3589)   
remote: Compressing objects:  67% (2405/3589)   
remote: Compressing objects:  68% (2441/3589)   
remote: Compressing objects:  69% (2477/3589)   
remote: Compressing objects:  70% (2513/3589)   
remote: Compressing objects:  71% (2549/3589)   
remote: Compressing objects:  72% (2585/3589)   
remote: Compressing objects:  73% (2620/3589)   
remote: Compressing objects:  74% (2656/3589)   
remote: Compressing objects:  75% (2692/3589)   
remote: Compressing objects:  76% (2728/3589)   
remote: Compressing objects:  77% (2764/3589)   
remote: Compressing objects:  78% (2800/3589)   
remote: Compressing objects:  79% (2836/3589)   
remote: Compressing objects:  80% (2872/3589)   
remote: Compressing objects:  81% (2908/3589)   
remote: Compressing objects:  82% (2943/3589)   
remote: Compressing objects:  83% (2979/3589)   
remote: Compressing objects:  84% (3015/3589)   
remote: Compressing objects:  85% (3051/3589)   
remote: Compressing objects:  86% (3087/3589)   
remote: Compressing objects:  87% (3123/3589)   
remote: Compressing objects:  88% (3159/3589)   
remote: Compressing objects:  89% (3195/3589)   
remote: Compressing objects:  90% (3231/3589)   
remote: Compressing objects:  91% (3266/3589)   
remote: Compressing objects:  92% (3302/3589)   
remote: Compressing objects:  93% (3338/3589)   
remote: Compressing objects:  94% (3374/3589)   
remote: Compressing objects:  95% (3410/3589)   
remote: Compressing objects:  96% (3446/3589)   
remote: Compressing objects:  97% (3482/3589)   
remote: Compressing objects:  98% (3518/3589)   
remote: Compressing objects:  99% (3554/3589)   
remote: Compressing objects: 100% (3589/3589)   
remote: Compressing objects: 100% (3589/3589), done.
Receiving objects:   0% (1/6137)   
Receiving objects:   1% (62/6137)   
Receiving objects:   2% (123/6137)   
Receiving objects:   3% (185/6137)   
Receiving objects:   4% (246/6137)   
Receiving objects:   5% (307/6137)   
Receiving objects:   6% (369/6137)   
Receiving objects:   7% (430/6137)   
Receiving objects:   8% (491/6137)   
Receiving objects:   9% (553/6137)   
Receiving objects:  10% (614/6137)   
Receiving objects:  11% (676/6137)   
Receiving objects:  12% (737/6137)   
Receiving objects:  13% (798/6137)   
Receiving objects:  14% (860/6137)   
Receiving objects:  15% (921/6137)   
Receiving objects:  16% (982/6137)   
Receiving objects:  17% (1044/6137)   
Receiving objects:  18% (1105/6137)   
Receiving objects:  19% (1167/6137)   
Receiving objects:  20% (1228/6137)   
Receiving objects:  21% (1289/6137)   
Receiving objects:  22% (1351/6137)   
Receiving objects:  23% (1412/6137)   
Receiving objects:  24% (1473/6137)   
Receiving objects:  25% (1535/6137)   
Receiving objects:  26% (1596/6137)   
Receiving objects:  27% (1657/6137)   
Receiving objects:  28% (1719/6137)   
Receiving objects:  29% (1780/6137)   
Receiving objects:  30% (1842/6137)   
Receiving objects:  31% (1903/6137)   
Receiving objects:  32% (1964/6137)   
Receiving objects:  33% (2026/6137)   
Receiving objects:  34% (2087/6137)   
Receiving objects:  35% (2148/6137)   
Receiving objects:  36% (2210/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  37% (2271/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  38% (2333/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  39% (2394/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  40% (2455/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  41% (2517/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  42% (2578/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  43% (2639/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  44% (2701/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  45% (2762/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  46% (2824/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  47% (2885/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  48% (2946/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  49% (3008/6137), 3.50 MiB | 6.97 MiB/s   
Receiving objects:  49% (3008/6137), 7.07 MiB | 7.04 MiB/s   
Receiving objects:  50% (3069/6137), 10.66 MiB | 7.08 MiB/s   
Receiving objects:  50% (3079/6137), 14.79 MiB | 7.38 MiB/s   
Receiving objects:  50% (3107/6137), 24.69 MiB | 8.21 MiB/s   
Receiving objects:  51% (3130/6137), 24.69 MiB | 8.21 MiB/s   
fatal: write error: No space left on device
fatal: index-pack failed

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1363)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:61)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:299)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:485)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1003)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: null
Couldn't read comment file
java.io.FileNotFoundException: File '/var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build77/commentinfo.md' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:124)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build83 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build83 |
| Installation process | http://install.openy-dev.ffwua.com/build83/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/83/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build83/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build83/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build83/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build83/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build83/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build83/blogWCAG2AAhtmlcs.txt

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build91 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build91 |
| Installation process | http://install.openy-dev.ffwua.com/build91/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/91/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build91/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build91/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build91/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build91/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build91/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build91/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
