### PR TITLE
[MAINTAIN-122] Remove excessive space for small webforms.

### PR DESCRIPTION
**Pull request by manachynskyi**
[Original Issue](https://openy.atlassian.net/browse/MAINTAIN-122), this PR is going to fix excessive space for small webforms for Carnation theme.

Before: https://i.imgur.com/an6E1rX.png
After: https://i.imgur.com/ffpYzqX.png

## Steps for review (should be tested on Carnation)
- [ ] Create new small webform /admin/structure/webform/add with one field https://i.imgur.com/1OIGNsd.png, (e.g. https://i.imgur.com/Vv6QBD6.png)
- [ ] create new landing page -> add Webform paragraph to it -> choose created webform https://i.imgur.com/pdugyHn.png (it will be easily see empty space if you add banners right before and after webform)
- [ ] visit page and make sure there no empty space before and after webform

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
@manachynskyi I've merged a fix for scss paths. Could you remove DO_NOT_MERGE tag from this?

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3504/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3504/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3504/

**Review by podarok — APPROVED** [review]
Code looks good

**Pull request merged**
