### PR TITLE
Carnation Alerts Improvements

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: [MAINTAIN-33](https://openy.atlassian.net/browse/MAINTAIN-33)

This one will provide some improvements for Alerts:
on the first and the last alert in slider we don't show arrow to side without slide.

Open-Y-CanationAlerts2

**Notice** **this will related to all themes: Carnation, Rose, Lily** (because changes was maded on module side)

MAINTAIN-33AlertArrowsLily

## Steps for review

- [ ] Go to the main page.
- [ ] Verify that you use Carnation theme.
- [ ] Verify alerts in header and footer area
- [ ] Verify that we don't see the previous arrow on first slide and don't see the next arrow on last slide
- [ ] Verify that **Call to action** buttons react on hover
- [ ] Verify that arrow placed right on the middle of allert slide
- [ ] Verify that alerts works fine on all type of screens
- [ ] Verify arrows for alert sliders for another themes (Rose, Lily)

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by hamrant** [comment]
ok to test

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3105/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3105/

**Comment by gundevel** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3105/

**Comment by hamrant** [comment]
Tested rose and carnation on http://upgrade.openy.cibox.tools/build3105/ : 

1. Slick arrows logic works fine
2. Button hover on Carnation fixed
3. `On Desktop alerts in the footer has an issue with alignment` - hard to test with broken icons

On carnation arrows displayed incorrectly:

screenshot-upgrade openy cibox tools-2021 02 25-20_04_10

Maybe some issue with the font awesome or caching (I switched to carnation theme from rose on http://upgrade.openy.cibox.tools/build3105/ )

@aleevas please double-check.

cc @podarok

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3106/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3106/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3106/

**Comment by aleevas** [comment]
> 
> On carnation arrows displayed incorrectly:
> 
> screenshot-upgrade openy cibox tools-2021 02 25-20_04_10
> 
> Maybe some issue with the font awesome or caching (I switched to carnation theme from rose on http://upgrade.openy.cibox.tools/build3105/ )

> cc @podarok

@hamrant looks like in this [PR](https://github.com/ymcatwincities/openy/pull/2405) I've made a bad desicion and when we switch to latest version of Font Awesome we lost old icons.
So, I returned it back.
But the AF4 remove button has old style of trash icon, because a new one was added only in 5.10 version of Awesome Font
MAINTAIN-33CarnationRigisterBtn

If we want to use the latest version of Font Awesome in Carnation theme we should double check all icons before switch.
cc @podarok

**Comment by aleevas** [comment]
Here is a list of using of the Font Awesome icons that I found in Carnation theme
**SCSS** fiels:
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/component/_addtocalendar.scss#L81
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_branch.scss#L182
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_branch.scss#L1339
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_geysir.scss#L5
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_global-search.scss#L19
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_global-search.scss#L121
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_global-search.scss#L126
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_location.scss#L68
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_news.scss#L54
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_site-alert.scss#L247
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/modules/_site-alert.scss#L255
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes
/openy_carnation/src/scss/paragraphs/_amenities.scss#L279
https://github.com/ymcatwincities/openy/blob/8219b5a8911a1d98ce169a7fe3d7c9b04e789361/themes/openy_themes/openy_carnation/src/scss/paragraphs/_amenities.scss#L294

Other files:
```
dist/js/openy_carnation_branch.js:15:fas 
templates/modules/openy-faq-item.html.twig:18:fas 
templates/modules/openy-faq-item.html.twig:19:fas 
templates/paragraph/paragraph--gallery--default.html.twig:67:fas 
templates/paragraph/paragraph--gallery--default.html.twig:71:fas 
templates/openy_schedules/openy-schedules-main-class.html.twig:17:fas 
templates/openy_schedules/openy-schedules-main-class.html.twig:18:fas 
templates/openy_schedules/openy-schedules-main-class.html.twig:59:fas 
templates/openy_schedules/openy-schedules-main.html.twig:51:fas 
templates/field/field--field-location-directions.html.twig:46:fas 
templates/field/field--field-location-directions.html.twig:53:fas 
templates/field/field--field-location-directions.html.twig:65:fas 
templates/field/field--address.html.twig:45:fas 
templates/block/block-branch-contacts-info.html.twig:30:fas 
templates/block/block-branch-contacts-info.html.twig:49:fas 
templates/elements/openy-class-sessions.html.twig:54:fas 
templates/elements/openy-class-sessions.html.twig:60:fas 
templates/node/facility/node--facility--full.html.twig:100:fas 
templates/node/facility/node--facility--full.html.twig:108:fas 
templates/node/facility/node--facility--full.html.twig:140:fas 
templates/node/branch/node--branch--class_location.html.twig:108:fas 
templates/node/news/node--news--full.html.twig:130:fas 
templates/node/node--location-type--teaser.html.twig:101:fas 
templates/node/node--location-type--teaser.html.twig:107:fas 
templates/node/node--location-type--teaser.html.twig:123:fas 
templates/node/node--location-type--teaser.html.twig:131:fas 
templates/node/camp/node--camp--class_location.html.twig:106:fas 
templates/node/event/event-location-info.html.twig:22:fas 
templates/node/event/node--event--teaser.html.twig:109:fas 

dist/js/openy_carnation_program.js:23:fa 
dist/js/openy_carnation_program.js:24:fa 
templates/paragraph/paragraph--grid-columns.html.twig:53:fa 
templates/menu/mobile/menu--main--mobile-menu.html.twig:42:fa 
templates/menu/mobile/menu--main--mobile-menu.html.twig:43:fa 
templates/menu/menu--main--primary-menu.html.twig:42:fa 
templates/menu/menu--main--primary-menu.html.twig:43:fa 
templates/menu/menu--main--primary-menu.html.twig:56:fa 
templates/menu/menu--main--primary-menu.html.twig:73:fa 
templates/openy_schedules/openy-schedules-subcategory-filters.html.twig:18:fa 
templates/field/field--paragraph--3c.html.twig:69:fa 
templates/field/field--paragraph--1c.html.twig:65:fa 
templates/field/field--paragraph--4c.html.twig:79:fa 
templates/field/field--node--field-page-related-content.html.twig:51:fa 
templates/field/field--node--field-blog-related--blog.html.twig:51:fa 
templates/field/field--node--field-location-state.html.twig:52:fa 
templates/field/field--paragraph--2c.html.twig:63:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:18:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:20:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:23:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:25:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:110:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:168:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:221:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig:318:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:29:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:30:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:52:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:53:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:68:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:69:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:100:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:101:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:126:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig:127:fa 
templates/openy_repeat/openy-repeat-schedule-dashboard.html.twig:26:fa 
templates/block/block-branch-contacts-info.html.twig:25:fa 
templates/block/block-branch-contacts-info.html.twig:41:fa 
templates/views/views-view-field--social-posts-view--social-posts-block--field-platform.html.twig:1:fa 
templates/openy_group_schedules/groupex-table-class-individual.html.twig:21:fa 
templates/openy_group_schedules/groupex-table-class-individual.html.twig:26:fa 
templates/openy_group_schedules/groupex-table-class-individual.html.twig:26:fa 
templates/openy_group_schedules/groupex-table-instructor-individual.html.twig:17:fa 
templates/openy_group_schedules/groupex-table-instructor-individual.html.twig:20:fa 
templates/openy_group_schedules/groupex-table-instructor-individual.html.twig:21:fa 
templates/openy_group_schedules/groupex-table-class.html.twig:17:fa 
templates/openy_group_schedules/groupex-table-class.html.twig:20:fa 
templates/openy_group_schedules/groupex-table-class.html.twig:20:fa 
templates/page/page.html.twig:88:fa 
templates/page/page.html.twig:129:fa 
templates/page/page.html.twig:134:fa 
templates/node/facility/node--facility--full.html.twig:135:fa 
templates/node/facility/node--facility--full.html.twig:156:fa 
templates/node/facility/node--facility--full.html.twig:162:fa 
templates/node/alert/node--alert--node-alert-header.html.twig:89:fa 
templates/node/alert/node--alert--node-alert-header.html.twig:108:fa 
templates/node/alert/node--alert--node-alert-footer.html.twig:89:fa 
templates/node/alert/node--alert--node-alert-footer.html.twig:108:fa 
templates/node/extends/post-teaser--default.html.twig:52:fa 
templates/node/news/node--news--teaser.html.twig:92:fa 
templates/node/news/node--news--full.html.twig:123:fa 
templates/node/event/event-location-info.html.twig:28:fa 
templates/node/event/event-contact-info.html.twig:21:fa 
templates/node/event/event-contact-info.html.twig:25:fa 
templates/node/event/event-contact-info.html.twig:29:fa 
```
cc @hamrant @podarok

**Comment by hamrant** [comment]
@aleevas thanks, I will test this on the build later today

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3107/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3107/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3107/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3108/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3108/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3108/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3109/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3109/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3109/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3110/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3110/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3110/

**Review by hamrant — APPROVED** [review]
Tested icons on carnation - http://upgrade.openy.cibox.tools/build3110/

Issue fixed.

Screenshot from 2021-02-26 17-53-41

**Comment by hamrant** [comment]
@podarok please note - this fix should be released with https://github.com/ymcatwincities/openy/pull/2405 (because it fixed a font-awesome issue that was introduced in that PR)

**Comment by podarok** [comment]
Done @hamrant 
Thank you @aleevas

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
