### PR TITLE
Externalize Vue libraries.

### LINKED ISSUE #1902: [Policy] Externalize Vue and related libraries
We need to put some order into how we use the Vue and related libs (vue-router, vuex, etc.) across the distribution. We already have several Vue-powered applications that include these libs in a variety of ways:
- Activity Finder has 2 separate Vue implementations - one for wizard steps, another one for results listing (https://github.com/ymcatwincities/openy/tree/8.x-2.x/modules/custom/openy_activity_finder)
-- Wizard is written using components approach and bundles Vue and Vue-router directly into the build artifact - https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js
-- Results listing is using the openy_system/vue and openy_system/vue_router libs which is getting assets from local libraries directory - https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_system/openy_system.libraries.yml

Suggestions:
- Change openy_system/vue and openy_system/vue_router libraries definition to get assets from CDN just like we already do with moment and jquery.matchHeight
- Add vuex library definition into openy_system module
- Remove vue and vue-router libraries from composer.json - https://github.com/ymcatwincities/openy/blob/8.x-2.x/composer.json#L119 and https://github.com/ymcatwincities/openy-project/blob/8.2.x/composer.json#L177
- Externalize Vue and related libs from build artifacts using Webpack 'externals' option - https://webpack.js.org/configuration/externals/ - to exclude them from the build asset
- Fix openy_activity_finder/openy_activity_finder library definition to depend on the openy_system/vue and openy_system/vue_router libraries
- Fix other Vue and vue-router usages in the codebase using the above approach

This will allow us to improve in several areas:
- Unify Vue libs usage in the project
- Libraries version bump will need to happen in one place - just the .libraries.yml definition in the openy_system module (and not in both composer.json + composer.lock in both openy and openy-project)
- Improve performance as libs will come from CDN

Please comment with any improvements to the above suggestions.

### PR DESCRIPTION
**Pull request by duozersk**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/1902

Open Y project PR - https://github.com/ymcatwincities/openy-project/pull/74

## Steps for review

- [ ] check code changes
- [ ] verify Activity Finder is working fine
- [ ] verify Schedules are working fine

The modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js is reduced significantly: 166.8 KB -> 42.1 KB

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by AndreyMaximov** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2044/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2044/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2044/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2044/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2044/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2044/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2044/blogWCAG2AAhtmlcs.txt

**Review by podarok — DISMISSED** [review]
Code looks good
@duozersk have you tested all vue apps we have after this?

**Comment by podarok** [comment]
@duozersk there are conflicts and probably would be nice to work on this post release. What do you think?

**Comment by duozersk** [comment]
Conflicts are fine, they are expected to happen :) I will resolve them from time to time :) 
As for the testing - nope, I didn't test the changes, they need to be tested.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2050/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2050/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2050/

**Comment by podarok** [comment]
@duozersk could you fix a conflict, please?

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2072/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2072/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2072/

**Comment by podarok** [comment]
This is great!
merging

**Pull request merged**
