### PR TITLE
Update tour.tour.openy-menu-overview.yml

### PR DESCRIPTION
**Pull request by Robert201-zz**
Update menu overview tour

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build343

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/343/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build343/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build351

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/351/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build351/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
