### PR TITLE
[OYPD-356] Changes for class listing page, lots of theme changes plus change to …

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x]  Visit a class listing page, like /programs/swimming/swim-lessons
- [x] Verify it looks right and still functions properly.

Note: This will not have the facet filter buttons like Seattle. This is more MVP.

screen shot 2017-04-21 at 4 53 23 pm
screen shot 2017-04-21 at 4 53 17 pm
screen shot 2017-04-21 at 4 53 02 pm
screen shot 2017-04-21 at 4 52 56 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1019 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1019 |
| Installation process | http://install.openy-dev.ffwua.com/build1019/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1019/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1019/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1021 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1021 |
| Installation process | http://install.openy-dev.ffwua.com/build1021/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1021/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1021/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Looks awesome!

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
