### PR TITLE
[OYPD-205] Replace Field Collections with paragraphs 

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-205
drupal.org issue - https://www.drupal.org/node/2851433

Steps for review:
- [x] login as admin
- [x] go to /node/add/branch
- [x] in CONTACT INFO use Seattle, Washington, 98118
- [x] add several BRANCH HOURS
- [x] check branch page and TODAY'S HOURS block
- [x] go to /node/add/membership
- [x] add Membership info
- [x] check fieds in Membership info paragraph
- [x] go to /node/add/session
- [x] Add TIME
- [x] check Session Time paragraph
- [x] go to /node/add/landing_page
- [x] Add to content "Grid Content" paragraph
- [x] add several columns in paragraph
- [x] check this paragraph on created page

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build418

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/418/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build418/profiles/openy/build/reports/behat

**Comment by hamrant** [comment]
**TODO:** Update CT documentation

**Comment by Sanchiz** [comment]
1. Let's update documentation:
- Add paragraphs
- Update CT definition

2. Let's fix Behat tests
image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build419

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/419/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build419/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Let's update documentation:
- Add paragraphs
- Update CT definition

2. Please exclude Field Collections from installation profile, drush make and composer

3. Please hide link label
image


4. Let's fix Behat tests
image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/420/

**Build Log**
*last 25 lines*

 ```
[...truncated 252 lines...]
stdout: You are about to create a /var/www/build420/sites/default/settings.php file and CREATE the 'drupal420' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=12   changed=5    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build425

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/425/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build425/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build426

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/426/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build426/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build432

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/432/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build432/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build433

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/433/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build433/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@hamrant seems there's a regression with changing cardinality in "Featured Content" paragraph.

With Field Collections single field was shared between 2 entities FC and Paragraph and for one it supported multivalue, for other no.

So with this migration we shouldn't use this field for both pargraphs.

New version:
image

FC version:
image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build435

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/435/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build435/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build436

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/436/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build436/profiles/openy/build/reports/behat

**Comment by hamrant** [comment]
test this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build442

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/442/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build442/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
I've noticed one thing, probably it's not related to your PR, but let's fix it here. Name is different from documentation. We should update field name to follow naming convention.

image

image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build452

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/452/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build452/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
