### PR TITLE
Replace select list widget with autocomplete widget for Group schedules paragraph

### PR DESCRIPTION
**Pull request by dbuzinov-yx**
Provide ability to change widget to autocomplete for Schedules Block.

## Steps for review

- Install/update from profile 
- Login to system 
- visit /admin/structure/paragraphs_type/group_schedules/form-display
  Schedules Block widget should be set to Autocomplete selection list
- Edit home page 
- add Group Schedules (GroupEx Pro) paragraph  to CONTENT AREA Content field
  Autocomplete selection should be used as select plugin

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]
Needs manual checking

**Comment by podarok** [comment]
ok to test

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build314 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build314 |
| Installation process | http://install.openy-dev.ffwua.com/build314/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/314/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build314/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build314/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build314/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build314/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build314/blogWCAG2AAhtmlcs.txt

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build323 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build323 |
| Installation process | http://install.openy-dev.ffwua.com/build323/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/323/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build323/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build323/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build323/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build323/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build323/blogWCAG2AAhtmlcs.txt

**Pull request merged**
