### PR TITLE
[OYPD-342] Change alert color on blog page header area.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-342
D.o https://www.drupal.org/node/2861645

Steps to review:
- [x] Visit /blog
- [x] See Be a part of OpenY is acceptable colors next to the banner color.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build765 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build765 |
| Installation process | http://install.openy-dev.ffwua.com/build765/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/765/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build765/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build777 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build777 |
| Installation process | http://install.openy-dev.ffwua.com/build777/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/777/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build777/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build780 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build780 |
| Installation process | http://install.openy-dev.ffwua.com/build780/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/780/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build780/profiles/contrib/openy/build/reports/behat

**Pull request merged**
