### PR TITLE
[OYPD-334] Removing alert button when there is no link

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Add alert to header. Check that button appears when there is a link.
- [x] Check that button does not appear when there is no link.
- [x] Add alert to footer. Check that button appears when there is a link.
- [x] Check that button does not appear when there is no link.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build727 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build727 |
| Installation process | http://install.openy-dev.ffwua.com/build727/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/727/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build727/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build729 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build729 |
| Installation process | http://install.openy-dev.ffwua.com/build729/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/729/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build729/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
