### PR TITLE
Fix parameters order in the implode for PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by NightHunterSV**
On one of the clients' projects we've noticed an error message about the deprecation of the order of the parameters used:

image

The site is currently on PHP 7.4, and there was deprecated the reverse order of parameters: https://www.php.net/manual/en/migration74.deprecated.php

Make sure these boxes are checked before asking for review of your pull request - thank you!

## Steps for review

- [ ] Run the build on PHP 7.4.
- [ ] Go to some theme settings page.
- [ ] Verify there are no error messages regarding the wrong parameters order on the `implode` call.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
@shelleygoetz @sarah-halby to include this into next point release, please

Thank you @NightHunterSV

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by sarah-halby** [comment]
@podarok to clarify, the next release on Nov 9 or the next point release in December?

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
@sarah-halby for next "any" release

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by shelleygoetz** [comment]
Added to Jira: https://openy.atlassian.net/browse/MAINTAIN-181

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
