### PR TITLE
[OYPD-275] Landing page context and menu on landing page.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-275
D.o https://www.drupal.org/node/2854653
Steps to review:
- [x] Create a Camp CT
- [x] In menu links add a Landing page as a link
- [x] Add a Camp Menu paragraph to Camp CT
- [x] Publish Camp CT
- [x] See Camp Menu links including link to Landing page
- [x] Edit linked Landing page
- [x] Add a Camp Menu paragraph to Landing page CT
- [x] Publish Landing page changes
- [x] See Same Camp Menu links as were on the Camp CT.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build539/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build539

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/539/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build539/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build540/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build540

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/540/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build540/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build549

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/549/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build549/profiles/openy/build/reports/behat

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
When I try to save a node  I see errors in console and form does not work.
```
An invalid form control with name='field_location_address[0][address_line1]' is not focusable.
An invalid form control with name='field_location_address[0][locality]' is not focusable.
An invalid form control with name='field_location_address[0][administrative_area]' is not focusable.
An invalid form control with name='field_location_address[0][postal_code]' is not focusable.
An invalid form control with name='field_location_phone[0][value]' is not focusable.
```
Seems it is not related to this PR, but I can't check until these errors presents.

**Comment by alexschedrov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build556

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/556/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build556/profiles/openy/build/reports/behat

**Pull request merged**
