### PR TITLE
[OYPD-450] Adjusting styling for edit link on class schedule pages

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Check edit link on class page with location chosen.
- [x] Check edit link on class page with all chosen.

screen shot 2017-06-01 at 2 30 40 pm
screen shot 2017-06-01 at 2 30 24 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1332 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1332 |
| Installation process | http://install.openy-dev.ffwua.com/build1332/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1332/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1332/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1338 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1338 |
| Installation process | http://install.openy-dev.ffwua.com/build1338/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1338/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1338/profiles/contrib/openy/build/reports/behat

**Pull request merged**
