### PR TITLE
[OYPD-383] WYSIWYG buttons.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue https://propeople-us.atlassian.net/browse/OYPD-383

Steps:
- [x] login as admin
- [x] go to [sitename]/admin/config/content/formats/manage/full_html
- [x] make sure you can see only one image icon in media toolbar
Please look https://monosnap.com/file/7uD5tHQ3rDTa2bjILxALeiJINdndKW
- [x] go to [sitename]/node/add/activity
- [x] click on "Content Area" 
- [x] make sure you can see only one image icon in media toolbar
Please look https://monosnap.com/file/oLEW9whMzvGy4YZo0ghZZbV7iRtY51
- [x] in the branch go to openy/docs/Development/Create View Modes.md and check instruction.
https://github.com/ivan-berezhnov/openy/blob/36e60302589dd5996c9dd12a5b56c15d1d159332/docs/Development/Create%20View%20Modes.md

Issue on Drupal.org https://www.drupal.org/node/2871738

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1001 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1001 |
| Installation process | http://install.openy-dev.ffwua.com/build1001/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1001/

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1002 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1002 |
| Installation process | http://install.openy-dev.ffwua.com/build1002/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1002/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1001/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1002/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1013 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1013 |
| Installation process | http://install.openy-dev.ffwua.com/build1013/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1013/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1013/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1014 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1014 |
| Installation process | http://install.openy-dev.ffwua.com/build1014/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1014/

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1014 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1014 |
| Installation process | http://install.openy-dev.ffwua.com/build1014/install.php |

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1015/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #310 of commit 150863ad7ea2f2c7267815a439eba95797ba4a3f.
GitHub pull request #310 of commit 150863ad7ea2f2c7267815a439eba95797ba4a3f.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git9207304198607713096.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git8989133539770389593.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse 150863ad7ea2f2c7267815a439eba95797ba4a3f^{commit} # timeout=10
FATAL: Command "git rev-parse 150863ad7ea2f2c7267815a439eba95797ba4a3f^{commit}" returned status code 128:
stdout: 150863ad7ea2f2c7267815a439eba95797ba4a3f^{commit}

stderr: fatal: ambiguous argument '150863ad7ea2f2c7267815a439eba95797ba4a3f^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "git rev-parse 150863ad7ea2f2c7267815a439eba95797ba4a3f^{commit}" returned status code 128:
stdout: 150863ad7ea2f2c7267815a439eba95797ba4a3f^{commit}

stderr: fatal: ambiguous argument '150863ad7ea2f2c7267815a439eba95797ba4a3f^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1576)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1572)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1233)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1245)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:607)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:85)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:934)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1044)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1016 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1016 |
| Installation process | http://install.openy-dev.ffwua.com/build1016/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1016/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1014/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1016/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
After review, I will resolve to merge conflict. 
If it needs to do before please tell me.
@Sanchiz

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1017 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1017 |
| Installation process | http://install.openy-dev.ffwua.com/build1017/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1017/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1017/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
