### PR TITLE
[OYPD-239] Remove demo modules from installation profile

### PR DESCRIPTION
**Pull request by ddrozdik**
Steps for review:
- [x] Do code review
- [x] Check that demo modules are not in the list of dependencies

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build497/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build497

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/497/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build497/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build498

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/498/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build498/profiles/openy/build/reports/behat

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build501

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/501/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build501/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
