### PR TITLE
[OYPD-291] Updates for color module support

### PR DESCRIPTION
**Pull request by david-hernandez**
This initial commit includes fixed for overriding buttons, and the changes for the header menu links. It would be good to get this reviewed before continuing with more changes.

This gets complicated. So the buttons have at least different implementations. There are blue buttons with no hover effect, blue text on hover, and white text with underline on hover. I assume this isn't on purpose. There is also the issue of other button types, like the white buttons which then have their own hover. Most of this doesn't make sense from a style guide stand point. As a solution I'm treating the buttons the same. On override the blue buttons can change background and link color, and I'm using no hover effect. The white buttons will stay the same, but look like the regular button on hover.

For the menu, I added settings for link color and hover color. For this I also unified the hover effect. It is doing different things depending on level of link and even the sidebar slideout, which I'm not sure was on purpose. (This might just be a consequence of when the theme was original converted to Rose.)

If the solution looks reasonable, I'll add the same for the footer. I assume this also needs to be duplicated to the Camp style, correct?

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build898 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build898 |
| Installation process | http://install.openy-dev.ffwua.com/build898/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/898/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build898/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@david-hernandez we should standardize buttons based on context or type and it totally makes sense to reduce number of variations of styles.

If you can provide screenshots of buttons - we can decide if we need them as separate type of we can replace them with some general style.

**Comment by david-hernandez** [comment]
Here are some screenshot of the existing buttons.

On the calculator the previous button is blue
screen shot 2017-04-06 at 2 35 08 pm

but the next button is purple and gets blue text on hover
screen shot 2017-04-06 at 2 33 55 pm

The white buttons stay white, but the text changes from light blue to dark blue on hover
screen shot 2017-04-06 at 2 34 12 pm

And then we have three kinds of blue buttons:

No hover effect. (and for some reason this one is bold.)
screen shot 2017-04-06 at 2 33 25 pm

Text turns blue.
screen shot 2017-04-06 at 2 32 52 pm

Text turns underline.
screen shot 2017-04-06 at 2 32 44 pm

In the initial commit in this branch I consolidated this to have all the blue buttons stay blue on hover with white text, but I left the underline one because that was specifically coming from the banner paragraph. I'd like to remove that underline, or add it for all. Either way, they should be the same.

For the white button, in this commit the button is white but on hover takes the appearance of a regular button. This is because all the buttons use the same hover CSS. I'd rather not try to make a setting just for white buttons.

screen shot 2017-04-06 at 2 40 40 pm
screen shot 2017-04-06 at 2 40 45 pm

The only real problem with the way they are in the commit is the purple button. Changing the link color can result in an ugly button, because that purple background color doesn't change.

**Comment by david-hernandez** [comment]
Added changes for footer text.

screen shot 2017-04-06 at 9 29 37 pm

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build904 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build904 |
| Installation process | http://install.openy-dev.ffwua.com/build904/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/904/

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build907 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build907 |
| Installation process | http://install.openy-dev.ffwua.com/build907/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/907/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build907/profiles/contrib/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Comment by david-hernandez** [comment]
Added a commit to add color changes for header menu link color, menu link hover, buttons, and footer text color, for the camp pages.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build912 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build912 |
| Installation process | http://install.openy-dev.ffwua.com/build912/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/912/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build912/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
1) Promo card on pages related to camp.
image
2) Slider on camp page has text not white:
image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build920 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build920 |
| Installation process | http://install.openy-dev.ffwua.com/build920/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/920/

**Comment by david-hernandez** [comment]
Thanks for finding that. I added a commit to include some missing camp overrides for the buttons.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build920/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build922 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build922 |
| Installation process | http://install.openy-dev.ffwua.com/build922/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/922/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build922/profiles/contrib/openy/build/reports/behat

**Pull request merged**
