### PR TITLE
Add Categories to Form

### PR DESCRIPTION
**Pull request by mattshoaf**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Drupal.org Issue: [https://www.drupal.org/project/openy/issues/2976415](https://www.drupal.org/project/openy/issues/2976415)

I noticed that categories were stubbed in, and they were necessary for my application so they should be working now as a selection option for the form.

## Steps for review

1. Install Module
2. Set your GroupEx Account ID at /admin/config/services/openy_group_schedules/settings 
3. Navigate to /all_y_schedules, after selecting a location, you can now filter by Category in addition to the previously available Class, Instructor and Date filters.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by podarok** [comment]
@mattshoaf 
Could you provide step by step how to manually test current functionality?
Thanks for the contribution

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build431 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build431 |
| Installation process | http://install.openy-dev.ffwua.com/build431/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/431/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build431/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build431/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build431/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build431/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build431/blogWCAG2AAhtmlcs.txt

**Comment by mattshoaf** [comment]
@podarok I add the steps for review to the main description. Also, pushed up a bug fix.

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build452 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build452 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build452 |
| Installation process | http://install.openy.cibox.tools/build452/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/452/

**Comment by podarok** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build456 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build456 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build456 |
| Installation process | http://install.openy.cibox.tools/build456/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/456/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build464 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build464 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build464 |
| Installation process | http://install.openy.cibox.tools/build464/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/464/

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build465 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build465 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build465 |
| Installation process | http://install.openy.cibox.tools/build465/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/465/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build465/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build465/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build465/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build465/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build465/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Pull request merged**
