### PR TITLE
[MAINTAIN-30] fixed layout for a taxonomy term pages

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: [MAINTAIN-30](https://openy.atlassian.net/browse/MAINTAIN-30)

This one should fix broken layout for news category page when you add the alert banner on the category page page for Carnation theme. 
Now it should looks like this:
MAINTAIN-30CarnationNewsCategoryPage

## Steps for review

- [ ] Make sure that you use Carnation theme.
- [ ] Go to the news page (/news)
- [ ] Click by one of the news
- [ ] On the news page in right sidebar click by category tag (for ex. Summer Day Camp)
- [x] Verify that page looks good
- [x] Create a new one or just edit esixting one of Alert node
- [x] Please set in the Visibility pages field: news/* (to show alert on the news pages)
- [x] Repeat step 1-3
- [ ] Verify that page looks good on all type of screens (desktop, tablet, mobile)

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by hamrant** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3112/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3112/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3112/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3113/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3113/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3113/

**Review by podarok — APPROVED** [review]

**Pull request merged**
