### PR TITLE
[OYPD-197] Footer block during installation

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-197

Steps for review
- [x] check footer social and copyright blocks
- [x] profit

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build358

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/358/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build358/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build359

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/359/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build359/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
