### PR TITLE
Install usefull behat extensions

### PR DESCRIPTION
**Pull request by alexschedrov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build670 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build670 |
| Installation process | http://install.openy-dev.ffwua.com/build670/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/670/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build670/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build671 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build671 |
| Installation process | http://install.openy-dev.ffwua.com/build671/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/671/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build671/profiles/openy/build/reports/behat

**Comment by AlexNetman** [comment]
Part of tests seems failing on "fill in" directive.
So we may try to fix this by changing steps:
'I fill in the following:'  to 'I fill the following:'
I fill in "field" with "value" to  'I fill "field" with "value"'

Test result was having no failed steps.
Just some of them was looking as not defined.
3 features failed of 12 features
12 scenarios failed of 32 scenarios

Also need to make sure that JS errors are not tried to be tracked in headless php tests.

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build726 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build726 |
| Installation process | http://install.openy-dev.ffwua.com/build726/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/726/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build726/profiles/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/756/

**Build Log**
*last 25 lines*

 ```
[...truncated 651 lines...]
#41 {main}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=19   changed=11   unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build757 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build757 |
| Installation process | http://install.openy-dev.ffwua.com/build757/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/757/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build757/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build758 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build758 |
| Installation process | http://install.openy-dev.ffwua.com/build758/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/758/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build758/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build759 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build759 |
| Installation process | http://install.openy-dev.ffwua.com/build759/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/759/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build759/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build761 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build761 |
| Installation process | http://install.openy-dev.ffwua.com/build761/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/761/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build761/profiles/contrib/openy/build/reports/behat

**Pull request closed without merging**
