### PR TITLE
[OPENY-240] Fixed styles of Limited Time Offer paragraph

### PR DESCRIPTION
**Pull request by miroslav-lee**
## Issue details:
When add Limited Time Offer paragraph, we can see ugly banner
banner

## Step for review:
- [x] Sign up as admin
- [x] Add new page of Landing page CT
- [x] Add Limited Time Offer paragraph to Content area
- [x] Save this page
- [x] Check that padding is missing.
banner

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1233 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1233 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1233 |
| Installation process | http://install.openy.cibox.tools/build1233/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1233/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1233/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1233/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1233/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1233/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1233/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
Looks good
Thank you
image

**Pull request merged**
