### PR TITLE
Fix Footer Menu editing links position #191: Also fixed overlapping o…

### PR DESCRIPTION
**Pull request by tolichka**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [x] Please provide steps for review here.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1317 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1317 |
| Installation process | http://install.openy-dev.ffwua.com/build1317/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1317/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1317/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1318 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1318 |
| Installation process | http://install.openy-dev.ffwua.com/build1318/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1318/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1318/profiles/contrib/openy/build/reports/behat

**Comment by ddrozdik** [comment]
@tolichka please provide steps for review

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1326 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1326 |
| Installation process | http://install.openy-dev.ffwua.com/build1326/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1326/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1326/profiles/contrib/openy/build/reports/behat

**Comment by tolichka** [comment]
@ddrozdik Steps for review:
1) Login as admin.
2) Scroll to the bottom of website
3) Hover for any footer nav

As a result you will see that edit button dont overlap any right positioned elements.

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
