### PR TITLE
[CIYMCA-150] Schedules aligning

### PR DESCRIPTION
**Pull request by AleksandrPrykhodkoDev**
Steps for review:

- [ ] turn on theme carnation
- [ ] visit page schedules
- [ ] schedules align in 1 line

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
@AleksandrPrykhodkoDev steps for review are not clear
Could you enrich it with Screenshots?
Also, could you compare output in Rose and Lily before/after and provide those as well?

**Comment by afi13** [comment]
@AleksandrPrykhodkoDev looks weird now, we should keep spacing between sidebar and content blocks.
Screenshot from 2019-12-17 17-06-41

**Review by afi13 — CHANGES_REQUESTED** [review]
Layout is not ok now

**Pull request closed without merging**
