### PR TITLE
Updating node templates to render AddThis

### PR DESCRIPTION
**Pull request by rootdamato**
Related to https://github.com/ymcatwincities/openy/issues/1145

## Steps for review

- [x] Create or edit a Node Landing Page
- [x] On the edit form check the `Enable AddThis` checkbox
- [x] Save the form
- [x] You should be able to see the AddThis buttons.

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/1162) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by kolesnikoff** [comment]
@podarok please review

**Comment by podarok** [comment]
ok to test

**Review by podarok — APPROVED** [review]
Code looks good

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build589 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build589 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build589 |
| Installation process | http://install.openy.cibox.tools/build589/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/589/

**Pull request merged**
