### PR TITLE
[PHP7.2] Converting each to foreach

### PR DESCRIPTION
**Pull request by podarok**
Check install process

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1652 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1652 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1652 |
| Installation process | http://install.openy.cibox.tools/build1652/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1652/

**Review by danylevskyi — APPROVED** [review]
Amazing!

**Comment by danylevskyi** [comment]
@podarok just got this error while installing.

```
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /build1652/core/install.php?rewrite=ok&profile=openy&terms_and_conditions=1&langcode=en&id=4&op=do_nojs&op=do
StatusText: OK
ResponseText: 
| Open Y
@import url("/build1652/core/assets/vendor/normalize-css/normalize.css?0");
@import url("/build1652/core/misc/normalize-fixes.css?0");
@import url("/build1652/core/themes/stable/css/system/components/ajax-progress.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/align.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/autocomplete-loading.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/fieldgroup.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/container-inline.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/clearfix.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/details.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/hidden.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/item-list.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/js.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/nowrap.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/position-container.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/progress.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/reset-appearance.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/resize.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/sticky-header.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/system-status-counter.css?0");
@import url("/build1652/core/themes/stable/css/system/components/system-status-report-counters.css?0");
@import url("/build1652/core/themes/stable/css/system/components/system-status-report-general-info.css?0");
@import url("/build1652/core/themes/stable/css/system/components/tabledrag.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/tablesort.module.css?0");
@import url("/build1652/core/themes/stable/css/system/components/tree-child.module.css?0");
@import url("/build1652/core/themes/stable/css/system/system.admin.css?0");
@import url("/build1652/core/themes/stable/css/system/system.maintenance.css?0");
@import url("/build1652/core/themes/seven/css/base/elements.css?0");
@import url("/build1652/core/themes/seven/css/base/typography.css?0");
@import url("/build1652/core/themes/seven/css/base/print.css?0");
@import url("/build1652/core/themes/seven/css/layout/layout.css?0");
@import url("/build1652/core/themes/classy/css/components/action-links.css?0");
@import url("/build1652/core/themes/classy/css/components/breadcrumb.css?0");
@import url("/build1652/core/themes/classy/css/components/button.css?0");
@import url("/build1652/core/themes/classy/css/components/collapse-processed.css?0");
@import url("/build1652/core/themes/classy/css/components/container-inline.css?0");
@import url("/build1652/core/themes/classy/css/components/exposed-filters.css?0");
@import url("/build1652/core/themes/classy/css/components/field.css?0");
@import url("/build1652/core/themes/classy/css/components/form.css?0");
@import url("/build1652/core/themes/classy/css/components/icons.css?0");
@import url("/build1652/core/themes/classy/css/components/inline-form.css?0");
@import url("/build1652/core/themes/classy/css/components/item-list.css?0");
@import url("/build1652/core/themes/classy/css/components/link.css?0");
@import url("/build1652/core/themes/classy/css/components/links.css?0");
@import url("/build1652/core/themes/classy/css/components/menu.css?0");
@import url("/build1652/core/themes/classy/css/components/more-link.css?0");
@import url("/build1652/core/themes/classy/css/components/pager.css?0");
@import url("/build1652/core/themes/classy/css/components/tabledrag.css?0");
@import url("/build1652/core/themes/classy/css/components/tableselect.css?0");
@import url("/build1652/core/themes/classy/css/components/tablesort.css?0");
@import url("/build1652/core/themes/classy/css/components/tabs.css?0");
@import url("/build1652/core/themes/classy/css/components/textarea.css?0");
@import url("/build1652/core/themes/classy/css/components/ui-dialog.css?0");
@import url("/build1652/core/themes/classy/css/components/messages.css?0");
@import url("/build1652/core/themes/classy/css/components/progress.css?0");
@import url("/build1652/core/themes/seven/css/components/admin-list.css?0");
@import url("/build1652/core/themes/seven/css/components/content-header.css?0");
@import url("/build1652/core/themes/seven/css/components/container-inline.css?0");
@import url("/build1652/core/themes/seven/css/components/container-inline.module.css?0");
@import url("/build1652/core/themes/seven/css/components/breadcrumb.css?0");
@import url("/build1652/core/themes/seven/css/components/buttons.css?0");
@import url("/build1652/core/themes/seven/css/components/details.css?0");
@import url("/build1652/core/themes/seven/css/components/messages.css?0");
@import url("/build1652/core/themes/seven/css/components/dropbutton.component.css?0");
@import url("/build1652/core/themes/seven/css/components/entity-meta.css?0");
@import url("/build1652/core/themes/seven/css/components/field-ui.css?0");
@import url("/build1652/core/themes/seven/css/components/form.css?0");
@import url("/build1652/core/themes/seven/css/components/help.css?0");
@import url("/build1652/core/themes/seven/css/components/menus-and-lists.css?0");
@import url("/build1652/core/themes/seven/css/components/modules-page.css?0");
@import url("/build1652/core/themes/seven/css/components/node.css?0");
@import url("/build1652/core/themes/seven/css/components/page-title.css?0");
@import url("/build1652/core/themes/seven/css/components/pager.css?0");
@import url("/build1652/core/themes/seven/css/components/panel.css?0");
@import url("/build1652/core/themes/seven/css/components/skip-link.css?0");
@import url("/build1652/core/themes/seven/css/components/tables.css?0");
@import url("/build1652/core/themes/seven/css/components/search-admin-settings.css?0");
@import url("/build1652/core/themes/seven/css/components/tablesort-indicator.css?0");
@import url("/build1652/core/themes/seven/css/components/system-status-report-general-info.css?0");
@import url("/build1652/core/themes/seven/css/components/system-status-report.css?0");
@import url("/build1652/core/themes/seven/css/components/system-status-report-counters.css?0");
@import url("/build1652/core/themes/seven/css/components/system-status-counter.css?0");
@import url("/build1652/core/themes/seven/css/components/tabs.css?0");
@import url("/build1652/core/themes/seven/css/components/views-ui.css?0");
@import url("/build1652/core/themes/seven/css/theme/colors.css?0");
@import url("/build1652/core/themes/seven/css/theme/maintenance-page.css?0");
@import url("/build1652/profiles/contrib/openy/themes/openy_themes/openy_admin/css/install-page.css?0");
Skip to main content
Open Y
8.x-2.1.4-dev
Installation tasks
Terms and Conditions
Choose language
Verify requirements
Set up database
Install site
Configure site
Select installation type
Select theme
Import demo content
Read font info
Processing
0%
Initializing. 
{"path":{"baseUrl":"\/build1652\/core\/install.php\/","scriptPath":null,"pathPrefix":"","currentPath":"","currentPathIsAdmin":false,"isFront":false,"currentLanguage":"en","currentQuery":{"_format":"json","id":"5","langcode":"en","op":"start","profile":"openy","rewrite":"ok","terms_and_conditions":"1"}},"pluralDelimiter":"\u0003","ajaxPageState":{"libraries":"classy\/base,classy\/messages,classy\/progress,core\/drupal.batch,core\/html5shiv,core\/normalize,seven\/install-page","theme":"openy_admin","theme_token":null},"ajaxTrustedUrl":[],"batch":{"errorMessage":"An error has occurred.\u003Cbr \/\u003EPlease continue to \u003Ca href=\u0022\/build1652\/core\/install.php?rewrite=ok\u0026amp;profile=openy\u0026amp;terms_and_conditions=1\u0026amp;langcode=en\u0026amp;id=5\u0026amp;op=finished\u0026amp;_format=json\u0022\u003Ethe error page\u003C\/a\u003E","initMessage":"Initializing.\u003Cbr\/\u003E\u0026nbsp;","uri":"\/build1652\/core\/install.php?rewrite=ok\u0026profile=openy\u0026terms_and_conditions=1\u0026langcode=en\u0026id=5\u0026op=do_nojs\u0026_format=json"},"user":{"uid":0,"permissionsHash":"e3bb86b7322087983fe60d968fe650bf41d8283d7775ddf749956c4e3622a7b5"}}
```

Could it be related?

**Comment by podarok** [comment]
@danylevskyi http://install.openy.cibox.tools/build1652/ I've installed it on my end, works well
So only code review and merge, please

**Pull request merged**
