### PR TITLE
[refs-733] Sniffer notices in the openy_map/map.js

### PR DESCRIPTION
**Pull request by ddrozdik**
Issue https://github.com/ymcatwincities/openy/issues/733

Steps for review:
- [x] review code changes
- [x] Go to Locations page
- [x] Verify map is working, nothing changed.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2026 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2026 |
| Installation process | http://install.openy-dev.ffwua.com/build2026/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2026/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build2026

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2026/profiles/contrib/openy/build/reports/behat

**Review by Kerby70 — APPROVED** [review]
This is good, all cleanup, no functionality code changes.

**Pull request merged**
