### PR TITLE
[OYPD-549][OYPD-547] Microsites menu behat test and tour.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issues: 
https://propeople-us.atlassian.net/browse/OYPD-548
https://propeople-us.atlassian.net/browse/OYPD-549
Drupal.org issues: 
https://www.drupal.org/node/2899564
https://www.drupal.org/node/2899565

# Steps to review tour:
- [ ] look to 
- [ ] go to /node/add/landing_page
- [ ] click on Tour in the top and rigth
- [ ] verify you can see steps for Microsutes menu

Check behat test for Microsites menu here https://github.com/ymcatwincities/openy/pull/732/files#diff-9d4a0d277ec6e5db49be99c270d8d8b5R14

Also I fix OpenY Tour, please look to https://github.com/ymcatwincities/openy/pull/732/files#diff-7854481feb41852f24f2001a9c265f00R24

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2017 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2017 |
| Installation process | http://install.openy-dev.ffwua.com/build2017/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2017/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2017

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2018 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2018 |
| Installation process | http://install.openy-dev.ffwua.com/build2018/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2018/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2018

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2017/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2018/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2019 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2019 |
| Installation process | http://install.openy-dev.ffwua.com/build2019/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2019/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2019

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2019/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2021 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2021 |
| Installation process | http://install.openy-dev.ffwua.com/build2021/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2021/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2021

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2021/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2023 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2023 |
| Installation process | http://install.openy-dev.ffwua.com/build2023/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2023/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2023

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2023/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2028 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2028 |
| Installation process | http://install.openy-dev.ffwua.com/build2028/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2028/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build2028

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2028/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2039 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2039 |
| Installation process | http://install.openy-dev.ffwua.com/build2039/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2039/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build2039

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2039/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2039/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2039/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2039/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2039/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2039/profiles/contrib/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Pull request merged**
