### PR TITLE
Page of Class content type loading is very long time

### PR DESCRIPTION
**Pull request by miroslav-lee**
## Issue details:
When go to on a Class content type first time, and on this page a lot of sessions, it is loading is very long time. Because it is loading all sessions.
I think, if you aren't chose location on popup, sessions shouldn't view on a page. 

## Steps for review

- [ ] Go to any page of Class content type
- [ ] You shouldn't see nothing sessions, before you aren't chose location on popup

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by AndreyMaximov** [comment]
o+k to test

**Comment by AndreyMaximov** [comment]
ok to test

**Comment by AndreyMaximov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1202 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1202 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1202 |
| Installation process | http://install.openy.cibox.tools/build1202/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1202/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1202/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1202/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1202/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1202/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1202/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Pull request merged**
