### PR TITLE
[OYPD-298] Adjusting embedded video and image captions

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Add nodes for different content types; landing page, blog posts, etc.
- [x] Embed video and image using WYSIWYG. Add caption text for embedded items.
- [x] Check the size and position of caption text when page is viewed. Text is smaller, italic, and right justified.
- [x] Check full size, half size, left, center, right, etc.

screen shot 2017-03-02 at 12 07 37 am
screen shot 2017-03-02 at 12 07 00 am
screen shot 2017-03-01 at 11 56 28 pm
screen shot 2017-03-01 at 11 55 52 pm
screen shot 2017-03-01 at 11 55 29 pm
screen shot 2017-03-01 at 11 54 48 pm

### CODE REVIEW

**Comment by david-hernandez** [comment]
The large space that appeared below some images was not caused by the caption. It was caused by styling on the blog post pages. The space only appeared on blogs. I adjusted that styling to remove the space for embedded items. That is why there are changes to the blog scss file.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build636 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build636 |
| Installation process | http://install.openy-dev.ffwua.com/build636/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/636/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build636/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
