### PR TITLE
[MAINTAIN-10] fixed a white background for local video in Safari browser

### LINKED ISSUE #1164: Local video player doesn't have border on table
Video player for location doesn't have any border in Safari. Which looks strange on iPad.
image

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: #1164 
Jira issue [MAINTAIN-10](https://openy.atlassian.net/browse/MAINTAIN-10)

This one should fix white background for Location Video on Safari browser for all 3 themes.
How it looks before this fix:
Rose:
MAINTAIN-10-RoseBefore
Lily:
MAINTAIN-10-LilyBefore

Carnation:
MAINTAIN-10-CarantionBefore

How it should looks after fix:
Rose:
MAINTAIN-10-fixedRose

Lily:
MAINTAIN-10-fixedLily

Carnation:
MAINTAIN-10-fixedCarnation

## Steps for review

- [ ] log as admin.
- [ ] create a new Landing page (Please fiil all fields: Title, Layout->One Column)
- [ ] in Content Area pleas add a new Simple content paragraph
- [ ] in this paragraph please add a new media entty **Local video** 
MAINTAIN-10-addLocalVideo
- [ ] save and check on Safari browser
- [ ] Go to the /admin/appearance page
- [ ] change theme and check for new theme

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by hamrant — APPROVED** [review]
Code looks ok

**Comment by hamrant** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3120/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3120/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3120/

**Comment by ekaterina-samuseva** [comment]
Fix was checked on iPhone 11 Pro, iOS 14.1, Safari
Page with added local video: http://upgrade.openy.cibox.tools/build3120/ekaterina-test 
image
image
image

**Review by podarok — APPROVED** [review]

**Pull request merged**
