### PR TITLE
[CR-40] Four columns paragraph fix (carnation)

### PR DESCRIPTION
**Pull request by hamrant**
## Original Issue, this PR is going to fix: 

On carnation theme 4 columns paragraph not work as expected

screenshot-openy-origin docksal-2020 08 31-12_17_10

## Steps for review

- [ ] Login as admin
- [ ] Create landing page with 4 columns paragraph

screenshot-openy-origin docksal-2020 08 31-12_16_27

- [ ] Check that it looks ok on all resolutions

Screenshot from 2020-08-31 12-42-47

Screenshot from 2020-08-31 13-41-47

Screenshot from 2020-08-31 13-42-42

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2455/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2455/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2455/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2455/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2455/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2455/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2455/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2455/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2455/

**Review by podarok — APPROVED** [review]

**Pull request merged**
