### PR TITLE
[OYPD-380] Adding header footer template module

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] On a new build check that header.html and footer.html return desired result.

screen shot 2017-04-19 at 10 58 00 am
screen shot 2017-04-19 at 10 57 51 am

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build980 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build980 |
| Installation process | http://install.openy-dev.ffwua.com/build980/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/980/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build980/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build985 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build985 |
| Installation process | http://install.openy-dev.ffwua.com/build985/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/985/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build985/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@david-hernandez looks awesome! Only 1 thing - please enable module in update https://github.com/ymcatwincities/openy/blob/8.x-1.x/openy.install#L168

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build994 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build994 |
| Installation process | http://install.openy-dev.ffwua.com/build994/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/994/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build994/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
