### PR TITLE
Taxonomy page in sitemap

### PR DESCRIPTION
**Pull request by yasik78**
Taxonomy page in sitemap  https://github.com/ymcatwincities/openy/issues/376

## Steps for review

- [ ] Go to  /sitemap.xml 
- [ ] Find  text blog/category/adults

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Comment by alexschedrov** [comment]
1. "Area" vocabulary should be added to the sitemap as well.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1743 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1743 |
| Installation process | http://install.openy-dev.ffwua.com/build1743/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1743/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1743

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1743

**Pull request closed without merging**
