### PR TITLE
OS-235: fix assessebility error for scroll top link.

### PR DESCRIPTION
**Pull request by SanyokMedved**
Steps for reproduce:
Download extension. http://wave.webaim.org/extension/
Open site. 
Enable extension.
Check Scroll To Top link with extension. There is no any Alerts now.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1576 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1576 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1576 |
| Installation process | http://install.openy.cibox.tools/build1576/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1576/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1576/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1576/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1576/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1576/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1576/blogWCAG2AAhtmlcs.txt

**Comment by kolesnikoff** [comment]
@podarok please review.

**Comment by podarok** [comment]
@kolesnikoff is this actual for lily or for all other themes?

**Comment by SanyokMedved** [comment]
This link is only in Lilly theme. Other themes don't have this link.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1578 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1578 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1578 |
| Installation process | http://install.openy.cibox.tools/build1578/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1578/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1578/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1578/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1578/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1578/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1578/blogWCAG2AAhtmlcs.txt

**Pull request merged**
