### PR TITLE
Trying to change failing Plugin Block field to view_field_view

### LINKED ISSUE #2138: TypeError: Argument 1 passed to Drupal\Core\Cache\CacheableMetadata::applyTo() must be of the type array, null given,
Adding Social List paragraph to Landing Page
```
TypeError: Argument 1 passed to Drupal\Core\Cache\CacheableMetadata::applyTo() must be of the type array, null given, called in /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/modules/contrib/plugin/src/Plugin/Plugin/PluginSelector/AdvancedPluginSelectorBase.php on line 76 in Drupal\Core\Cache\CacheableMetadata->applyTo() (line 135 of /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Cache/CacheableMetadata.php)
#0 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/modules/contrib/plugin/src/Plugin/Plugin/PluginSelector/AdvancedPluginSelectorBase.php(76): Drupal\Core\Cache\CacheableMetadata->applyTo()
#1 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/modules/contrib/plugin/src/Plugin/Field/FieldWidget/PluginSelector.php(60): Drupal\plugin\Plugin\Plugin\PluginSelector\AdvancedPluginSelectorBase->buildSelectorForm()
#2 [internal function]: Drupal\plugin\Plugin\Field\FieldWidget\PluginSelector::processFormElement()
#3 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1009): call_user_func_array()
#4 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#5 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#6 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#7 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#8 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#9 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#10 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#11 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(445): Drupal\Core\Form\FormBuilder->doBuildForm()
#12 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(629): Drupal\Core\Form\FormBuilder->rebuildForm()
#13 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm()
#14 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#15 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#16 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#17 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#18 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#19 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#20 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#21 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#22 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle()
#23 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle()
#24 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#25 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#26 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/profiles/contrib/openy/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle()
#27 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle()
#28 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#29 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#30 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/DrupalKernel.php(705): Stack\StackedHttpKernel->handle()
#31 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/index.php(19): Drupal\Core\DrupalKernel->handle()
#32 {main}
.
```

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

## Steps for review

- [ ] Add LP with Social List component. It should be able to add it to a page with no errors
- [ ] Check in Rose - should look like this 
image
- [ ] Check the same on upgrade path build
- [ ] Verify there are no outdated base field definitions in the Status report screen of the Upgrade path build

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2646/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2646/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2646/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2646/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2646/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2646/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2646/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2646/

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2647/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2647/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2647/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2647/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2647/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2647/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2647/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2647/

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2647/

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2648/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2648/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2648/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2648/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2648/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2648/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2648/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2648/

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2648/

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2665/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2665/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2665/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2665/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2665/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2665/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2665/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2665/

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2666/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2666/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2666/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2666/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2666/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2666/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2666/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2666/

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2665/

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2666/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2667/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2667/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2667/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2667/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2667/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2667/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2667/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2667/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2667/

**Comment by danylevskyi** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2670/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2670/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2670/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2670/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2670/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2670/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2670/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2670/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2670/

**Pull request merged**
