### PR TITLE
[OPENY-244] Change background image to the installation process

### PR DESCRIPTION
**Pull request by miroslav-lee**
## Steps for review

- [ ] Run the installation of site.
- [x] Check that the background image is the same as pictures.

Desktop
Desktop

Tablet
Tablet

Mobile
Mobile

Thank you for your contribution!

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1297 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1297 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1297 |
| Installation process | http://install.openy.cibox.tools/build1297/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1297/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1298 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1298 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1298 |
| Installation process | http://install.openy.cibox.tools/build1298/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1298/

**Pull request merged**
