### PR TITLE
[OYPD-423] Add ability to javascript events on Tours.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue https://propeople-us.atlassian.net/browse/OYPD-423
Drupal.org issue: 

Steps:
- [ ] login as admin
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1266 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1266 |
| Installation process | http://install.openy-dev.ffwua.com/build1266/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1266/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1266/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1286 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1286 |
| Installation process | http://install.openy-dev.ffwua.com/build1286/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1286/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1286/profiles/contrib/openy/build/reports/behat

**Pull request closed without merging**
