### PR TITLE
[OYPD-119] Remove block title

### PR DESCRIPTION
**Pull request by danylevskyi**
Task: OYPD-119

### How to review

- [x] Add landing page with `blog post listing` paragraph
- [x] Make sure there is no `VERF` title
- [x] Make sure there is no `block` title on exposed filters

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build319

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/319/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build319/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build320

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/320/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build320/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build325

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/325/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build325/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
