### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by podarok**
```
There are only two hard things in Computer Science: cache invalidation and naming things.

(c)Phil Karlton
```

**And third one - dependencies - (c)OpenY**

There is a datalayer module in dependencies of the config, but the module is not added to openy_node_landing info file
https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/openy_features/openy_node/modules/openy_node_landing/config/install/field.field.node.landing_page.field_meta_tags.yml#L8

This fix helps to get openy_node_landing enabled on non OpenY projects

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1383 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1383 |
| Installation process | http://install.openy-dev.ffwua.com/build1383/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1383/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1383/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Move to separate queue, since needs more work.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1428 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1428 |
| Installation process | http://install.openy-dev.ffwua.com/build1428/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1428/

**Pull request closed without merging**
