### PR TITLE
[OYPD 626] Updating templates, css, and default config for making the site slogan appear in the header

### PR DESCRIPTION
**Pull request by david-hernandez**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Add site slogan at /admin/config/system/site-information
- [ ] Enabled site slogan in the branding block. /admin/structure/block/manage/openy_rose_branding
- [ ] Look at header. See screenshots.
- [ ] Turn on and off the slogan to see if displays well both ways.

screen shot 2017-12-06 at 3 23 29 pm
screen shot 2017-12-06 at 3 23 16 pm
screen shot 2017-12-06 at 3 23 02 pm

### CODE REVIEW

**Comment by david-hernandez** [comment]
I didn't add an upgrade path. Do we want this forced on for existing installations? If so, where should the update function go? In the profile?

**Comment by david-hernandez** [comment]
I forgot about altering the form to change the text to “This will display your association name in the header as per Y USA brand guidelines”. I'm assuming a form alter. What module should that go in?

**Comment by david-hernandez** [comment]
I went ahead and added it to the profile.

**Comment by david-hernandez** [comment]
screen shot 2017-12-06 at 4 35 49 pm

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build120 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build120 |
| Installation process | http://install.openy-dev.ffwua.com/build120/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/120/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build120/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build120/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build120/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build120/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build120/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build120/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build120/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by alexschedrov** [comment]
1. Main menu and User menu are not clickable anymore on Desktop
2. Please add default value for the slogan "Open YMCA"

**Comment by david-hernandez** [comment]
That commit should fix the clicking issue. I also added default value for the install config. I had the earlier question about upgrade path. Do we want to do that?

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build124 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build124 |
| Installation process | http://install.openy-dev.ffwua.com/build124/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/124/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build124/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build124/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build124/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build124/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build124/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL http://ci.openymca.org/build124/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build124/profiles/contrib/openy/build/reports/behat/screenshots

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
