### PR TITLE
Fix description for landing_page.field_content.yml

### PR DESCRIPTION
**Pull request by alex-poletaev**
Fixed description for field.field.node.landing_page.field_content.yml

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

Open http://ci.openymca.org/build1449
1.Login as admin
2.Go to Administration -> Structure -> Content types -> Landing Page -> Manage Fields -> field_content -> Edit.
3.Check if Help text present

- [x] Please provide steps for review here.

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Review by alexschedrov — APPROVED** [review]
Code looks good.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1449 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1449 |
| Installation process | http://install.openy-dev.ffwua.com/build1449/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1449/

**Comment by alex-poletaev** [comment]
Steps for review:

1. Open http://ci.openymca.org/build1449
2. Login as admin
3. Go to Administration -> Structure -> Content types -> Landing Page -> Manage Fields -> field_content -> Edit.
4. Check if Help text present

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
