### PR TITLE
[RGTC-1280] Replace deprecated method rightJoin

### LINKED ISSUE #2116: Error: Call to undefined method Drupal\Core\Database\Query\Select::rightJoin()
See https://www.drupal.org/node/2765249

/schedules/get-pdf?categories=&date=2020-08-27&limit=Cardio%2CStrength%2CForever%20Well&locations=&rooms=

```
Error: Call to undefined method Drupal\Core\Database\Query\Select::rightJoin() in Drupal\openy_repeat\Controller\RepeatController->getData() (line 453 of /home/jenkins/workspace/D9_SANDBOX_CARNATION_CUSTOM/build/docroot/profiles/contrib/openy/modules/custom/openy_repeat/src/Controller/RepeatController.php)
#0 /home/jenkins/workspace/D9_SANDBOX_CARNATION_CUSTOM/build/docroot/profiles/contrib/openy/modules/custom/openy_repeat/src/Controller/RepeatController.php(772): Drupal\openy_repeat\Controller\RepeatController->getData()
#1 /home/jenkins/workspace/D9_SANDBOX_CARNATION_CUSTOM/build/docroot/profiles/contrib/openy/modules/custom/openy_repeat/src/Controller/RepeatController.php(715): Drupal\openy_repeat\Controller\RepeatController->getPdfContent()
#2 [internal function]: Drupal\openy_repeat\Controller\RepeatController->getPdf()
```

### PR DESCRIPTION
**Pull request by shuklina**
Issue: https://github.com/ymcatwincities/openy/issues/2116

Make sure that the deprecated method `rightJoin` is replaced.

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2452/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2452/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2452/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2452/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2452/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2452/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2452/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2452/

**Comment by podarok** [comment]
works great, thank you

**Pull request merged**
