### PR TITLE
[OYPD-477] Gallery next/previous buttons are not keyboard operable.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-477
Drupal.org issue: https://www.drupal.org/node/2885460

# Steps to review:
- [x] Go to [sitename]/locations/west-ymca
- [x] Click "Tab" on keybord 
- [x] When you have focused on the Left Arrow or Right  in the Gallery
- [x] Verify you can see blue border near the Left Arrow or Right buttons

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1510 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1510 |
| Installation process | http://install.openy-dev.ffwua.com/build1510/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1510/

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1511 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1511 |
| Installation process | http://install.openy-dev.ffwua.com/build1511/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1511/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1510/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1511/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1515 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1515 |
| Installation process | http://install.openy-dev.ffwua.com/build1515/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1515/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1515/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1524 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1524 |
| Installation process | http://install.openy-dev.ffwua.com/build1524/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1524/

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1531 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1531 |
| Installation process | http://install.openy-dev.ffwua.com/build1531/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1531/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1531/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
