### PR TITLE
Remove block which is not used

### LINKED ISSUE #1928: GroupExScheduleFetcher cache not validated correctly
When a user visits a page using the Groupex Pro `group_schedules` block, once they've made the initial selection, changing the form does not update the results.

After some debugging, I discovered that by commenting out
```
 if ($this->schedule) {
   return $this->schedule;
 }  
```
line 127 in `docroot/profiles/contrib/openy/modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php` the results will update correctly.

Suggestion: we need to check that the parameters are the same for the new query, and not just that the schedule exists.

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/1928 + https://openy.atlassian.net/browse/MAINTAIN-20

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Just a code review. We are not using cache, which was glitchy anyway
- [ ] Add Group Schedules on LP and check it is working http://upgrade.openy.cibox.tools/build3204/demo-landing?location=5729&filter_date=6/07/21
image

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3204/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3204/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3204/

**Review by hamrant — CHANGES_REQUESTED** [review]
In this case we can remove everything related to this:

```php
$this->schedule = $schedule;
return $this->schedule;
```
just `return $schedule;`

And remove 
```php
  /**
   * Cached schedule.
   *
   * @var array
   */
  private $schedule = [];
```

**Review by hamrant — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3205/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3205/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3206/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3206/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3205/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3206/

**Pull request merged**
