### PR TITLE
Update tour.tour.openy-menu-management.yml

### PR DESCRIPTION
**Pull request by Robert201-zz**
update menu management tour

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build342

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/342/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build342/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build350

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/350/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build350/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
