### PR TITLE
[OYPD-482] on sub category page the image is the hot link and it come before the title which is the header.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-482
Drupal.org issue: https://www.drupal.org/node/2885742

# Steps to review:
- [x] go to page [sitename]/programs/swimming
- [x] inspect content item
Please look: https://propeople-us.atlassian.net/secure/thumbnail/40938/Screen+Shot+2017-06-06+at+16.56.50.png?default=false
- [x] verify in article tag title first and above all links

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1519 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1519 |
| Installation process | http://install.openy-dev.ffwua.com/build1519/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1519/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1519/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1538 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1538 |
| Installation process | http://install.openy-dev.ffwua.com/build1538/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1538/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1538/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
