### PR TITLE
[INOYI-22]: [Rose theme] Half size image alignment

### LINKED ISSUE #1803: [Rose theme] Half size image alignment
I faced the issue in the Rose theme while I was trying to embed the image with the options of half size and center alignment in the Header area. After saving the page, the image was not centered in the header.

The steps how to reproduce

1. Add content of some kind. I did Landing Page.
2. Choose Layout - One column Full width
3. Expand Header Area and add 1 column
4. Embed Image in WYSIWYG editor
5. Select options look for the image: Half  and Center
6. Save
7. The image will be aligned in the left, not centered.

alignment

**Expected Result**:
The image in the header area is centered.

### PR DESCRIPTION
**Pull request by AleksandrPrykhodkoDev**
Original Issue: https://github.com/ymcatwincities/openy/issues/1803

## Steps for review

- [ ] Add content of some kind. I did a Landing Page
- [ ] Choose Layout - One column Full width
- [ ] Expand Header Area and add 1 column
- [ ] Embed Image in WYSIWYG editor
- [ ] Select options look for the image: Half and Center
- [ ] Save
- [ ] The image will be centered
- [ ] Also fixed in Lily theme

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by AndreyMaximov** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2141/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2141/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2141/

**Review by ddrozdik — APPROVED** [review]

**Review by podarok — APPROVED** [review]

**Pull request merged**
