### PR TITLE
[OYPD-363] Add post-install and post-update action to remove docroot from the profile folder.

### PR DESCRIPTION
**Pull request by Kerby70**
I'd like to get feedback on how to test this for a normal openy-project requirement process. I am currently assuming the scripts are triggered relative to the library but haven't found a description stating that.

Jira https://propeople-us.atlassian.net/browse/OYPD-363
D.o https://www.drupal.org/node/2877010

Make sure these boxes are checked before asking for review of your pull request - thank you!

Steps to review: Code only 

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1130/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #345 of commit af5a22e7cf9ff4017452b0fd96005116c2ff2e23.
GitHub pull request #345 of commit af5a22e7cf9ff4017452b0fd96005116c2ff2e23.
GitHub pull request #345 of commit af5a22e7cf9ff4017452b0fd96005116c2ff2e23.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git8735177415813099457.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git4961751990680410854.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse af5a22e7cf9ff4017452b0fd96005116c2ff2e23^{commit} # timeout=10
 > git branch -a --contains af5a22e7cf9ff4017452b0fd96005116c2ff2e23 # timeout=10
 > git rev-parse remotes/origin/pr/345/head^{commit} # timeout=10
Checking out Revision af5a22e7cf9ff4017452b0fd96005116c2ff2e23 (origin/pr/345/head)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f af5a22e7cf9ff4017452b0fd96005116c2ff2e23
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson6482981562478052496.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory1186587644897258376.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1130 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory1056355180234186256.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1130 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1130/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1130 -e drupal_folder=/var/www/build1130 -e site_url=http://openy-dev.ffwua.com/build1130 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
changed: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [localhost] => (item={'status': True, 'name': '$config["system.file"]["path.temporary"]', 'value': '/tmp'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
skipping: [localhost]

TASK: [Creating drupal database] ********************************************** 
skipping: [localhost]

TASK: [Downloading latest backup to local environment] ************************ 
skipping: [localhost]

TASK: [Removing possible abandoned dump] ************************************** 
skipping: [localhost]

TASK: [Importing from remote backup] ****************************************** 
skipping: [localhost]

TASK: [Copy latest backup to build folder] ************************************ 
skipping: [localhost]

TASK: [Importing from local backup] ******************************************* 
skipping: [localhost]

TASK: [Remove local backup from build folder] ********************************* 
skipping: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
skipping: [localhost]

TASK: [Clear Drupal cache] **************************************************** 
skipping: [localhost]

TASK: [Updating database] ***************************************************** 
skipping: [localhost]

TASK: [Apply pending entity schema updates] *********************************** 
skipping: [localhost]

TASK: [Download stage file proxy] ********************************************* 
skipping: [localhost]

TASK: [Enable stage file proxy] *********************************************** 
skipping: [localhost]

TASK: [Set configuration for stage file proxy] ******************************** 
skipping: [localhost]

TASK: [Set folder for stage file proxy] *************************************** 
skipping: [localhost]

TASK: [Updates listing] ******************************************************* 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
ok: [localhost]

TASK: [Creating drupal database] ********************************************** 
changed: [localhost]

TASK: [Remove settings.php] *************************************************** 
ok: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
failed: [localhost] => {"changed": true, "cmd": "cd profiles/contrib/openy && APP_ENV=dev drush make drupal-org.make -y --no-core --no-cache", "delta": "0:00:23.199273", "end": "2017-05-09 13:01:12.975768", "rc": 1, "start": "2017-05-09 13:00:49.776495", "warnings": []}
stderr: Beginning to build drupal-org.make.                                  [ok]
features-8.x-3.5 downloaded.                                         [ok]
config_update-8.x-1.3 downloaded.                                    [ok]
entity-8.x-1.0-alpha4 downloaded.                                    [ok]
datalayer-8.x-1.x-dev downloaded.                                    [ok]
datalayer patched with                                               [ok]
2857270-4-fix-entity-reference-field-using-name-property.patch.
Generated PATCHES.txt file for datalayer                             [ok]
media_entity-8.x-1.x-dev downloaded.                                 [ok]
media_entity_image-8.x-1.x-dev downloaded.                           [ok]
media_entity_document-8.x-1.x-dev downloaded.                        [ok]
address-8.x-1.0-rc3 downloaded.                                      [ok]
paragraphs-8.x-1.0 downloaded.                                       [ok]
entity_reference_revisions-8.x-1.2 downloaded.                       [ok]
pathauto-8.x-1.0-rc1 downloaded.                                     [ok]
ctools-8.x-3.0-alpha27 downloaded.                                   [ok]
token-8.x-1.0-rc1 downloaded.                                        [ok]
field_group-8.x-1.0-rc6 downloaded.                                  [ok]
video_embed_field-8.x-1.4 downloaded.                                [ok]
jquery_colorpicker-8.x-1.3 downloaded.                               [ok]
entity_browser-8.x-1.0-rc1 downloaded.                               [ok]
entity_browser patched with 2845037_15.patch.                        [ok]
Generated PATCHES.txt file for entity_browser                        [ok]
dropzonejs-8.x-1.0-alpha3 downloaded.                                [ok]
inline_entity_form-8.x-1.0-beta1 downloaded.                         [ok]
embed-8.x-1.0-rc3 downloaded.                                        [ok]
entity_embed-8.x-1.0-beta2 downloaded.                               [ok]
views_block_filter_block-8.x-1.x-dev downloaded.                     [ok]
Unable to patch views_block_filter_block with                        [error]
empty_exposed_forms-2790505-10.patch.
plugin-8.x-2.4 downloaded.                                           [ok]
plugin patched with plugin-id-2851503-8.patch.                       [ok]
Generated PATCHES.txt file for plugin                                [ok]
libraries-8.x-3.x-dev downloaded.                                    [ok]
migrate_plus-8.x-3.0-beta1 downloaded.                               [ok]
migrate_tools-8.x-3.0-beta1 downloaded.                              [ok]
optimizely-8.x-1.2 downloaded.                                       [ok]
verf-8.x-1.0-beta6 downloaded.                                       [ok]
simple_menu_icons-8.x-1.x-dev downloaded.                            [ok]
simple_menu_icons patched with                                       [ok]
clear-cache-after-simple_menu_icons_css_generate-2847964.patch.
Generated PATCHES.txt file for simple_menu_icons                     [ok]
views_infinite_scroll-8.x-1.3 downloaded.                            [ok]
slick-8.x-1.0-rc1 downloaded.                                        [ok]
slick_views-8.x-1.0-rc2 downloaded.                                  [ok]
blazy-8.x-1.0-rc1 downloaded.                                        [ok]
geolocation-8.x-1.9 downloaded.                                      [ok]
google_tag-8.x-1.x-dev downloaded.                                   [ok]
google_analytics-8.x-2.1 downloaded.                                 [ok]
redirect-8.x-1.0-alpha4 downloaded.                                  [ok]
simple_sitemap-8.x-2.8 downloaded.                                   [ok]
metatag-8.x-1.0 downloaded.                                          [ok]
confi-8.x-1.3 downloaded.                                            [ok]
confi patched with                                                   [ok]
confi-drush-call-hooks-from-disabled-2856910.patch.
Generated PATCHES.txt file for confi                                 [ok]
Drush Make failed to download all projects. See the log above for the[error]
specific errors.
stdout: Make new site in the current directory? (y/n): y
Project features contains 2 modules: features_ui, features.
Project config_update contains 2 modules: config_update_ui, config_update.
Project paragraphs contains 3 modules: paragraphs_type_permissions, paragraphs_demo, paragraphs.
Project ctools contains 3 modules: ctools_views, ctools_block, ctools.
Project field_group contains 2 modules: field_group_migrate, field_group.
Project video_embed_field contains 3 modules: video_embed_media, video_embed_wysiwyg, video_embed_field.
Project entity_browser contains 3 modules: entity_browser_example, entity_browser_entity_form, entity_browser.
Project dropzonejs contains 2 modules: dropzonejs_eb_widget, dropzonejs.
Project migrate_plus contains 5 modules: migrate_example_setup, migrate_example, migrate_example_advanced_setup, migrate_example_advanced, migrate_plus.
Project slick contains 2 modules: slick_ui, slick.
Project blazy contains 2 modules: blazy_ui, blazy.
Project geolocation contains 2 modules: geolocation_google_places_api, geolocation.
Project redirect contains 3 modules: redirect_domain, redirect_404, redirect.
Project metatag contains 14 modules: metatag_app_links, metatag_mobile, metatag_verification, metatag_open_graph_products, metatag_open_graph, metatag_favicons, metatag_dc, metatag_dc_advanced, metatag_google_cse, metatag_hreflang, metatag_google_plus, metatag_twitter_cards, metatag_facebook, metatag.
Project confi contains a module named config_import.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=13   changed=5    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by Kerby70** [comment]
If we want to add something to verify the script is running relative to the script we could add:
```if [ -f "openy.info.yml" ]; then rm -rf docroot/ > /dev/null 2>&1; fi```

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1134 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1134 |
| Installation process | http://install.openy-dev.ffwua.com/build1134/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1134/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1134/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Create folder `scripts` in this projet and place bash file there.
2. Move script to that folder
3. Please add condition `if [ -f "openy.info.yml" ]; then rm -rf docroot/ > /dev/null 2>&1; fi`

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1141 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1141 |
| Installation process | http://install.openy-dev.ffwua.com/build1141/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1141/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1141/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1158 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1158 |
| Installation process | http://install.openy-dev.ffwua.com/build1158/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1158/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1158/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@Kerby70 testing flow is pretty simple. You can override the source for OpenY Installation profile in `composer.json` in `openy-project`. Here is documentation https://github.com/ymcatwincities/openy-project#use-fork-for-the-development

1. Add your fork to the `composer.json` in `openy-project`.
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/Kerby70/openy"
    }
]
```

2. Change version of OpenY installation profile.
```
"require": {
    "ymcatwincities/openy": "dev-OYPD-363",
}
```

3. Run composer update


Whole composer.json from root folder:
```
{
    "name": "ymcatwincities/openy-project",
    "description": "Project template for OpenY projects with composer",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "ymcatwincities/openy": "dev-OYPD-363",
        "composer/installers": "^1.2",
        "drupal-composer/drupal-scaffold": "^2.2",
        "cweagans/composer-patches": "~1.0"
    },
    "require-dev": {
        "ymcatwincities/openy-cibox-build": "dev-master",
        "ymcatwincities/openy-cibox-vm": "dev-master",
        "ymcatwincities/openy-docksal": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Kerby70/openy"
        },
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "package",
            "package": {
                "name": "library-kenwheeler/slick",
                "version": "1.6.0",
                "type": "drupal-library",
                "source": {
                    "url": "https://github.com/kenwheeler/slick",
                    "type": "git",
                    "reference": "1.6.0"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "library-dinbror/blazy",
                "version": "1.8.2",
                "type": "drupal-library",
                "source": {
                    "url": "https://github.com/dinbror/blazy",
                    "type": "git",
                    "reference": "1.8.2"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "library-gdsmith/jquery.easing",
                "version": "1.4.1",
                "type": "drupal-library",
                "source": {
                    "url": "https://github.com/gdsmith/jquery.easing",
                    "type": "git",
                    "reference": "1.4.1"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "library-enyo/dropzone",
                "version": "4.3.0",
                "type": "drupal-library",
                "source": {
                    "url": "https://github.com/enyo/dropzone",
                    "type": "git",
                    "reference": "v4.3.0"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "library-jaypan/jquery_colorpicker",
                "version": "1.0.1",
                "type": "drupal-library",
                "source": {
                    "url": "https://github.com/jaypan/jquery_colorpicker",
                    "type": "git",
                    "reference": "da978ae124c57817021b3166a31881876882f5f9"
                }
            }
        }
    ],
    "scripts": {
        "post-install-cmd": [
            "@composer drupal-scaffold",
            "@cibox-build",
            "@cibox-vm",
            "@docksal"
        ],
        "post-update-cmd": [
            "@cibox-build",
            "@cibox-vm",
            "@docksal"
        ],
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "cibox-build": "[ -d ./vendor/ymcatwincities/openy-cibox-build ] && (rsync -r --exclude=composer.json --exclude=.gitignore --exclude=.git ./vendor/ymcatwincities/openy-cibox-build/ ./docroot) || (rm -rf ./docroot/devops ./docroot/*.sh ./docroot/*.yml ./docroot/*.md ./docroot/ansible.cfg)",
        "cibox-vm": "[ -d ./vendor/ymcatwincities/openy-cibox-vm ] && (rsync -r --exclude=composer.json --exclude=README.md --exclude=.gitignore --exclude=.git --exclude=LICENSE ./vendor/ymcatwincities/openy-cibox-vm/ ./) || (rm -rf cibox provisioning Vagrantfile .vagrant backup cache)",
        "docksal": "[ -d ./vendor/ymcatwincities/openy-docksal ] && (rsync -r --exclude=composer.json --exclude=.git --exclude=README.md ./vendor/ymcatwincities/openy-docksal/ ./) || (rm -rf .docksal build.sh)"
    },
    "extra": {
        "installer-paths": {
            "docroot/core": ["type:drupal-core"],
            "docroot/libraries/{$name}": ["type:drupal-library"],
            "docroot/modules/contrib/{$name}": ["type:drupal-module"],
            "docroot/profiles/contrib/{$name}": ["type:drupal-profile"],
            "docroot/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        },
        "enable-patching": true
    },
    "config": {
        "bin-dir": "vendor/bin/"
    }
}
```

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
