### PR TITLE
[OYS-28] Open Y Data Wrapper documentation

### PR DESCRIPTION
**Pull request by hamrant**
## Steps for review

- [ ] Read documentation
- [ ] Profit

### CODE REVIEW

**Comment by hamrant** [comment]
Hi @podarok!

I have another task related to documentation - `Extend documentation about using prefixes`.

Screenshot from 2019-10-04 20-01-22


Can you share your thoughts and ideas on this?

**Review by anprok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1827 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1827 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1827 |
| Installation process | http://install.openy.cibox.tools/build1827/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1827/

**Comment by podarok** [comment]
@hamrant 
I don't think having prefixes is a viable solution.
Let me explain why

- You have your instance of OpenY and you keep having prefixed version of some component ( In this case - content type )

- Every time OpenY upgrade happen - you have no issues with upgrade, only if there is a dependency from the disabled "vanilla" feature that you have changed one.

- There almost 0 motivation to backport your feature into OpenY and over time legacy nature of prefixed feature makes your site even more non OpenY.

What I'd prefer more - is to decouple some specific component ( in your case Events CT ) into dedicated packagist module. I'd take care about ejecting it to openy/whatever githubrepo and you'd add your changes into a fork of main repo. This will keep connection and we'd have ability to oversee what changes are requested and what blockers we have preventing us from having same functionality in core.


In YGTC we started to think about ejecting all legacy code completely to dedicated repository for composer to collect the code back during upgrade. 
I'm dreaming to see repository where different Y associations keep their changes to specific OpenY component in forks/branches @hamrant

**Comment by podarok** [comment]
@hamrant could you start this topic in community board?

**Pull request merged**
