### PR TITLE
[ROY-37] Fix header.html for Rose theme

### LINKED ISSUE #2171: header.html/footer.html in Rose error 500
Location | https://sandbox-rose-cus-d9.openy.org/header.html
-- | --
``` 
Error: Cannot use object of type Drupal\Core\Render\Markup as array in openy_rose_preprocess_page() (line 344 of /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/profiles/contrib/openy/themes/openy_themes/openy_rose/openy_rose.theme)#0 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(287): openy_rose_preprocess_page() #1 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render() #2 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender() #3 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(450): Drupal\Core\Render\Renderer->render() #4 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/sites/default/files/php/twig/5f58ad51c83ba_html--header.html.html.tw_ZC-HRwKl23qQLbdHd0KxZ3WxR/dWblKbomR8fD3K28qmybuWY4GyPM866uBiRP-wMsytk.php(137): Drupal\Core\Template\TwigExtension->escapeFilter() #5 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8db6ab46df60c5d3629ad34b023bfbb6fec754852458808f8655bbf4ced0bad8->doDisplay() #6 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling() #7 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display() #8 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/themes/engines/twig/twig.engine(65): Twig\Template->render() #9 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template() #10 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render() #11 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender() #12 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render() #13 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #14 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext() #15 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse() #16 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/event-dispatcher/LegacyEventDispatcherProxy.php(78): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray() #17 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(163): Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy->dispatch() #18 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #19 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle() #20 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle() #21 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle() #22 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass() #23 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/profiles/contrib/openy/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle() #24 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle() #25 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() #26 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() #27 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/DrupalKernel.php(705): Stack\StackedHttpKernel->handle() #28 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/index.php(19): Drupal\Core\DrupalKernel->handle() #29 {main}.
```

### PR DESCRIPTION
**Pull request by shuklina**
Issue: https://github.com/ymcatwincities/openy/issues/2171

## Steps for review

- [x] Go to `/header.html`
- [x] Make sure that there is not error 500 for the Rose theme.
image

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Review by podarok — APPROVED** [review]
Code looks good

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2860/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2860/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2860/

**Comment by podarok** [comment]
works great 
image

**Pull request merged**
