### PR TITLE
[OYPD-172] Fix namespace for custom libraries

### PR DESCRIPTION
**Pull request by alexschedrov**
Packagist https://packagist.org/packages/ymcatwincities/openy is complaining about prohibited characters in custom packages. Replaced ":" with "/".

> [Composer\Repository\InvalidRepositoryException]: No valid composer.json was found in any branch or tag of https://github.com/ymcatwincities/openy, could not load a package from it.
Reading composer.json of ymcatwincities/openy (8.x-1.x)
Importing branch 8.x-1.x (dev-8.x-1.x)
Skipped branch 8.x-1.x, Invalid package information: 
require.library:jaypan/jquery_colorpicker : invalid key, package names must be strings containing only [A-Za-z0-9_./-]
require.library:enyo/dropzone : invalid key, package names must be strings containing only [A-Za-z0-9_./-]
require.library:kenwheeler/slick : invalid key, package names must be strings containing only [A-Za-z0-9_./-]
require.library:dinbror/blazy : invalid key, package names must be strings containing only [A-Za-z0-9_./-]
require.library:gdsmith/jquery.easing : invalid key, package names must be strings containing only [A-Za-z0-9_./-]

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build310

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/310/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build310/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build311

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/311/

**Review by ddrozdik — APPROVED** [review]

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build311/profiles/openy/build/reports/behat

**Pull request merged**
