### PR TITLE
Retention Campaign refactoring

### PR DESCRIPTION
**Pull request by kolesnikoff**
Refactoring based on the code review https://docs.google.com/spreadsheets/d/1a7HPY5aVtMn2TUY2KXYSn8QoTEd1l2dg7hVBZU3-Xj8/edit?pli=1#gid=0.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1097 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1097 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1097 |
| Installation process | http://install.openy.cibox.tools/build1097/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1097/

**Comment by kolesnikoff** [comment]
@podarok @ddrozdik Gents, please review.

**Review by podarok — APPROVED** [review]
@kolesnikoff 
All config changes should be reflected in respective hook_update_Ns. Could you make it in a follow up?

**Comment by podarok** [comment]
@ddrozdik I've merged this for the sake of speed of fixing a huge list. Let's add comments to follow up fixes

**Pull request merged**
