### PR TITLE
Fix description in the module openy_block_basic 

### PR DESCRIPTION
**Pull request by kristolukky**
Issue on drupal.org - https://www.drupal.org/node/2885219

Issue - https://github.com/ymcatwincities/openy/issues/499

Steps for review: 

- [x] Login as admin
- [x] Go to /admin/structure/block/block-content/manage/basic_block
- [x] Check that block description is exist
- [x] Go to /admin/structure/block/block-content/manage/basic_block/fields/block_content.basic_block.field_block_content
- [x] Check that field description is exist

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by kristolukky** [comment]
test this please

**Comment by danylevskyi** [comment]
ok to test

**Comment by danylevskyi** [comment]
retest this please

**Comment by danylevskyi** [comment]
retest this please

**Review by alexschedrov — APPROVED** [review]
Code looks good.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1447 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1447 |
| Installation process | http://install.openy-dev.ffwua.com/build1447/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1447/

**Pull request merged**
