### PR TITLE
Move Drush to the development section of the makefile for Aegir compatibility

### PR DESCRIPTION
**Pull request by colans**
Currently, it's not possible to install a Y site on [Aegir](https://www.aegirproject.org/) because it requires a site-local Drush.  See [Aegir 3 is incompatible with Drush 9+](https://www.drupal.org/project/provision/issues/2953349) for details.

Given that Drush isn't generally required for Production sites, the simplest and best-practice workaround is to move it from `require` to `require-dev` so that it's still available in development environments, but not in Aegir deployments (which always assume Production).

Original Issue, this PR is going to fix: NA; this MR is self-contained.

## Steps for review

1. Get access to an Aegir instance by setting it up on a real VM or by using https://gitlab.com/aegir/aegir-dev-vm.
2. Create a new Platform (Aegir-speak for a Drupal codebase) using https://github.com/ymcatwincities/openy-project.
3. Create a site using the Open Y distro on that Platform.

If everything is green, it succeeded.  If you get errors as described in [Aegir 3 is incompatible with Drush 9+](https://www.drupal.org/project/provision/issues/2953349), then it failed.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by sarah-halby** [comment]
@podarok can you please review? @shelleygoetz please open a ticket in Jira.

**Comment by podarok** [comment]
There is a chance CI will be broken, I'll verify overnight @sarah-halby 

Thank you @colans

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by colans** [comment]
Thanks!  That was fast.  I created a d.o issue for credit purposes @ https://www.drupal.org/project/openy/issues/3253330

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
> Thanks! That was fast. I created a d.o issue for credit purposes @ https://www.drupal.org/project/openy/issues/3253330

Fixed on drupal.org.
Thank you

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by shelleygoetz** [comment]
@sarah-halby created: (https://openy.atlassian.net/browse/MAINTAIN-222)

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
[skip ci]

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
