### PR TITLE
[OYPD-493] Blog components heading.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-493?focusedCommentId=93495&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-93495
Drupal.org issue: https://www.drupal.org/node/2887825

# Steps to review:
- [x] go to Blog page [sitename]/blog
- [x] find blog items
Please look https://monosnap.com/file/8n1AW7LhEgfMmibGXhv84521sZuaus
- [x] use browser inspector check category
- [x] verify h4 removed and now div with class blog-category
- [x] go to any branch or camp
- [x] find blog items
- [x] use browser inspector check category
- [x] verify h4 removed and now div with class blog-category

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1669 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1669 |
| Installation process | http://install.openy-dev.ffwua.com/build1669/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1669/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1669

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1669/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1677 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1677 |
| Installation process | http://install.openy-dev.ffwua.com/build1677/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1677/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1677

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1677/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1685 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1685 |
| Installation process | http://install.openy-dev.ffwua.com/build1685/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1685/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1685

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1685/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
