### PR TITLE
Update tour.tour.openy-landing-page-add.yml

### PR DESCRIPTION
**Pull request by Robert201-zz**
small changes grammer

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build344

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/344/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build344/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build352

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/352/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build352/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
