### PR TITLE
[OPENY-68] Amenities & Color taxonomy decoupling

### PR DESCRIPTION
**Pull request by hamrant**
## Note:

We can't do normal testing of this PR because "OpenY Taxonomy Amenities" exist in dependencies of "OpenY Branch" module  see https://github.com/ymcatwincities/openy/pull/1150.  

Similar situation with "OpenY Taxonomy Color" module, it used in most openy modules:
```
Required by: Openy Block Menu, OpenY Paragraph Microsites Menu, OpenY Branch, OpenY Membership, OpenY Facility, OpenY Program, OpenY Program Subcategory, OpenY Node Blog, OpenY Node Event, OpenY Paragraph Small Banner, OpenY Paragraph Banner, OpenY Activity, OpenY Class, OpenY Session, OpenY Session instance, OpenY Schedules, OpenY Paragraph Schedule Search, OpenY Paragraph Featured Blog Posts, OpenY Paragraph Classes Listing, OpenY Paragraph Class Sessions, OpenY Paragraph Latest Blog Posts, OpenY Paragraph Latest Blog Posts (Camp), OpenY Paragraph Latest Blog Posts (Branch), OpenY Paragraph Blog Posts Listing, OpenY Paragraph Location Finder, OpenY Membership Calculator, OpenY Paragraph Membership Calculator, OpenY Paragraph Latest Event Posts, OpenY Paragraph Event Posts Listing, OpenY Paragraph Categories Listing, OpenY Node - Social Post, OpenY Branch Selector, OpenY Demo Block Microsites Menu, OpenY Demo Node Landing Page, OpenY Demo Node Alert, OpenY Demo Taxonomy Blog Category, OpenY Demo Node Blog, OpenY Demo Node Camp, OpenY Demo Node Program, OpenY Demo Node Program Subcategory, OpenY Demo Node Class, OpenY Demo Node Event, OpenY Demo Taxonomy Facility Type, OpenY Demo Node Facility, OpenY Demo Node Membership, OpenY Paragraph Latest News Posts (Branch), OpenY Demo Node News, OpenY Demo Node Sessions, OpenY Node Alert
```

So I suggest just check code from hook_uninstall with devel help.

## Steps for review

- [x] login as admin
- [x] go to /admin/structure/taxonomy/manage/amenities/overview
- [x] Check that you can see list of amenities taxonomy terms
- [x] go to /admin/modules
- [x] install devel module
- [x] go to /devel/php
- [x] run code from hook_uninstall
```php
  \Drupal::service('openy.modules_manager')
    ->removeEntityBundle('taxonomy_term', 'taxonomy_vocabulary', 'amenities', 'vid');
  $configFactory = \Drupal::configFactory();
  $configs = [
    'pathauto.pattern.amenities',
    'core.entity_view_mode.taxonomy_term.icon',
  ];
  foreach ($configs as $config) {
    $configFactory->getEditable($config)->delete();
  }
```
- [x] return to /admin/structure/taxonomy/manage/amenities/overview
- [x] check that amenities taxonomy terms and vocabulary was removed
- [x] go to /admin/structure/taxonomy
- [x] check that "Amenities" not exist in this list
- [x] go to /admin/structure/taxonomy/manage/color/overview
- [x] Check that you can see list of color taxonomy terms
- [x] go to /devel/php
- [x] run code from hook_uninstall
```php
  \Drupal::service('openy.modules_manager')
    ->removeEntityBundle('taxonomy_term', 'taxonomy_vocabulary', 'color', 'vid');
  $configFactory = \Drupal::configFactory();
  $configs = [
    'rabbit_hole.behavior_settings.taxonomy_vocabulary_color',
    'core.entity_view_mode.taxonomy_term.color',
  ];
  foreach ($configs as $config) {
    $configFactory->getEditable($config)->delete();
  }
```
- [x] return to /admin/structure/taxonomy/manage/color/overview
- [x] check that color taxonomy terms and vocabulary was removed
- [x] go to /admin/structure/taxonomy
- [x] check that "Color" not exist in this list

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build561 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build561 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build561 |
| Installation process | http://install.openy.cibox.tools/build561/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/561/

**Comment by hamrant** [comment]
For Taxonomy Amenities we need to move amenities field from "OpenY Branch" to Amenities module and add this field deleting in hook_uninstall. As result we will have normal decoupling for Taxonomy Amenities.

cc @podarok @ddrozdik

**Comment by ddrozdik** [comment]
@hamrant  - Also, Color taxonomy should be enabled in Extended and Standard versions, since many paragraphs have dependencies on this taxonomy.

**Review by podarok — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build584 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build584 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build584 |
| Installation process | http://install.openy.cibox.tools/build584/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/584/

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
