### PR TITLE
[OYPD-504] Upgrade path for CodeSprint issues.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-504
Drupal.org issue: https://www.drupal.org/node/2887965

# Steps to review:
- [x] check in upgraded(upgrade path) installation
- [x] login as admin

- [x] go to admin/structure/block/block-content/manage/basic_block/fields/block_content.basic_block.field_block_content and admin/structure/block/block-content/types
- [x] verify you can see description

- [x] go to media/add/video
- [x] verify you can see description after "Save to my media library"

- [x] go to /node/add/activity
- [x] verify you can see description after "Program Subcategory" and WYSIWYG

- [x] go to node/add/landing_page
- [x] verify you can see description  Content Area after Content

- [x] go to /media/add/image
- [x] verify all fields have description

- [x] go to /node/add/program_subcategory
- [x] check field descritpions

- [x] go to /node/add/program
- [x] verify you can see description for all fields in Header Area, Content Area, Sidebar Area

- [x] go to node/add/session
- [x] verify you can see description in after all fields in each Area

- [x] go to /media/add/document
- [x] verify all fields have description

- [x] go to /node/add/alert
- [x] verify all fields have description

- [x] go to /node/add/blog (https://github.com/ymcatwincities/openy/pull/535)
- [x] verify all fields have description 

- [x] go to /node/add/class
- [x] verify all fields have description 

- [x] go to /node/add/membership
- [x] verify all fields have description 

- [x] go to /node/add/landing_page
- [x] add paragraf block Small banner
- [x] check description for fields

- [x] go to /node/add/landing_page
- [x] add paragraf block teaser
- [x] check description for fields

- [x] go to /node/add/landing_page
- [x] add paragraf block Simple content
- [x] check description for fields

- [x] go to /node/add/landing_page
- [x] add paragraph banner
- [x] check description for fields

- [x] go to /node/add/landing_page
- [x] add paragraph featured content
- [x] check description for fields

- [x] go to /node/add/landing_page
- [x] add paragraf block Grid paragraph
- [x] check description for fields

- [x] go to /node/add/landing_page
- [x] add paragraf block Location finder filter
- [x] check description for fields

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1673 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1673 |
| Installation process | http://install.openy-dev.ffwua.com/build1673/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1673/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1673

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1673/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1674 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1674 |
| Installation process | http://install.openy-dev.ffwua.com/build1674/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1674/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1674

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1674/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
