### PR TITLE
Adjust spacings in the header according to Open Y & YUSA branding

### PR DESCRIPTION
**Pull request by kolesnikoff**
*Steps to review:*
- update the code;
- check that the spacing between the logo and AOF is correct;
- check that top menu and "Open YMCA" text are aligned;
- check that main menu doesn't jump on hover or focus.

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build264 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build264 |
| Installation process | http://install.openy-dev.ffwua.com/build264/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/264/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build264/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build264/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build264/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build264/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build264/blogWCAG2AAhtmlcs.txt

**Pull request merged**
