### PR TITLE
Fix arrows for alerts

### PR DESCRIPTION
**Pull request by shuklina**
### How to review:

- [x] Make sure that slick arrows for alert work correctly when there are 2 alerts on a page

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by AndreyMaximov** [comment]
test this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1783 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1783 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1783 |
| Installation process | http://install.openy.cibox.tools/build1783/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1783/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1783/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1783/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1783/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1783/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1783/blogWCAG2AAhtmlcs.txt

**Pull request merged**
