### PR TITLE
OYPD-478.

### PR DESCRIPTION
**Pull request by tolichka**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [x] Please provide steps for review here.
1) Go to home page or any other page where we have blog teasers.
2) Find blog teaser.
3) Now we have title in H3 at the top, and category in H4 at the bottom of teaser.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1544 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1544 |
| Installation process | http://install.openy-dev.ffwua.com/build1544/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1544/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1544/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1545 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1545 |
| Installation process | http://install.openy-dev.ffwua.com/build1545/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1545/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1545/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1547 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1547 |
| Installation process | http://install.openy-dev.ffwua.com/build1547/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1547/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1547/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1567 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1567 |
| Installation process | http://install.openy-dev.ffwua.com/build1567/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1567/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1567/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
