### PR TITLE
[OYPD-527] Theme setting fixes

### PR DESCRIPTION
**Pull request by david-hernandez**
I went through all existing theme color settings and fixed them. They should all be working again, including the hovers.

- [x] Verify all theme color settings.
- [x] Verify no PHP errors occur when submitting the settings form.
- [x] Verify color settings for the camp pages work correctly using different colors than the main theme.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1823 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1823 |
| Installation process | http://install.openy-dev.ffwua.com/build1823/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1823/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1823

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1823/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1823/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1823/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1823/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1823/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1823/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
I can see Top Menu items highlighted, but not Main menu items
image

Actually seems Main Menu items wasn't highlighted when we implemented them. (Only "Programs" menu item was. )
But from theme configuration it looks like they should
image

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1826 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1826 |
| Installation process | http://install.openy-dev.ffwua.com/build1826/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1826/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1826

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1826/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1826/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1826/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1826/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1826/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1826/profiles/contrib/openy/build/reports/behat

**Comment by david-hernandez** [comment]
I added the background color change on hover for the main nav. For regular pages and camp pages.

screen shot 2017-07-07 at 11 40 41 am
screen shot 2017-07-07 at 11 40 28 am

**Comment by david-hernandez** [comment]
p.s. The extra spacing at the bottom of the menu is just the way the menu currently has its padding setup. If we think that should be changed, let's do that in a new issue.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1827 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1827 |
| Installation process | http://install.openy-dev.ffwua.com/build1827/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1827/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1827

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1827/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1827/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1827/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1827/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1827/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1827/profiles/contrib/openy/build/reports/behat

**Review by Kerby70 — APPROVED** [review]

**Pull request merged**
