### PR TITLE
[OPENY-38] Amenities paragraphs decoupling

### PR DESCRIPTION
**Pull request by hamrant**
## Steps for review

- [x] login as admin
- [x] go to "/locations"
- [x] check that you can see location filter by amenities
- [x] go to "/admin/modules/uninstall"
- [x] uninstall "OpenY Paragraph Location By Amenities" module
- [x] go to "/locations"
- [x] check that location filter by amenities was removed
- [x] go to "/admin/modules/uninstall"
- [x] uninstall "OpenY Paragraph Amenities" module
- [x] go to "/amenities"
- [x] check that amenities paragraph was removed
- [x] go to "/admin/modules"
- [x] install "OpenY Paragraph Amenities" module
- [x] go to "/amenities" and edit node
- [x] add "All Amenities" paragraph to content section and save
- [x] check that you can see paragraph content and all works fine
- [x] go to "/admin/modules"
- [x] install "OpenY Paragraph Location By Amenities" module
- [x] go to "/locations" and edit node
- [x] Add to sidebar section "Location filter by amenities" paragraph and save
- [x] check that you can see paragraph content and all works fine

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build461 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build461 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build461 |
| Installation process | http://install.openy.cibox.tools/build461/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/461/

**Review by podarok — APPROVED** [review]
Looks good code wise

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build470 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build470 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build470 |
| Installation process | http://install.openy.cibox.tools/build470/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/470/

**Pull request merged**
