### PR TITLE
[OYPD-443]: Paragraphs update.

### PR DESCRIPTION
**Pull request by goranmiric**
Issue: [443](https://github.com/ymcatwincities/openy/issues/443)

## Steps for review

- [x] Go to some of the node add pages and confirm that paragraphs are working well.
- [x] Go to the node view page and confirm that paragraphs are working well.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1362 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1362 |
| Installation process | http://install.openy-dev.ffwua.com/build1362/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1362/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1362/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1398 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1398 |
| Installation process | http://install.openy-dev.ffwua.com/build1398/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1398/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1398/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
