### PR TITLE
[OYPD-108] Theme customization tour

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-108
drupal.org issue - https://www.drupal.org/node/2850096

Steps for review:
- [x] login as admin
- [x] go to /admin/appearance/settings/openy_rose?tour=1
- [x] check tour
- [x] profit

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build377

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/377/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build377/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@hamrant Tour button is highlighted in weird way.

Let's play with it and let's set location "bottom". If it doesn't work, let's don't set focus on button and change text to "If you would like to open tour on page where it's available, you can use "Tour" button at the top-right corner.".

image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build378

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/378/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build378/profiles/openy/build/reports/behat

**Pull request merged**
