### PR TITLE
Update paragraphs to latest stable version #2077

### LINKED ISSUE #2077: Upgrade paragraphs module - in Drupal 8
In order to become ready for Drupal 9 we should get this module upgraded
drupal/paragraphs 1.6 => 1.12
After upgrade we need to ensure our paragraphs remain working

Let's upgrade these in Drupal 8 first

PS. All demo content was successfully imported with 1.12 Paragraps in Drupal 9.

### PR DESCRIPTION
**Pull request by podarok**
Proceed #2077

Original Issue, this PR is going to fix: #2077

## Steps for review

- [ ] Ensure paragraphs are working in Drupal 8 ( Tested as fine in Drupal 9 - see https://sandboxes-d9.openy.org/ )
- [ ] Verify there are no upgrade issues

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2421/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2421/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2421/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2421/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2421/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2421/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2421/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2421/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2421/

**Review by hamrant — APPROVED** [review]
http://install.openy.cibox.tools/build2421/admin/modules - Paragraphs Version: 8.x-1.12
Tested several paragraphs here - http://install.openy.cibox.tools/build2421/test-paragraphs

Works fine

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2433/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2433/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2433/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2433/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2433/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2433/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2433/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2433/

**Review by AndreyMaximov — APPROVED** [review]

**Pull request merged**
