### PR TITLE
[OYPD-267] [OYPD-318] Membership Calculator MVP - backend

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-267
drupal.org issue - https://www.drupal.org/node/2856195

**Steps for review:**
- [x]  login as admin
- [x]  go to /node/add/membership
- [x]  add several memberships (with Membership info)
- [x]  go to /node/add/landing_page
- [x]  create landing_page with Membership calculator paragraph in content area
- [x]  check Membership calculator on landing page
- [x]  go to 3 step
- [x]  check that branch title on left side
- [x]  return to 2 step
- [x]  select branch (in selected membership there should be no information about this branch)
- [x]  go to 3 step
- [x]  check message in membership (must be "Selected branch doesn't provide needed ...")
- [x]  check that missing "Complete registration" button
- [x]  return to 2 step
- [x]  select branch (in selected membership there should be information about this branch)
- [x]  go to 3 step
- [x]  check that "Complete registration" button is exist
- [x]  profit

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build591

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/591/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build591/profiles/openy/build/reports/behat

**Comment by AlexNetman** [comment]
1) Change Typo from:
Selected branch doesn't provide needed membership type of it wasn't configured yet
to 
Selected branch doesn't provide needed membership type OR it wasn't configured yet


2) That " Complete registration" button is doing nothing.

**Comment by alexschedrov** [comment]
image

This button doesn't redirect to the URL.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build593

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/593/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build593/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build594

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/594/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build594/profiles/openy/build/reports/behat

**Comment by AlexNetman** [comment]
Still button "Complete Registration" don't redirected to the link from Membership content type info.

**Comment by alexschedrov** [comment]
@hamrant can we redirect even if link is not valid?
Right now it's not obvious behaviour.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build614 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build614 |
| Installation process | http://install.openy-dev.ffwua.com/build614/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/614/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build614/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build625 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build625 |
| Installation process | http://install.openy-dev.ffwua.com/build625/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/625/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build625/profiles/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Pull request merged**
