### PR TITLE
OpenY Lily changing colours  and other minor fixes. 

### PR DESCRIPTION
**Pull request by ddrozdik**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [x] login as admin 
- [x] Go to Admin -> Appearance 
- [x] Install and set as default openy_lily theme
- [x] play with colors and check that they change colors on pages. 
- [x] check mobile menu for microsites menu and for camp menu

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build333 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build333 |
| Installation process | http://install.openy-dev.ffwua.com/build333/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/333/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build333/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build333/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build333/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build333/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build333/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build333/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build333/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build335 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build335 |
| Installation process | http://install.openy-dev.ffwua.com/build335/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/335/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build335/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build335/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build335/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build335/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build335/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build335/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build335/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by ddrozdik** [comment]
retest this please

**Comment by ddrozdik** [comment]
retest this please

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build348/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build348/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build348/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build348/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build348/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build348/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build348/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by ddrozdik** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build350 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build350 |
| Installation process | http://install.openy-dev.ffwua.com/build350/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/350/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build350/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build350/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build350/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build350/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build350/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build351 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build351 |
| Installation process | http://install.openy-dev.ffwua.com/build351/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/351/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build351/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build351/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build351/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build351/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build351/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL http://ci.openymca.org/build350/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build350/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by bjwilkins** [comment]
Behat test results file URL http://ci.openymca.org/build351/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build351/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by AlexNetman** [comment]
Button text hasn't changed color to yellow as expected.
http://upgrade.openy-dev.ffwua.com/build351/locations/west-ymca
http://upgrade.openy-dev.ffwua.com/build351/schedules/group-schedules?location=203&filter_date=2/23/18
image

**Comment by AlexNetman** [comment]
Given I have changed colors of camp menu to "Black text on green"
When I hover over the current menu item arrow-indicator
Then  I see grey square http://upgrade.openy-dev.ffwua.com/build351/camps/camp-colman?lk
image

**Comment by AlexNetman** [comment]
* Purple color for font-awesome icons remains purple on branch 3 column paragraph:
image
And label is magenta.

* All colors of groupex tiles are hardcoded:
image

**Comment by AlexNetman** [comment]
/amenities colors are hardcoded:
image

**Comment by AlexNetman** [comment]
Also I haven't found way to change color of global link on hover.
image

**Comment by AlexNetman** [comment]
Seems grey menu  color on microsite is hardcoded to grey too.
And it has a white padding
image
And it should not have a white line below.

**Comment by AlexNetman** [comment]
So we decided to merge it with these minor issues.
Improvements can be made in #964

**Pull request merged**
