### PR TITLE
[YGSSLA-64] Make Class/Activity/Category/Program nodes' cascade update procedures take moderation states into account

### PR DESCRIPTION
**Pull request by AndreyMaximov**
https://github.com/ymcatwincities/openy/issues/1673 the issues is described here

## Steps for review

- [ ] enable editorial workflow for Program node content type
- [ ] edit any program node
- [ ] do not publish the changes, but leave them in draft ("create a draft of the node" in other words)
- [ ] verify the referencing Program subcategory nodes are not getting unpublished

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1684 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1684 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1684 |
| Installation process | http://install.openy.cibox.tools/build1684/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1684/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1684/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1684/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1684/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1684/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1684/blogWCAG2AAhtmlcs.txt

**Comment by ddrozdik** [comment]
I think after implementing these changes we can investigate the possibility of removing openy_moderation_wrapper from the Open Y distribution. There are a couple of reasons for that: 
1. openy_moderation_wrapper has been developed for Drupal 8.3 core while we currently have 8.6 and workbench_moderation module which is supposed to be used there is not used anymore. 
2. This PR simplifies and removes a big chunk of logic which could be replaced now by a couple of strings from the core. 
cc @AndreyMaximov, @hamrant, @podarok

**Review by hamrant — APPROVED** [review]

**Comment by AndreyMaximov** [comment]
@ddrozdik you are right!

I apologize for including changes to `openy_moderation_wrapper` module in this PR.

In fact, they are not related to the addressed issue. I'm removing these changes, filing another issue, preparing another PR.

**Comment by AndreyMaximov** [comment]
C'mon! @podarok

**Pull request merged**
