### PR TITLE
Taxonomy page no results behaviour

### PR DESCRIPTION
**Pull request by yasik78**
Taxonomy page no results behaviour https://github.com/ymcatwincities/openy/issues/377

## Steps for review

- [x] Go to site  /blog/category/general-wellness

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1724 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1724 |
| Installation process | http://install.openy-dev.ffwua.com/build1724/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1724/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1724

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1724

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1724/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1737 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1737 |
| Installation process | http://install.openy-dev.ffwua.com/build1737/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1737/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1737

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1737

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1737/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. It should have better looking and within 12 grid columns.
image

2. Please change text to "We are sorry, but no content available".

3. Please add upgrade path for the configuration
https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md#revert-only-specific-property-from-config

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1772 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1772 |
| Installation process | http://install.openy-dev.ffwua.com/build1772/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1772/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1772

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1772

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1772/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1773 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1773 |
| Installation process | http://install.openy-dev.ffwua.com/build1773/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1773/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1773

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1773

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1773/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1784 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1784 |
| Installation process | http://install.openy-dev.ffwua.com/build1784/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1784/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1784

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1784

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1784/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
This page still doesn't use Grid markup.
Current version:
image

Should be:
image

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request closed without merging**
