### PR TITLE
OpenY MyY

### PR DESCRIPTION
**Pull request by jediandrey**
Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2006/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2006/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2006/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2006/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2006/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2006/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2006/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2006/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2006/

**Review by podarok — CHANGES_REQUESTED** [review]
See https://github.com/ymcatwincities/openy/pull/1887#pullrequestreview-351343757

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2020/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #1895 of commit 29b27addf17096087d1de8ee8baaf845f9b9ea47 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build2020/openy-profile # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5721904940592052364.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: remote: Enumerating objects: 14117, done.
remote: Counting objects:   0% (1/14117)
remote: Counting objects:   1% (142/14117)
remote: Counting objects:   2% (283/14117)
remote: Counting objects:   3% (424/14117)
remote: Counting objects:   4% (565/14117)
remote: Counting objects:   5% (706/14117)
remote: Counting objects:   6% (848/14117)
remote: Counting objects:   7% (989/14117)
remote: Counting objects:   8% (1130/14117)
remote: Counting objects:   9% (1271/14117)
remote: Counting objects:  10% (1412/14117)
remote: Counting objects:  11% (1553/14117)
remote: Counting objects:  12% (1695/14117)
remote: Counting objects:  13% (1836/14117)
remote: Counting objects:  14% (1977/14117)
remote: Counting objects:  15% (2118/14117)
remote: Counting objects:  16% (2259/14117)
remote: Counting objects:  17% (2400/14117)
remote: Counting objects:  18% (2542/14117)
remote: Counting objects:  19% (2683/14117)
remote: Counting objects:  20% (2824/14117)
remote: Counting objects:  21% (2965/14117)
remote: Counting objects:  22% (3106/14117)
remote: Counting objects:  23% (3247/14117)
remote: Counting objects:  24% (3389/14117)
remote: Counting objects:  25% (3530/14117)
remote: Counting objects:  26% (3671/14117)
remote: Counting objects:  27% (3812/14117)
remote: Counting objects:  28% (3953/14117)
remote: Counting objects:  29% (4094/14117)
remote: Counting objects:  30% (4236/14117)
remote: Counting objects:  31% (4377/14117)
remote: Counting objects:  32% (4518/14117)
remote: Counting objects:  33% (4659/14117)
remote: Counting objects:  34% (4800/14117)
remote: Counting objects:  35% (4941/14117)
remote: Counting objects:  36% (5083/14117)
remote: Counting objects:  37% (5224/14117)
remote: Counting objects:  38% (5365/14117)
remote: Counting objects:  39% (5506/14117)
remote: Counting objects:  40% (5647/14117)
remote: Counting objects:  41% (5788/14117)
remote: Counting objects:  42% (5930/14117)
remote: Counting objects:  43% (6071/14117)
remote: Counting objects:  44% (6212/14117)
remote: Counting objects:  45% (6353/14117)
remote: Counting objects:  46% (6494/14117)
remote: Counting objects:  47% (6635/14117)
remote: Counting objects:  48% (6777/14117)
remote: Counting objects:  49% (6918/14117)
remote: Counting objects:  50% (7059/14117)
remote: Counting objects:  51% (7200/14117)
remote: Counting objects:  52% (7341/14117)
remote: Counting objects:  53% (7483/14117)
remote: Counting objects:  54% (7624/14117)
remote: Counting objects:  55% (7765/14117)
remote: Counting objects:  56% (7906/14117)
remote: Counting objects:  57% (8047/14117)
remote: Counting objects:  58% (8188/14117)
remote: Counting objects:  59% (8330/14117)
remote: Counting objects:  60% (8471/14117)
remote: Counting objects:  61% (8612/14117)
remote: Counting objects:  62% (8753/14117)
remote: Counting objects:  63% (8894/14117)
remote: Counting objects:  64% (9035/14117)
remote: Counting objects:  65% (9177/14117)
remote: Counting objects:  66% (9318/14117)
remote: Counting objects:  67% (9459/14117)
remote: Counting objects:  68% (9600/14117)
remote: Counting objects:  69% (9741/14117)
remote: Counting objects:  70% (9882/14117)
remote: Counting objects:  71% (10024/14117)
remote: Counting objects:  72% (10165/14117)
remote: Counting objects:  73% (10306/14117)
remote: Counting objects:  74% (10447/14117)
remote: Counting objects:  75% (10588/14117)
remote: Counting objects:  76% (10729/14117)
remote: Counting objects:  77% (10871/14117)
remote: Counting objects:  78% (11012/14117)
remote: Counting objects:  79% (11153/14117)
remote: Counting objects:  80% (11294/14117)
remote: Counting objects:  81% (11435/14117)
remote: Counting objects:  82% (11576/14117)
remote: Counting objects:  83% (11718/14117)
remote: Counting objects:  84% (11859/14117)
remote: Counting objects:  85% (12000/14117)
remote: Counting objects:  86% (12141/14117)
remote: Counting objects:  87% (12282/14117)
remote: Counting objects:  88% (12423/14117)
remote: Counting objects:  89% (12565/14117)
remote: Counting objects:  90% (12706/14117)
remote: Counting objects:  91% (12847/14117)
remote: Counting objects:  92% (12988/14117)
remote: Counting objects:  93% (13129/14117)
remote: Counting objects:  94% (13270/14117)
remote: Counting objects:  95% (13412/14117)
remote: Counting objects:  96% (13553/14117)
remote: Counting objects:  97% (13694/14117)
remote: Counting objects:  98% (13835/14117)
remote: Counting objects:  99% (13976/14117)
remote: Counting objects: 100% (14117/14117)
remote: Counting objects: 100% (14117/14117), done.
remote: Compressing objects:   0% (1/7866)
remote: Compressing objects:   1% (79/7866)
remote: Compressing objects:   2% (158/7866)
remote: Compressing objects:   3% (236/7866)
remote: Compressing objects:   4% (315/7866)
remote: Compressing objects:   5% (394/7866)
remote: Compressing objects:   6% (472/7866)
remote: Compressing objects:   7% (551/7866)
remote: Compressing objects:   8% (630/7866)
remote: Compressing objects:   9% (708/7866)
remote: Compressing objects:  10% (787/7866)
remote: Compressing objects:  11% (866/7866)
remote: Compressing objects:  12% (944/7866)
remote: Compressing objects:  13% (1023/7866)
remote: Compressing objects:  14% (1102/7866)
remote: Compressing objects:  15% (1180/7866)
remote: Compressing objects:  16% (1259/7866)
remote: Compressing objects:  17% (1338/7866)
remote: Compressing objects:  18% (1416/7866)
remote: Compressing objects:  19% (1495/7866)
remote: Compressing objects:  20% (1574/7866)
remote: Compressing objects:  21% (1652/7866)
remote: Compressing objects:  22% (1731/7866)
remote: Compressing objects:  23% (1810/7866)
remote: Compressing objects:  24% (1888/7866)
remote: Compressing objects:  25% (1967/7866)
remote: Compressing objects:  26% (2046/7866)
remote: Compressing objects:  27% (2124/7866)
remote: Compressing objects:  28% (2203/7866)
remote: Compressing objects:  29% (2282/7866)
remote: Compressing objects:  30% (2360/7866)
remote: Compressing objects:  31% (2439/7866)
remote: Compressing objects:  32% (2518/7866)
remote: Compressing objects:  33% (2596/7866)
remote: Compressing objects:  34% (2675/7866)
remote: Compressing objects:  35% (2754/7866)
remote: Compressing objects:  36% (2832/7866)
remote: Compressing objects:  37% (2911/7866)
remote: Compressing objects:  38% (2990/7866)
remote: Compressing objects:  39% (3068/7866)
remote: Compressing objects:  40% (3147/7866)
remote: Compressing objects:  41% (3226/7866)
remote: Compressing objects:  42% (3304/7866)
remote: Compressing objects:  43% (3383/7866)
remote: Compressing objects:  44% (3462/7866)
remote: Compressing objects:  45% (3540/7866)
remote: Compressing objects:  46% (3619/7866)
remote: Compressing objects:  47% (3698/7866)
remote: Compressing objects:  48% (3776/7866)
remote: Compressing objects:  49% (3855/7866)
remote: Compressing objects:  50% (3933/7866)
remote: Compressing objects:  51% (4012/7866)
remote: Compressing objects:  52% (4091/7866)
remote: Compressing objects:  53% (4169/7866)
remote: Compressing objects:  54% (4248/7866)
remote: Compressing objects:  55% (4327/7866)
remote: Compressing objects:  56% (4405/7866)
remote: Compressing objects:  57% (4484/7866)
remote: Compressing objects:  58% (4563/7866)
remote: Compressing objects:  59% (4641/7866)
remote: Compressing objects:  60% (4720/7866)
remote: Compressing objects:  61% (4799/7866)
remote: Compressing objects:  62% (4877/7866)
remote: Compressing objects:  63% (4956/7866)
remote: Compressing objects:  64% (5035/7866)
remote: Compressing objects:  65% (5113/7866)
remote: Compressing objects:  66% (5192/7866)
remote: Compressing objects:  67% (5271/7866)
remote: Compressing objects:  68% (5349/7866)
remote: Compressing objects:  69% (5428/7866)
remote: Compressing objects:  70% (5507/7866)
remote: Compressing objects:  71% (5585/7866)
remote: Compressing objects:  72% (5664/7866)
remote: Compressing objects:  73% (5743/7866)
remote: Compressing objects:  74% (5821/7866)
remote: Compressing objects:  75% (5900/7866)
remote: Compressing objects:  76% (5979/7866)
remote: Compressing objects:  77% (6057/7866)
remote: Compressing objects:  78% (6136/7866)
remote: Compressing objects:  79% (6215/7866)
remote: Compressing objects:  80% (6293/7866)
remote: Compressing objects:  81% (6372/7866)
remote: Compressing objects:  82% (6451/7866)
remote: Compressing objects:  83% (6529/7866)
remote: Compressing objects:  84% (6608/7866)
remote: Compressing objects:  85% (6687/7866)
remote: Compressing objects:  86% (6765/7866)
remote: Compressing objects:  87% (6844/7866)
remote: Compressing objects:  88% (6923/7866)
remote: Compressing objects:  89% (7001/7866)
remote: Compressing objects:  90% (7080/7866)
remote: Compressing objects:  91% (7159/7866)
remote: Compressing objects:  92% (7237/7866)
remote: Compressing objects:  93% (7316/7866)
remote: Compressing objects:  94% (7395/7866)
remote: Compressing objects:  95% (7473/7866)
remote: Compressing objects:  96% (7552/7866)
remote: Compressing objects:  97% (7631/7866)
remote: Compressing objects:  98% (7709/7866)
remote: Compressing objects:  99% (7788/7866)
remote: Compressing objects: 100% (7866/7866)
remote: Compressing objects: 100% (7866/7866), done.
Receiving objects:   0% (1/14117)   
Receiving objects:   1% (142/14117)   
Receiving objects:   2% (283/14117)   
Receiving objects:   3% (424/14117)   
Receiving objects:   4% (565/14117)   
Receiving objects:   5% (706/14117)   
Receiving objects:   6% (848/14117)   
Receiving objects:   7% (989/14117)   
Receiving objects:   8% (1130/14117)   
Receiving objects:   9% (1271/14117)   
Receiving objects:  10% (1412/14117)   
Receiving objects:  11% (1553/14117)   
Receiving objects:  12% (1695/14117)   
Receiving objects:  13% (1836/14117)   
Receiving objects:  14% (1977/14117)   
Receiving objects:  15% (2118/14117)   
Receiving objects:  16% (2259/14117)   
Receiving objects:  17% (2400/14117)   
Receiving objects:  18% (2542/14117)   
Receiving objects:  19% (2683/14117)   
Receiving objects:  20% (2824/14117)   
Receiving objects:  21% (2965/14117)   
Receiving objects:  22% (3106/14117)   
Receiving objects:  23% (3247/14117)   
Receiving objects:  24% (3389/14117)   
Receiving objects:  25% (3530/14117)   
Receiving objects:  26% (3671/14117)   
Receiving objects:  27% (3812/14117)   
Receiving objects:  28% (3953/14117)   
Receiving objects:  29% (4094/14117)   
Receiving objects:  30% (4236/14117)   
Receiving objects:  31% (4377/14117)   
Receiving objects:  32% (4518/14117)   
Receiving objects:  33% (4659/14117)   
Receiving objects:  34% (4800/14117)   
fatal: write error: No space left on device
fatal: index-pack failed

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1363)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:61)
	at org.jenkinsci.plugins.gitclient.CliGit
```

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2030/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2030/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2030/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2030/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2030/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2030/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2030/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2038/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2038/

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2038/

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2039/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2039/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2039/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2039/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2039/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2039/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2039/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2043/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2043/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2043/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2043/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2043/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2043/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2043/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2043/

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2046/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2046/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2046/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2046/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2046/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2046/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2046/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2046/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2049/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2049/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2049/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2051/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2051/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2051/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2051/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2051/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2051/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2051/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2051/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2057/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2057/

**Review by podarok — APPROVED** [review]
Code looks great!!!

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2057/

**Pull request merged**
