### PR TITLE
[OS-250] Add aria-label to alert carousel previous/next buttons

### PR DESCRIPTION
**Pull request by lazylinol**
## Steps to Reproduce
The alerts carousel on each page has a previous and next button, they have a title on them, but they are not labeled properly. They need aria-label on each of the buttons.

## Current Results
Title attributes do not read consistently across browsers and screen readers and across navigation methods, the title here would be better put into an aria-label to make sure reading of important information was consistent: 
`<a href="#previous" data-role="none" class="slick-prev slick-arrow" role="button" aria-disabled="true">Previous</a>`

## Expected Results
Use aria-label="Previous alert message" & aria-label="Next alert message" instead of/along with the title for more consistent reading:
`<a href="#previous" data-role="none" class="slick-prev slick-arrow" role="button" aria-disabled="true" aria-label="Previous alert message">Previous alert message</a>`

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by kolesnikoff** [comment]
test it please

**Comment by kolesnikoff** [comment]
@podarok please review the PR.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1541 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1541 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1541 |
| Installation process | http://install.openy.cibox.tools/build1541/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1541/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1541/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1541/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1541/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1541/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1541/blogWCAG2AAhtmlcs.txt

**Pull request merged**
