### PR TITLE
Add descriptions & placeholders to Gallery paragraph

### PR DESCRIPTION
**Pull request by yasik78**
Gallery paragraph descriptions & placeholders #480

## Steps for review
- [x] Go to /node/add/landing_page
- [x] Add paragraf block Gallery 
- [x] Check description for fields and compare with docs.  https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Content%20structure/Paragraphs/Gallery.md

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1599 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1599 |
| Installation process | http://install.openy-dev.ffwua.com/build1599/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1599/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1599/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
