### PR TITLE
[OPENY-255] Update demo content for the Give page

### PR DESCRIPTION
**Pull request by miroslav-lee**
## Details issue
Styles of demo content for the Give page in the Standart and Extended version, was different

Styles from Standard version:
default

Styles from Extended version:
default

## Steps for review

- [ ] Install Extended version of the build.
- [ ] Go to /give.
- [ ] Check that description the same as Standart version of the build or as on the picture.
default

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by miroslav-lee** [comment]
retest this please

**Comment by miroslav-lee** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1354 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1354 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1354 |
| Installation process | http://install.openy.cibox.tools/build1354/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1354/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1355 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1355 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1355 |
| Installation process | http://install.openy.cibox.tools/build1355/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1355/

**Review by podarok — APPROVED** [review]

**Comment by miroslav-lee** [comment]
retest this please

**Review by ddrozdik — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1361 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1361 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1361 |
| Installation process | http://install.openy.cibox.tools/build1361/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1361/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1364 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1364 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1364 |
| Installation process | http://install.openy.cibox.tools/build1364/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1364/

**Pull request merged**
