### PR TITLE
Activity Finder: Add exclude param to "View all programs" link

### PR DESCRIPTION
**Pull request by hamrant**
## Steps for review

- [ ] Setup in activity finder paragraph "CATEGORIES EXCLUDE"

Screenshot from 2019-09-12 17-29-18

- [ ] Check that "View all programs" link contains exclude params

screenshot-ygbw docksal-2019 09 12-17_27_18

- [ ] Click on this link
- [ ] Check that after redirect categories excluded from filters

### CODE REVIEW

**Comment by ghost** [comment]
[**DeepCode Report (#75b7cc)**](https://www.deepcode.ai/app/gh/ymcatwincities/openy/1122c54ec414b7223e310bbea2288ef8d03bb819/ymcatwincities/openy/75b7cc83d31a7a28b60fddfa8b14d7ae9bde91d0/_/%2F/code/)
---
DeepCode analyzed this pull request.
There are no new issues.

**Comment by hamrant** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1793 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1793 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1793 |
| Installation process | http://install.openy.cibox.tools/build1793/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1793/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1793/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1793/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1793/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1793/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1793/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Pull request merged**
