### PR TITLE
[OYPD-462] Resolve schedules page and class page popup behavior issues.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-462
D.o https://www.drupal.org/node/2883136

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [x] As anonymous user
- [x] On schedules page
- [x] Selecting a location in the location popup does results are properly filtered.
- [x] Click on a class with a location & session id in the url parameters.
- [x] Class should load with proper content for the location & sessions.
- [x] Edit location on class page and select a location on the popup
- [x] The new page should strip the session from the url parameters and have the proper location set.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1333 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1333 |
| Installation process | http://install.openy-dev.ffwua.com/build1333/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1333/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1333/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1339 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1339 |
| Installation process | http://install.openy-dev.ffwua.com/build1339/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1339/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1339/profiles/contrib/openy/build/reports/behat

**Pull request merged**
