### PR TITLE
Update links in documentation

### PR DESCRIPTION
**Pull request by ddrozdik**
- [ ] Please check new links in documentation.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build403

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/403/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build403/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build405

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/405/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build405/profiles/openy/build/reports/behat

**Pull request merged**
