### PR TITLE
Test media embedded into WYSIWYG

### PR DESCRIPTION
**Pull request by AlexNetman**
Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build806 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build806 |
| Installation process | http://install.openy-dev.ffwua.com/build806/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/806/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build806/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build807 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build807 |
| Installation process | http://install.openy-dev.ffwua.com/build807/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/807/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build807/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build808 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build808 |
| Installation process | http://install.openy-dev.ffwua.com/build808/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/808/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build808/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build809 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build809 |
| Installation process | http://install.openy-dev.ffwua.com/build809/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/809/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build809/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build813 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build813 |
| Installation process | http://install.openy-dev.ffwua.com/build813/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/813/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build813/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build860 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build860 |
| Installation process | http://install.openy-dev.ffwua.com/build860/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/860/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build860/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
Test is failed because of Core drupal extension function failed.
image
This was working locally.
Need to be fixed on CI level.

**Comment by alexschedrov** [comment]
It requires some updates:
- We should test Image, Document and Video
- We shouldn’t use demo content

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build868 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build868 |
| Installation process | http://install.openy-dev.ffwua.com/build868/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/868/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build868/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build871 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build871 |
| Installation process | http://install.openy-dev.ffwua.com/build871/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/871/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build871/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Fixed in separate PR.

**Pull request closed without merging**
