### PR TITLE
[OYPD-293] Landing page form paragraph fields option configuration & sidebar visibility states

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-293
D.o https://www.drupal.org/node/2858527

Make sure these boxes are checked before asking for review of your pull request - thank you!

Steps to review:
- [x] Go to add a landing page /node/add/landing_page
- [x] Make sure that "Sidebar Area" is available only when 2 columns layout is selected.
image
- [x] See limitation for paragraphs(for all content where we have these areas):
  - Header area:
    - Banner
    - Gallery
    - Camp menu
    - Classes listing filters
    - Location finder filter
    - Simple content
  - Content area:
    - Everything except
      - Membership info
      - Grid columns
      - Session Time
  - Sidebar area:
    - Promo Card
    - Simple content
    - Small banner
    - Story Card

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build697/build_reports/Drupalsniff.txt
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build697 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build697 |
| Installation process | http://install.openy-dev.ffwua.com/build697/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/697/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build697/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build698 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build698 |
| Installation process | http://install.openy-dev.ffwua.com/build698/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/698/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build698/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build699/build_reports/Drupalsniff.txt
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build699 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build699 |
| Installation process | http://install.openy-dev.ffwua.com/build699/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/699/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build699/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build700 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build700 |
| Installation process | http://install.openy-dev.ffwua.com/build700/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/700/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build700/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build701 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build701 |
| Installation process | http://install.openy-dev.ffwua.com/build701/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/701/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build701/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build702 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build702 |
| Installation process | http://install.openy-dev.ffwua.com/build702/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/702/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build702/profiles/openy/build/reports/behat

**Comment by AlexNetman** [comment]
Would like to hide:
-  Latest blog posts (branch)
- Latest blog posts (camp)

Cause they are not supposed to be pasted on landing pages.

Also remove from Content area:
 - promo card
 - story card

Because they are designed for sidebar only.

Remove:
 - Categories listing
Because it works only for Program page.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build707 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build707 |
| Installation process | http://install.openy-dev.ffwua.com/build707/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/707/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build707/profiles/openy/build/reports/behat

**Comment by Kerby70** [comment]
@AlexNetman The latest pull request solves the generic cases for Promo card & Story card. The other requests would require a new content type specific solution to be built. Based on my discussion in scrum with Robert OConnor, these other requirements should be put in a new task.

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
