### PR TITLE
Ymcawnc 133 update schedule behavior

### PR DESCRIPTION
**Pull request by SanyokMedved**
Update filter behavior for /group-exercise-classes
Added class filters and instructors filters.

Steps:

1) Go to page /group-exercise-classes
2) Edit page. Edit paragraph Repeat Schedules in content section.
3) Enable all filters. 
 by category
by class name
by instructors
4) Enable - Show instructions.
5) If you don't have imported data with instructors - groupex doesn't give this info to us.
6) All filters should be on page.
Default state - all are collapsed. 
If filter is opened - icon changed to '-'.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1645 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1645 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1645 |
| Installation process | http://install.openy.cibox.tools/build1645/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1645/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1646 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1646 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1646 |
| Installation process | http://install.openy.cibox.tools/build1646/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1646/

**Review by podarok — DISMISSED** [review]
Code looks good
@SanyokMedved could you provide steps for review, please

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1646/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1646/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1646/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1646/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1646/blogWCAG2AAhtmlcs.txt

**Comment by kolesnikoff** [comment]
@podarok could you please review it once again?

**Comment by podarok** [comment]
@kolesnikoff @SanyokMedved code conflicts, please rebase

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1689 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1689 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1689 |
| Installation process | http://install.openy.cibox.tools/build1689/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1689/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1689/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1689/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1689/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1689/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1689/blogWCAG2AAhtmlcs.txt

**Comment by kolesnikoff** [comment]
@podarok the code is updated, please check.

**Pull request merged**
