### PR TITLE
[OYPD-186] Images are not displayed to anonymous users

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-186

Steps for review:
- [x] login as admin
- [x] Create a blog with image
- [x] Create a landing page with banner with image
- [x] logout 
- [x] check images in created content
- [x] profit

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build308

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/308/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build308/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build309

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/309/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build309/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
