### PR TITLE
YMCAWNC-132: fix step 2 of activity finder.

### PR DESCRIPTION
**Pull request by SanyokMedved**
Steps:
1) go to /activity-finder or /programs-search-wizard page. It depends on what setting has your Y.
2) Go to step 2.
3) If your category filter is disabled, you should see only 2 columns of filters. (Age and Day).

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1648 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1648 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1648 |
| Installation process | http://install.openy.cibox.tools/build1648/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1648/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1649 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1649 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1649 |
| Installation process | http://install.openy.cibox.tools/build1649/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1649/

**Comment by podarok** [comment]
@SanyokMedved there is ActivityFinder 2 in code now
Please check if this still actual

**Comment by SanyokMedved** [comment]
> @SanyokMedved there is ActivityFinder 2 in code now
> Please check if this still actual

@podarok Looks like this code is not actual more.

**Comment by SanyokMedved** [comment]
Code is no more actual. Activity finder V 2.0 is not using this files more.

**Pull request closed without merging**
