### PR TITLE
Getting RepeatActualizeBatch class back (seems it's forgotten)

### LINKED ISSUE #1811: PEF: openy_repeat_nodes module uses RepeatActualizeBatch class which is not defined in Open Y
`openy_repeat_nodes` module uses RepeatActualizeBatch class, but the class doesn't exist in Open Y.

https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_repeat/modules/openy_repeat_nodes/openy_repeat_nodes.module#L9
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_repeat/modules/openy_repeat_nodes/openy_repeat_nodes.module#L113

### PR DESCRIPTION
**Pull request by vitalii-stepaniuk**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/1811

According to git history, it seems that the class was forgotten on some updates. Since this error dies silently, the chance to notice it is too small - you can see it in logs only.

I've returned this class, however, it requires a person who knows the project very well to ensure that the returned stuff is not deprecated and not breaking existing functionality.

## Steps for review

- [ ] Make sure that openy_repeat_nodes module is enabled. Also dblog module (recent log messages) would be helpful to track errors related to the module.
- [ ] Edit 'class' node and make a significant change to it (change activity).
- [ ] Save the node.
- [ ] Batch will start shortly. Check for errors in Recent log messages. There should not be any related to the module.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1951/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1951/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1951/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1951/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1951/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1951/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1951/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1951/

**Pull request merged**
