### PR TITLE
[OYPD-347] Update composer adding php 5.6+ dependency.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-347
D.o https://www.drupal.org/node/2862553

Steps to review
- [x] Composer install will object on systems with version of php lower than 5.6
- [x] Drupal profile/module install should object on system with version of php lower than 5.6

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build797 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build797 |
| Installation process | http://install.openy-dev.ffwua.com/build797/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/797/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build797/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
When I pulled in from this branch to my local and run "composer install" - I saw:
"""
image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build802 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build802 |
| Installation process | http://install.openy-dev.ffwua.com/build802/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/802/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build802/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
Now "up to date".

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
