### PR TITLE
update dismissed alerts filter

### PR DESCRIPTION
**Pull request by retif**
Fix for a bug where closing one alert stops all other alerts from showing up on subsequent page loads

## Steps for review

- [x] Close one alert
- [x] Refresh the page
- [x] Make sure other alerts are visible

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
@retif could you update PR's description with steps for review, please?

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2740/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2740/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2740/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2740/

**Review by podarok — APPROVED** [review]

**Pull request merged**
