### PR TITLE
[MAINTAIN-102] Decouple essential demo content

### PR DESCRIPTION
**Pull request by hamrant**
Original Issue, this PR is going to fix: https://openy.atlassian.net/browse/MAINTAIN-102

Related PR's:
- https://github.com/open-y-subprojects/openy_content_core/pull/1
- https://github.com/open-y-subprojects/openy_demo_content/pull/2

## Steps for review

- [x] Merge related PR's
- [x] Create new version for https://packagist.org/packages/open-y-subprojects/openy_content_core
- [x] Install site on the build with `Open Y Installation Wizard`
- [x] On demo content step select 'No'
- [x] Check that color taxonomy contains terms
- [ ] Test same with `Yes` option for demo content
- [x] Test that taxonomy demo content works fine
- [x] Check that color taxonomy contains content

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3269/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3269/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3269/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3270/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3270/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3270/

**Comment by podarok** [comment]
Added reference to https://github.com/ymcatwincities/openy/wiki/Decouple-component-from-Open-Y-as-independent-module-project#references 

 
In regards to essential demo content
I’ve released dependencies and changed in your PR https://github.com/ymcatwincities/openy/pull/2507/commits/1f7b3c1942a2ec67e22b1961ba7573181aba3b5e 

But accordingly, to acceptance criteria, we need to ensure it is added by default 
At least https://github.com/hamrant/openy/pull/1 + ensure it is working when Demo content is disabled during installation.

@hamrant

**Comment by podarok** [comment]
Looks great 
image
Thank you @hamrant

**Comment by hamrant** [comment]
@podarok please merge https://github.com/open-y-subprojects/openy_content_core/pull/2 
we need this fix for https://github.com/ymcatwincities/openy/pull/2507/commits/208ab9ddb60d9d9eecba66e71d1216bc7f08f0ac commit

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3271/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3271/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3271/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3272/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3272/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3272/

**Comment by podarok** [comment]
Looks like all good when no Demo content chosen during the install
image

**Review by podarok — APPROVED** [review]

**Pull request merged**
