### PR TITLE
[OYPD-263] Removing Ubuntu Condensed from the Helvetic mixin

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Verify font was updated.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build489

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/489/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build489/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build490

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/490/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build490/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
