### PR TITLE
[OYPD-381] Incorrect prefix is being stored with urls during default content migration for menu items.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue https://propeople-us.atlassian.net/browse/OYPD-381

- [x] login as admin.
- [x] go to [sitename] /openy page.
- [x] please check (click) all links in main and footer menus
- [x] verify all links work as needed and yo can't see an error.
- [x] go to [sitename] /admin/structure/menu/item/2/edit
Please look 
https://monosnap.com/file/qBSTUoDmNvjBKeSak4VV43D1CKFqyf
https://monosnap.com/file/H8W15sfIP9E3Ulct2YQPRwjERVoTao
- [x] verify in the link field chossen right link
- [x] go to [sitename] /about
- [x] find "Our Mission" and verify "Learn more" link follow to /openy page without any error.
- [x] go to [sitename] /accelerator
- [x] find "Housing & Transition Planning" and verify "Learn more" link follow to /openy page without any error.

Also please check my comment
https://github.com/ymcatwincities/openy/pull/303#issuecomment-295201674

Issue in Drupal.org https://www.drupal.org/node/2871041

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build976 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build976 |
| Installation process | http://install.openy-dev.ffwua.com/build976/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/976/

**Comment by ivan-berezhnov** [comment]
About the line
https://github.com/ymcatwincities/openy/pull/303/files#diff-6e5a3408844365dbbb6209fbb06c9bf7R81
I changed value to NULL because the "learn_more" link doesn't exist and follow to 404 page.

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build976/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@ivan-berezhnov I see fatal error on http://openy-dev.ffwua.com/build976/about and http://openy-dev.ffwua.com/build976/accelerator pages.

That's because you've added `NULL`. Let's just put link to `http://www.openymca.org` there.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build978 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build978 |
| Installation process | http://install.openy-dev.ffwua.com/build978/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/978/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build978/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@ivan-berezhnov I still see fatal errors on those pages.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build979 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build979 |
| Installation process | http://install.openy-dev.ffwua.com/build979/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/979/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build979/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build981 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build981 |
| Installation process | http://install.openy-dev.ffwua.com/build981/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/981/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build981/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build984 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build984 |
| Installation process | http://install.openy-dev.ffwua.com/build984/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/984/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build984/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
