### PR TITLE
[OYPD-497] Adjusting headers for sub-category class listing pages

### PR DESCRIPTION
**Pull request by david-hernandez**
Make sure the items in the attached image are correct.
- [x] H1 tag in header
- [x] H2 tag in header
- [x] Filter button alignment
- [x] H2 tag in section title
- [x] H3 tag in class title.

image-2017-06-14-15-27-04-657

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1731 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1731 |
| Installation process | http://install.openy-dev.ffwua.com/build1731/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1731/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1731

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1731

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1731/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1747 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1747 |
| Installation process | http://install.openy-dev.ffwua.com/build1747/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1747/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1747

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1747

**Comment by alexschedrov** [comment]
1. According to requirements it should be like this
image

Now we have h3 for group title and h2 for class title which breaks sequence.

**Comment by david-hernandez** [comment]
Sorry about that. I changed the wrong file.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1750 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1750 |
| Installation process | http://install.openy-dev.ffwua.com/build1750/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1750/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1750

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1750

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1750/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1751 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1751 |
| Installation process | http://install.openy-dev.ffwua.com/build1751/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1751/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1751

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1751

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1751/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
