### PR TITLE
refs #684: Add update dependency.

### PR DESCRIPTION
**Pull request by ddrozdik**
Issue is described here https://github.com/ymcatwincities/openy/issues/684

## Steps for review
- [ ] review code changes

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1843 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1843 |
| Installation process | http://install.openy-dev.ffwua.com/build1843/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1843/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1843

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1843/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1843/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1843/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1843/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1843/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1843/profiles/contrib/openy/build/reports/behat

**Review by Kerby70 — APPROVED** [review]

**Pull request merged**
