### PR TITLE
Remove unnecessary $install_state argument

### LINKED ISSUE #1556: Terms and Conditions triggers a warning after platform upgrade to v2.0
We've just upgraded to v2.0 and got this warning in admin area:

> Warning: Parameter 3 to Drupal\openy\Form\TermsOfUseForm::buildForm() expected to be a reference, value given in Drupal\Core\Form\FormBuilder->retrieveForm() (line 518 of core/lib/Drupal/Core/Form/FormBuilder.php).

, coming from brand new [Terms of Use](https://github.com/ymcatwincities/openy/pull/1418) feature that was intended to popup during the site installation w/o problems.

image

In our case it gets called from a route `openy_system.openy_terms_and_conditions` and has no 3rd argument **$install_state** hence producing a warning.

As long as the form was intended to be used during profile installation and not using the 3rd argument, the easiest solution could be removing it from _**TermsOfUseForm::buildForm**_ declaration here 
https://github.com/ymcatwincities/openy/blob/42a96117bee4907cc121041e8fbade886515932b/src/Form/TermsOfUseForm.php#L56.

This simple fix does a trick very well!

### PR DESCRIPTION
**Pull request by vitaly-malashevsky**
Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

Fixes https://github.com/ymcatwincities/openy/issues/1556

## Steps for review

- [ ] Install site using openy profile
- [ ] clean terms and condition timestamp (optional)
- [ ] navigate to /admin/openy/terms-and-conditions
- [ ] makes sure no warning displayed

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1562 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1562 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1562 |
| Installation process | http://install.openy.cibox.tools/build1562/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1562/

**Review by afi13 — APPROVED** [review]
Yes, we can remove this arg, so it looks ok for me.

**Comment by vraychev** [comment]
retry deepcode

**Pull request merged**
