### PR TITLE
issue/1335 added title of the PDF schedules page

### PR DESCRIPTION
**Pull request by denisbilchenko**
## Steps for review

- [ ] Open PDF generator page (e.g. by clicking on button "Weekly PDF Schedule " on /group-exercise-classes page).
- [ ] Make sure the title is displayed correctly(should be "Download PDF schedule").

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1179 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1179 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1179 |
| Installation process | http://install.openy.cibox.tools/build1179/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1179/

**Review by ddrozdik — APPROVED** [review]

**Comment by AndreyMaximov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1192 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1192 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1192 |
| Installation process | http://install.openy.cibox.tools/build1192/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1192/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1192/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1192/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1192/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1192/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1192/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Pull request merged**
