### PR TITLE
[OYPD-257] Update blog post styles in demo content

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-257
drupal.org issue - https://www.drupal.org/node/2854229

Steps for review:
- [x] go to /blog
- [x] check blog teasers
- [x] profit

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build522

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/522/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build522/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
image

1. Please set Photo style to for "Nourish yourself with healthy fats" blog post
2. This blog post style for "Don’t let summer sneak up on your family", but with white text

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build523

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/523/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build523/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
