### PR TITLE
[OYPD-178] Adding jquery.ui tabs code for branch header

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Add a branch page with header that includes address, phone, etc.
- [x] Check how the header area looks when using a smaller screen size.

screen shot 2017-02-10 at 5 17 12 pm

### CODE REVIEW

**Comment by david-hernandez** [comment]
https://www.drupal.org/node/2851656

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build423

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/423/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build423/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build428

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/428/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build428/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
