### PR TITLE
[OYPD-350] Fatal error fix twig check data before use. Plus some profiles/contrib/openy cleanup.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-350
D.o https://www.drupal.org/node/2861571

Steps to review:
- [x] Visit homepage
- [x] See page in working order 
- [x] Click menu item locations
- [x] See page in working order with location finder and branches
- [x] Click "East YMCA"
- [x] See page in working order with branch info, gallery, and blog posts list
- [x] Click menu item join
- [x] See page in working order with gallery, and membership selector

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build763 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build763 |
| Installation process | http://install.openy-dev.ffwua.com/build763/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/763/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build763/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build776 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build776 |
| Installation process | http://install.openy-dev.ffwua.com/build776/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/776/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build776/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
