### PR TITLE
[MAINTAIN-203] updated the openy_daxko_gxp_syncer module version up to 1.1.1

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: [MAINTAIN-203](https://openy.atlassian.net/browse/MAINTAIN-203)

## Steps for review

- [ ] the build should be build in correct way
- [ ] log as admin
- [ ] verify that you don't see the 500 error
- [ ] verify that you can visit /admin/openy/integrations/groupex-pro

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by hamrant** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3567/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3567/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3567/

**Comment by hamrant** [comment]
http://install.openy.cibox.tools/build3567/user/1

Screenshot from 2021-11-08 19-14-37

Standard installation without demo content, @aleevas maybe it not related to your previous fixes and to current PR, but we should find the reason of this issue.

@aleevas can you test on local `Open Y Installation Wizard` and install Standard Open Y profile without demo content.

@podarok can you provide the error log from this build, maybe now we have a different error?

**Comment by podarok** [comment]
```
[Mon Nov 08 17:27:13.057041 2021] [php7:notice] [pid 523] [client 178.54.63.218:49403] Uncaught PHP Exception Drupal\\Component\\Plugin\\Exception\\PluginNotFoundException: "The "webform" entity type does not exist." at /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build3567/openy-project/docroot/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 143
```
@hamrant

**Comment by hamrant** [comment]
https://github.com/ymcatwincities/openy/pull/2581#issuecomment-963391144

Wow, this is interesting 🤔

**Comment by hamrant** [comment]
@podarok looks like @froboy is already faced with this issue - https://www.drupal.org/project/drupal/issues/3056633#comment-14149342 😬

**Comment by podarok** [comment]
@hamrant https://github.com/ymcatwincities/openy-cibox-build/pull/18
```php
$settings['class_loader_auto_detect'] = FALSE;
```

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3571/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3571/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3571/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3572/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3572/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3572/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3573/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3573/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3573/

**Comment by podarok** [comment]
image
image


Infrastructure is ready @hamrant

**Review by podarok — APPROVED** [review]
code looks good

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3574/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3574/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3574/

**Review by hamrant — APPROVED** [review]

**Pull request merged**
