### PR TITLE
[OYPD-645]: move Featured Highlights paragraph from LI to OpenY.

### PR DESCRIPTION
**Pull request by fandm**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Jira issue
https://propeople-us.atlassian.net/browse/OYPD-645

## Steps for review

- [ ] Review code changes.
- [ ] Create `Landing Page` node and add `Featured Highlights` paragraph to `Content Area` section.
- [ ] Save the node and verify how it looks. Please note this new paragraph type should be styled.
- [ ] Verify Featured Highlights Paragraphs Behat test.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build244 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build244 |
| Installation process | http://install.openy-dev.ffwua.com/build244/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/244/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build244/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build244/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build244/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build244/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build244/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build244/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build244/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build248 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build248 |
| Installation process | http://install.openy-dev.ffwua.com/build248/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/248/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build248/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build248/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build248/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build248/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build248/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build248/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build248/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build251 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build251 |
| Installation process | http://install.openy-dev.ffwua.com/build251/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/251/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build251/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build251/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build251/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build251/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build251/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build251/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build251/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build260 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build260 |
| Installation process | http://install.openy-dev.ffwua.com/build260/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/260/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build260/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build260/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build260/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build260/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build260/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build260/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build260/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by AlexNetman** [comment]
Making description text white would make this usable in main theme.
image
Also  this images on the right are not taking full space of image. Look like issue with image style. I suggest to use 'blog teaser' image style.
image

Make sure that images are ok when 4 in a row too.
image

**Comment by fandm** [comment]
1. 
>Making description text white would make this usable in main theme.

@david-hernandez will work on it as I know.
2. 
>I suggest to use 'blog teaser' image style.

Done.

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build263 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build263 |
| Installation process | http://install.openy-dev.ffwua.com/build263/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/263/

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build263/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build263/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by ddrozdik** [comment]
After discussions with the team, we decided to do next:
1. Add the possibility specify a type of block. By default should be `Featured Highlights block`. Available options should be: `Basic Block`, `Date Block`, `Simple Block`. 
35809935-2c011718-0a9b-11e8-911f-f7b3fa136cb8 png 1172x207 2018-02-05 19-01-16
2. Update documentation and Behat tests.
3. Provide styles to display the content correctly. Try to copy from YLI. but styles should be part of the module.

**Comment by AlexNetman** [comment]
"Featured Hightlights" naming should be used for the block anymore.
Since this with latest request to add ability to insert other blocks like Basic, Simple, Date block.
Let's name paragraph just as "Columns"

**Comment by ddrozdik** [comment]
We plan to finish this PR here https://github.com/ymcatwincities/openy/pull/953

**Pull request closed without merging**
