### PR TITLE
[OPENY-66] Branch CT decoupling

### PR DESCRIPTION
**Pull request by hamrant**
## Note:

We can't do normal testing of this PR because "OpenY Branch" exist in dependencies almost in all OpenY modules and some of them can't be uninstalled.  

```
OpenY Branch.
Machine name: openy_loc_branch
Version: 8.x-1.0
Required by: 
OpenY Membership
OpenY Facility
OpenY Node Blog
OpenY Node Event
OpenY Session
OpenY Session instance
OpenY Schedules
OpenY Paragraph Schedule Search
OpenY Paragraph Featured Blog Posts
OpenY Paragraph Class Sessions
OpenY Paragraph Latest Blog Posts
OpenY Paragraph Latest Blog Posts (Camp)
OpenY Paragraph Latest Blog Posts (Branch)
OpenY Paragraph Blog Posts Listing
OpenY Paragraph Location Finder
OpenY Paragraph Amenities
OpenY Paragraph Location By Amenities
OpenY Membership Calculator
OpenY Paragraph Membership Calculator
OpenY Paragraph Latest Event Posts
OpenY Paragraph Event Posts Listing
OpenY Branch Selector
OpenY Demo Node Landing Page
OpenY Demo Node Alert
OpenY Demo Taxonomy Blog Category
OpenY Demo Node Blog
OpenY Demo Node Camp
OpenY Demo Node Event
OpenY Demo Taxonomy Facility Type
OpenY Demo Node Facility
OpenY Demo Node Membership
OpenY Paragraph Latest News Posts (Branch)
OpenY Demo Node News
OpenY Demo Node Sessions
```

So I suggest just check code from hook_uninstall with devel help.

## Steps for review

- [x] login as admin
- [x] go to /admin/content?title=&type=branch&status=All&langcode=All
- [x] Check that some branch nodes exist in this list
- [x] go to /admin/modules
- [x] install devel module
- [x] go to /devel/php
- [x] run code from hook_uninstall
- [x] return to /admin/content?title=&type=branch&status=All&langcode=All
- [x] check that branch nodes was removed
- [x] go to /admin/structure/types
- [x] check that "Branch" not exist in this list

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build560 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build560 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build560 |
| Installation process | http://install.openy.cibox.tools/build560/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/560/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build560/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build560/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build560/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build560/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build560/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Comment by ddrozdik** [comment]
This PR is not ready yet since it has unmet dependencies(Amenities) that should be resolved first.

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build585 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build585 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build585 |
| Installation process | http://install.openy.cibox.tools/build585/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/585/

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
