### PR TITLE
[OPENY-224] Remove excluded categories from PEF schedule filter

### PR DESCRIPTION
**Pull request by anprok**
## Steps for review

- [x] Login as admin.
- [x] Go to page /schedules-0
- [x] Click "edit" link.
- [x] Edit Repeat Schedules in Content Area
- [x] Add to CATEGORIES EXCLUDE field Strength category
- [x] Save the page as published.
- [x] Make sure not listed Strength in sidebar filter of categories

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1245 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1245 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1245 |
| Installation process | http://install.openy.cibox.tools/build1245/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1245/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1245/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1245/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1245/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1245/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1245/blogWCAG2AAhtmlcs.txt

**Comment by anprok** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1246 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1246 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1246 |
| Installation process | http://install.openy.cibox.tools/build1246/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1246/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1246/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1246/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1246/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1246/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1246/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1251 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1251 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1251 |
| Installation process | http://install.openy.cibox.tools/build1251/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1251/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1251/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1251/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1251/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1251/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1251/blogWCAG2AAhtmlcs.txt

**Review by AndreyMaximov — APPROVED** [review]

**Comment by AndreyMaximov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1253 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1253 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1253 |
| Installation process | http://install.openy.cibox.tools/build1253/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1253/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1253/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1253/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1253/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1253/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1253/blogWCAG2AAhtmlcs.txt

**Comment by AndreyMaximov** [comment]
looks good!

**Review by ddrozdik — APPROVED** [review]

**Review by podarok — APPROVED** [review]

**Pull request merged**
