### PR TITLE
Added EntityBrowserFormTrait (Activity Finder 4).

### PR DESCRIPTION
**Pull request by duozersk**
Added EntityBrowserFormTrait class used in Activity Finder 4.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
How urgent is this? @duozersk

**Comment by duozersk** [comment]
@podarok It is not urgent at all - I just needed a patch to reference for now. Will post here once it becomes more relevant.

**Comment by podarok** [comment]
Ok, great, thank you @duozersk 

This is a backporting, code needed for external dependency @sarah-halby 
It adds 0 functionality for Open Y - needed only in Activity Finder v4 as a dependency.

I'm fine with merging it even now because of 0 chance for any bugs or regressions. But technically this is a feature.
We can keep this PR up until needed for AFv4 without risk of code conflicts or code outdated.

**Pull request merged**
