### PR TITLE
Adding infinite=true to the blog slider on mobile

### PR DESCRIPTION
**Pull request by rootdamato**
Related to https://github.com/ymcatwincities/openy/issues/1140

## Steps for review

- [x] Go to /blog page on mobile
- [x] Go to the Featured Stories slider and click on next arrow until you reach the last item, then click next arrow again.
- [x] You should see the first item.

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/1162) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by kolesnikoff** [comment]
@podarok please review

**Comment by podarok** [comment]
ok to test

**Review by podarok — APPROVED** [review]
Let's check on a build to get merged

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build588 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build588 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build588 |
| Installation process | http://install.openy.cibox.tools/build588/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/588/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build588/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build588/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build588/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build588/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build588/blogWCAG2AAhtmlcs.txt

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build592 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build592 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build592 |
| Installation process | http://install.openy.cibox.tools/build592/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/592/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build601 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build601 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build601 |
| Installation process | http://install.openy.cibox.tools/build601/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/601/

**Pull request merged**
