### PR TITLE
[GitHub#541] Field Meta Tags is not present in the documentation.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Issues: 
GitHub #541 
Jira https://propeople-us.atlassian.net/browse/OYPD-525
Drupal.org issue: https://www.drupal.org/node/2891701

# Steps to review:
- [x] login as admin
- [x] verify each CT from list below have text helper
List: Blog Post, Branch, Camp, Class, Facility, Landing Page, Program, Program Subcategory
Please look: https://monosnap.com/file/fTZfYKU82tqKwgy3VoLDcMk8bGfawY
- [x] go to 
docs/Content structure/Content Types/Blog.md
docs/Content structure/Content Types/Branch.md
docs/Content structure/Content Types/Camp.md
docs/Content structure/Content Types/Class.md
docs/Content structure/Content Types/Facility.md
docs/Content structure/Content Types/Landing Page.md
docs/Content structure/Content Types/Program Subcategory.md
docs/Content structure/Content Types/Program.md
- [x] verify Meta Tags is present in the documentation for each content type above

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1776 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1776 |
| Installation process | http://install.openy-dev.ffwua.com/build1776/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1776/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1776

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1776

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1776/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1779 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1779 |
| Installation process | http://install.openy-dev.ffwua.com/build1779/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1779/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1779

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1779

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1779/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@ivan-berezhnov needs re-roll.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1786 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1786 |
| Installation process | http://install.openy-dev.ffwua.com/build1786/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1786/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1786

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1786

**Review by alexschedrov — APPROVED** [review]

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1786/profiles/contrib/openy/build/reports/behat

**Pull request merged**
