### PR TITLE
[OYPD-348] Relative path for demo content assets.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-348
D.o https://www.drupal.org/node/2862170

Steps to review:
- [x] Login as administrator
- [x] Go to /admin/content/media
- [x] See demo content assets have loaded properly

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build791 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build791 |
| Installation process | http://install.openy-dev.ffwua.com/build791/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/791/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build791/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build792 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build792 |
| Installation process | http://install.openy-dev.ffwua.com/build792/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/792/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build792/profiles/contrib/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Comment by AlexNetman** [comment]
Seems to be fine.
Note that we still not have images on upgrade env.
http://upgrade.openy-dev.ffwua.com/build792/
Since we don't need support upgrade path there - I suggest to take fresh Db for upgrade path now.

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build795 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build795 |
| Installation process | http://install.openy-dev.ffwua.com/build795/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/795/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build795/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build796 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build796 |
| Installation process | http://install.openy-dev.ffwua.com/build796/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/796/

**Comment by alexschedrov** [comment]
@AlexNetman I've fixed images for upgrade path environment on CI server.

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build796/profiles/contrib/openy/build/reports/behat

**Pull request merged**
