### PR TITLE
[CIYMCA-98] Add option to hide program and home branch block in af.

### PR DESCRIPTION
**Pull request by manachynskyi**
## Steps for review

- [ ] visit edit page where activity finder paragraph is present (or create new node)
- [ ] check **Hide program and home branch block** -> save
- [ ] visit this node, block with Program, and Home branch should be hidden

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by hamrant — APPROVED** [review]
Code looks ok for me

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1929/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1929/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1929/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1929/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1929/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1929/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1929/blogWCAG2AAhtmlcs.txt

**Review by jediandrey — APPROVED** [review]

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build1929/

**Pull request merged**
