### PR TITLE
CSS Fix for subcategory images in mobiles.

### PR DESCRIPTION
**Pull request by bharath-kondeti**
Another fix for: https://github.com/ymcatwincities/openy/issues/2539

Steps to test:
- Visit an openy site.
- Go to the program subcategory page preferably with category listing block present in that.
- Now, adjust the content for the program subcategories that displayed in that page and reduce the description to two or three words and save the content. Next, refresh the page.
- Adjust the browser to different breakpoints for mobile devices to check the fix for the issue

**Note:** Test this fix against carnation theme for now. I am working on the fix for rose/lily theme.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
Could you solve conflict, please? @bharath-kondeti

**Review by podarok — APPROVED** [review]
Code looks good

**Comment by bharath-kondeti** [comment]
@podarok I have resolved the conflicts. Please do verify.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3505/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3505/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3505/

**Pull request merged**
