### PR TITLE
[OYPD-XXX] Fix some typos.

### PR DESCRIPTION
**Pull request by duozersk**
Steps to review:
- [ ] check code changes

### CODE REVIEW

**Review by danylevskyi — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build910 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build910 |
| Installation process | http://install.openy-dev.ffwua.com/build910/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/910/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build911 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build911 |
| Installation process | http://install.openy-dev.ffwua.com/build911/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/911/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build910/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build911/profiles/contrib/openy/build/reports/behat

**Pull request merged**
