### PR TITLE
[OS-168] Backport room filter functionality to OpenY + bugfix of modals

### PR DESCRIPTION
**Pull request by jediandrey**
* room filter should be shown when there are rooms available and location is selected
* modals should be possible to close on mobile

### CODE REVIEW

**Review by podarok — DISMISSED** [review]
Looks good

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build933 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build933 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build933 |
| Installation process | http://install.openy.cibox.tools/build933/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/933/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build933/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build933/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build933/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build933/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build933/blogWCAG2AAhtmlcs.txt

**Comment by ygerasimov** [comment]
@jediandrey additional styling should be added to rooms filter. Rooms should have left padding.

Please ensure it is like that in all themes and also on mobile.

image

**Comment by jediandrey** [comment]
@ygerasimov added the styles^^

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build970 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build970 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build970 |
| Installation process | http://install.openy.cibox.tools/build970/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/970/

**Comment by ygerasimov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1040 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1040 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1040 |
| Installation process | http://install.openy.cibox.tools/build1040/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1040/

**Review by podarok — APPROVED** [review]
Code looks good

**Pull request merged**
