### PR TITLE
[OPENY-48] Date Block paragraph decoupling

### PR DESCRIPTION
**Pull request by hamrant**
## Steps for review

- [x] login as admin
- [x] go to /node/add/landing_page
- [x] create landing page with "Date Block" paragraph in content area
- [x] go to /admin/modules/uninstall
- [x] uninstall "OpenY Paragraph for Date Block" module
- [x] return to created page 
- [x] check that "Date Block" paragraph was removed from CONTENT AREA
- [x] go to /admin/structure/paragraphs_type
- [x] check that "Date Block" paragraph not exist in this list
- [x] go to /admin/modules
- [x] install "OpenY Paragraph for Date Block" module
- [x] return to created page 
- [x] check that you can add "Date Block" paragraph
- [x] check that all components that related to "OpenY Paragraph for Date Block" module was restored and works fine

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build497 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build497 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build497 |
| Installation process | http://install.openy.cibox.tools/build497/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/497/

**Review by ddrozdik — APPROVED** [review]

**Comment by hamrant** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build500 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build500 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build500 |
| Installation process | http://install.openy.cibox.tools/build500/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/500/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build500/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build500/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build500/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build500/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build500/blogWCAG2AAhtmlcs.txt

**Review by ddrozdik — APPROVED** [review]

**Review by podarok — APPROVED** [review]

**Pull request merged**
