### PR TITLE
Make “Hide Main Menu” functionality available from any page. Minor bug fixing.

### PR DESCRIPTION
**Pull request by kolesnikoff**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by kolesnikoff** [comment]
@podarok can you review, please.

**Steps to review**
1. "Hide Main Menu" functionality on Microsites Menu paragraph menu doesn't work at all #834.
- Add "Microsites Menu" paragraph to any node and check how the checkbox work.
- If more than one paragraphs are added, only the first one will affect the main menu.

2. Warning while saving session node #678.
- Create a new session.
- Add session time.
- Add the second fieldset for the session time and leave it empty.
- Save the node.
- No warnings or notices should appear.

3. Unknown errors preventing page save #948.
- Open any Branch node from the demo content (/node/1).
- Find the paragraph "Latest blog posts (branch)".
- It should contain the title "Blog posts (branch)".
- Save the node.
- No errors should appear.

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build376 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build376 |
| Installation process | http://install.openy-dev.ffwua.com/build376/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/376/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build376/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build376/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build376/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build376/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build376/blogWCAG2AAhtmlcs.txt

**Comment by podarok** [comment]
- 1 is fine
- 2 - 
```

Warning: DateTime::createFromFormat() expects parameter 2 to be string, array given in Drupal\Component\Datetime\DateTimePlus::createFromFormat() (line 246 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Component/Datetime/DateTimePlus.php) #0 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/includes/bootstrap.inc(566): _drupal_error_handler_real(2, 'DateTime::creat...', '/var/lib/jenkin...', 246, Array) #1 [internal function]: _drupal_error_handler(2, 'DateTime::creat...', '/var/lib/jenkin...', 246, Array) #2 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Component/Datetime/DateTimePlus.php(246): DateTime::createFromFormat('Y-m-d\\TH:i:s', Array, Object(DateTimeZone)) #3 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/modules/datetime/src/DateTimeComputed.php(51): Drupal\Component\Datetime\DateTimePlus::createFromFormat('Y-m-d\\TH:i:s', Array, 'UTC') #4 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Field/FieldItemBase.php(140): Drupal\datetime\DateTimeComputed->getValue() #5 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/modules/datetime_range/src/Plugin/Field/FieldWidget/DateRangeWidgetBase.php(33): Drupal\Core\Field\FieldItemBase->__get('start_date') #6 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/modules/datetime_range/src/Plugin/Field/FieldWidget/DateRangeDefaultWidget.php(60): Drupal\datetime_range\Plugin\Field\FieldWidget\DateRangeWidgetBase->formElement(Object(Drupal\datetime_range\Plugin\Field\FieldType\DateRangeFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState)) #7 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(322): Drupal\datetime_range\Plugin\Field\FieldWidget\DateRangeDefaultWidget->formElement(Object(Drupal\datetime_range\Plugin\Field\FieldType\DateRangeFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState)) #8 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(189): Drupal\Core\Field\WidgetBase->formSingleElement(Object(Drupal\datetime_range\Plugin\Field\FieldType\DateRangeFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState)) #9 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(104): Drupal\Core\Field\WidgetBase->formMultipleElements(Object(Drupal\datetime_range\Plugin\Field\FieldType\DateRangeFieldItemList), Array, Object(Drupal\Core\Form\FormState)) #10 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(168): Drupal\Core\Field\WidgetBase->form(Object(Drupal\datetime_range\Plugin\Field\FieldType\DateRangeFieldItemList), Array, Object(Drupal\Core\Form\FormState)) #11 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/InlineParagraphsWidget.php(646): Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object(Drupal\paragraphs\Entity\Paragraph), Array, Object(Drupal\Core\Form\FormState)) #12 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(322): Drupal\paragraphs\Plugin\Field\FieldWidget\InlineParagraphsWidget->formElement(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState)) #13 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/InlineParagraphsWidget.php(818): Drupal\Core\Field\WidgetBase->formSingleElement(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState)) #14 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(104): Drupal\paragraphs\Plugin\Field\FieldWidget\InlineParagraphsWidget->formMultipleElements(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState)) #15 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/InlineParagraphsWidget.php(922): Drupal\Core\Field\WidgetBase->form(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState), NULL) #16 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(168): Drupal\paragraphs\Plugin\Field\FieldWidget\InlineParagraphsWidget->form(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState)) #17 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Entity/ContentEntityForm.php(122): Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object(Drupal\node\Entity\Node), Array, Object(Drupal\Core\Form\FormState)) #18 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/modules/node/src/NodeForm.php(113): Drupal\Core\Entity\ContentEntityForm->form(Array, Object(Drupal\Core\Form\FormState)) #19 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Entity/EntityForm.php(117): Drupal\node\NodeForm->form(Array, Object(Drupal\Core\Form\FormState)) #20 [internal function]: Drupal\Core\Entity\EntityForm->buildForm(Array, Object(Drupal\Core\Form\FormState)) #21 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(514): call_user_func_array(Array, Array) #22 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(364): Drupal\Core\Form\FormBuilder->retrieveForm('node_session_fo...', Object(Drupal\Core\Form\FormState)) #23 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(621): Drupal\Core\Form\FormBuilder->rebuildForm('node_session_fo...', Object(Drupal\Core\Form\FormState), Array) #24 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(314): Drupal\Core\Form\FormBuilder->processForm('node_session_fo...', Array, Object(Drupal\Core\Form\FormState)) #25 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Entity/EntityFormBuilder.php(48): Drupal\Core\Form\FormBuilder->buildForm('node_session_fo...', Object(Drupal\Core\Form\FormState)) #26 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/modules/node/src/Controller/NodeController.php(113): Drupal\Core\Entity\EntityFormBuilder->getForm(Object(Drupal\node\Entity\Node)) #27 [internal function]: Drupal\node\Controller\NodeController->add(Object(Drupal\node\Entity\NodeType)) #28 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #29 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #30 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #31 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #32 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #33 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array) #34 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #35 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-profile/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #41 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #42 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #43 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #44 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build376/openy-project/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #45 {main}.
--

```
image
- 3 - ok

**Review by podarok — APPROVED** [review]
Code looks good
@kolesnikoff ensure log messaged are not related to the bullet 2 you have been trying fix, please

**Pull request merged**
