### PR TITLE
[carnation] Fix for openy subcategory page image resize issue.

### LINKED ISSUE #2539: Carnation: Subprogram listing item images not 100% on mobile
To reproduce:

- Visit https://sandbox-carnation-cus.openy.org/programs/health-and-fitness
- Edit one of the description fields to be just a few words.
- observe the entire row width shrinks.

Health_and_Fitness___Drush_Site-Install

Proposed resolution:

It looks like:
```
 .subprogram-listing-item {
    display: table;
    ...
 }

.subprogram-listing-item .image {
    display: table-caption;
}
```    
are causing the issue. Removing `display:table;` or replacing with `display:block` seems to resolve the issue.

### PR DESCRIPTION
**Pull request by bharath-kondeti**
Fixes: https://github.com/ymcatwincities/openy/issues/2539

Steps to test:
- Visit an openy site.
- Go to the program subcategory page preferably with category listing block present in that.
- Now, adjust the content for the program subcategories that displayed in that page and reduce the description to two or three words and save the content. Next, refresh the page.
- Adjust the browser to different breakpoints for mobile devices to check the fix for the issue.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by bharath-kondeti** [comment]
o+k to test

**Comment by podarok** [comment]
@bharath-kondeti I see you have a change in compiled main.js file, but there is no source js change in PR.
Could you add it as well?
I want to ensure we are not losing your change once main.js recompiled next time without your change in source files

**Comment by bharath-kondeti** [comment]
@podarok, I did not make any changes to any JS file. When I complied my css change there were changes in both styles.css and main.js as well. Hence, i have added those as a part of this PR.

**Pull request merged**
