### PR TITLE
[OPENY-22] Gallery - component decoupling

### PR DESCRIPTION
**Pull request by AndreyMaximov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [x]  Login as admin
- [x]  Go to /node/add/landing_page
- [x]  Create a node of CT Landing Page with a "Gallery" paragraph
- [x]  go to /admin/modules/uninstall
- [x]  uninstall "OpenY Paragraph Gallery"
- [x]  return to the created landing page, verify the page works fine and doesn't contain "Gallery" content (try to edit this page, all must be fine)
- [x]  go to /admin/config/media/image-styles
- [x]  check that "Paragraph gallery" is not presented
- [x]  go to /admin/structure/display-modes/view
- [x]  check that "Paragraph gallery" doesn't exist in Media section
- [x]  go to /admin/modules
- [x]  enable "OpenY Paragraph Gallery"
- [x]  verify the modules functionality has restored and it works fine, when the module is enabled back

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build360 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build360 |
| Installation process | http://install.openy-dev.ffwua.com/build360/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/360/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build360/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build360/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build360/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build360/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build360/blogWCAG2AAhtmlcs.txt

**Comment by AndreyMaximov** [comment]
Demo content module migrations depend on the paragraph affected by the changes, but there is no dependency specified within the modules.
If it was specified, it would be impossible to disable gallery paragraph module though.

**Review by podarok — APPROVED** [review]

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build363 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build363 |
| Installation process | http://install.openy-dev.ffwua.com/build363/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/363/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build363/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build363/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build363/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build363/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build363/blogWCAG2AAhtmlcs.txt

**Pull request merged**
