### PR TITLE
[OPYD-321] fixing admin menu visbility on mobile viewpoint

### PR DESCRIPTION
**Pull request by xcf33**
Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by xcf33** [comment]
Steps to test,

1. Login as administrator
2. Resize browser to the smallest size
3. verify the admin toolbar appears on top
4. verify when scroll down on the page, the admin toolbar is not fixed (sticky on top)
5. click on the sandwich menu on the toolbar
6. Make sure the to navigation is not blocking part of the expanded admin tool bar

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1050 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1050 |
| Installation process | http://install.openy-dev.ffwua.com/build1050/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1050/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1050/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1051 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1051 |
| Installation process | http://install.openy-dev.ffwua.com/build1051/install.php |

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1052/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #323 of commit 80533c7ad12ceadcc3693dfdd511234c28136725 automatically merged.
GitHub pull request #323 of commit 80533c7ad12ceadcc3693dfdd511234c28136725 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git6267567096594643302.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: remote: Counting objects: 2906, done.
remote: Compressing objects:   0% (1/1804)   
remote: Compressing objects:   1% (19/1804)   
remote: Compressing objects:   2% (37/1804)   
remote: Compressing objects:   3% (55/1804)   
remote: Compressing objects:   4% (73/1804)   
remote: Compressing objects:   5% (91/1804)   
remote: Compressing objects:   6% (109/1804)   
remote: Compressing objects:   7% (127/1804)   
remote: Compressing objects:   8% (145/1804)   
remote: Compressing objects:   9% (163/1804)   
remote: Compressing objects:  10% (181/1804)   
remote: Compressing objects:  11% (199/1804)   
remote: Compressing objects:  12% (217/1804)   
remote: Compressing objects:  13% (235/1804)   
remote: Compressing objects:  14% (253/1804)   
remote: Compressing objects:  15% (271/1804)   
remote: Compressing objects:  16% (289/1804)   
remote: Compressing objects:  17% (307/1804)   
remote: Compressing objects:  18% (325/1804)   
remote: Compressing objects:  19% (343/1804)   
remote: Compressing objects:  20% (361/1804)   
remote: Compressing objects:  21% (379/1804)   
remote: Compressing objects:  22% (397/1804)   
remote: Compressing objects:  23% (415/1804)   
remote: Compressing objects:  24% (433/1804)   
remote: Compressing objects:  25% (451/1804)   
remote: Compressing objects:  26% (470/1804)   
remote: Compressing objects:  27% (488/1804)   
remote: Compressing objects:  28% (506/1804)   
remote: Compressing objects:  29% (524/1804)   
remote: Compressing objects:  30% (542/1804)   
remote: Compressing objects:  31% (560/1804)   
remote: Compressing objects:  32% (578/1804)   
remote: Compressing objects:  33% (596/1804)   
remote: Compressing objects:  34% (614/1804)   
remote: Compressing objects:  35% (632/1804)   
remote: Compressing objects:  36% (650/1804)   
remote: Compressing objects:  37% (668/1804)   
remote: Compressing objects:  38% (686/1804)   
remote: Compressing objects:  39% (704/1804)   
remote: Compressing objects:  40% (722/1804)   
remote: Compressing objects:  41% (740/1804)   
remote: Compressing objects:  42% (758/1804)   
remote: Compressing objects:  43% (776/1804)   
remote: Compressing objects:  44% (794/1804)   
remote: Compressing objects:  45% (812/1804)   
remote: Compressing objects:  46% (830/1804)   
remote: Compressing objects:  47% (848/1804)   
remote: Compressing objects:  48% (866/1804)   
remote: Compressing objects:  49% (884/1804)   
remote: Compressing objects:  50% (902/1804)   
remote: Compressing objects:  51% (921/1804)   
remote: Compressing objects:  52% (939/1804)   
remote: Compressing objects:  53% (957/1804)   
remote: Compressing objects:  54% (975/1804)   
remote: Compressing objects:  55% (993/1804)   
remote: Compressing objects:  56% (1011/1804)   
```

**Comment by xcf33** [comment]
image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1054 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1054 |
| Installation process | http://install.openy-dev.ffwua.com/build1054/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1054/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1054/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
