### PR TITLE
Close access to the taxonomy pages

### PR DESCRIPTION
**Pull request by yasik78**
https://github.com/ymcatwincities/openy/issues/378

## Steps for review 

- [ ] Login  as admin
- [ ] Check  term  admin/structure/taxonomy/manage/area/overview                                 -  page 404            
- [ ] Check  term  admin/structure/taxonomy/manage/color/overview                                -  page 404         
- [ ] Check  term  admin/structure/taxonomy/manage/facility_type/overview                      -  page 404 
     
- [ ] Check  term  admin/structure/taxonomy/manage/blog_category/overview                  -   ok

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1723 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1723 |
| Installation process | http://install.openy-dev.ffwua.com/build1723/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1723/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1723

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1723

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1723/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1736 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1736 |
| Installation process | http://install.openy-dev.ffwua.com/build1736/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1736/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1736

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1736

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1736/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@yasik78 
1. We should close access only to followign taxonomy terms
image

2. Please use module `rabbit_hole` to close access. It should be already in the distribution.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1764/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #617 of commit dd3d9e210a57b0b406ca6fda18bd2da4846f9241 automatically merged.
GitHub pull request #617 of commit dd3d9e210a57b0b406ca6fda18bd2da4846f9241 automatically merged.
GitHub pull request #617 of commit dd3d9e210a57b0b406ca6fda18bd2da4846f9241 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5945194190354798410.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git3238611665996187470.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/617/merge^{commit} # timeout=10
 > git branch -a --contains 1a622b5344a158f91bbee459d2526652934278a2 # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
Checking out Revision 1a622b5344a158f91bbee459d2526652934278a2 (origin/pr/617/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1a622b5344a158f91bbee459d2526652934278a2
First time build. Skipping changelog.
Waiting for the completion of SERVER_CLEANER_FIFO
SERVER_CLEANER_FIFO #127 completed. Result was SUCCESS
Build step 'Trigger/call builds on other projects' changed build result to SUCCESS
[workspace] $ /bin/sh -xe /tmp/hudson2846388450407207908.sh
+ rm -Rf /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ cp -R ../vm /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
From github.com:propeoplemd/openy_vm
   ce3ae8d..b0a8a31  master     -> origin/master
Updating ce3ae8d..b0a8a31
Fast-forward
 .../libraries/colordialog/dialogs/colordialog.css  |   20 +
 .../libraries/colordialog/dialogs/colordialog.js   |  343 +++
 docroot/libraries/colordialog/lang/af.js           |   11 +
 docroot/libraries/colordialog/lang/ar.js           |   11 +
 docroot/libraries/colordialog/lang/az.js           |   11 +
 docroot/libraries/colordialog/lang/bg.js           |   11 +
 docroot/libraries/colordialog/lang/bn.js           |   11 +
 docroot/libraries/colordialog/lang/bs.js           |   11 +
 docroot/libraries/colordialog/lang/ca.js           |   11 +
 docroot/libraries/colordialog/lang/cs.js           |   11 +
 docroot/libraries/colordialog/lang/cy.js           |   11 +
 docroot/libraries/colordialog/lang/da.js           |   11 +
 docroot/libraries/colordialog/lang/de-ch.js        |   11 +
 docroot/libraries/colordialog/lang/de.js           |   11 +
 docroot/libraries/colordialog/lang/el.js           |   11 +
 docroot/libraries/colordialog/lang/en-au.js        |   11 +
 docroot/libraries/colordialog/lang/en-ca.js        |   11 +
 docroot/libraries/colordialog/lang/en-gb.js        |   11 +
 docroot/libraries/colordialog/lang/en.js           |   11 +
 docroot/libraries/colordialog/lang/eo.js           |   11 +
 docroot/libraries/colordialog/lang/es.js           |   11 +
 docroot/libraries/colordialog/lang/et.js           |   11 +
 docroot/libraries/colordialog/lang/eu.js           |   11 +
 docroot/libraries/colordialog/lang/fa.js           |   11 +
 docroot/libraries/colordialog/lang/fi.js           |   11 +
 docroot/libraries/colordialog/lang/fo.js           |   11 +
 docroot/libraries/colordialog/lang/fr-ca.js        |   11 +
 docroot/libraries/colordialog/lang/fr.js           |   11 +
 docroot/libraries/colordialog/lang/gl.js           |   11 +
 docroot/libraries/colordialog/lang/gu.js           |   11 +
 docroot/libraries/colordialog/lang/he.js           |   11 +
 docroot/libraries/colordialog/lang/hi.js           |   11 +
 docroot/libraries/colordialog/lang/hr.js           |   11 +
 docroot/libraries/colordialog/lang/hu.js           |   11 +
 docroot/libraries/colordialog/lang/id.js           |   11 +
 docroot/libraries/colordialog/lang/is.js           |   11 +
 docroot/libraries/colordialog/lang/it.js           |   11 +
 docroot/libraries/colordialog/lang/ja.js           |   11 +
 docroot/libraries/colordialog/lang/ka.js           |   11 +
 docroot/libraries/colordialog/lang/km.js           |   11 +
 docroot/libraries/colordialog/lang/ko.js           |   11 +
 docroot/libraries/colordialog/lang/ku.js           |   11 +
 docroot/libraries/colordialog/lang/lt.js           |   11 +
 docroot/libraries/colordialog/lang/lv.js           |   11 +
 docroot/libraries/colordialog/lang/mk.js           |   11 +
 docroot/libraries/colordialog/lang/mn.js           |   11 +
 docroot/libraries/colordialog/lang/ms.js           |   11 +
 docroot/libraries/colordialog/lang/nb.js           |   11 +
 docroot/libraries/colordialog/lang/nl.js           |   11 +
 docroot/libraries/colordialog/lang/no.js           |   11 +
 docroot/libraries/colordialog/lang/oc.js           |   11 +
 docroot/libraries/colordialog/lang/pl.js           |   11 +
 docroot/libraries/colordialog/lang/pt-br.js        |   11 +
 docroot/libraries/colordialog/lang/pt.js           |   11 +
 docroot/libraries/colordialog/lang/ro.js           |   11 +
 docroot/libraries/colordialog/lang/ru.js           |   11 +
 docroot/libraries/colordialog/lang/si.js           |   11 +
 docroot/libraries/colordialog/lang/sk.js           |   11 +
 docroot/libraries/colordialog/lang/sl.js           |   11 +
 docroot/libraries/colordialog/lang/sq.js           |   11 +
 docroot/libraries/colordialog/lang/sr-latn.js      |   11 +
 docroot/libraries/colordialog/lang/sr.js           |   11 +
 docroot/libraries/colordialog/lang/sv.js           |   11 +
 docroot/libraries/colordialog/lang/th.js           |   11 +
 docroot/libraries/colordialog/lang/tr.js           |   11 +
 docroot/libraries/colordialog/lang/tt.js           |   11 +
 docroot/libraries/colordialog/lang/ug.js           |   11 +
 docroot/libraries/colordialog/lang/uk.js           |   11 +
 docroot/libraries/colordialog/lang/vi.js           |   11 +
 docroot/libraries/colordialog/lang/zh-cn.js        |   11 +
 docroot/libraries/colordialog/lang/zh.js           |   11 +
 docroot/libraries/colordialog/plugin.js            |   71 +
 docroot/libraries/glyphicons/css/config.json       |  402 ++++
 docroot/libraries/glyphicons/css/css/bootstrap.css |  819 +++++++
 .../css/fonts/glyphicons-halflings-regular.eot     |  Bin 0 -> 20127 bytes
 .../css/fonts/glyphicons-halflings-regular.svg     |  288 +++
 .../css/fonts/glyphicons-halflings-regular.ttf     |  772 +++++++
 .../css/fonts/glyphicons-halflings-regular.woff    |  Bin 0 -> 23424 bytes
 .../css/fonts/glyphicons-halflings-regular.woff2   |  Bin 0 -> 18028 bytes
 docroot/libraries/glyphicons/css/js/bootstrap.js   | 2366 ++++++++++++++++++++
 .../libraries/glyphicons/css/js/bootstrap.min.js   |   12 +
 docroot/libraries/glyphicons/css/style.css         |   13 +
 docroot/libraries/glyphicons/dialogs/glyphicons.js |  141 ++
 docroot/libraries/glyphicons/icons/glyphicons.png  |    6 +
 docroot/libraries/glyphicons/plugin.js             |   40 +
 85 files changed, 6052 insertions(+)
 create mode 100644 docroot/libraries/colordialog/dialogs/colordialog.css
 create mode 100644 docroot/libraries/colordialog/dialogs/colordialog.js
 create mode 100644 docroot/libraries/colordialog/lang/af.js
 create mode 100644 docroot/libraries/colordialog/lang/ar.js
 create mode 100644 docroot/libraries/colordialog/lang/az.js
 create mode 100644 docroot/libraries/colordialog/lang/bg.js
 create mode 100644 docroot/libraries/colordialog/lang/bn.js
 create mode 100644 docroot/libraries/colordialog/lang/bs.js
 create mode 100644 docroot/libraries/colordialog/lang/ca.js
 create mode 100644 docroot/libraries/colordialog/lang/cs.js
 create mode 100644 docroot/libraries/colordialog/lang/cy.js
 create mode 100644 docroot/libraries/colordialog/lang/da.js
 create mode 100644 docroot/libraries/colordialog/lang/de-ch.js
 create mode 100644 docroot/libraries/colordialog/lang/de.js
 create mode 100644 docroot/libraries/colordialog/lang/el.js
 create mode 100644 docroot/libraries/colordialog/lang/en-au.js
 create mode 100644 docroot/libraries/colordialog/lang/en-ca.js
 create mode 100644 docroot/libraries/colordialog/lang/en-gb.js
 create mode 100644 docroot/libraries/colordialog/lang/en.js
 create mode 100644 docroot/libraries/colordialog/lang/eo.js
 create mode 100644 docroot/libraries/colordialog/lang/es.js
 create mode 100644 docroot/libraries/colordialog/lang/et.js
 create mode 100644 docroot/libraries/colordialog/lang/eu.js
 create mode 100644 docroot/libraries/colordialog/lang/fa.js
 create mode 100644 docroot/libraries/colordialog/lang/fi.js
 create mode 100644 docroot/libraries/colordialog/lang/fo.js
 create mode 100644 docroot/libraries/colordialog/lang/fr-ca.js
 create mode 100644 docroot/libraries/colordialog/lang/fr.js
 create mode 100644 docroot/libraries/colordialog/lang/gl.js
 create mode 100644 docroot/libraries/colordialog/lang/gu.js
 create mode 100644 docroot/libraries/colordialog/lang/he.js
 create mode 100644 docroot/libraries/colordialog/lang/hi.js
 create mode 100644 docroot/libraries/colordialog/lang/hr.js
 create mode 100644 docroot/libraries/colordialog/lang/hu.js
 create mode 100644 docroot/libraries/colordialog/lang/id.js
 create mode 100644 docroot/libraries/colordialog/lang/is.js
 create mode 100644 docroot/libraries/colordialog/lang/it.js
 create mode 100644 docroot/libraries/colordialog/lang/ja.js
 create mode 100644 docroot/libraries/colordialog/lang/ka.js
 create mode 100644 docroot/libraries/colordialog/lang/km.js
 create mode 100644 docroot/libraries/colordialog/lang/ko.js
 create mode 100644 docroot/libraries/colordialog/lang/ku.js
 create mode 100644 docroot/libraries/colordialog/lang/lt.js
 create mode 100644 docroot/libraries/colordialog/lang/lv.js
 create mode 100644 docroot/libraries/colordialog/lang/mk.js
 create mode 100644 docroot/libraries/colordialog/lang/mn.js
 create mode 100644 docroot/libraries/colordialog/lang/ms.js
 create mode 100644 docroot/libraries/colordialog/lang/nb.js
 create mode 100644 docroot/libraries/colordialog/lang/nl.js
 create mode 100644 docroot/libraries/colordialog/lang/no.js
 create mode 100644 docroot/libraries/colordialog/lang/oc.js
 create mode 100644 docroot/libraries/colordialog/lang/pl.js
 create mode 100644 docroot/libraries/colordialog/lang/pt-br.js
 create mode 100644 docroot/libraries/colordialog/lang/pt.js
 create mode 100644 docroot/libraries/colordialog/lang/ro.js
 create mode 100644 docroot/libraries/colordialog/lang/ru.js
 create mode 100644 docroot/libraries/colordialog/lang/si.js
 create mode 100644 docroot/libraries/colordialog/lang/sk.js
 create mode 100644 docroot/libraries/colordialog/lang/sl.js
 create mode 100644 docroot/libraries/colordialog/lang/sq.js
 create mode 100644 docroot/libraries/colordialog/lang/sr-latn.js
 create mode 100644 docroot/libraries/colordialog/lang/sr.js
 create mode 100644 docroot/libraries/colordialog/lang/sv.js
 create mode 100644 docroot/libraries/colordialog/lang/th.js
 create mode 100644 docroot/libraries/colordialog/lang/tr.js
 create mode 100644 docroot/libraries/colordialog/lang/tt.js
 create mode 100644 docroot/libraries/colordialog/lang/ug.js
 create mode 100644 docroot/libraries/colordialog/lang/uk.js
 create mode 100644 docroot/libraries/colordialog/lang/vi.js
 create mode 100644 docroot/libraries/colordialog/lang/zh-cn.js
 create mode 100644 docroot/libraries/colordialog/lang/zh.js
 create mode 100644 docroot/libraries/colordialog/plugin.js
 create mode 100644 docroot/libraries/glyphicons/css/config.json
 create mode 100644 docroot/libraries/glyphicons/css/css/bootstrap.css
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.eot
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.svg
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.ttf
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.woff
 create mode 100644 docroot/libraries/glyphicons/css/fonts/glyphicons-halflings-regular.woff2
 create mode 100644 docroot/libraries/glyphicons/css/js/bootstrap.js
 create mode 100644 docroot/libraries/glyphicons/css/js/bootstrap.min.js
 create mode 100644 docroot/libraries/glyphicons/css/style.css
 create mode 100644 docroot/libraries/glyphicons/dialogs/glyphicons.js
 create mode 100644 docroot/libraries/glyphicons/icons/glyphicons.png
 create mode 100644 docroot/libraries/glyphicons/plugin.js
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory1706085327280347428.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1764 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory6357025522402877324.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1764 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1764/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1764 -e drupal_folder=/var/www/build1764 -e site_url=http://openy-dev.ffwua.com/build1764 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
changed: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [localhost] => (item={'status': True, 'name': '$config["system.file"]["path.temporary"]', 'value': '/tmp'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
skipping: [localhost]

TASK: [Creating drupal database] ********************************************** 
skipping: [localhost]

TASK: [Downloading latest backup to local environment] ************************ 
skipping: [localhost]

TASK: [Removing possible abandoned dump] ************************************** 
skipping: [localhost]

TASK: [Importing from remote backup] ****************************************** 
skipping: [localhost]

TASK: [Copy latest backup to build folder] ************************************ 
skipping: [localhost]

TASK: [Importing from local backup] ******************************************* 
skipping: [localhost]

TASK: [Remove local backup from build folder] ********************************* 
skipping: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
skipping: [localhost]

TASK: [Clear Drupal cache] **************************************************** 
skipping: [localhost]

TASK: [Updating database] ***************************************************** 
skipping: [localhost]

TASK: [Apply pending entity schema updates] *********************************** 
skipping: [localhost]

TASK: [Download stage file proxy] ********************************************* 
skipping: [localhost]

TASK: [Enable stage file proxy] *********************************************** 
skipping: [localhost]

TASK: [Set configuration for stage file proxy] ******************************** 
skipping: [localhost]

TASK: [Set folder for stage file proxy] *************************************** 
skipping: [localhost]

TASK: [Updates listing] ******************************************************* 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
ok: [localhost]

TASK: [Creating drupal database] ********************************************** 
changed: [localhost]

TASK: [Remove settings.php] *************************************************** 
ok: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
changed: [localhost]

TASK: [Installing drupal] ***************************************************** 
failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush -y si openy --db-url=mysql://root:root@127.0.0.1:/drupal1764 --account-name=admin --account-pass=openy --uri=http://openy-dev.ffwua.com/build1764", "delta": "0:01:53.528476", "end": "2017-06-29 13:32:56.417216", "rc": 1, "start": "2017-06-29 13:31:02.888740", "warnings": []}
stderr: Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects [error]
provided by <em class="placeholder">openy_taxonomy</em> have unmet
dependencies: <em class="placeholder">views.view.taxonomy_term
(taxonomy.vocabulary.blog_category)</em> in
/var/www/build1764/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98
Stack trace:
#0
/var/www/build1764/core/lib/Drupal/Core/Config/ConfigInstaller.php(469):
Drupal\Core\Config\UnmetDependenciesException::create('openy_taxonomy',
Array)
#1
/var/www/build1764/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module',
'openy_taxonomy')
#2
/var/www/build1764/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#3 /var/www/build1764/core/includes/install.core.inc(1800):
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array,
false)
#4 /var/www/build1764/core/includes/batch.inc(252):
_install_module_batch('openy_taxonomy', 'OpenY Taxonomy ...', Array)
#5 /var/www/build1764/core/includes/form.inc(874): _batch_process()
#6 /var/www/build1764/core/includes/install.core.inc(619):
batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#7 /var/www/build1764/core/includes/install.core.inc(540):
install_run_task(Array, Array)
#8 /var/www/build1764/core/includes/install.core.inc(117):
install_run_tasks(Array)
#9 /usr/local/src/drush/includes/drush.inc(726):
install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#10 /usr/local/src/drush/includes/drush.inc(711):
drush_call_user_func_array('install_drupal', Array)
#11 /usr/local/src/drush/commands/core/drupal/site_install.inc(80):
drush_op('install_drupal', Object(Composer\Autoload\ClassLoader),
Array)
#12 /usr/local/src/drush/commands/core/site_install.drush.inc(249):
drush_core_site_install_version('openy', Array)
#13 /usr/local/src/drush/includes/command.inc(422):
drush_core_site_install('openy')
#14 /usr/local/src/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#15 /usr/local/src/drush/includes/command.inc(199):
drush_command('openy')
#16 /usr/local/src/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#17 /usr/local/src/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#18 /usr/local/src/drush/drush.php(12): drush_main()
#19 {main}
stdout: You are about to create a /var/www/build1764/sites/default/settings.php file and DROP all tables in your 'drupal1764' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by ddrozdik** [comment]
Also we need to add upgrade path here

**Comment by alexschedrov** [comment]
This has been fixed by another community member here #669. Thank you for contribution!

**Pull request closed without merging**
