### PR TITLE
[OPENY-50] Featured Blog Posts paragraph decoupling

### PR DESCRIPTION
**Pull request by hamrant**
## Steps for review

- [x] login as admin
- [x] Go to "/blog"
- [x] Check that you can see here "Featured Blog Posts" paragraph in content area
- [x] go to "/admin/modules/uninstall"
- [x] uninstall "OpenY Paragraph Featured Blog Posts" module
- [x] return to "/blog" page
- [x] check that "Featured Blog Posts" paragraph was removed
- [x] edit this page
- [x] check that you can't add "Featured Blog Posts" paragraph
- [x] go to "/admin/modules"
- [x] install "OpenY Paragraph Featured Blog Posts"
- [x] return to "/blog" page and edit
- [x] add "Featured Blog Posts" paragraph  to content area with random list of blog posts
- [x] save node and check that all works fine

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build463 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build463 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build463 |
| Installation process | http://install.openy.cibox.tools/build463/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/463/

**Review by podarok — APPROVED** [review]
Looks good code wise

**Comment by ddrozdik** [comment]
retest this please

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build476 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build476 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build476 |
| Installation process | http://install.openy.cibox.tools/build476/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/476/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build476/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build476/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build476/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build476/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build476/blogWCAG2AAhtmlcs.txt

**Comment by hamrant** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build477 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build477 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build477 |
| Installation process | http://install.openy.cibox.tools/build477/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/477/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build477/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build477/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build477/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build477/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build477/blogWCAG2AAhtmlcs.txt

**Pull request merged**
