### PR TITLE
[OYPD-385] Resolve Footer menu is empty.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-385
D.o https://www.drupal.org/node/2871597

Steps to review
- [x] The Footer menus have links

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1007 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1007 |
| Installation process | http://install.openy-dev.ffwua.com/build1007/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1007/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1007/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1010 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1010 |
| Installation process | http://install.openy-dev.ffwua.com/build1010/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1010/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1010/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
