### PR TITLE
[OYPD-376] Update function, form alter, view config change to modify blog search…

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Update
- [x] Verify labels on /blog filter changed.
- [x] Verify the search box has a placeholder.
- [x] Verify upgrade is supported for the view config changes.

screen shot 2017-04-12 at 8 48 44 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build926 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build926 |
| Installation process | http://install.openy-dev.ffwua.com/build926/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/926/

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build928 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build928 |
| Installation process | http://install.openy-dev.ffwua.com/build928/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/928/

**Comment by david-hernandez** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build931 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build931 |
| Installation process | http://install.openy-dev.ffwua.com/build931/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/931/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build931/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build944 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build944 |
| Installation process | http://install.openy-dev.ffwua.com/build944/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/944/

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build946 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build946 |
| Installation process | http://install.openy-dev.ffwua.com/build946/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/946/

**Comment by alexschedrov** [comment]
@david-hernandez it turns out that when there's no results it displays nothing.

Can you please add text "Sorry, no content matched your criteria." or something like this.
image

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build946/profiles/contrib/openy/build/reports/behat

**Comment by david-hernandez** [comment]
Updated the view. 

screen shot 2017-04-14 at 10 25 19 am

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build950 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build950 |
| Installation process | http://install.openy-dev.ffwua.com/build950/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/950/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build950/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
We should not remove labels like this. But hide them.
Because form elements without labels are needed for accessibility.

 **A properly associated label is:**
a <label> element with a for attribute value that is equal to the id of a unique form control
a <label> element that surrounds the form control, does not surround any other form controls, and does not reference another element with its for attribute
a non-empty title attribute, or
a non-empty aria-labelledby attribute

**Comment by david-hernandez** [comment]
@AlexNetman I put a label back for the search box and hid it accessibly.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build952 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build952 |
| Installation process | http://install.openy-dev.ffwua.com/build952/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/952/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build952/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build960 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build960 |
| Installation process | http://install.openy-dev.ffwua.com/build960/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/960/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build960/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build963 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build963 |
| Installation process | http://install.openy-dev.ffwua.com/build963/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/963/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build963/profiles/contrib/openy/build/reports/behat

**Pull request merged**
