### PR TITLE
[OYPD-347] Update composer adding php >=5.6 dependency.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-347
D.o https://www.drupal.org/node/2862553
Also previous Pull request #250 
Steps to review
- [x] Composer install will fail on systems with version of php lower than 5.6
- [x] Drupal profile/module install should fail on system with version of php lower than 5.6
- [x] Composer will install on a system with php >=5.6 including 7.*

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build823 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build823 |
| Installation process | http://install.openy-dev.ffwua.com/build823/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/823/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build823/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build829 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build829 |
| Installation process | http://install.openy-dev.ffwua.com/build829/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/829/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build829/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
