### PR TITLE
Update 1 column styles

### LINKED ISSUE #2557: 1 Column paragraph body text looks awkward
- Edit a Landing Page
- Add a `1 Column` Paragraph to the Content
- Add some text to the `Paragraph Description`
- Observe the text doesn't match the body text of the `Simple Content`  Paragraph

In screenshots, the top is "Simple Content" the bottom is "1 Column".

Here's Carnation:
image

Here's Lily:
image

Rose:
image

### PR DESCRIPTION
**Pull request by froboy**
Fixes https://github.com/ymcatwincities/openy/issues/2557.

WIP:
- [x] do other themes
- [ ] compile it all

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Visit /about
- [ ] Copy the text in the Simple Content Paragraph and add it to a 1 Column
- [ ] See that it's consistent across themes and mostly matches

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3506/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3506/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3506/

**Comment by froboy** [comment]
@podarok I had some issues compiling and I don't have time to resolve them right now. Would you be able to compile things when this is ready to review?

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3507/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3507/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3507/

**Comment by podarok** [comment]
@froboy yes, I can pick it up
Let me know when you done with your part

@sarah-halby @shelleygoetz could you take care about Jira tracking for this task, please?

**Comment by sarah-halby** [comment]
@podarok there is a ticket in Jira for this - it's the GitHub ticket rather than the PR as usual.

**Comment by shelleygoetz** [comment]
Link to Jira ticket: https://openy.atlassian.net/jira/software/c/projects/MAINTAIN/boards/2?modal=detail&selectedIssue=MAINTAIN-179

**Comment by froboy** [comment]
@podarok it's all ready for you. Thank you! I do need to get the compiling working locally at some point though... :\

**Comment by podarok** [comment]
Task continuation is https://github.com/ymcatwincities/openy/pull/2574

**Pull request closed without merging**
