### PR TITLE
[OPENY-94] OpenY Popups decoupling

### PR DESCRIPTION
**Pull request by anprok**
OpenY Popups required by _openy_prgf_branches_popup_all_, _openy_prgf_branches_popup_class_ modules that already decoupled. 

## Steps for review

- [x] login as admin.
- [x] visit admin/config/content
- [x] make sure OpenY Popups settings page listed and points to settings page
- [x] visit admin/people/permissions
- [x] make sure listed permissions **Administer popups**, **View popups**
- [x] go to /admin/modules/uninstall.
- [x] uninstall "OpenY Paragraph Branches Popup (All)" and "OpenY Paragraph Branches Popup (Class)" - [ ] uninstall "OpenY Popups" module
- [x] visit admin/config/content page
- [x] make sure OpenY Popups settings page not listed
- [x] visit admin/people/permissions
- [x] make sure that not listed permissions **Administer popups**, **View popups**
- [x]  go to /admin/modules
 - [x]  install "OpenY Popups" module
 - [x]  check that all module components was restored

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Review by podarok — APPROVED** [review]

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build634 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build634 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build634 |
| Installation process | http://install.openy.cibox.tools/build634/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/634/

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build637 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build637 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build637 |
| Installation process | http://install.openy.cibox.tools/build637/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/637/

**Pull request merged**
