### PR TITLE
[OYPD-457] Remove unused dependency cevou/behat-screenshot-compare-ex…

### PR DESCRIPTION
**Pull request by Kerby70**
…tension, and update bash scripts to run from bash not sh.

Jira https://propeople-us.atlassian.net/browse/OYPD-457
D.o https://www.drupal.org/node/2882792

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1324 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1324 |
| Installation process | http://install.openy-dev.ffwua.com/build1324/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1324/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1324/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Needs re-roll.

**Comment by Kerby70** [comment]
Updated.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1329 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1329 |
| Installation process | http://install.openy-dev.ffwua.com/build1329/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1329/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1329/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
