### PR TITLE
[OYPD-474] Add option required for image in media and wysywyg.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Issue: https://propeople-us.atlassian.net/browse/OYPD-474
Drupal.org issue: https://www.drupal.org/node/2884035

Steps to review:
- [x] login as admin
- [x] add image (go to [sitename]/media/add/image)
- [x] find field Image and click on "Choose File"
- [x] select any file
- [x] verify "Alternative text" is required with red star
Please look https://monosnap.com/file/AeOxZz6kWxU53XUZYcPciSG1dzYtHr

Also please read my comment https://propeople-us.atlassian.net/browse/OYPD-474?focusedCommentId=95148&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-95148

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1768 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1768 |
| Installation process | http://install.openy-dev.ffwua.com/build1768/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1768/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1768

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1768

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1768/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1794 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1794 |
| Installation process | http://install.openy-dev.ffwua.com/build1794/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1794/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1794

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1794

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1794/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1798 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1798 |
| Installation process | http://install.openy-dev.ffwua.com/build1798/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1798/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1798

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1798

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1798/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1799 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1799 |
| Installation process | http://install.openy-dev.ffwua.com/build1799/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1799/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1799

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1799

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1799/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1800 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1800 |
| Installation process | http://install.openy-dev.ffwua.com/build1800/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1800/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1800

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1800

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1800/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1801 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1801 |
| Installation process | http://install.openy-dev.ffwua.com/build1801/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1801/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1801

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1801

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1803 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1803 |
| Installation process | http://install.openy-dev.ffwua.com/build1803/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1803/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1803

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1803

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1803/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
