### PR TITLE
Test location finder

### PR DESCRIPTION
**Pull request by AlexNetman**
Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build551

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/551/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build551/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Requirements from tasks weren't covered:

Background:
- Create Landing Page
- Add Location finder paragraph
- Create 3 branches
-- 1st with comings soon
-- 2nd without coming soon
-- 3rd unpublished
- Create 3 camps
-- 1st and 2nd published
-- 2nd unpublished
- Create 3 facilities
-- 1st and 2nd published
-- 2nd unpublished

Scenario: Make sure map is available
- Make sure map is rendered with pins

Scenario: Make sure filters are available
- Make sure all filters are available

Scenario: Check branches availability
- Make sure 1st branch has coming soon label
- Make sure 2nd branch is displayed
- Make sure 3rd branch is not displayed

Scenario: Check camps availability
- Make sure 1st and 2nd camps are displayed
- Make sure 3rd camp is not displayed

Scenario: Check facilities availability
- Make sure 1st and 2nd facilities are displayed
- Make sure 3rd facility is not displayed

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build626 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build626 |
| Installation process | http://install.openy-dev.ffwua.com/build626/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/626/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build626/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build631 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build631 |
| Installation process | http://install.openy-dev.ffwua.com/build631/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/631/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build631/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
