### PR TITLE
Perform tests under Editor role

### PR DESCRIPTION
**Pull request by AlexNetman**
With this change most of behat tests will be performed under Editor role.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build775 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build775 |
| Installation process | http://install.openy-dev.ffwua.com/build775/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/775/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build775/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
In one of tests "Editor" can't set new Camp-landing-page as home page.
Actually I don't think this case is required to be checked regularly , because Camp-landing-page is always supposed to be under camp. And url like "/camps/great-camp-name/about" .
So probably we should remove that test case from regular set.

**Comment by Sanchiz** [comment]
retest this please

**Comment by alexschedrov** [comment]
@AlexNetman we shouldn't remove this case. It's a test for the Camp Menu, so there are a lot of use cases. Let's just leave "Admin" role for this specific scenario

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build785 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build785 |
| Installation process | http://install.openy-dev.ffwua.com/build785/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/785/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build785/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build787 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build787 |
| Installation process | http://install.openy-dev.ffwua.com/build787/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/787/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build787/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
