### PR TITLE
[OYPD-309] Camp menu behat tests.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-309
D.o https://www.drupal.org/node/2856963

Steps to review:
- [x] See tests run and pass in behat

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>12</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build617/build_reports/Drupalsniff.txt
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build617 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build617 |
| Installation process | http://install.openy-dev.ffwua.com/build617/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/617/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build617/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build618 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build618 |
| Installation process | http://install.openy-dev.ffwua.com/build618/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/618/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build618/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build619 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build619 |
| Installation process | http://install.openy-dev.ffwua.com/build619/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/619/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build619/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build620 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build620 |
| Installation process | http://install.openy-dev.ffwua.com/build620/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/620/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build620/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build621 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build621 |
| Installation process | http://install.openy-dev.ffwua.com/build621/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/621/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build621/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build622 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build622 |
| Installation process | http://install.openy-dev.ffwua.com/build622/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/622/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build622/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build623 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build623 |
| Installation process | http://install.openy-dev.ffwua.com/build623/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/623/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build623/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build624 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build624 |
| Installation process | http://install.openy-dev.ffwua.com/build624/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/624/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build624/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build630 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build630 |
| Installation process | http://install.openy-dev.ffwua.com/build630/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/630/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build630/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
