### PR TITLE
[OYPD-357] Style changes for schedule page

### PR DESCRIPTION
**Pull request by david-hernandez**
Style changes

screen shot 2017-05-17 at 5 15 47 pm

### CODE REVIEW

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1220 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1220 |
| Installation process | http://install.openy-dev.ffwua.com/build1220/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1220/

**Comment by alexschedrov** [comment]
@david-hernandez can we have more space in following places:
image

image

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1220/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1227 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1227 |
| Installation process | http://install.openy-dev.ffwua.com/build1227/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1227/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1227/profiles/contrib/openy/build/reports/behat

**Comment by david-hernandez** [comment]
I didn't realize there was existing CSS for this. I removed what I added and made the old CSS work. I also added a little extra space. This also fixes the "included in membership" boxes that I didn't realize were there.

screen shot 2017-05-19 at 4 31 56 pm

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1240 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1240 |
| Installation process | http://install.openy-dev.ffwua.com/build1240/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1240/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1240/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1244 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1244 |
| Installation process | http://install.openy-dev.ffwua.com/build1244/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1244/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1244/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
