### PR TITLE
[OYPD-379] Resolve Featured stories are missed.

### PR DESCRIPTION
**Pull request by Kerby70**
Resolve Featured stories are missed.

Jira https://propeople-us.atlassian.net/browse/OYPD-379
D.o https://www.drupal.org/node/2871579

Steps to review
- [x] Featured stories can be seen on demo /blog page.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1003 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1003 |
| Installation process | http://install.openy-dev.ffwua.com/build1003/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1003/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1003/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1004 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1004 |
| Installation process | http://install.openy-dev.ffwua.com/build1004/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1004/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1004/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1011 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1011 |
| Installation process | http://install.openy-dev.ffwua.com/build1011/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1011/

**Comment by alexschedrov** [comment]
1. Camp menu is still broken
image

2. Join page still broken
image

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1011/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1022 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1022 |
| Installation process | http://install.openy-dev.ffwua.com/build1022/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1022/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1022/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@Kerby70 behat test has been failed. Seems this one still uses demo content.
image

Another thing that blog posts has been rearranged for some reason and now homepage and blog page looks a little bit worse.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1023 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1023 |
| Installation process | http://install.openy-dev.ffwua.com/build1023/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1023/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1023/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
@Sanchiz All good now. The blog listing is date sensitive and the timestamps were sometimes equal, causing the issue. I added create times to the data and fixed an unknown bug in that.

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1024 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1024 |
| Installation process | http://install.openy-dev.ffwua.com/build1024/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1024/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1024/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1025 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1025 |
| Installation process | http://install.openy-dev.ffwua.com/build1025/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1025/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1025/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1029 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1029 |
| Installation process | http://install.openy-dev.ffwua.com/build1029/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1029/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1029/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1039 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1039 |
| Installation process | http://install.openy-dev.ffwua.com/build1039/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1039/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build1039/profiles/contrib/openy/build/reports/behat

**Pull request merged**
