### PR TITLE
[OPENY-167] Set langcode en for demo content

### PR DESCRIPTION
**Pull request by anprok**
Updated langcode only for demo content. To check more that one language should be enabled on site
## Steps for review
- [x] login as admin
- [x] visit admin/config/regional/language
- [x] add new language (like Ukrainian)
- [x] visit admin/content
- [x] Select in Language filter "Non specified" or "Not applicable" and select in Content type filter any type except of session (for example, Landing page).
- [x] make sure that no content in list
- [x] select English in language filter
- [x] make sure that some content listed.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1070 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1070 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1070 |
| Installation process | http://install.openy.cibox.tools/build1070/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1070/

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1071 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1071 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1071 |
| Installation process | http://install.openy.cibox.tools/build1071/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1071/

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1072 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1072 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1072 |
| Installation process | http://install.openy.cibox.tools/build1072/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1072/

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1073 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1073 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1073 |
| Installation process | http://install.openy.cibox.tools/build1073/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1073/

**Comment by podarok** [comment]
@ddrozdik @Sanchiz - I bet we should make EN as default language in all UI forms in admin interface for not confusing und and en in database. Remember - this needs comprehensive testing

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1074 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1074 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1074 |
| Installation process | http://install.openy.cibox.tools/build1074/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1074/

**Review by hamrant — APPROVED** [review]

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1076 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1076 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1076 |
| Installation process | http://install.openy.cibox.tools/build1076/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1076/

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1077 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1077 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1077 |
| Installation process | http://install.openy.cibox.tools/build1077/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1077/

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1078 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1078 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1078 |
| Installation process | http://install.openy.cibox.tools/build1078/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1078/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1079 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1079 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1079 |
| Installation process | http://install.openy.cibox.tools/build1079/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1079/

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
> @ddrozdik @Sanchiz - I bet we should make EN as default language in all UI forms in admin interface for not confusing und and en in database. Remember - this needs comprehensive testing

@podarok  by default, Open Y has only one language and language selector is disabled everywhere. We are not quite sure understood what are you talking about. Please provide more details.

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
@ddrozdik when you have all data in English in db, then you'll get a lot of issues content is not accessible, because by default all UI widgets are UND

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1080 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1080 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1080 |
| Installation process | http://install.openy.cibox.tools/build1080/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1080/

**Comment by ddrozdik** [comment]
The conversation with @podarok has been moved to https://github.com/ymcatwincities/openy/issues/1348

**Review by podarok — CHANGES_REQUESTED** [review]
We can't change default langcode if Drupal i18n and l10n systems are disabled.
In the end we'll be fighting with windmills when UND and EN entities mixed in database and some fields are not rendering.
This should be done only after native Drupal localization enabled for OpenY

**Pull request merged**
