### PR TITLE
Backport EntityManager change from 9.x-2.x issue #2100

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: https://www.drupal.org/node/2549139

## Steps for review

- [ ] Ensure /locations page works.
- [ ] Code review

Thank you for your contribution!

### CODE REVIEW

**Review by hamrant — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2445/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2445/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2445/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2445/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2445/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2445/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2445/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2445/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2445/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2446/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2446/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2446/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2446/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2446/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2446/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2446/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2447/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #2115 of commit 79202b433d6733b77ae3cfd00dd010cc28ad4f42.
Building on master in workspace /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build2447/openy-profile # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git520257524947859995.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: remote: Enumerating objects: 16762, done.        
remote: Counting objects:   0% (1/16762)        
remote: Counting objects:   1% (168/16762)        
remote: Counting objects:   2% (336/16762)        
remote: Counting objects:   3% (503/16762)        
remote: Counting objects:   4% (671/16762)        
remote: Counting objects:   5% (839/16762)        
remote: Counting objects:   6% (1006/16762)        
remote: Counting objects:   7% (1174/16762)        
remote: Counting objects:   8% (1341/16762)        
remote: Counting objects:   9% (1509/16762)        
remote: Counting objects:  10% (1677/16762)        
remote: Counting objects:  11% (1844/16762)        
remote: Counting objects:  12% (2012/16762)        
remote: Counting objects:  13% (2180/16762)        
remote: Counting objects:  14% (2347/16762)        
remote: Counting objects:  15% (2515/16762)        
remote: Counting objects:  16% (2682/16762)        
remote: Counting objects:  17% (2850/16762)        
remote: Counting objects:  18% (3018/16762)        
remote: Counting objects:  19% (3185/16762)        
remote: Counting objects:  20% (3353/16762)        
remote: Counting objects:  21% (3521/16762)        
remote: Counting objects:  22% (3688/16762)        
remote: Counting objects:  23% (3856/16762)        
remote: Counting objects:  24% (4023/16762)        
remote: Counting objects:  25% (4191/16762)        
remote: Counting objects:  26% (4359/16762)        
remote: Counting objects:  27% (4526/16762)        
remote: Counting objects:  28% (4694/16762)        
remote: Counting objects:  29% (4861/16762)        
remote: Counting objects:  30% (5029/16762)        
remote: Counting objects:  31% (5197/16762)        
remote: Counting objects:  32% (5364/16762)        
remote: Counting objects:  33% (5532/16762)        
remote: Counting objects:  34% (5700/16762)        
remote: Counting objects:  35% (5867/16762)        
remote: Counting objects:  36% (6035/16762)        
remote: Counting objects:  37% (6202/16762)        
remote: Counting objects:  38% (6370/16762)        
remote: Counting objects:  39% (6538/16762)        
remote: Counting objects:  40% (6705/16762)        
remote: Counting objects:  41% (6873/16762)        
remote: Counting objects:  42% (7041/16762)        
remote: Counting objects:  43% (7208/16762)        
remote: Counting objects:  44% (7376/16762)        
remote: Counting objects:  45% (7543/16762)        
remote: Counting objects:  46% (7711/16762)        
remote: Counting objects:  47% (7879/16762)        
remote: Counting objects:  48% (8046/16762)        
remote: Counting objects:  49% (8214/16762)        
remote: Counting objects:  50% (8381/16762)        
remote: Counting objects:  51% (8549/16762)        
remote: Counting objects:  52% (8717/16762)        
remote: Counting objects:  53% (8884/16762)        
remote: Counting objects:  54% (9052/16762)        
remote: Counting objects:  55% (9220/16762)        
remote: Counting objects:  56% (9387/16762)        
remote: Counting objects:  57% (9555/16762)        
remote: Counting objects:  58% (9722/16762)        
remote: Counting objects:  59% (9890/16762)        
remote: Counting objects:  60% (10058/16762)        
remote: Counting objects:  61% (10225/16762)        
remote: Counting objects:  62% (10393/16762)        
remote: Counting objects:  63% (10561/16762)        
remote: Counting objects:  64% (10728/16762)        
remote: Counting objects:  65% (10896/16762)        
remote: Counting objects:  66% (11063/16762)        
remote: Counting objects:  67% (11231/16762)        
remote: Counting objects:  68% (11399/16762)        
remote: Counting objects:  69% (11566/16762)        
remote: Counting objects:  70% (11734/16762)        
remote: Counting objects:  71% (11902/16762)        
remote: Counting objects:  72% (12069/16762)        
remote: Counting objects:  73% (12237/16762)        
remote: Counting objects:  74% (12404/16762)        
remote: Counting objects:  75% (12572/16762)        
remote: Counting objects:  76% (12740/16762)        
remote: Counting objects:  77% (12907/16762)        
remote: Counting objects:  78% (13075/16762)        
remote: Counting objects:  79% (13242/16762)        
remote: Counting objects:  80% (13410/16762)        
remote: Counting objects:  81% (13578/16762)        
remote: Counting objects:  82% (13745/16762)        
remote: Counting objects:  83% (13913/16762)        
remote: Counting objects:  84% (14081/16762)        
remote: Counting objects:  85% (14248/16762)        
remote: Counting objects:  86% (14416/16762)        
remote: Counting objects:  87% (14583/16762)        
remote: Counting objects:  88% (14751/16762)        
remote: Counting objects:  89% (14919/16762)        
remote: Counting objects:  90% (15086/16762)        
remote: Counting objects:  91% (15254/16762)        
remote: Counting objects:  92% (15422/16762)        
remote: Counting objects:  93% (15589/16762)        
remote: Counting objects:  94% (15757/16762)        
remote: Counting objects:  95% (15924/16762)        
remote: Counting objects:  96% (16092/16762)        
remote: Counting objects:  97% (16260/16762)        
remote: Counting objects:  98% (16427/16762)        
remote: Counting objects:  99% (16595/16762)        
remote: Counting objects: 100% (16762/16762)        
remote: Counting objects: 100% (16762/16762), done.        
remote: Compressing objects:   0% (1/9276)        
remote: Compressing objects:   1% (93/9276)        
remote: Compressing objects:   2% (186/9276)        
remote: Compressing objects:   3% (279/9276)        
remote: Compressing objects:   4% (372/9276)        
remote: Compressing objects:   5% (464/9276)        
remote: Compressing objects:   6% (557/9276)        
remote: Compressing objects:   7% (650/9276)        
remote: Compressing objects:   8% (743/9276)        
remote: Compressing objects:   9% (835/9276)        
remote: Compressing objects:  10% (928/9276)        
remote: Compressing objects:  11% (1021/9276)        
remote: Compressing objects:  12% (1114/9276)        
remote: Compressing objects:  13% (1206/9276)        
remote: Compressing objects:  14% (1299/9276)        
remote: Compressing objects:  15% (1392/9276)        
remote: Compressing objects:  16% (1485/9276)        
remote: Compressing objects:  17% (1577/9276)        
remote: Compressing objects:  18% (1670/9276)        
remote: Compressing objects:  19% (1763/9276)        
remote: Compressing objects:  20% (1856/9276)        
remote: Compressing objects:  21% (1948/9276)        
remote: Compressing objects:  22% (2041/9276)        
remote: Compressing objects:  23% (2134/9276)        
remote: Compressing objects:  24% (2227/9276)        
remote: Compressing objects:  25% (2319/9276)        
remote: Compressing objects:  26% (2412/9276)        
remote: Compressing objects:  27% (2505/9276)        
remote: Compressing objects:  28% (2598/9276)        
remote: Compressing objects:  29% (2691/9276)        
remote: Compressing objects:  30% (2783/9276)        
remote: Compressing objects:  31% (2876/9276)        
remote: Compressing objects:  32% (2969/9276)        
remote: Compressing objects:  33% (3062/9276)        
remote: Compressing objects:  34% (3154/9276)        
remote: Compressing objects:  35% (3247/9276)        
remote: Compressing objects:  36% (3340/9276)        
remote: Compressing objects:  37% (3433/9276)        
remote: Compressing objects:  38% (3525/9276)        
remote: Compressing objects:  39% (3618/9276)        
remote: Compressing objects:  40% (3711/9276)        
remote: Compressing objects:  41% (3804/9276)        
remote: Compressing objects:  42% (3896/9276)        
remote: Compressing objects:  43% (3989/9276)        
remote: Compressing objects:  44% (4082/9276)        
remote: Compressing objects:  45% (4175/9276)        
remote: Compressing objects:  46% (4267/9276)        
remote: Compressing objects:  47% (4360/9276)        
remote: Compressing objects:  48% (4453/9276)        
remote: Compressing objects:  49% (4546/9276)        
remote: Compressing objects:  50% (4638/9276)        
remote: Compressing objects:  51% (4731/9276)        
remote: Compressing objects:  52% (4824/9276)        
remote: Compressing objects:  53% (4917/9276)        
remote: Compressing objects:  54% (5010/9276)        
remote: Compressing objects:  55% (5102/9276)        
remote: Compressing objects:  56% (5195/9276)        
remote: Compressing objects:  57% (5288/9276)        
remote: Compressing objects:  58% (5381/9276)        
remote: Compressing objects:  59% (5473/9276)        
remote: Compressing objects:  60% (5566/9276)        
remote: Compressing objects:  61% (5659/9276)        
remote: Compressing objects:  62% (5752/9276)        
remote: Compressing objects:  63% (5844/9276)        
remote: Compressing objects:  64% (5937/9276)        
remote: Compressing objects:  65% (6030/9276)        
remote: Compressing objects:  66% (6123/9276)        
remote: Compressing objects:  67% (6215/9276)        
remote: Compressing objects:  68% (6308/9276)        
remote: Compressing objects:  69% (6401/9276)        
remote: Compressing objects:  70% (6494/9276)        
remote: Compressing objects:  71% (6586/9276)        
remote: Compressing objects:  72% (6679/9276)        
remote: Compressing objects:  73% (6772/9276)        
remote: Compressing objects:  74% (6865/9276)        
remote: Compressing objects:  75% (6957/9276)        
remote: Compressing objects:  76% (7050/9276)        
remote: Compressing objects:  77% (7143/9276)        
remote: Compressing objects:  78% (7236/9276)        
remote: Compressing objects:  78% (7263/9276)        
remote: Compressing objects:  79% (7329/9276)        
remote: Compressing objects:  80% (7421/9276)        
remote: Compressing objects:  81% (7514/9276)        
remote: Compressing objects:  82% (7607/9276)        
remote: Compressing objects:  83% (7700/9276)        
remote: Compressing objects:  84% (7792/9276)        
remote: Compressing objects:  85% (7885/9276)        
remote: Compressing objects:  86% (7978/9276)        
remote: Compressing objects:  87% (8071/9276)        
remote: Compressing objects:  88% (8163/9276)        
remote: Compressing objects:  89% (8256/9276)        
remote: Compressing objects:  90% (8349/9276)        
remote: Compressing objects:  91% (8442/9276)        
remote: Compressing objects:  92% (8534/9276)        
remote: Compressing objects:  93% (8627/9276)        
remote: Compressing objects:  94% (8720/9276)        
remote: Compressing objects:  95% (8813/9276)        
remote: Compressing objects:  96% (8905/9276)        
remote: Compressing objects:  97% (8998/9276)        
remote: Compressing objects:  98% (9091/9276)        
remote: Compressing objects:  99% (9184/9276)        
remote: Compressing objects: 100% (9276/9276)        
remote: Compressing objects: 100% (9276/9276), done.        
Receiving objects:   0% (1/16762)   
Receiving objects:   1% (168/16762)   
Receiving ob
```

**Pull request merged**
