### PR TITLE
[OPENY-81] Camp CT decouling

### PR DESCRIPTION
**Pull request by anprok**
"OpenY Camp" exist in dependencies of these modules at this moment
- openy_prgf_blog_camp
- openy_prgf_news_camp
- openy_prgf_loc_finder
- openy_demo_nnews

## Steps for review

- [x]  login as admin
- [x]   go to /admin/content?title=&type=camp&status=All&langcode=All
- [x]   Check that some camp nodes exist in this list
- [x]   go to /admin/modules/unistall
- [x] uninstall "OpenY Demo Node News" module
- [x] uninstall "OpenY Paragraph Latest Blog Posts (Camp)"
- [x] uninstall "OpenY Paragraph Latest News Posts (Camp)"
- [x] uninstall "OpenY Paragraph Location Finder"
- [x] uninstal "OpenY Camp"
- [x] return to /admin/content?title=&type=camp&status=All&langcode=All
- [x] check that camp nodes was removed
- [x] visit /schedules page
- [x] check that Camp category not displayed in Location filter at the top of page
- [x] go to /admin/structure/types
- [x] check that "Camp" not exist in this list
- [x] go to /admin/modules
- [x] enable  "OpenY Camp" module
- [x] check that all components that related to "OpenY Camp" module was restored and works fine

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]

**Review by ddrozdik — APPROVED** [review]

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build630 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build630 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build630 |
| Installation process | http://install.openy.cibox.tools/build630/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/630/

**Comment by ddrozdik** [comment]
@anprok currently, OpenY Camp module has a lot of dependencies to content types that should not be in the list of direct dependencies, for example, `OpenY Node Blog`, `OpenY Node Event`, `OpenY Session`. First of all, we have to resolve these dependencies. See how we did this before https://github.com/ymcatwincities/openy/pull/1118

**Comment by ddrozdik** [comment]
@anprok there is no upgrade path for the modified configs. Please add upgrade path.

**Comment by ddrozdik** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build635 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build635 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build635 |
| Installation process | http://install.openy.cibox.tools/build635/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/635/

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
@anprok after switching Camps off I get an error on any page
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "openy_loc_camp.camp_service". in 
Drupal\Component\DependencyInjection\Container->get() (line 151 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build635/openy-project/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php).
```

**Comment by ddrozdik** [comment]
retest this please

**Review by ddrozdik — APPROVED** [review]

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/641/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #1183 of commit 8cbd7eda3f8b1180faf3e24b710e283d8ecd4f7f automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build641/openy-profile # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git6008121106185413135.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git6544575821395674948.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/1183/merge^{commit} # timeout=10
 > git branch -a --contains a46bc02fe15b09d23de56cc283bd99935260ea6d # timeout=10
 > git rev-parse remotes/origin/pr/1183/merge^{commit} # timeout=10
Checking out Revision a46bc02fe15b09d23de56cc283bd99935260ea6d (origin/pr/1183/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a46bc02fe15b09d23de56cc283bd99935260ea6d # timeout=10
 > git branch -a # timeout=10
 > git rev-parse remotes/origin/8.x-1.13-dev^{commit} # timeout=10
 > git rev-parse remotes/origin/8.x-1.x^{commit} # timeout=10
 > git rev-parse remotes/origin/advanced_css^{commit} # timeout=10
 > git rev-parse remotes/origin/decoupling^{commit} # timeout=10
 > git rev-parse remotes/origin/drupal8_5_1^{commit} # timeout=10
 > git rev-parse remotes/origin/ducuments_library_fields^{commit} # timeout=10
 > git rev-parse remotes/origin/experimental_features^{commit} # timeout=10
 > git rev-parse remotes/origin/lndr115^{commit} # timeout=10
 > git rev-parse remotes/origin/oat_refactor^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/10/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/100/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1000/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1001/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1002/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1003/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1003/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1004/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1005/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1006/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1006/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1007/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1008/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1009/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/101/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1011/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1011/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1012/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1013/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1014/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1015/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1016/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1016/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1017/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1018/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1019/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1019/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/102/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1022/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1023/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1024/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1025/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1026/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1027/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1028/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1029/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/103/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1030/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1031/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1032/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1033/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1034/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1035/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1036/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1037/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1037/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1038/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1039/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/104/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1040/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1041/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1042/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1043/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1044/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1047/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1047/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1048/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/105/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1052/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1053/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1054/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1055/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1057/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1058/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1059/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1059/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/106/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1060/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1061/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1062/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1064/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1065/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1066/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/107/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1071/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1073/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1073/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1074/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1075/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1076/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1079/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/108/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1080/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1081/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1082/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1084/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1084/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/109/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1090/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1091/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1091/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1094/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1095/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1097/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1097/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1098/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1099/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/11/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1100/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1102/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1103/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1104/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1105/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1106/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1107/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1108/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1108/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1109/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/111/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1110/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1110/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1111/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1112/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1113/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1114/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1115/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1116/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1117/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1118/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1119/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/112/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1120/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1121/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1123/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1124/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1125/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1126/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1127/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1128/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1129/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/113/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1136/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1136/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1137/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1138/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1139/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/114/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1141/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1142/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1144/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1146/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1147/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1148/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1149/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/115/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1150/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1151/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1154/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1155/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/116/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1160/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1161/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1161/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1162/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1163/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1166/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1167/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1168/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1169/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/117/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1170/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1171/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1174/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1174/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1175/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1176/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1177/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1178/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1178/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1179/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/118/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1180/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1181/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1182/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1183/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1183/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1184/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1185/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1186/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1186/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1187/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1187/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1188/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1189/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/119/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1190/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1191/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1192/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1193/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1193/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/12/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/120/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/121/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/122/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/123/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/124/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/125/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/126/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/127/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/127/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/128/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/128/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/129/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/13/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/130/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/131/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/132/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/133/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/133/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/134/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/135/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/136/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/137/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/138/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/139/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/14/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/140/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/141/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/142/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/143/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/144/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/145/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/146/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/147/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/148/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/149/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/15/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/15/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/150/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/151/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/152/head^{commit} # timeout=10
FATAL: Could not checkout OPENY-81 with start point a46bc02fe15b09d23de56cc283bd99935260ea6d
hudson.plugins.git.GitException: Could not checkout OPENY-81 with start point a46bc02fe15b09d23de56cc283bd99935260ea6d
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1865)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1060)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Caused by: hudson.plugins.git.GitException: Command "git rev-parse remotes/origin/pr/152/head^{commit}" returned status code 128:
stdout: remotes/origin/pr/152/head^{commit}

stderr: fatal: ambiguous argument 'remotes/origin/pr/152/head^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1576)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1572)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1233)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1245)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:607)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.parseBranches(CliGitAPIImpl.java:1702)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getBranches(CliGitAPIImpl.java:1722)
	at hudson.plugins.git.GitAPI.getBranches(GitAPI.java:195)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1844)
	... 10 more
Couldn't read comment file
java.io.FileNotFoundException: File '/var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build641/commentinfo.md' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:124)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build644 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build644 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build644 |
| Installation process | http://install.openy.cibox.tools/build644/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/644/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build644/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build644/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build644/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build644/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build644/blogWCAG2AAhtmlcs.txt

**Comment by ddrozdik** [comment]
@anprok after disabling Camps still there are some references to Camps, let's fix them: 
- Paragraph - Classes Listing - https://monosnap.com/file/8LYvyspiTthKpxhC5yw54HzDV62UEE
- /schedules - same thing with filters

 and check other pages if I missed something.

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build662 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build662 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build662 |
| Installation process | http://install.openy.cibox.tools/build662/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/662/

**Pull request merged**
