### PR TITLE
feat!: add webp for all image styles

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Ensure webp is used for all Open Y image styles, e.g. /admin/config/media/image-styles/manage/carnation_banner_1920_700 
image
- [ ] check images are in webp format 
image
- [ ] Check https://github.com/open-y-subprojects/openy_features/pull/19
- [ ] Check upgrade path
```sh
            "  openy_med   8016                 hook_update_n   8016 - Apply Webp to all     ",
            "  ia_image                                         image styles.                ",
            "  openy_nod   8009                 hook_update_n   8009 - Apply Webp to all     ",
            "  e                                                image styles.                ",
            "  openy_nod   8015                 hook_update_n   8015 - Apply Webp to all     ",
            "  e_blog                                           image styles.                ",
            "  openy_nod   8017                 hook_update_n   8017 - Apply Webp to all     ",
            "  e_categor                                        image styles.                ",
            "  y                                                                             ",
            "  openy_nod   8003                 hook_update_n   8003 - Apply Webp to all     ",
            "  e_event                                          image styles.                ",
            "  openy_nod   8007                 hook_update_n   8007 - Apply Webp to all     ",
            "  e_news                                           image styles.                ",
            "  openy_nod   8015                 hook_update_n   8015 - Apply Webp to all     ",
            "  e_program                                        image styles.                ",
            "  openy_nod   8004                 hook_update_n   8004 - Apply Webp to all     ",
            "  e_social_                                        image styles.                ",
            "  post                                                                          ",
            "  openy_prg   8013                 hook_update_n   8013 - Apply Webp to all     ",
            "  f_banner                                         image styles.                ",
            "  openy_prg   8010                 hook_update_n   8010 - Apply Webp to all     ",
            "  f_gallery                                        image styles.                ",
            "  openy_prg   8006                 hook_update_n   8006 - Apply Webp to all     ",
            "  f_mbrshp_                                        image styles.                ",
            "  calc                                                                          ",
            "  openy_prg   8010                 hook_update_n   8010 - Apply Webp to all     ",
            "  f_small_b                                        image styles.                ",
            "  anner                                                                         ",
            "  openy_prg   8011                 hook_update_n   8011 - Apply Webp to all     ",
            "  f_teaser                                         image styles.                ",
```

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3700/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3700/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3700/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://profile.openy.cibox.tools/build3700/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3701/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3701/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3701/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://profile.openy.cibox.tools/build3701/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3702/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3702/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3703/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3703/

**Review by danylevskyi — APPROVED** [review]

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3702/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3703/

**Pull request merged**
