### PR TITLE
[ROY-22] Fix required marks for fields in webform

### LINKED ISSUE #2299: Visual Issues for Webform 5 in Rose, Lily, Carnation
**Visual issues:**
1. on Carnation and Rose some fields are longer than the other
Carnation   Rose Spacing Issue

2. On Carnation a big free space before the form (seen on the first screenshot). On Rose strange dividing line before the first field (seen on the second screenshot)
Carnation   Rose Webform Field Length

3. Rose and Lily - fields that I marked as required doesn't have any marking that can show that they are required (star or whatever)
Rose   Lily Required Fields

### PR DESCRIPTION
**Pull request by shuklina**
Issue: https://github.com/ymcatwincities/openy/issues/2299

## Steps for review

- [x] Login as admin.
- [x] Go to `/admin/structure/webform` and create custom webform.
- [x] Go to `/admin/structure/webform/manage/virtual/source` for example you can add this code or `Add elements` youself.
```
first:
  '#type': textfield
  '#title': First
  '#required': true
last:
  '#type': textfield
  '#title': Last
  '#required': true
add_your_email:
  '#type': email
  '#title': 'Add your email'
  '#required': true
number:
  '#type': number
  '#title': Number
tell_us_you_what_you_think:
  '#type': textarea
  '#title': 'What you think'
choose:
  '#type': checkbox
  '#title': Choose
checkboxes:
  '#type': checkboxes
  '#title': Checkboxes
  '#options':
    'Question 1': 'Question 1'
    'Question 2': 'Question 2'
    'Question 3': 'Question 3'
actions:
  '#type': webform_actions
  '#title': 'Submit button(s)'
  '#submit__label': 'Send message'
```
- [x] Save and add this form to Landing page.
- [x] Make sure that there are marks for required fields for Rose and Lily themes.

image

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2854/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2854/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2854/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2854/

**Comment by podarok** [comment]
Looks good 
image

**Pull request merged**
