### PR TITLE
[OYPD-482] on sub category page the image is the hot link and it come before the title which is the header.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-482?focusedCommentId=93493&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-93493

# Steps to review:
- [x] go to [sitename]/programs/swimming
- [x] use inspector check html dom title must be above image
- [x] check it for iPhone, IE, Chrome, Safari, iPad

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1729 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1729 |
| Installation process | http://install.openy-dev.ffwua.com/build1729/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1729/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1729

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1729

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1729/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1730 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1730 |
| Installation process | http://install.openy-dev.ffwua.com/build1730/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1730/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1730

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1730

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1730/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1739 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1739 |
| Installation process | http://install.openy-dev.ffwua.com/build1739/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1739/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1739

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1739

**Comment by alexschedrov** [comment]
@ivan-berezhnov this PR needs re-roll.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1748 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1748 |
| Installation process | http://install.openy-dev.ffwua.com/build1748/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1748/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1748

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1748

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1748/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1757 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1757 |
| Installation process | http://install.openy-dev.ffwua.com/build1757/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1757/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1757

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1757

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1757/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1765 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1765 |
| Installation process | http://install.openy-dev.ffwua.com/build1765/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1765/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1765

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1765

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1765/profiles/contrib/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Pull request merged**
