### PR TITLE
#1351 fixed slick index of removed slide

### PR DESCRIPTION
**Pull request by denisbilchenko**
## Steps for review

- [ ] Create or edit new Alert and configure it to show on specific page. After saving the alert node, it should appearing on the configured page.
- [ ] Open another page which is not in the list and close one or more slide(s).
- [ ] Go back to allowed page, configured Alert should appearing on this page.

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1177 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1177 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1177 |
| Installation process | http://install.openy.cibox.tools/build1177/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1177/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1177/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1177/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1177/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1177/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1177/blogWCAG2AAhtmlcs.txt

**Comment by ddrozdik** [comment]
@denisbilchenko Can you update this PR for the 2.x version and check that it is still relevant in the 2.x version??

**Comment by denisbilchenko** [comment]
@ddrozdik , I've checked on my local machine alerts did not work as expected. There are no way to close alert, also my Test Alert appeared on all pages, it does not matter what options I choose. Could you please confirm?
image

**Comment by ddrozdik** [comment]
cc @podarok ^^

**Comment by denisbilchenko** [comment]
After clean installation of the OpenY v2 (composer create-project ymcatwincities/openy-project:8.2.x-development-dev MY_PROJECT --no-interaction --no-dev and switched to the 8.x-2.x in the profile), I could not reproduce the issue. Alerts work as expected. 

@ddrozdik @podarok

**Comment by podarok** [comment]
great!!
Closing then

**Pull request closed without merging**
