### PR TITLE
[OYS-36] Fix drush error for migrate tools and warning during install

### LINKED ISSUE #1856: Install is broken in 8.2.3.4
Install OpenY 8.2.3.4 by using composer
Run web install
Profile - Standard
Carnation theme
Import demo content
On some step, you'll see an error

```
[Tue Dec 17 17:01:07.202299 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP Fatal error:  Class 'Drush\\Commands\\DrushCommands' not found in /var/www/html/docroot/modules/contrib/migrate_tools/src/Commands/MigrateToolsCommands.php on line 23
[Tue Dec 17 17:01:07.202519 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP Stack trace:
[Tue Dec 17 17:01:07.202599 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   1. {main}() /var/www/html/docroot/core/install.php:0
[Tue Dec 17 17:01:07.202662 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   2. install_drupal() /var/www/html/docroot/core/install.php:44
[Tue Dec 17 17:01:07.202734 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   3. install_run_tasks() /var/www/html/docroot/core/includes/install.core.inc:118
[Tue Dec 17 17:01:07.202801 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   4. install_run_task() /var/www/html/docroot/core/includes/install.core.inc:577
[Tue Dec 17 17:01:07.202867 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   5. _batch_page() /var/www/html/docroot/core/includes/install.core.inc:672
[Tue Dec 17 17:01:07.202940 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   6. _batch_progress_page() /var/www/html/docroot/core/includes/batch.inc:86
[Tue Dec 17 17:01:07.203004 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   7. _batch_process() /var/www/html/docroot/core/includes/batch.inc:186
[Tue Dec 17 17:01:07.203061 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   8. openy_import_migration() /var/www/html/docroot/core/includes/batch.inc:295
[Tue Dec 17 17:01:07.203117 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP   9. Drupal\\openy_migrate\\Importer->importByTag() /var/www/html/docroot/profiles/contrib/openy/openy.profile:543
[Tue Dec 17 17:01:07.203166 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP  10. Drupal\\openy_migrate\\Importer->importMigration() /var/www/html/docroot/profiles/contrib/openy/modules/custom/openy_migrate/src/Importer.php:68
[Tue Dec 17 17:01:07.203216 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP  11. Drupal\\migrate_tools\\MigrateExecutable->__construct() /var/www/html/docroot/profiles/contrib/openy/modules/custom/openy_migrate/src/Importer.php:50
[Tue Dec 17 17:01:07.203262 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP  12. Drupal\\migrate_tools\\MigrateTools::buildIdList() /var/www/html/docroot/modules/contrib/migrate_tools/src/MigrateExecutable.php:107
[Tue Dec 17 17:01:07.203308 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP  13. spl_autoload_call() /var/www/html/docroot/modules/contrib/migrate_tools/src/MigrateTools.php:24
[Tue Dec 17 17:01:07.203360 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP  14. Composer\\Autoload\\ClassLoader->loadClass() /var/www/html/docroot/modules/contrib/migrate_tools/src/MigrateTools.php:24
[Tue Dec 17 17:01:07.203407 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP  15. Composer\\Autoload\\includeFile() /var/www/html/vendor/composer/ClassLoader.php:322
[Tue Dec 17 17:01:07.203470 2019] [php7:notice] [pid 20712] [client 178.54.63.218:54713] PHP  16. include() /var/www/html/vendor/composer/ClassLoader.php:444

```

### PR DESCRIPTION
**Pull request by anprok**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/1856

Check install log for errors

Tested locally with Drush 10.1 - no errors

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1978/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1978/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1978/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1978/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1978/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1978/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1978/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1978/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1979/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1979/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1979/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build1978/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build1979/

**Pull request merged**
