### PR TITLE
fixed the "Today's hours" block time: removed hardcoded keys array for the 'Branch Hours' field; fixed dayOfWeek format

### PR DESCRIPTION
**Pull request by aleevas**
This one should be related to #2344 too.

Currently we used [hardcoded](https://github.com/ymcatwincities/openy/blob/f06361f1f8b96aee9c1e60acc177e40cdcb70047/modules/custom/openy_hours_formatter/js/openy_hours_formatter.js#L62) keys, that formated from the label of **Custom hours label**

In the **[CustomHoursToday.php](https://github.com/ymcatwincities/openy/blob/f06361f1f8b96aee9c1e60acc177e40cdcb70047/modules/custom/openy_hours_formatter/src/Plugin/Field/FieldFormatter/CustomHoursToday.php#L41)**  we transform a label
hardcodedKeyLabel
 to key:
`$js_key = str_ireplace('-', '_', Html::getClass($label));`
```
 ['branch_hours', 'center_hours', 'open_hours', 'before_school_enrichment'].reverse().forEach(function (name) {
        if (typeof branchHours[name] != 'undefined') {
          hoursData = branchHours[name];
        }
      });
```
In this PR I suggest to send this keys from **drupalSettings** array
So even a user will change a title, we shouldn't lose this functionality.

`'keys' => array_keys($js_settings), `

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

you can try the steps from this PR https://github.com/ymcatwincities/openy/pull/2345

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]
Looks good

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2905/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2905/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2905/

**Comment by podarok** [comment]
@aleevas we should start creating all PRs against 9.x-2.x branch. 8.x-2.x branch is history and will be receiving only critical security fixes
/cc @sarah-halby

**Comment by hamrant** [comment]
test this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2921/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2921/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2921/

**Review by manachynskyi — APPROVED** [review]

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2921/

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
@podarok feel free to merge, I tested this code on local, looks ok for me. @manachynskyi reproduced the origin issue and tested with this fix, currently, we used this as a patch on one of our projects.

**Comment by podarok** [comment]
Approved by @sarah-halby 
Thanks @hamrant @aleevas @manachynskyi for your work

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
