### PR TITLE
[OYPD-455] Fixing membership type being only 3 per row instead of 4

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Visit the "Join" page
- [x] Verify that on large screen sizes the membership types are 4 per row.
screen shot 2017-06-01 at 11 20 56 am

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1331 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1331 |
| Installation process | http://install.openy-dev.ffwua.com/build1331/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1331/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1331/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1337 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1337 |
| Installation process | http://install.openy-dev.ffwua.com/build1337/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1337/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1337/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
