### PR TITLE
Remove outlines rule from :focus pseudo-selectors in favor of box-shadow

### PR DESCRIPTION
**Pull request by Sardis93**
I haven't found any issue, that this commit is aimed to fix, however here comes the small adjustment.

Here's the default state of text input:
Screenshot 2020-11-11 at 13 30 51
Here's the same text input with focus state:
Screenshot 2020-11-11 at 13 31 00
Please, take notice of the edges. Once outline is applied, the border radius is changed. Since there's no control over border radius of the outline, the workaround would be to replace it with
 `box-shadow: inset 0 0 0 2px`
The result can be seen below:
Screenshot 2020-11-11 at 13 46 17

No issues are reported by CodeSniffer.
No changes to documentation are required.
No hook_updates are necessary.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2797/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2797/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2797/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2797/

**Comment by podarok** [comment]
I didn't get what is fixed here but sounds beautiful, so merging

**Pull request merged**
