### PR TITLE
[OYPD-269] Blog post style changes

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-269
Drupal.org issue - https://www.drupal.org/node/2854125

Steps for review:
- [x] login as admin
- [x] go to /admin/content?status=All&type=blog&title=&langcode=All
- [x] edit any blog post
- [x] in Style section set Style - color card and set colors
- [x] go to /node/add/landing_page
- [x] in content area add Blog Posts Listing paragraph
- [x] check blog teaser with color card style
- [x] profit

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build503

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/503/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build503/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build504

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/504/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build504/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
When you select new Color Card, it renders nothing.
image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build510

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/510/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build510/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build515

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/515/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build515/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
