### PR TITLE
[OYPD-221] Behat tests for the membership calculator paragraph.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-221
D.o https://www.drupal.org/node/2864798

Steps to review:
- [x] See test results & code.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build798 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build798 |
| Installation process | http://install.openy-dev.ffwua.com/build798/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/798/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build798/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build799 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build799 |
| Installation process | http://install.openy-dev.ffwua.com/build799/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/799/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build799/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build814 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build814 |
| Installation process | http://install.openy-dev.ffwua.com/build814/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/814/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build814/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build824 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build824 |
| Installation process | http://install.openy-dev.ffwua.com/build824/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/824/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build824/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build825 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build825 |
| Installation process | http://install.openy-dev.ffwua.com/build825/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/825/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build825/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
The first step failing `Then I should see "Find the Membership That’s Best For You" 
(The text "Find the Membership That’s Best For You" was not found anywhere in the text of the current page.)` does not fail locally (at least without selenium running).
- I can see the url being requested is correct even given the build prefix.

The next step failing `Given I am logged in as a user with the Administrator role 
(Unable to determine if logged in because 'log_out' link cannot be found for user 'cvJv7sLw' with role 'Administrator')` 
- Next attempt will be without the admin role 
image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build826 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build826 |
| Installation process | http://install.openy-dev.ffwua.com/build826/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/826/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build826/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build827 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build827 |
| Installation process | http://install.openy-dev.ffwua.com/build827/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/827/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build827/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build831 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build831 |
| Installation process | http://install.openy-dev.ffwua.com/build831/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/831/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build831/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build833 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build833 |
| Installation process | http://install.openy-dev.ffwua.com/build833/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/833/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build833/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build834 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build834 |
| Installation process | http://install.openy-dev.ffwua.com/build834/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/834/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build834/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
@Sanchiz The tests continue to fail after I have been able to successfully test with the new Selenium changes locally.

**Comment by Kerby70** [comment]
please retest this

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build848 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build848 |
| Installation process | http://install.openy-dev.ffwua.com/build848/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/848/

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build849 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build849 |
| Installation process | http://install.openy-dev.ffwua.com/build849/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/849/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build849/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build850 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build850 |
| Installation process | http://install.openy-dev.ffwua.com/build850/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/850/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build850/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build851 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build851 |
| Installation process | http://install.openy-dev.ffwua.com/build851/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/851/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build851/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build852 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build852 |
| Installation process | http://install.openy-dev.ffwua.com/build852/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/852/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build852/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build853 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build853 |
| Installation process | http://install.openy-dev.ffwua.com/build853/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/853/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build853/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
@Sanchiz This is now ready for review.

Please let me know when this is merged as OYPD-354 needs to be rebased with this.

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build857 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build857 |
| Installation process | http://install.openy-dev.ffwua.com/build857/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/857/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build857/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
