### PR TITLE
Stable contribs for Major Release in November

### PR DESCRIPTION
**Pull request by podarok**
```sh
composer why-not php:7.3
There is no installed package depending on "php" in versions not matching 7.3
```

Original Issue, this PR is going to fix: get rid of dev/alpha dependencies

## Steps for review

- [ ] 100% of these modules tested in Drupal 9, so requesting just a smoke test if any concerns.

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2722/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2722/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2722/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2722/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2723/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2723/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2723/

**Review by hamrant — APPROVED** [review]
Checked release notes for contribs, looks like there no huge changes.

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2723/

**Pull request merged**
