### PR TITLE
[OYPD-451] Daxko program registration component (styles).

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-451
Drupal.org issue: https://www.drupal.org/node/2892296

# Steps to review:
- [x] login as admin
- [x] follow all steps from https://propeople-us.atlassian.net/wiki/display/OYPD/Daxko+program+registration.
- [x] go to your lading page
- [x] verify for desktop: Alignment in one vertical line and shows radiobuttons in multiple columns (4 columns on a desktop) also'result' and 'no result' text has style.
- [x] verify for mobile: Alignment in one vertical line and shows radiobuttons in multiple columns (4 columns on a desktop) also 'result' and 'no result' text has style.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1804 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1804 |
| Installation process | http://install.openy-dev.ffwua.com/build1804/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1804/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1804

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1804

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1804/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Let's align elements in the form.
image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1807 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1807 |
| Installation process | http://install.openy-dev.ffwua.com/build1807/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1807/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1807

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1807

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1808 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1808 |
| Installation process | http://install.openy-dev.ffwua.com/build1808/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1808/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1808

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1808

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1807/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1808/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
