### PR TITLE
Repair footer alerts for Lily & Rose

### LINKED ISSUE #2427: Footer Alerts do not display in Rose & Lily
As reported in Slack, with Open Y 8.2.7.3 footer alerts do not display in Rose and Lily, but still function in Carnation.

An error in the console is also thrown:
```
Uncaught TypeError: Node.insertBefore: Argument 1 is not an object.
    attach https://....y.org/profiles/contrib/openy/modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js?v=0.6:1
```

This seems to be a regression introduced in https://github.com/ymcatwincities/openy/pull/2317. I'll be submitting a PR shortly.

### PR DESCRIPTION
**Pull request by froboy**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/2427

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Add an alert in the footer
- [ ] Observe the alert displays in Carnation
- [ ] Switch to Lily/Rose and observe the alert is displayed

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3127/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3127/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3127/

**Comment by podarok** [comment]
image

**Comment by podarok** [comment]
Thank you @froboy

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
