### PR TITLE
[OYPD-275] Add aliases lookup, & front page check, to camp menu query conditions.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-275
D.o https://www.drupal.org/node/2855834

Steps to review:
- [x] Create a landing page
  - [x] With the  title "Test OYPD-275"
  - [x] With the alias "/test-OYPD-275"
  - [x] Notice the Node id for use later (THE_LP_NID)
- [x] Create a Camp CT
  - [x] In menu links add a Landing page as a link by looking up "Test OYPD-275" and selecting the reference.
  - [x] Add a 'Camp menu'
  - [x] Publish and see the Camp menu
- [x] Edit "Test OYPD-275" and add a 'Camp Menu' paragraph
  - [x] Publish and see the Camp menu

- [x] Go to /admin/config/system/site-information
  - [x] Set the Default front page to "/test-OYPD-275"
- [x] View each the homepage, and "/test-OYPD-275"
  - [x] See the Camp menu

- [x] Edit the Camp CT
  - [x] Replace the menu link for "Test OYPD-275" to "<front>"
  - [x] Publish
- [x] View each the homepage, and "/test-OYPD-275"
  - [x] See the Camp menu

- [x] Go to /admin/config/system/site-information
  - [x] Set the Default front page to "/node/THE_LP_NID"
- [x] View each the homepage, and "/test-OYPD-275"
  - [x] See the Camp menu

- [x] Edit the Camp CT
  - [x] Replace the menu link for "<front>" to "/node/THE_LP_NID"
  - [x] Publish
- [x] View each the homepage, and "/test-OYPD-275"
  -  [x] See the Camp menu

- [x] Go to /admin/config/search/path/add
  - [x] Add an alias "/test-OYPD-275-again" for "/node/THE_LP_NID"
- [x] Edit the Camp CT
  - [x] Replace the menu link for "<front>" to "/test-OYPD-275-again"
  - [x] Publish
- [x] View each the homepage, and "/test-OYPD-275", and "/test-OYPD-275-again"
  -  [x] See the Camp menu

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>3</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build585/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build585

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/585/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build585/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build586/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build586

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/586/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build586/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build587/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build587

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/587/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build587/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build588/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build588

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/588/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build588/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build589/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build589

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/589/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build589/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build590

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/590/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build590/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build592

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/592/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build592/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by vlkff** [comment]
I was working on backporting the feature to other project and found that would be better to have a form validator to check that only single Camp node can reference to Landing. Otherwise links may be messed up on Landing page as the plugin always get only first Camp referencing the Landing  
screen shot 2017-03-02 at 18 09 41

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build641 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build641 |
| Installation process | http://install.openy-dev.ffwua.com/build641/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/641/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build641/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build642 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build642 |
| Installation process | http://install.openy-dev.ffwua.com/build642/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/642/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build642/profiles/openy/build/reports/behat

**Pull request merged**
