### PR TITLE
[MAINTAIN-5] fixed an error message for the 'Type' option in the Membership Calc form

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: [MAINTAIN-5](https://openy.atlassian.net/browse/MAINTAIN-5)

This one should fix an error message of not selected type field in Membership Calc form

## Steps for review

- [ ] go to /membership page (if it not exist please create a new Landning page with Membership calculator paragraph)
- [ ] don't select anyvalues on first step and click next
- [ ] verify that you see the message without text **field is required** after question mark
MAINTAIN-5MembershipTypeErrorMessage

- [ ] select type and verify that you can go to next option
- [ ] verify that you can submit the form with all necessary options

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3210/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3210/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3210/

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
retest

**Comment by hamrant** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3211/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3211/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3211/

**Comment by hamrant** [comment]
Tested on http://upgrade.openy.cibox.tools/build3211/test

Screenshot from 2021-06-08 12-35-26

**Comment by aleevas** [comment]
@hamrant 
please re-check this.
I've added fix to a validation rule.
Previous one was wrong on last step, if you'll click **prev** button, its fails.
cc @podarok

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3213/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3213/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3213/

**Review by hamrant — APPROVED** [review]
Tested on http://upgrade.openy.cibox.tools/build3213/test?type&amenities

**Review by podarok — APPROVED** [review]

**Pull request merged**
