### PR TITLE
[OYPD-168] demo landing pages

### PR DESCRIPTION
**Pull request by RoloDMonkey**
Steps for review:

- [x]  `drush mi --all` (may have to run twice because of undocumented dependencies in other modules)
- [x] go to: /admin/content?status=All&type=landing_page&title=&langcode=All
- [x] click on each landing page and confirm that content is there (it probably won't display correctly yet)

The grid content does not have anything in the field collections yet because the field collections module doesn't have a release that supports the migrate module. If we want to continue with field collections, we will have to, at the very least, apply this patch: https://www.drupal.org/node/2721823

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build302

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/302/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build302/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Good to be merged as initial version, but following fixes should be applied:

### Page - /openy
1. Layout should be "one_column"
2. Let's skip grid content for now.
3. For some reason paragraph with blog posts is not displayed
image


### Page - /about-ymca
1. Layout should be "one_column"
2. Let's put /openy link here
image

### Skip grid content for now.

### Page - /give
1. Layout should be "one_column"
2. Let's put /openy link here
image
3. Skip grid content for now.

### Page - /accelerator
1. Layout should be "one_column"
2. Let's put /openy link here
image

### Page - /blog
1. Layout should be "one_column"
2. Blog listing paragraphs is empty
image

**Review by alexschedrov — APPROVED** [review]
Fixes should be included as follow up.

**Pull request merged**
