### PR TITLE
[OYPD-522] Fixing focus background color for load more button

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Use tab to switch focus to load more buttons.
- [x] Verify that the background stays the correct color, and not grey.

screen shot 2017-07-07 at 3 31 15 pm

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1828 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1828 |
| Installation process | http://install.openy-dev.ffwua.com/build1828/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1828/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1828

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1828/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1828/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1828/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1828/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1828/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1828/profiles/contrib/openy/build/reports/behat

**Review by Kerby70 — APPROVED** [review]

**Pull request merged**
