### PR TITLE
[OYPD-141] Camp page full view mode

### PR DESCRIPTION
**Pull request by hamrant**
Old PR - https://github.com/ymcatwincities/openy/pull/74

### CODE REVIEW

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build256/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build256

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/256/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build257

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/257/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build257/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
