### PR TITLE
[OPENY-267]: Missing demo content

### PR DESCRIPTION
**Pull request by afi13**
## Steps for review

- [ ] Go to `/locations/downtown-ymca` and make sure
- [ ] Verify **Demo Latest blog posts**, **Volunteers Needed**, **Our story**, **We Appreciate Your Support** content are created.
- [ ] Go to `/camps/camp-colman`
- [ ] Make sure demo content **Demo Latest blog posts** is created

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1449 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1449 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1449 |
| Installation process | http://install.openy.cibox.tools/build1449/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1449/

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1461 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1461 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1461 |
| Installation process | http://install.openy.cibox.tools/build1461/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1461/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1467 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1467 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1467 |
| Installation process | http://install.openy.cibox.tools/build1467/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1467/

**Comment by ddrozdik** [comment]
issue was fixed in the PR https://github.com/ymcatwincities/openy/pull/1511

**Pull request closed without merging**
