### PR TITLE
Issue 1300

### PR DESCRIPTION
**Pull request by denisbilchenko**
## Steps for review

- [x] switch to Lily theme
- [x] go to /group-exercise-classes page
- [x] make sure that link "Add to Calendar" is displayed without any additional data

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by kolesnikoff** [comment]
@podarok please review

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1009 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1009 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1009 |
| Installation process | http://install.openy.cibox.tools/build1009/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1009/

**Review by podarok — APPROVED** [review]

**Pull request merged**
