### PR TITLE
OS-160: Carnation Navigation Bug

### PR DESCRIPTION
**Pull request by aaronjchristian**
…upport for the main navigation on window.resize().

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature, please create PR against 8.x-1.xx-dev branch.

If this is a bug fix - use 8.x-1.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Visit any page using the carnation theme. Click on a dropdown enabled link, start to resize your browser and ensure that the columns start wrapping properly between the tablet and large desktop viewports.
- [ ] Resize your browser while the mobile menu is opened. It should collapse automatically when you resize past the "mobile" enabled viewport (> 991px).

https://www.drupal.org/project/openy/issues/2996533

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by aaronjchristian** [comment]
@podarok can you take a look when you have a minute. Thank you!

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build859 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build859 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build859 |
| Installation process | http://install.openy.cibox.tools/build859/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/859/

**Comment by podarok** [comment]
@aaronjchristian 
Could you please follow the rules we have in comment - from the code it is not easy to understand what was fixed in this PR and how to test functionality that was fixed. In the comment there is a section where every developer should provide steps for review, these steps is a crucial part or review process.

Thanks in advance
PS. I've added some permissions, could you check if you received ability to assign reviewers to PR?

**Review by podarok — CHANGES_REQUESTED** [review]
Code looks good
Please provide steps for review to be able to check functionality on a build

**Comment by aaronjchristian** [comment]
Awesome thanks @podarok. I've updated the testing steps and added a link to the issue on d.o for credits. Thanks!

**Comment by aaronjchristian** [comment]
@podarok is there anything I need to do for this or has it been merged into 1.14 already?

**Comment by podarok** [comment]
@aaronjchristian merged. Is here any reason you pushed code to 1.14, not to 8.x-1.x for point release?

**Pull request merged**
