### PR TITLE
[OYPD-470] Remove <meta http-equiv="content-language" content="en" /> from all pages 

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue: https://propeople-us.atlassian.net/browse/OYPD-470
Drupal.org issue: 

Steps for review:
- [x] go to [sitename]/about
- [x] use "View Page source" open page source code
- [x] verify you don't see meta http-equiv="content-language"

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1353 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1353 |
| Installation process | http://install.openy-dev.ffwua.com/build1353/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1353/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1353/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1356 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1356 |
| Installation process | http://install.openy-dev.ffwua.com/build1356/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1356/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1356/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
