### PR TITLE
[CR-2] Update language on Open Y Terms & Conditions

### PR DESCRIPTION
**Pull request by hamrant**
Change request from Paige Thell (Kiecker)

## Steps for review

- [ ] Login as admin
- [ ] Go to /admin/openy/terms-and-conditions
- [ ] Check that Optional Permissions item text was upated

Screenshot from 2020-08-03 12-24-13

### CODE REVIEW

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2337/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #2066 of commit 49c274cb00f45dae5e4e2239401cffba9d650806 automatically merged.
Building on master in workspace /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build2337/openy-profile # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7744068213521320328.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: remote: Enumerating objects: 16571, done.        
remote: Counting objects:   0% (1/16571)        
remote: Counting objects:   1% (166/16571)        
remote: Counting objects:   2% (332/16571)        
remote: Counting objects:   3% (498/16571)        
remote: Counting objects:   4% (663/16571)        
remote: Counting objects:   5% (829/16571)        
remote: Counting objects:   6% (995/16571)        
remote: Counting objects:   7% (1160/16571)        
remote: Counting objects:   8% (1326/16571)        
remote: Counting objects:   9% (1492/16571)        
remote: Counting objects:  10% (1658/16571)        
remote: Counting objects:  11% (1823/16571)        
remote: Counting objects:  12% (1989/16571)        
remote: Counting objects:  13% (2155/16571)        
remote: Counting objects:  14% (2320/16571)        
remote: Counting objects:  15% (2486/16571)        
remote: Counting objects:  16% (2652/16571)        
remote: Counting objects:  17% (2818/16571)        
remote: Counting objects:  18% (2983/16571)        
remote: Counting objects:  19% (3149/16571)        
remote: Counting objects:  20% (3315/16571)        
remote: Counting objects:  21% (3480/16571)        
remote: Counting objects:  22% (3646/16571)        
remote: Counting objects:  23% (3812/16571)        
remote: Counting objects:  24% (3978/16571)        
remote: Counting objects:  25% (4143/16571)        
remote: Counting objects:  26% (4309/16571)        
remote: Counting objects:  27% (4475/16571)        
remote: Counting objects:  28% (4640/16571)        
remote: Counting objects:  29% (4806/16571)        
remote: Counting objects:  30% (4972/16571)        
remote: Counting objects:  31% (5138/16571)        
remote: Counting objects:  32% (5303/16571)        
remote: Counting objects:  33% (5469/16571)        
remote: Counting objects:  34% (5635/16571)        
remote: Counting objects:  35% (5800/16571)        
remote: Counting objects:  36% (5966/16571)        
remote: Counting objects:  37% (6132/16571)        
remote: Counting objects:  38% (6297/16571)        
remote: Counting objects:  39% (6463/16571)        
remote: Counting objects:  40% (6629/16571)        
remote: Counting objects:  41% (6795/16571)        
remote: Counting objects:  42% (6960/16571)        
remote: Counting objects:  43% (7126/16571)        
remote: Counting objects:  44% (7292/16571)        
remote: Counting objects:  45% (7457/16571)        
remote: Counting objects:  46% (7623/16571)        
remote: Counting objects:  47% (7789/16571)        
remote: Counting objects:  48% (7955/16571)        
remote: Counting objects:  49% (8120/16571)        
remote: Counting objects:  50% (8286/16571)        
remote: Counting objects:  51% (8452/16571)        
remote: Counting objects:  52% (8617/16571)        
remote: Counting objects:  53% (8783/16571)        
remote: Counting objects:  54% (8949/16571)        
remote: Counting objects:  55% (9115/16571)        
remote: Counting objects:  56% (9280/16571)        
remote: Counting objects:  57% (9446/16571)        
remote: Counting objects:  58% (9612/16571)        
remote: Counting objects:  59% (9777/16571)        
remote: Counting objects:  60% (9943/16571)        
remote: Counting objects:  61% (10109/16571)        
remote: Counting objects:  62% (10275/16571)        
remote: Counting objects:  63% (10440/16571)        
remote: Counting objects:  64% (10606/16571)        
remote: Counting objects:  65% (10772/16571)        
remote: Counting objects:  66% (10937/16571)        
remote: Counting objects:  67% (11103/16571)        
remote: Counting objects:  68% (11269/16571)        
remote: Counting objects:  69% (11434/16571)        
remote: Counting objects:  70% (11600/16571)        
remote: Counting objects:  71% (11766/16571)        
remote: Counting objects:  72% (11932/16571)        
remote: Counting objects:  73% (12097/16571)        
remote: Counting objects:  74% (12263/16571)        
remote: Counting objects:  75% (12429/16571)        
remote: Counting objects:  76% (12594/16571)        
remote: Counting objects:  77% (12760/16571)        
remote: Counting objects:  78% (12926/16571)        
remote: Counting objects:  79% (13092/16571)        
remote: Counting objects:  80% (13257/16571)        
remote: Counting objects:  81% (13423/16571)        
remote: Counting objects:  82% (13589/16571)        
remote: Counting objects:  83% (13754/16571)        
remote: Counting objects:  84% (13920/16571)        
remote: Counting objects:  85% (14086/16571)        
remote: Counting objects:  86% (14252/16571)        
remote: Counting objects:  87% (14417/16571)        
remote: Counting objects:  88% (14583/16571)        
remote: Counting objects:  89% (14749/16571)        
remote: Counting objects:  90% (14914/16571)        
remote: Counting objects:  91% (15080/16571)        
remote: Counting objects:  92% (15246/16571)        
remote: Counting objects:  93% (15412/16571)        
remote: Counting objects:  94% (15577/16571)        
remote: Counting objects:  95% (15743/16571)        
remote: Counting objects:  96% (15909/16571)        
remote: Counting objects:  97% (16074/16571)        
remote: Counting objects:  98% (16240/16571)        
remote: Counting objects:  99% (16406/16571)        
remote: Counting objects: 100% (16571/16571)        
remote: Counting objects: 100% (16571/16571), done.        
remote: Compressing objects:   0% (1/9075)        
remote: Compressing objects:   1% (91/9075)        
remote: Compressing objects:   2% (182/9075)        
remote: Compressing objects:   3% (273/9075)        
remote: Compressing objects:   4% (363/9075)        
remote: Compressing objects:   5% (454/9075)        
remote: Compressing objects:   6% (545/9075)        
remote: Compressing objects:   7% (636/9075)        
remote: Compressing objects:   8% (726/9075)        
remote: Compressing objects:   9% (817/9075)        
remote: Compressing objects:  10% (908/9075)        
remote: Compressing objects:  11% (999/9075)        
remote: Compressing objects:  12% (1089/9075)        
remote: Compressing objects:  13% (1180/9075)        
remote: Compressing objects:  14% (1271/9075)        
remote: Compressing objects:  15% (1362/9075)        
remote: Compressing objects:  16% (1452/9075)        
remote: Compressing objects:  17% (1543/9075)        
remote: Compressing objects:  18% (1634/9075)        
remote: Compressing objects:  19% (1725/9075)        
remote: Compressing objects:  20% (1815/9075)        
remote: Compressing objects:  21% (1906/9075)        
remote: Compressing objects:  22% (1997/9075)        
remote: Compressing objects:  23% (2088/9075)        
remote: Compressing objects:  24% (2178/9075)        
remote: Compressing objects:  25% (2269/9075)        
remote: Compressing objects:  26% (2360/9075)        
remote: Compressing objects:  27% (2451/9075)        
remote: Compressing objects:  28% (2541/9075)        
remote: Compressing objects:  29% (2632/9075)        
remote: Compressing objects:  30% (2723/9075)        
remote: Compressing objects:  31% (2814/9075)        
remote: Compressing objects:  32% (2904/9075)        
remote: Compressing objects:  33% (2995/9075)        
remote: Compressing objects:  34% (3086/9075)        
remote: Compressing objects:  35% (3177/9075)        
remote: Compressing objects:  36% (3267/9075)        
remote: Compressing objects:  37% (3358/9075)        
remote: Compressing objects:  38% (3449/9075)        
remote: Compressing objects:  39% (3540/9075)        
remote: Compressing objects:  40% (3630/9075)        
remote: Compressing objects:  41% (3721/9075)        
remote: Compressing objects:  42% (3812/9075)        
remote: Compressing objects:  43% (3903/9075)        
remote: Compressing objects:  44% (3993/9075)        
remote: Compressing objects:  45% (4084/9075)        
remote: Compressing objects:  46% (4175/9075)        
remote: Compressing objects:  47% (4266/9075)        
remote: Compressing objects:  48% (4356/9075)        
remote: Compressing objects:  49% (4447/9075)        
remote: Compressing objects:  50% (4538/9075)        
remote: Compressing objects:  51% (4629/9075)        
remote: Compressing objects:  52% (4719/9075)        
remote: Compressing objects:  52% (4738/9075)        
remote: Compressing objects:  53% (4810/9075)        
remote: Compressing objects:  54% (4901/9075)        
remote: Compressing objects:  55% (4992/9075)        
remote: Compressing objects:  56% (5082/9075)        
remote: Compressing objects:  57% (5173/9075)        
remote: Compressing objects:  58% (5264/9075)        
remote: Compressing objects:  59% (5355/9075)        
remote: Compressing objects:  60% (5445/9075)        
remote: Compressing objects:  61% (5536/9075)        
remote: Compressing objects:  62% (5627/9075)        
remote: Compressing objects:  63% (5718/9075)        
remote: Compressing objects:  64% (5808/9075)        
remote: Compressing objects:  65% (5899/9075)        
remote: Compressing objects:  66% (5990/9075)        
remote: Compressing objects:  67% (6081/9075)        
remote: Compressing objects:  68% (6171/9075)        
remote: Compressing objects:  69% (6262/9075)        
remote: Compressing objects:  70% (6353/9075)        
remote: Compressing objects:  71% (6444/9075)        
remote: Compressing objects:  72% (6534/9075)        
remote: Compressing objects:  73% (6625/9075)        
remote: Compressing objects:  74% (6716/9075)        
remote: Compressing objects:  75% (6807/9075)        
remote: Compressing objects:  76% (6897/9075)        
remote: Compressing objects:  77% (6988/9075)        
remote: Compressing objects:  78% (7079/9075)        
remote: Compressing objects:  79% (7170/9075)        
remote: Compressing objects:  80% (7260/9075)        
remote: Compressing objects:  81% (7351/9075)        
remote: Compressing objects:  82% (7442/9075)        
remote: Compressing objects:  83% (7533/9075)        
remote: Compressing objects:  84% (7623/9075)        
remote: Compressing objects:  85% (7714/9075)        
remote: Compressing objects:  86% (7805/9075)        
remote: Compressing objects:  87% (7896/9075)        
remote: Compressing objects:  88% (7986/9075)        
remote: Compressing objects:  89% (8077/9075)        
remote: Compressing objects:  90% (8168/9075)        
remote: Compressing objects:  91% (8259/9075)        
remote: Compressing objects:  92% (8349/9075)        
remote: Compressing objects:  93% (8440/9075)        
remote: Compressing objects:  94% (8531/9075)        
remote: Compressing objects:  95% (8622/9075)        
remote: Compressing objects:  96% (8712/9075)        
remote: Compressing objects:  97% (8803/9075)        
remote: Compressing objects:  98% (8894/9075)        
remote: Compressing objects:  99% (8985/9075)        
remote: Compressing objects: 100% (9075/9075)        
remote: Compressing objects: 100% (9075/9075), done.        
Receiving objects:   0% (1/16571)   
Receiving objects:   1% (166/165
```

**Review by AndreyMaximov — APPROVED** [review]

**Comment by AndreyMaximov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2341/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2341/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2341/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2341/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2341/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2341/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2341/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2341/

**Review by podarok — APPROVED** [review]

**Pull request merged**
