### PR TITLE
[OYPD-450] Location popup pages

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-390
D.o https://www.drupal.org/node/2881444

Steps to review
*Use case 1: Subcategory page, schedule page WITHOUT location popup paragraph*
1.1 Preferred branch is selected and no location in URL
- [x] When I open Subcategory/Schedule page WITHOUT location popup on page
- [x] And I have a preferred branch
- [x] And I don't have location=% in the URL
- [x] Filter by location should be predefined based on cookie
- [x] Results should be filtered

1.2 Preferred branch is empty and no location in URL
- [x] When I open Subcategory/Schedule page WITHOUT location popup on page
- [x] And I don't have a preferred branch
- [x] And I don't have location=% in the URL
- [x] Filter by location should show "All"
- [x] Results should be shown for all branches

1.3 Location in specified URL
- [x] When I open Subcategory/Schedule page WITHOUT location popup on page
- [x] And I have location=% in the URL
- [x] We skip cookie whether is empty or exist
- [x] Filter by location should show branch from URL
- [x] Results should be filtered

*Use case 2: Subcategory page, schedule page WITH location popup*
2.1 Preferred branch is selected and no location in URL
- [x] When I open Subcategory/Schedule page WITH location popup on page
- [x] And I have a preferred branch
- [x] And I don't have location=% in the URL
- [x] Location popup shouldn't be shown
- [x] Filter by location should be predefined based on cookie
- [x] Results should be filtered

2.2 Preferred branch is empty and no location in URL
- [x] When I open Subcategory/Schedule page WITH location popup on page
- [x] And I don't have a preferred branch
- [x] And I don't have location=% in the URL
- [x] Filter by location should show "All"
- [x] Results should be shown for all branches
- [x] Location popup should be shown

2.3 Location in specified URL
- [x] When I open Subcategory/Schedule page WITH location popup on page
- [x] And I have location=% in the URL
- [x] We skip cookie whether is empty or exist
- [x] Location popup shouldn't be shown
- [x] Filter by location should show branch from URL
- [x] Results should be filtered

*Use case 3: Class page WITHOUT location popup*
3.1 Location in specified URL
- [x] When I open Class page WITHOUT location popup on page
- [x] And I have location=% in the URL
- [x] We skip cookie whether is empty or exist
- [x] Results should be filtered based on location from URL
- [x] In sidebar we should see location teaser

3.2 Preferred branch is empty and no location in URL or Preferred branch is selected and no location in URL
- [x] When I open Class page WITHOUT location popup on page
- [x] And I don't have a preferred branch
- [x] Or I have a preferred branch
- [x] And I don't have location=% in the URL
- [x] Results should contain all branches
- [x] In sidebar we should see "All locations...."

*Use case 4: Class page WITH location popup*
4.1 Location in specified URL
- [x] When I open Class page WITH location popup on page
- [x] And I have location=% in the URL
- [x] We skip cookie whether is empty or exist
- [x] Results should be filtered based on location from URL
- [x] In sidebar we should see location teaser
- [x] Location is sidebar should have "Edit" button that will open location popup

4.2 Preferred branch is empty and no location in URL or Preferred branch is selected and no location in URL
- [x] When I open Class page WITH location popup on page
- [x] And I don't have a preferred branch
- [x] Or I have a preferred branch
- [x] And I don't have location=% in the URL
- [x] Results should contain all branches
- [x] In sidebar we should see "All locations...."
- [x] Location popup should be shown

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1274 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1274 |
| Installation process | http://install.openy-dev.ffwua.com/build1274/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1274/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1274/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1283 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1283 |
| Installation process | http://install.openy-dev.ffwua.com/build1283/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1283/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1283/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1284 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1284 |
| Installation process | http://install.openy-dev.ffwua.com/build1284/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1284/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1284/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1290 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1290 |
| Installation process | http://install.openy-dev.ffwua.com/build1290/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1290/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1290/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. There are some errors in JS console
https://cloud.githubusercontent.com/assets/1316234/26542672/900f9c38-4463-11e7-8fb0-43b3ab4b12af.png
https://cloud.githubusercontent.com/assets/1316234/26542673/900f4b66-4463-11e7-862a-fc3071aae4e8.png

2. Let's add "All locations" option to the Branches popup for class, because there's no way to get back to class with all locations.
https://cloud.githubusercontent.com/assets/1316234/26542694/a7c6437c-4463-11e7-8016-a401181cfcc8.png


3. When there's no session for the class, let's display some text. This use case may be relevant if someone added class to the bookmarks but the it became not active or something like this.
https://cloud.githubusercontent.com/assets/1316234/26542771/ddfd69d4-4463-11e7-9886-9f0e7251d993.png

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1307 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1307 |
| Installation process | http://install.openy-dev.ffwua.com/build1307/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1307/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1307/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1310 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1310 |
| Installation process | http://install.openy-dev.ffwua.com/build1310/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1310/

**Comment by alexschedrov** [comment]
1. Edit is missed in case when we see session for all locations.
image

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1310/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1319/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1320 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1320 |
| Installation process | http://install.openy-dev.ffwua.com/build1320/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1320/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1320/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
