### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by podarok**
Enable all configs to be translatable by default

This came from YGH
Changes are visible only after translation and localization modules are enabled

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build506

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/506/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build506/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build507

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/507/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build507/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
