### PR TITLE
Issue 2100 - error 500

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: #2100

## Steps for review

- [ ] Code review and compare with https://www.drupal.org/node/2549139.
- [ ] Verify respective subsystems are working `/locations`

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2444/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2444/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2444/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2444/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2444/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2444/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2444/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2444/

**Comment by hamrant** [comment]
Something with Amenities form: http://openy.cibox.tools/build2444/locations?type=ymca,camps&amenities

Screenshot from 2020-08-27 16-42-22

Also, all menu links navigated to the front page...

Not sure that this related to current PR, but better double check.

**Comment by podarok** [comment]
> Something with Amenities form: http://openy.cibox.tools/build2444/locations?type=ymca,camps&amenities
> 
> Screenshot from 2020-08-27 16-42-22
> 
> Also, all menu links navigated to the front page...
> 
> Not sure that this related to current PR, but better double check.

both are known issues and are not related to this PR https://github.com/ymcatwincities/openy/issues/2114 + https://github.com/ymcatwincities/openy/issues/2101

**Review by hamrant — APPROVED** [review]

**Pull request merged**
