### PR TITLE
[OYPD-510] Update small banners color for all content.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-510
Drupal.org issue: https://www.drupal.org/node/2888824

# Steps to review:
- [x] login as admin
- [x] go to Color taxonomy (/admin/structure/taxonomy/manage/color/overview)
- [x] verify you can see Gray color
- [x] in the main menu click on "Program"
- [x] open each item in submenu "Program"
- [x] for each page check title must be white and bg color gray
- [x] go to /blog page
- [x] after menu you can see small banner as title page
- [ ] check title must be white and bg color gray

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1711 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1711 |
| Installation process | http://install.openy-dev.ffwua.com/build1711/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1711/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1711

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1711

**Review by AlexNetman — APPROVED** [review]

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1711/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1718 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1718 |
| Installation process | http://install.openy-dev.ffwua.com/build1718/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1718/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1718

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1718

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1718/profiles/contrib/openy/build/reports/behat

**Pull request merged**
