### PR TITLE
Issues 1609 and 1423

### PR DESCRIPTION
**Pull request by denisbilchenko**
Original Issue, this PR is going to fix: 
https://github.com/ymcatwincities/openy/issues/1609
https://github.com/ymcatwincities/openy/issues/1423

### CODE REVIEW

**Comment by kolesnikoff** [comment]
@podarok please review.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1630 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1630 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1630 |
| Installation process | http://install.openy.cibox.tools/build1630/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1630/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1630/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1630/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1630/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1630/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1630/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1634 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1634 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1634 |
| Installation process | http://install.openy.cibox.tools/build1634/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1634/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1634/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1634/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1634/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1634/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1634/blogWCAG2AAhtmlcs.txt

**Pull request merged**
