### PR TITLE
[OPENY-138] Fix install error with moderation_state

### PR DESCRIPTION
**Pull request by anprok**
During site install I got error` Error: Call to a member function getTypePlugin() on null in /var/www/docroot/core/modules/content_moderation/src/Plugin/Field/ModerationStateFieldItemList.php on line 156 #0 /var/www/docroot/core/modules/content_moderation/src/Plugin/Field/ModerationStateFieldItemList.php(137): Drupal\content_moderation\Plugin\Field\ModerationStateFieldItemList->updateModeratedEntity('published')`
I found it caused by assigning value to the moderation_state field during landing page creation in openy_demo_nlanding.module. 

I suggest deleting the assignment of values to the moderation_state  field. it does not affect access to the pages being created. In addition, similar fields don't have value assignments on pages created in migrations

#
## Steps for review

- [x] make sure that no install error.
- [x] male sure that you have access to listed pages as an anonymous and registered user
/select-location
/schedules-0
/group-exercise-classes
/programs-activities
/swim
/personal-training
/camp
/kids-teens

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by ddrozdik — APPROVED** [review]
OK

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build857 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build857 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build857 |
| Installation process | http://install.openy.cibox.tools/build857/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/857/

**Comment by ddrozdik** [comment]
@podarok can be merged. feel free to merge after review.

**Review by podarok — APPROVED** [review]
moderation_state is pain
We have to remove it globally
Approved

**Pull request merged**
