### PR TITLE
[INOYI-19]: Closing quotation mark does not appear for Story Card

### PR DESCRIPTION
**Pull request by AleksandrPrykhodkoDev**
Original Issue: https://github.com/ymcatwincities/openy/issues/1872

## Steps for review

- [ ] Check code changes
- [ ] Add story card paragraph type to sidebar for any CT
- [ ] Check quotes, this fix applies to Rose and Lily themes

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by AndreyMaximov** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2142/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2142/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2142/

**Review by ddrozdik — APPROVED** [review]

**Review by podarok — APPROVED** [review]

**Review by podarok — CHANGES_REQUESTED** [review]
Code conflict. Please recompile a style

**Comment by anprok** [comment]
Continued in https://github.com/ymcatwincities/openy/pull/1993

**Pull request merged**
