### PR TITLE
OS-146: fix position for date and arrows.

### PR DESCRIPTION
**Pull request by SanyokMedved**
Go to http://sandbox.openymca.org/group-exercise-classes and try switch dates to left or right. Arrows should be on the same place with any length of date string.

### CODE REVIEW

**Comment by kolesnikoff** [comment]
@podarok please review

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1017 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1017 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1017 |
| Installation process | http://install.openy.cibox.tools/build1017/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1017/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1017/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1017/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1017/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1017/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1017/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
This is a bug fix, could you change the base to 8.x-1.x ? @SanyokMedved

**Comment by SanyokMedved** [comment]
@podarok  Base branch was changed. Please merge.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1025 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1025 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1025 |
| Installation process | http://install.openy.cibox.tools/build1025/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1025/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1025/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1025/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1025/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1025/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1025/blogWCAG2AAhtmlcs.txt

**Pull request merged**
