### PR TITLE
[OYPD-410-355] Add template for membership full page.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue #355 
Drupal.org issue: https://www.drupal.org/node/2879124

Steps:
- [x] login as admin
- [x] go to /admin/content
- [x] in the filter select content type 'membership'
- [x] click on view any membership
- [x] verify page have simple style

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1205 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1205 |
| Installation process | http://install.openy-dev.ffwua.com/build1205/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1205/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1205/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1210 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1210 |
| Installation process | http://install.openy-dev.ffwua.com/build1210/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1210/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1210/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1216 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1216 |
| Installation process | http://install.openy-dev.ffwua.com/build1216/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1216/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1216/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
