### PR TITLE
Skip moderation state checking if bundle not support content moderation

### PR DESCRIPTION
**Pull request by hamrant**
Backported from the YMCA of Greater Seattle
----
In case moderation state disabled for the class content type we got incorrect work for session instances and repeat event recreating. Both services use `EntityModerationStatus` from `openy_moderation_wrapper` module so we need to add additional checking to these service methods. 

For this checking, I have used `getWorkflowForEntity` from `ModerationInformation` service that exists in content and workbench moderation. 
```php
  /**
   * Gets the workflow for the given content entity.
   *
   * @param \Drupal\Core\Entity\ContentEntityInterface $entity
   *   The content entity to get the workflow for.
   *
   * @return \Drupal\workflows\WorkflowInterface|null
   *   The workflow entity. NULL if there is no workflow.
   */
  public function getWorkflowForEntity(ContentEntityInterface $entity) {
    $bundles = $this->bundleInfo->getBundleInfo($entity->getEntityTypeId());
    if (isset($bundles[$entity->bundle()]['workflow'])) {
      return $this->entityTypeManager->getStorage('workflow')->load($bundles[$entity->bundle()]['workflow']);
    };
    return NULL;
  }
```

## Steps to reproduce

- [x] Login as admin
- [x] Go to /admin/modules/uninstall and remove all modules that related to repeat event (it override session instance manager)
- [x] Go to /admin/config/workflow/workflows/manage/editorial
- [x] If your section `THIS WORKFLOW APPLIES TO:` contain not configured Content types row - add all content types except session.
- [x] Create class with valid rules for session instance (it must be published and contain filled in the Activity field with correct data)
- [x] Create several sessions with valid rules for session instance (it must be published and contain filled in the fields with correct data)
- [x] Check that on /admin/structure/session_instance you can see created instances
- [x] Go to /admin/config/workflow/workflows/manage/editorial
- [x] Disable moderation for class content type
- [x] Repeat steps with classes and sessions
- [x] Check that session instances not created

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1195 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1195 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1195 |
| Installation process | http://install.openy.cibox.tools/build1195/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1195/

**Review by podarok — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1314 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1314 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1314 |
| Installation process | http://install.openy.cibox.tools/build1314/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1314/

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1348 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1348 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1348 |
| Installation process | http://install.openy.cibox.tools/build1348/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1348/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1348/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1348/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1348/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1348/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1348/blogWCAG2AAhtmlcs.txt

**Comment by ddrozdik** [comment]
@hamrant I tried to go through steps but I finished on the step `Check that on /admin/structure/session_instance you can see created instances`. I created a session but the session instance was not created.

**Comment by hamrant** [comment]
Class from this session was without activity - http://openy.cibox.tools/build1348/admin/structure/session_instance
He did not pass validation

**Pull request merged**
