### PR TITLE
[Minor-Fix][385] Do not render colors where there is nothing to render.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue: https://github.com/ymcatwincities/openy/issues/385
Drupal.org issue: https://www.drupal.org/node/2884307

Steps for review:
- [x] go to page /blog
- [x] use inspector page
- [x] check blocks and verify you can't see empty css styles.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1363 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1363 |
| Installation process | http://install.openy-dev.ffwua.com/build1363/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1363/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1363/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1399 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1399 |
| Installation process | http://install.openy-dev.ffwua.com/build1399/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1399/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1399/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
