### PR TITLE
embedded_groupexpro_schedule: Config fixes

### PR DESCRIPTION
**Pull request by alexander-danilenko**
## Problem

Once YMCA Long Island was updated to latest `v8.1.2` on each configuration import (using `openy_upgrade_tool.importer` service) on site reinstall we got following error: 
```bash
TASK: [Updating database] *****************************************************
<localhost> REMOTE_MODULE command APP_ENV=dev drush -y updb -l http://drupal.192.168.56.132.xip.io #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1498046419.26-78978995355492 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1498046419.26-78978995355492 && echo $HOME/.ansible/tmp/ansible-tmp-1498046419.26-78978995355492']
<localhost> PUT /tmp/tmpoBtVVD TO /home/vagrant/.ansible/tmp/ansible-tmp-1498046419.26-78978995355492/command
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=vkpplizhujqbtklbrddvdudngcsdpzon] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vkpplizhujqbtklbrddvdudngcsdpzon; LANG=C LC_CTYPE=C /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1498046419.26-78978995355492/command; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1498046419.26-78978995355492/ >/dev/null 2>&1'"'"''
failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush -y updb -l http://drupal.192.168.56.132.xip.io", "delta": "0:00:40.989986", "end": "2017-06-21 12:01:00.277026", "rc": 1, "start": "2017-06-21 12:00:19.287040", "warnings": []}
stderr: Configuration <em                                                    [error]
class="placeholder">embeddedgroupexpro.settings</em> depends on the
<em class="placeholder">embeddedgroupexpro</em> extension that will
not be installed after import.
Performing modulename_update_8038                                 [ok]
Failed: Configuration embeddedgroupexpro.settings depends on the     [error]
embeddedgroupexpro extension that will not be installed after import.
Cache rebuild complete.                                              [ok]
Finished performing updates.                                         [ok]
stdout: The following updates are pending:
ymcali_master module :
  8038 -   hook_update_N comment.
Do you wish to run all pending updates? (y/n): y
FATAL: all hosts have already failed -- aborting
PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/vagrant/reinstall.retry
localhost                  : ok=24   changed=15   unreachable=0    failed=1
```

I've started to investigate this problem, because all PR builds failed with no possibility of config updates and found that module `embedded_groupexpro_schedule` saves config to `embeddedgroupexpro.settings` which is not followed config naming conventions: https://www.drupal.org/docs/develop/coding-standards/configuration-file-coding-standards#filename 

So, update is here :) I've also added install config and schema files for module.

## Changes
- Just renamed config from `embeddedgroupexpro.settings` to `embedded_groupexpro_schedule.settings`

## Questions
- Should this bug be fixed in module with configuration (as in this PR), or in [openy_upgrade_tool.importer](https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/custom/openy_upgrade_tool/src/ConfigUpdater.php) service?

## Steps for review

- [x] Review code updates.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1693 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1693 |
| Installation process | http://install.openy-dev.ffwua.com/build1693/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1693/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1693

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1693/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1694 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1694 |
| Installation process | http://install.openy-dev.ffwua.com/build1694/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1694/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1694

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1694/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1700 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1700 |
| Installation process | http://install.openy-dev.ffwua.com/build1700/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1700/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1700

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1700/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Looks good! However we need au upgrade path for this to support already provisioned websites.

1. Add hook_update to `embedded_groupexpro_schedule` modules
2. Import new schema in update
3. Get `embeddedgroupexpro.settings` config in update
4. Save this config as `embedded_groupexpro_schedule.settings`
5. Remove `embeddedgroupexpro.settings` config from database

**Comment by alexander-danilenko** [comment]
@Sanchiz added hook_update_N, please review.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1710 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1710 |
| Installation process | http://install.openy-dev.ffwua.com/build1710/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1710/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1710

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1710

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1710/profiles/contrib/openy/build/reports/behat

**Comment by alexander-danilenko** [comment]
Hi @Sanchiz, any updates on this?

**Comment by alexschedrov** [comment]
@fat763 please change label to "Needs review" whether it's ready for review :) It still has "Needs work", that's why review has been delayed.

**Comment by alexander-danilenko** [comment]
@Sanchiz I haven`t permissions to do that :) 
thanks!

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1733 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1733 |
| Installation process | http://install.openy-dev.ffwua.com/build1733/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1733/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1733

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1733

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1733/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
