### PR TITLE
[OYPD-216] Blog post listing is filtering only by Description, but not by Title.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-216
D.o https://www.drupal.org/node/2852593

Steps to review
- [x] Go to /blog
- [x] See view with filters on page displaying blog posts
- [x] Test search: The text field filter can search both title text such as "Mood-boosting" and blog description field such as "Y Run in mid-April"

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build465

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/465/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build465/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build472

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/472/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build472/profiles/openy/build/reports/behat

**Pull request merged**
