### PR TITLE
[OYPD-209] Adding nav menu hover to color module override file

### PR DESCRIPTION
**Pull request by david-hernandez**
screen shot 2017-02-08 at 6 21 52 pm

Bug fix. The top nav didnt not get its hover color overridden when color module override was change to a different color.

- [x] On "Appearance" where theme settings are changed, change the colors for header menu hover.
- [x] Make sure the color appears when hovering over the "My Account" menu link in the color and the main nav drop down.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build398

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/398/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build398/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build402

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/402/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build402/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
There's small blue border. Let's get rid of it or override with selected color.
image

**Comment by david-hernandez** [comment]
Thanks for catching that. Latest commit should fix it.

screen shot 2017-02-09 at 8 10 20 am

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build406

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/406/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build406/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
