### PR TITLE
#1567: New alerts (React component) -- placement, template

### PR DESCRIPTION
**Pull request by SanyokMedved**
On some sites we found out that we need to place alerts to the different areas on the page.
We added the logic into main Alert's library, that inserts Alerts' code in `<div id="openy_alerts_header_placeholder"></div>` tag if it exists on the page. 
If not, everything stays as before.

As an example you can take a look at https://ymcawnc.org/ - we added this placeholder to the site's theme.

Please suggest, should we add this placeholder to all default themes and should we add the placeholder for the footer alerts?

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1605 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1605 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1605 |
| Installation process | http://install.openy.cibox.tools/build1605/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1605/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1605/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1605/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1605/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1605/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1605/blogWCAG2AAhtmlcs.txt

**Comment by kolesnikoff** [comment]
@podarok please review.

**Review by podarok — APPROVED** [review]
@kolesnikoff 
What about same, but for footer?

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1607 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1607 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1607 |
| Installation process | http://install.openy.cibox.tools/build1607/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1607/

**Comment by kolesnikoff** [comment]
@podarok We need your decision about the footer. 
Currently, alerts are inserted into ` <div class="pre-footer"></div>`, that's why we are not sure if we need to add one more placeholder for it.

**Pull request merged**
