### PR TITLE
[OYPD 414] GroupEx Pro API and paragraph

### PR DESCRIPTION
**Pull request by david-hernandez**
This does not work at the moment. The block seems to work, or at least return data, but there is an issue with the paragraph working.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1275 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1275 |
| Installation process | http://install.openy-dev.ffwua.com/build1275/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1275/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1275/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@david-hernandez I think this is related to plugin upgrade to 2.5. AFAIK plugin 2.4 doesn't save block configuration. But with upgrade to 2.5 other part of the website become broken.

**Comment by david-hernandez** [comment]
Looks like I can get it to kind of work with the form cache module turned off. This also has plugin 2.5. What doesn't seem to work is the JS update. The form change only seems to work on page refresh, though sometimes I can get it to work. :/
screen shot 2017-05-26 at 10 51 35 am

**Comment by david-hernandez** [comment]
Andriy confirmed they are running plugin 2.5 on Houston

**Pull request closed without merging**
