### PR TITLE
ConfigParamUpdaterService checking of existing key, not value

### PR DESCRIPTION
**Pull request by yasik78**
issue https://github.com/ymcatwincities/openy/issues/571

## Steps for review

- [ ] Check this issue on drupal.org - https://www.drupal.org/node/2886443
- [ ] View  patch https://www.drupal.org/files/issues/ConfigParamUpdaterService-checking-of-existing-key-2886443.patch

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1619 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1619 |
| Installation process | http://install.openy-dev.ffwua.com/build1619/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1619/

**Review by hamrant — APPROVED** [review]

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1619/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
