### PR TITLE
OYPD-458 upgrade plugin module to latest release

### PR DESCRIPTION
**Pull request by Kerby70**
**What should be done** 

Upgrade plugin module to latest release

**Requirements**
upgrade plugin module
Address regression issues with paragraphs with block not loading correctly. This may be resolved by moving the function that loads demo content to the end of the install process.

Jira https://propeople-us.atlassian.net/browse/OYPD-458
D.o https://www.drupal.org/node/2885054

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

## FOR OpenY issue queue
The Plugin module (https://www.drupal.org/project/plugin) has been updated to version 2.5. With that update new install demo content referencing custom blocks from fields has broken, displaying the message "This block is broken or missing. You may be missing content or you might need to enable the original module." in the place of the block. Manually removing and replacing the paragraph will result in the appropriate behavior from the paragraph.

The paragraphs affected are:
* Branches popup (All)
* Branches popup (Class)
* Camp menu
* Class location
* Class Sessions
* Embedded GroupEx Pro Schedule
* Location finder
* Location finder filters
* Membership calculator
* Schedule search form
* Schedule search list

From the following feature modules:
* openy_prgf_branches_popup_all
* openy_prgf_branches_popup_class
* openy_prgf_camp_menu
* openy_prgf_class_location
* openy_prgf_class_sessions
* openy_prgf_embedded_groupexpro_schedule
* openy_prgf_loc_finder
* openy_prgf_mbrshp_calc
* openy_prgf_schedule_search

## FOR Plugin issue queue
As a part of the OpenY distribution project there are paragraphs referencing custom blocks. After the Plugin module update to version 2.5 the OpenY demo content added during site install, fails to reference these blocks. It appears to related to the changes in https://www.drupal.org/node/2807901 although debugging did not yield a clear cause. When the paragraphs are created via the migration module the field plugin_id's are being set to 'broken'. This all only occurs when installing via command-line using drush, and does not occur from the UI site install.

## Steps for review

- [x] Paragraphs work (Demo content paragraph exceptions listed above)

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1408 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1408 |
| Installation process | http://install.openy-dev.ffwua.com/build1408/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1408/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1408/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1501 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1501 |
| Installation process | http://install.openy-dev.ffwua.com/build1501/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1501/

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1504 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1504 |
| Installation process | http://install.openy-dev.ffwua.com/build1504/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1504/

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1507 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1507 |
| Installation process | http://install.openy-dev.ffwua.com/build1507/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1507/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1507/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
