### PR TITLE
Add placeholders for 3rd party services

### PR DESCRIPTION
**Pull request by yasik78**
https://github.com/ymcatwincities/openy/issues/382  
## Steps for review

- [x] install openy project 
- [x] check  3rd party services configuration form

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1722 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1722 |
| Installation process | http://install.openy-dev.ffwua.com/build1722/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1722/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1722

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1722

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1722/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1735 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1735 |
| Installation process | http://install.openy-dev.ffwua.com/build1735/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1735/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1735

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1735

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1735/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Review by alexschedrov — APPROVED** [review]
Code looks good.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1742 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1742 |
| Installation process | http://install.openy-dev.ffwua.com/build1742/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1742/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1742

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1742

**Comment by alexschedrov** [comment]
1. Recaptcha requires placeholders as well.
image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1771 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1771 |
| Installation process | http://install.openy-dev.ffwua.com/build1771/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1771/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1771

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1771

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1771/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1783 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1783 |
| Installation process | http://install.openy-dev.ffwua.com/build1783/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1783/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1783

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1783

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1783/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
