### PR TITLE
[OYPD-518] Adding a JS file for the openy_calc module and adding function to sc…

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Go to /join page.
- [x] Try to click "next" without choosing a membership type.
- [x] Make sure the page scrolls up to where the error message displays.
- [x] Check with different screen sizes and browsers.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1755 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1755 |
| Installation process | http://install.openy-dev.ffwua.com/build1755/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1755/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1755

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1755

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1755/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1761 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1761 |
| Installation process | http://install.openy-dev.ffwua.com/build1761/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1761/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1761

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1761

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1761/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
If that is in accessibility scope - we need to set focus to that error, when it appear.
Otherwise screenreader remains on "Next" button and it's no way to understand that page has produced error and was scrolled up.

**Review by AlexNetman — APPROVED** [review]

**Comment by alexschedrov** [comment]
@david-hernandez please set focus to the error.

**Comment by david-hernandez** [comment]
So since the error message isn't a link I added tabindex to shift focus to it. Without that the browser still leaves focus on the "next" button and then doesn't want to scroll the page with the next button out of view.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1791 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1791 |
| Installation process | http://install.openy-dev.ffwua.com/build1791/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1791/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1791

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1791

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1791/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1792 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1792 |
| Installation process | http://install.openy-dev.ffwua.com/build1792/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1792/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1792

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1792

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1792/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
When focus jumps to the message - it just reads "content info - 1 item" and not reading error message.

**Comment by david-hernandez** [comment]
That is tab focus. It isn't going to read the message unless the whole thing was made a link, which I don't think we'd expect to do, would we?

**Comment by david-hernandez** [comment]
The screen reader should read it now. I had to move the focus to the inner element which had role="alert" on it.

screen shot 2017-07-05 at 10 15 44 am

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1809 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1809 |
| Installation process | http://install.openy-dev.ffwua.com/build1809/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1809/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1809

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1809/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1809/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1809/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1809/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1809/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1809/blogWCAG2AAhtmlcs.txt

**Pull request merged**
