### PR TITLE
Fix embed icons generation

### LINKED ISSUE #2011: Buttons icons
When I try to add an icon to the button, I can't seem to have icons displayed properly.

Steps to Recreate:

- Log into Sandbox
- Edit any Page that contains a WYSIWYG editable field. (http://sandbox.openymca.org/about - for example)
- Add a button to the page content by clicking the 'button' icon in WYSIWYG
- Go to the Icons tab in the modal window
- Add Fontawesome icon code, i.e. fa-ad or fa-amazon
- Save the page (icons do not appear on the Button or a rectangle is displayed instead of a button)

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/2011

Backport from https://github.com/ymcatwincities/openy/pull/2225

## Steps for review

- [x] check WYSIWYG entity embed icons .

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2878/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2878/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2878/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2878/

**Comment by podarok** [comment]
image

**Comment by podarok** [comment]
Fontawesome icon also works well 
image

**Pull request merged**
