### PR TITLE
[OPENY-180] Fix broken location finder blocks on locations page

### PR DESCRIPTION
**Pull request by anprok**
## Steps for review
- [x] open demo site
- [x] visit /locations page.
- [x] make sure that map and filters displayed.
- [x] make sure that no errors at upgrade path installation

### CODE REVIEW

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1107 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1107 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1107 |
| Installation process | http://install.openy.cibox.tools/build1107/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1107/

**Comment by ddrozdik** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1115 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1115 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1115 |
| Installation process | http://install.openy.cibox.tools/build1115/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1115/

**Comment by ddrozdik** [comment]
@anprok Upgrade path build does not work. It has an error on the Locations page 
```
Error: Call to a member function setDisplay() on null in Drupal\openy_map\Plugin\Block\LocationFinder->build() (line 84 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1115/openy-profile/modules/custom/openy_map/src/Plugin/Block/LocationFinder.php) #0 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1115/openy-project/docroot/modules/contrib/plugin/src/Plugin/Field/FieldFormatter/BuiltBlock.php(30): Drupal\openy_map\Plugin\Block\LocationFinder->build() 

#1 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1115/openy-project/docroot/core/lib/Drupal/Core/Field/FormatterBase.php(80): Drupal\plugin\Plugin\Field\FieldFormatter\BuiltBlock->viewElements(Object(Drupal\plugin\Plugin\Field\FieldType\PluginCollectionItemList), 'en') 

#2 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1115/openy-project/docroot/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(259): Drupal\Core\Field\FormatterBase->view(Object(Drupal\plugin\Plugin\Field\FieldType\PluginCollectionItemList), 'en') 
```

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1115/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1115/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1115/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1115/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1115/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]
Code looks good, but ensure upgrade path is covered

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1130/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1130/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1130/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1130/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1130/blogWCAG2AAhtmlcs.txt

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1131 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1131 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1131 |
| Installation process | http://install.openy.cibox.tools/build1131/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1131/

**Comment by anprok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1136 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1136 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1136 |
| Installation process | http://install.openy.cibox.tools/build1136/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1136/

**Pull request merged**
