### PR TITLE
Issues #1254

### PR DESCRIPTION
**Pull request by Fant0m771**
Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature, please create PR against 8.x-1.xx-dev branch.

If this is a bug fix - use 8.x-1.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

Issue: https://github.com/ymcatwincities/openy/issues/1254

## Steps for review

- [x] Go to /admin/config/services/openy_map.
- [x] Try to find "Locations Map icon" and put new icons as described in help text : "Choose content type map icon. To redefine icons add file in {default_theme}/img/locations_icons directory in active default theme"
- [x] After put icons in described directory you should see new icons in "Locations Map icon" list.

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Fant0m771** [comment]
retest this please

**Comment by ddrozdik** [comment]
retest this please

**Review by ddrozdik — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build879 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build879 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build879 |
| Installation process | http://install.openy.cibox.tools/build879/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/879/

**Review by AndreyMaximov — APPROVED** [review]

**Review by podarok — APPROVED** [review]

**Pull request merged**
