### PR TITLE
[OYPD-193] Updating blog content type files to new name of just blog

### PR DESCRIPTION
**Pull request by david-hernandez**
The name changed from "bog posts" to just "blog". The featured blog posts paragraph type should look proper now.

screen shot 2017-02-01 at 5 17 28 pm

- [x] Add node of type blog.
- [x] Make sure css loads. You can see the full page should have margin bottom 50px below the blog content. It is on the article tag. You can also check how featured blog posts look when added to a landing page.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build321

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/321/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build321/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build328

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/328/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build328/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
There's some problem with blog listing paragraph.
- Create LP
- Insert "Blog Posts Listing" paragraph
- For some reason it look like this
image

**Comment by david-hernandez** [comment]
Last update should fix the basic reported bugs including the issue with the title not aligned. There are going to be other bugs. We should discuss at some point how this is setup. The blog teaser does not have a generic component style. It seems to have been style for a specific use case.
screen shot 2017-02-02 at 11 56 19 am

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build340

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/340/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build340/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by Sanchiz** [comment]
Looks good, but as a temporary solution. Later on we should get rid of %%%% in styles and use grid columns.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build356

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/356/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build356/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@david-hernandez it still looks ugly.
image

1. We should get rid of % it styles and use grid classes for that.
2. It should be 3 teasers per row on mobile, 2 on table and 1 one mobile with Slick. Take a look here http://www.seattleymca.org/blog

**Comment by david-hernandez** [comment]
Not sure why you are getting different results than me. The problem is this
is for some reason all hard coded in the node styling which the paragraphs
are overriding. I don't know why it was done that way. I was trying to
avoid redoing all of that. Are there any other places blog teasers are used
before I try to retractor all that?

**Comment by alexschedrov** [comment]
@david-hernandez 5 paragraphs:
- Blog listing camp
- Blog listing branch
- Blog posts listing
- Latest blog posts
- Featured blog posts

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build372

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/372/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build372/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build373

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/373/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build373/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build374

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/374/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build374/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Taxonomy page has some regressions, /blog/category/community-outreach
2. Blog posts listing paragraph: should have 3 items per row.
https://cloud.githubusercontent.com/assets/1316234/22640585/fb1b1742-ec5b-11e6-8ae9-4e3537b8a4a7.png

3. Blog posts listing paragraph: tablet layout look completely different from original website.
https://cloud.githubusercontent.com/assets/1316234/22640620/2c01eee4-ec5c-11e6-9041-0c6369c68c4e.png

https://cloud.githubusercontent.com/assets/1316234/22640630/31d1eb12-ec5c-11e6-89cc-a10c07fc35ac.png

4. Blog posts listing paragraph: mobile layout look completely different from original website.
https://cloud.githubusercontent.com/assets/1316234/22640686/625a4496-ec5c-11e6-9b95-ce633256c37d.png

https://cloud.githubusercontent.com/assets/1316234/22640694/6863a5b2-ec5c-11e6-9778-300699d6b339.png

5. Make sure you've tested all other pargraphs

**Comment by david-hernandez** [comment]
The blog listing view was set to be a grid style with a 4 column layout. This is completely different than the featured blogs layout. Was there a reason than that was done? I have to modify the view.

**Comment by david-hernandez** [comment]
screen shot 2017-02-06 at 19 17 52-fullpage
screen shot 2017-02-06 at 19 17 20-fullpage
screen shot 2017-02-06 at 19 17 02-fullpage
screen shot 2017-02-06 at 19 16 52-fullpage
screen shot 2017-02-06 at 19 16 38-fullpage
screen shot 2017-02-06 at 19 15 57-fullpage

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build381

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/381/

**Comment by david-hernandez** [comment]
Some things to note. I applied the grid styling to the taxonomy term page, but this will apply to all taxonomy vocabularies. I don't know if that is wanted. I checked the Seattle and demo site and neither one are properly styled, and neither seem to have listing pages for anything other than the blog post terms.

The blog post list will be one per row below 760, because I'm using the defined bootstrap breakpoints we have in openy_rose. The Seattle theme has a mix of custom breakpoints and sizes.

The exposed form might need some changes. It isn't exactly the same as the other sites, but I don't know if this is suppose to be different. It is now styled the same, but it has different form elements and labels than the other sites, so I left it. If that needs to be changed, maybe we can do that in a follow up.

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build381/profiles/openy/build/reports/behat

**Comment by david-hernandez** [comment]
Also, the gaps on the smallest screen size are because of the posts that use images. They shrink smaller than the container. This is the same as the live sites. Putting a default background color there might be the easiest solution. It only happens below 360px.

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build383

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/383/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build383/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Blog posts listing paragraph - looks good
2. Latest blog posts paragraph - still looks weird. Should be like here http://seattleymca.org/
image


3. Latest blog posts paragraph(branch/camp) - still looks weird. Should be like here http://seattleymca.org/locations/bellevue-family-ymca
image

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://10.0.2.15:8080/job/PR_BUILDER/2/

**Build Log**
*last 25 lines*

 ```
[...truncated 29 lines...]
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
Couldn't read comment file
java.io.FileNotFoundException: File '/var/lib/jenkins/jobs/PR_BUILDER/workspace/commentinfo.md' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:124)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by david-hernandez** [comment]
latestsmall
latestmedium
latestlarge
branchsmall
branchmedium
branchlarge
camplarge

**Comment by david-hernandez** [comment]
The camp list will look a bit off width wise because the layout of camp pages doesn't seem correct. They are currently full width. But styling should be correct.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build384

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/384/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build384/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
