### PR TITLE
[OYPD-415] 	Adding templates and style changes for GroupEx schedule

### PR DESCRIPTION
**Pull request by david-hernandez**
There is a change to add openy_group_schedules as a dependency in the groupex_form_cache module. This solved the problem I kept having with demo content not working. For some reason the groupex_form_cache module is getting installed first which causes a failure because it depends on traits in the openy_group_schedules module. I don't know why I'm the only one seeing this problem though.

- [x] Visit the groupex schedules page. /schedules/group-schedules
- [x] Choose location
- [x] Verify the design looks ok. It should be similar to Houston, with some slight differences. http://ygh.ffwua.com/demo/schedules
- [x] Check main schedule page.
- [x] Click instructor links and check the instructor pages.
- [x] Click class links and check the class pages.
- [x] Check responsive sizes.

Note: The large spacing at the bottom of some tiles is because of the equal height of the tiles. Also, for some reason the multiple instructor names wrap to the next line. This is not the styling. The instructor names have a BR tag in between them. I don't know why that was done, but assume it was on purpose.

screen shot 2017-07-27 at 10 59 07 pm
screen shot 2017-07-27 at 10 58 52 pm
screen shot 2017-07-27 at 10 58 45 pm
screen shot 2017-07-27 at 10 58 36 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1964 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1964 |
| Installation process | http://install.openy-dev.ffwua.com/build1964/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1964/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1964

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1964/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1964/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1964/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1964/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1964/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1964/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1967 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1967 |
| Installation process | http://install.openy-dev.ffwua.com/build1967/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1967/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1967

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1967/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1967/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1967/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1967/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1967/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1967/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. We need more space on mobile device
image

2. Select some branch in paragraph settings, apply filter by class is applied. Calendar icon has weird alignment and needs some margin
image

3. Behat tests are failed

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1973 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1973 |
| Installation process | http://install.openy-dev.ffwua.com/build1973/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1973/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1973

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1973/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1973/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1973/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1973/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1973/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1973/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1975 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1975 |
| Installation process | http://install.openy-dev.ffwua.com/build1975/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1975/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1975

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1975/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1975/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1975/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1975/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1975/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1975/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1980 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1980 |
| Installation process | http://install.openy-dev.ffwua.com/build1980/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1980/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1980

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1980/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1980/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1980/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1980/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1980/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1980/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@david-hernandez these issues are still relevant https://github.com/ymcatwincities/openy/pull/723#issuecomment-318599503

image

**Comment by david-hernandez** [comment]
So for some reason that class selector renders out of order. I'm trying to track that down.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1993 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1993 |
| Installation process | http://install.openy-dev.ffwua.com/build1993/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1993/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1993

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1993/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1993/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1993/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1993/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1993/blogWCAG2AAhtmlcs.txt

**Comment by david-hernandez** [comment]
There is a fair amount of shifting going on with some of these elements in the different versions of the schedules, for some reason. I made some adjustment, but trying to avoid redoing all of it. See if this is better.

screen shot 2017-07-31 at 11 19 42 am
screen shot 2017-07-31 at 11 18 43 am
screen shot 2017-07-31 at 11 18 17 am

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1993/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1994 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1994 |
| Installation process | http://install.openy-dev.ffwua.com/build1994/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1994/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1994

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1994/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1994/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1994/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1994/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1994/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1994/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1996 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1996 |
| Installation process | http://install.openy-dev.ffwua.com/build1996/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1996/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1996

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1996/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1996/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1996/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1996/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1996/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1996/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
image

**Comment by alexschedrov** [comment]
@AlexNetman this is not related to theming. You've already reported this as separate JIRA ticket https://propeople-us.atlassian.net/browse/OYPD-551.

**Comment by AlexNetman** [comment]
Cards are stacked together on iPhone/iPad Safari.
http://ci.openymca.org/build1996/schedules/group-schedules?location=2577&filter_date=8/01/17
Houston Groupex account used.
image

**Comment by AlexNetman** [comment]
image

**Comment by david-hernandez** [comment]
I'm not sure what you are asking in the last comment. The spacing is the same on top and bottom.

**Comment by david-hernandez** [comment]
I'm not seeing the issue with the bunched up cards in my simulator. Can you send me the Houston account id in slack or email?

screen shot 2017-08-01 at 10 14 03 am

**Comment by AlexNetman** [comment]
retest this please

**Comment by AlexNetman** [comment]
@david-hernandez 
I have recheck that stacked issue - actually that is not reproduced on latest iOS 10.
Just I was able to reproduce on iPhone 6 - iOS 8. So may be we should ignore that.

But I noticed issue for long titles, when cards are displayed not of the same size
image

* You can use Houston account from here. https://propeople-us.atlassian.net/wiki/display/OYPD/GroupExPro+Schedules

______________
And about padding - we need some White space before filters. Now it look like the stick to the banner above.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2003 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2003 |
| Installation process | http://install.openy-dev.ffwua.com/build2003/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2003/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build2003

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2003/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2003/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2003/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2003/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2003/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2003/profiles/contrib/openy/build/reports/behat

**Comment by david-hernandez** [comment]
For the long tiles, I"m not sure there is much to do. They get equal height, but when resizing a third line for the title pushes it beyond its design size. I'd half to make them bigger by default which would create a lot of extra white space for all the others. Unless people are ok with adding all the extra white space. I don't know what these class titles are like for other Ys, so what is the chance it could go to four or even more lines?

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
