### PR TITLE
[OYPD-356] Demo content for program sub category, activity, class, and sessions.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-356
D.o https://www.drupal.org/node/2870367

Steps to review:
- On each subcategory demo page:
  - [ ] See Classes Listing Filters & Classes Listing view
  - [ ] See demo classes for each subcategory (related to branch 'West YMCA')
More list & filter functionality to come in https://propeople-us.atlassian.net/browse/OYPD-357

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build925 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build925 |
| Installation process | http://install.openy-dev.ffwua.com/build925/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/925/

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build949 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build949 |
| Installation process | http://install.openy-dev.ffwua.com/build949/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/949/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build949/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build955 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build955 |
| Installation process | http://install.openy-dev.ffwua.com/build955/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/955/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build955/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build962 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build962 |
| Installation process | http://install.openy-dev.ffwua.com/build962/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/962/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build962/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build977 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build977 |
| Installation process | http://install.openy-dev.ffwua.com/build977/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/977/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build977/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Place activity after category
image

2. Program and Category should be popullated, since we already know Program and Category from the page context. Like here http://www.seattleymca.org/programs/swimming/swim-lessons

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build982 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build982 |
| Installation process | http://install.openy-dev.ffwua.com/build982/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/982/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build982/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build988 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build988 |
| Installation process | http://install.openy-dev.ffwua.com/build988/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/988/

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build989 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build989 |
| Installation process | http://install.openy-dev.ffwua.com/build989/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/989/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build989/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by alexschedrov** [comment]
@Kerby70 please add upgrade path for the changes in view.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build993 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build993 |
| Installation process | http://install.openy-dev.ffwua.com/build993/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/993/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build993/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
Upgrade path working http://upgrade.openy-dev.ffwua.com/build993/programs/health-and-fitness/test

**Pull request merged**
