### PR TITLE
[OYPD-XXX] Update plugin contrib module

### PR DESCRIPTION
**Pull request by duozersk**
Steps to review:
- [ ] review code changes

### CODE REVIEW

**Review by danylevskyi — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build913 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build913 |
| Installation process | http://install.openy-dev.ffwua.com/build913/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/913/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build913/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build914 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build914 |
| Installation process | http://install.openy-dev.ffwua.com/build914/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/914/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build914/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
please retest this

**Comment by Kerby70** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build927 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build927 |
| Installation process | http://install.openy-dev.ffwua.com/build927/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/927/

**Comment by alexschedrov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build929 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build929 |
| Installation process | http://install.openy-dev.ffwua.com/build929/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/929/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build929/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build936 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build936 |
| Installation process | http://install.openy-dev.ffwua.com/build936/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/936/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build936/profiles/contrib/openy/build/reports/behat

**Pull request merged**
