### PR TITLE
[OYPD-292] Adding color preview to theme settings

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Enable theme and visit theme settings page for OpenY Rose.
- [x] You should now see a preview for main style and camp style. Change colors for main style, and verify the preview updates. 
- [x] Change colors for camp style and make sure preview updates.
- [x] Change main logo and verify previews updates with the new logo.

screen shot 2017-03-06 at 8 57 47 pm

screen shot 2017-03-06 at 9 00 35 pm

### CODE REVIEW

**Comment by david-hernandez** [comment]
This is branched from OYPD-280 because I need those changes.

One thing puzzling me at the moment is why the branch subheader settings show up at the bottom. All the other settings come out in the correct order. Weird.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build679 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build679 |
| Installation process | http://install.openy-dev.ffwua.com/build679/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/679/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build679/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build683 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build683 |
| Installation process | http://install.openy-dev.ffwua.com/build683/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/683/

**Comment by Sanchiz** [comment]
1. Let's replace Lorem ipsum with something meaningful and related to YMCA.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build683/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Let's replace Lorem ipsum with something meaningful and related to YMCA.

**Comment by david-hernandez** [comment]
Changed the text.

screen shot 2017-03-07 at 8 40 52 am

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build688 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build688 |
| Installation process | http://install.openy-dev.ffwua.com/build688/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/688/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build688/profiles/openy/build/reports/behat

**Pull request merged**
