### PR TITLE
issue-1235 fixed methods calls in the child component

### PR DESCRIPTION
**Pull request by denisbilchenko**
issue: https://github.com/ymcatwincities/openy/issues/1235
I added $parent. before methods calls in the child component template. It resolve a problem, but it is not so good solution to call directly parent(root) methods in child component. In true way we have to use another relations between parent(root) and child components(e.g. props -> down, $emit -> up). It requires more time and re-test whole feature.

@podarok, please review and advise.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1039 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1039 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1039 |
| Installation process | http://install.openy.cibox.tools/build1039/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1039/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1039/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1039/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1039/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1039/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1039/blogWCAG2AAhtmlcs.txt

**Comment by podarok** [comment]
@denisbilchenko fix conflict

@ygerasimov could you suggest better solution for this?

**Review by podarok — DISMISSED** [review]
I'm fine with having this merged while we are looking for better solution

**Review by podarok — DISMISSED** [review]

**Comment by podarok** [comment]
@denisbilchenko please resolve conflict

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1063 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1063 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1063 |
| Installation process | http://install.openy.cibox.tools/build1063/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1063/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1063/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1063/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1063/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1063/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1063/blogWCAG2AAhtmlcs.txt

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
@podarok since we do not have a better solution so far, let's merge

**Pull request merged**
