### PR TITLE
[OPYD-XXX] Adding Open Y installation theme

### PR DESCRIPTION
**Pull request by xcf33**
Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build951 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build951 |
| Installation process | http://install.openy-dev.ffwua.com/build951/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/951/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build951/profiles/contrib/openy/build/reports/behat

**Comment by xcf33** [comment]
Steps to Review:

1. Please follow the installation process link, you should see a background image as well as YMCA favicon during the installation (see below)

image

**Comment by Sanchiz** [comment]
retest this please

**Comment by alexschedrov** [comment]
@xcf33 looks awesome! Only one thing, theme should be placed in `openy_themes` folder https://github.com/ymcatwincities/openy/tree/8.x-1.x/themes/openy_themes.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build961 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build961 |
| Installation process | http://install.openy-dev.ffwua.com/build961/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/961/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build961/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build966 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build966 |
| Installation process | http://install.openy-dev.ffwua.com/build966/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/966/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build966/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
