### PR TITLE
[CIYMCA-132] Make not show the icon if the email is empty

### PR DESCRIPTION
**Pull request by AleksandrPrykhodkoDev**
Steps for review:

- turn on theme carnation
- visit any page event (Content Type "Event")
- verify the email icon is not shown

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1950/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1950/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1950/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build1950/

**Pull request merged**
