### PR TITLE
Fix update issue for openy_loc_branch and openy_node_alert modules

### LINKED ISSUE #1940: Broken update (openy_loc_branch)
I get the following on database update:

ArgumentCountError: Too few arguments to function Drupal\openy_upgrade_tool\ConfigParamUpgradeTool::update(), 2 passed in                                                                                                   [error]
/var/www/docroot/profiles/contrib/openy/modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install on line 389 and exactly 3 expected in
Drupal\openy_upgrade_tool\ConfigParamUpgradeTool->update() (line 56 of /var/www/docroot/profiles/contrib/openy/modules/custom/openy_upgrade_tool/src/ConfigParamUpgradeTool.php) #0
/var/www/docroot/profiles/contrib/openy/modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install(389): Drupal\openy_upgrade_tool\ConfigParamUpgradeTool->update('profiles/contri...',
'third_party_set...')
#1 /var/www/vendor/drush/drush/commands/core/drupal/update.inc(65): openy_loc_branch_update_8018(Array)
#2 /var/www/vendor/drush/drush/commands/core/drupal/batch.inc(163): drush_update_do_one('openy_loc_branc...', 8018, Array, Object(DrushBatchContext))
#3 /var/www/vendor/drush/drush/commands/core/drupal/batch.inc(111): _drush_batch_worker()
#4 /var/www/vendor/drush/drush/includes/batch.inc(98): _drush_batch_command('259')
#5 /var/www/vendor/drush/drush/commands/core/drupal/update.inc(235): drush_batch_command('259')
#6 /var/www/vendor/drush/drush/commands/core/core.drush.inc(1231): _update_batch_command('259')
#7 /var/www/vendor/drush/drush/includes/command.inc(422): drush_core_updatedb_batch_process('259')
#8 /var/www/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#9 /var/www/vendor/drush/drush/includes/command.inc(199): drush_command('259')
#10 /var/www/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#11 /var/www/vendor/drush/drush/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 phar:///usr/local/bin/drush/bin/drush.php(153): drush_main()
#13 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#14 {main}.

The root of the problem is here:
https://github.com/ymcatwincities/openy/blob/a5276c4ab247e4e0821a102430759d8bca7c3eb1/modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install#L389

### PR DESCRIPTION
**Pull request by anprok**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/1940
Dependency fix required for upgrade from OpenY 8.2.2.2 to 8.2.4.3

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2110/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2110/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2110/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2110/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2110/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2110/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2110/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2110/

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2110/

**Pull request merged**
