### PR TITLE
[OYPD-423] Add ability to javascript events on Tours.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue https://propeople-us.atlassian.net/browse/OYPD-423
Drupal.org issue: 

Steps:
- [x] login as admin
- [x] go to page: [sitename]/admin/structure/menu
- [x] in the top right click on Tour
- [x] go to 7 step and click on "Show operations" button
- [x] verify operations list open
- [x] go to page: [sitename]/admin/structure/taxonomy
- [x] in the top right click on Tour
- [x] go to 8 step and click on "Show operations" button
- [x] verify operations list open
- [x] go to page: [sitename]/admin/structure/taxonomy/manage/color/add
- [x] in the top right click on Tour
- [x] go to 5 step and click on "Open color picker" button
- [x] verify color picker list open
- [x] also verify "Open color picker" button hide and show "Next" button

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1336 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1336 |
| Installation process | http://install.openy-dev.ffwua.com/build1336/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1336/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1336/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1341 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1341 |
| Installation process | http://install.openy-dev.ffwua.com/build1341/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1341/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1341/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1368 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1368 |
| Installation process | http://install.openy-dev.ffwua.com/build1368/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1368/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1368/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1369 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1369 |
| Installation process | http://install.openy-dev.ffwua.com/build1369/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1369/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1369/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1371 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1371 |
| Installation process | http://install.openy-dev.ffwua.com/build1371/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1371/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1371/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1372 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1372 |
| Installation process | http://install.openy-dev.ffwua.com/build1372/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1372/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1372/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1373 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1373 |
| Installation process | http://install.openy-dev.ffwua.com/build1373/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1373/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1373/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Step 8 on taxonomy page is missed for some reason. It jumps from 7 to 9.

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1390 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1390 |
| Installation process | http://install.openy-dev.ffwua.com/build1390/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1390/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1390/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1391 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1391 |
| Installation process | http://install.openy-dev.ffwua.com/build1391/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1391/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1391/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1393 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1393 |
| Installation process | http://install.openy-dev.ffwua.com/build1393/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1393/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1393/profiles/contrib/openy/build/reports/behat

**Pull request closed without merging**
