### PR TITLE
[Openy 266]: Make T&C Agreement the first step of installation process

### PR DESCRIPTION
**Pull request by afi13**
## Steps for review

- [x] Install Open Y manually.
- [x] Verify T&C is the first step of the installation process.
- [x] Make sure Open Y can be completely installed without any regressions.
- [x] Go to `/terms.txt` and verify T&C is accepted during installation.
- [x] Make sure Open Y can be installed with drush.

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1476 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1476 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1476 |
| Installation process | http://install.openy.cibox.tools/build1476/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1476/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1477 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1477 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1477 |
| Installation process | http://install.openy.cibox.tools/build1477/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1477/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1478 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1478 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1478 |
| Installation process | http://install.openy.cibox.tools/build1478/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1478/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1478/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1478/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1478/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1478/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1478/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]
Code looks good

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
