### PR TITLE
[MAINTAIN-131] Install theme's footer block before theme installation.

### PR DESCRIPTION
**Pull request by manachynskyi**
Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

Should be review after [PR](https://github.com/open-y-subprojects/openy_content_core/pull/4) and [PR](https://github.com/open-y-subprojects/openy_demo_content/pull/3) will be merged.

## Steps for review
- [ ] Check logs of installation process
- [ ] make sure no errors after `openy_select_theme` step, related to the `block_content`, appears https://i.imgur.com/W4zNQ0i.png

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
ok to test

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3568/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3568/

**Comment by gundevel** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3568/

**Comment by hamrant** [comment]
I fink we need to remove `openy_demo_bfooter` from `openy_demo_content_configs_map` because no need to install this module a second time on the demo content step:

https://github.com/ymcatwincities/openy/blob/9.x-2.x/openy.profile#L178

Screenshot from 2021-11-08 19-02-59

cc @manachynskyi

**Comment by manachynskyi** [comment]
Fixed

**Review by hamrant — APPROVED** [review]

**Comment by gundevel** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3569/

**Comment by hamrant** [comment]
Testing blocked by https://github.com/ymcatwincities/openy/pull/2581#issuecomment-963384193

**Comment by hamrant** [comment]
restest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3578/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3578/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3578/

**Comment by hamrant** [comment]
restest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3579/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3579/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3579/

**Comment by hamrant** [comment]
http://install.openy.cibox.tools/build3579/core/install.php?rewrite=ok&profile=openy&terms_and_conditions=1&langcode=en

Screenshot from 2021-11-10 16-31-51

As far as I know, this is env problem, I will try to test this later on the new build.

**Comment by hamrant** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3610/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3610/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3610/

**Pull request merged**
