### PR TITLE
[YGBWSLA-154] Fix ie11 bug with default js value for Home branch module

### PR DESCRIPTION
**Pull request by anprok**
Fix console error in IE 11 with message Expected ')'
Reason: IE11 and under, doesn't implement ES6 and breaks on default parameters

## Steps for review
- [ ] login as admin on IE 11
- [ ]  enable openy_home_branch module and back to home page
- [ ]  make sure home branch modal displayed at first opening
- [ ] make sure no console errors for a default value
- [ ]  reload page and make sure that home branch modal not displayed
- [ ]  click Home branch link in top menu
- [ ]  make sure modal displayed
- [ ]  select any branch and close modal
- [ ]  make sure home branch link changed to branch name you selected
- [ ]  click on branch link at top menu
- [ ]  make sure you redirected to branch page
- [ ]  click on change location link in banner
- [ ]  make sure home branch modal displayed

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2062/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2062/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2062/

**Review by hamrant — CHANGES_REQUESTED** [review]
@anprok Please provide fix according to https://stackoverflow.com/questions/15178700/javascript-functions-and-default-parameters-not-working-in-ie-and-chrome

We need this default value here.

**Comment by podarok** [comment]
@anprok @hamrant 
Is there a chance this script to be converted to webpack/yarn compile with adding polyfill there?
We have examples in OpenY code for this
Let us know if you can't find it

**Comment by anprok** [comment]
> @anprok Please provide fix according to https://stackoverflow.com/questions/15178700/javascript-functions-and-default-parameters-not-working-in-ie-and-chrome
> 
> We need this default value here.

there is a validation condition after that code https://github.com/ymcatwincities/openy/pull/1915/files#diff-b81ea127aa9e17fe8818ad055002cfdaR90
 that will only pass if `forceShow = true`, in all other cases (null or undefined), the validation will fail. If the default value was a number or a string, then an assignment would be required, but we have boolean here. So is enough

**Comment by hamrant** [comment]
@podarok Unfortunately, we're running out of SLA hours on this project.

Anyway, it's a good idea, we'll try to find time for that and make a separate fix.

**Comment by hamrant** [comment]
@anprok please update current branch.
@podarok this code works fine, tested on YGBW. Can be merged with https://github.com/ymcatwincities/openy/pull/1929

**Review by hamrant — APPROVED** [review]

**Comment by podarok** [comment]
No need to update. This is GitHub being too picky )
Thank you @anprok @hamrant

**Comment by hamrant** [comment]
@podarok thanks!

**Pull request merged**
