### PR TITLE
[OYPD-556] Update openy_group_schedules from Houston YMCA.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-556
D.o https://www.drupal.org/node/2898815

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [x] As admin
- [x] Add Group Schedules paragraph
- [x] See Class & Instructor filters

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1995 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1995 |
| Installation process | http://install.openy-dev.ffwua.com/build1995/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1995/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1995

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1995/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1995/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1995/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1995/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1995/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1995/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1999 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1999 |
| Installation process | http://install.openy-dev.ffwua.com/build1999/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1999/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1999

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1999/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1999/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1999/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1999/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1999/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1999/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2004 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2004 |
| Installation process | http://install.openy-dev.ffwua.com/build2004/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2004/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2004

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2004/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2004/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2004/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2004/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2004/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2004/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
I've resolved some issues I saw while trying to resolve the anonymous user errors. I have not seen these issues but I am not seeing the filtering expected.

The code is more inline with Houston, but I still see issues with results & with values coming back after being cleared.

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2015 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2015 |
| Installation process | http://install.openy-dev.ffwua.com/build2015/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2015/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2015

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2015/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2020 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2020 |
| Installation process | http://install.openy-dev.ffwua.com/build2020/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2020/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2020

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2020/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
The last two commits should receive a code reviewed.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2024 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2024 |
| Installation process | http://install.openy-dev.ffwua.com/build2024/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2024/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2024

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2024/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
Behat test needs rework, since date field has changed.

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2040

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2040/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2040/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2040/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2040/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2040/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2040/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2042 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2042 |
| Installation process | http://install.openy-dev.ffwua.com/build2042/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2042/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2042

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2042/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2042/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2042/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2042/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2042/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2042/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2045 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2045 |
| Installation process | http://install.openy-dev.ffwua.com/build2045/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2045/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2045

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2045/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2045/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2045/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2045/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2045/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2045/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2054 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2054 |
| Installation process | http://install.openy-dev.ffwua.com/build2054/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2054/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2054

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2054/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2054/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2054/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2054/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2054/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2054/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
I see filters not aligned:
image
http://ci.openymca.org/build2054/schedules/group-schedules?location=204&filter_date=8/07/17

**Comment by AlexNetman** [comment]
When I select "Melissa T (sub for Eric B)"
Then I should see 'Tabata class'
http://ci.openymca.org/build2054/schedules/group-schedules?location=204&filter_date=8/07/17&class=any&filter_length=week&category=any&groupex_class=groupex_table_instructor_individual&instructor=Melissa%20T.%3Cspan%20class=%22subbed%22%20style=%22color:%20#cc0000;"><br>(sub for Eric  B.)</span>
But it's not displayed (see that HTML in URL)

Also when I go to schedule by Trainer, I should see that trainer selected in filters.
But I don't see:

image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2061 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2061 |
| Installation process | http://install.openy-dev.ffwua.com/build2061/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2061/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2061

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2061/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2061/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2061/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2061/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2061/blogWCAG2AAhtmlcs.txt

**Comment by Kerby70** [comment]
@Sanchiz @AlexNetman  I could not find a format for the instructor select that would resolve the filtering for the markup entries. Is this a common to include the html in the returned data? I am not sure what the values need to be, I did not find another site with a resolution to this.

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2061/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2064 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2064 |
| Installation process | http://install.openy-dev.ffwua.com/build2064/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2064/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2064

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2064/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2064/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2064/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2064/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2064/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2064/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. "Date" field is dissapear
- Open /schedules/group-schedules
- Select branch
- Select any value in Class filter
- Filter by date will be hidden

Expected behavior: filter by date should be available

2. Issue that is reported above is fixed on the YMCA Twin Cities website. Here's the results page https://www.ymcamn.org/all_y_schedules?location=32&filter_date=8/08/17.

Instead of creating link to filter by substitute, we just cut the value to trainer.
So, when I click this filter, it will filter results by Sarah D. Please find the solution in the YGTC codebase.

image

**Comment by Kerby70** [comment]
Date field no longer disappearing updated in latest commit.

Instructor link of sub broken here (twin cities, is this the correct demo site?)/(no instructor field)
- http://ymca.ffwua.com/ygb-demo/all_y_schedules?location=31&class=any&category=any&filter_length=week&filter_date=08/08/17&groupex_class=groupex_table_instructor_individual&filter_timestamp=1502175600&instructor=Dan%20S.
- Also sub link not working on
-- Page is missing "Activity Together" https://www.ymcamn.org/all_y_schedules?location=32&class=any&category=any&filter_length=week&filter_date=08/08/17&groupex_class=groupex_table_instructor_individual&filter_timestamp=1502175600&instructor=Wendy%20G.
--- 
image
-- Sarah D. link has no results https://www.ymcamn.org/all_y_schedules?location=32&class=any&category=any&filter_length=week&filter_date=08/08/17&groupex_class=groupex_table_instructor_individual&filter_timestamp=1502175600&instructor=Sarah%20D.
image

Instructor link not setting field here. Also it does not appear to have any subs. http://ygh.ffwua.com/demo/schedules?location=2575&filter_date=8/08/17

**Comment by Kerby70** [comment]
Instructor link now updating the dropdown.

**Outstanding question**: How do we query the substitute instructor entries? That will drive the solution for the dropdown & how we need to modify the link.

**Comment by Sanchiz** [comment]
retest this please

**Comment by Sanchiz** [comment]
test this please

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2065 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2065 |
| Installation process | http://install.openy-dev.ffwua.com/build2065/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2065/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2065

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2065/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2065/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2065/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2065/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2065/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2065/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Nothing happens when I change date filter https://screencast.com/t/JFYLAmXuA
2. Links and options in the dropdown where we have sub, should be cleaned up from markup and as value for filter use only person who is specified as substitude - https://screencast.com/t/uGblaCfy

**Comment by Kerby70** [comment]
1. It looks like date field is a core issue https://www.drupal.org/node/2781103 I could try an apply the patch but otherwise we might want a FE dev to take a look.

2. In new commit
** Some keys now overwrite others, the sub classes do not get returned in these queries.
**  Indoor Cycling from results on /schedules/group-schedules?location=202&filter_date=8/10/17&class=any&filter_length=week&category=any&groupex_class=groupex_table_instructor_individual
image
** Is missing in /schedules/group-schedules?location=202&filter_date=8/10/17&class=any&filter_length=week&category=any&groupex_class=groupex_table_instructor_individual&instructor=Melissa%20T.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2074 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2074 |
| Installation process | http://install.openy-dev.ffwua.com/build2074/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2074/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2074

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2074/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2074/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2074/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2074/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2074/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2074/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
Must
* Set date on link click
* Strip sub text from instructor filter
* Add submit button

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2077 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2077 |
| Installation process | http://install.openy-dev.ffwua.com/build2077/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2077/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2077

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2077/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2077/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2077/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2077/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2077/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2077/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2079 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2079 |
| Installation process | http://install.openy-dev.ffwua.com/build2079/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2079/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build2079

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2079/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2079/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2079/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2079/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2079/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2079/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@Kerby70 Submit button is not visible on Schedules page, but it visible on Branch page.

image

Please fix this and we're good to go.

**Comment by Robert201-zz** [comment]
retest this please

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2082 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2082 |
| Installation process | http://install.openy-dev.ffwua.com/build2082/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2082/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build2082

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2082 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2082 |
| Installation process | http://install.openy-dev.ffwua.com/build2082/install.php |

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2083/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #728 of commit 60e4ddafedd7322cd532ba5174a4908d3c375ab7.
GitHub pull request #728 of commit 60e4ddafedd7322cd532ba5174a4908d3c375ab7.
GitHub pull request #728 of commit 60e4ddafedd7322cd532ba5174a4908d3c375ab7.
GitHub pull request #728 of commit 60e4ddafedd7322cd532ba5174a4908d3c375ab7.
GitHub pull request #728 of commit 60e4ddafedd7322cd532ba5174a4908d3c375ab7.
GitHub pull request #728 of commit 60e4ddafedd7322cd532ba5174a4908d3c375ab7.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7064891301553190416.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git2938553864781385604.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse 60e4ddafedd7322cd532ba5174a4908d3c375ab7^{commit} # timeout=10
 > git branch -a --contains 60e4ddafedd7322cd532ba5174a4908d3c375ab7 # timeout=10
 > git rev-parse remotes/origin/pr/728/head^{commit} # timeout=10
Checking out Revision 60e4ddafedd7322cd532ba5174a4908d3c375ab7 (origin/pr/728/head)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 60e4ddafedd7322cd532ba5174a4908d3c375ab7
Build was aborted
Aborted by anonymous
```

**Pull request merged**
