### PR TITLE
[OYPD-387] Styling adjustment for location in sidebar for classes

### PR DESCRIPTION
**Pull request by david-hernandez**
Straightforward adjustment. One thing to note is the linked text comes out purple. I left this because this is how all the other sidebar facility/branch/location teasers are setup to work, though I don't know why.

screen shot 2017-05-15 at 11 30 33 am

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1182 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1182 |
| Installation process | http://install.openy-dev.ffwua.com/build1182/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1182/

**Comment by alexschedrov** [comment]
@david-hernandez can we adjust styles for message when we see schedule for all locations? Something like this
image

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1182/profiles/contrib/openy/build/reports/behat

**Comment by david-hernandez** [comment]
don't merge that last commit. i need to fix it.

**Comment by david-hernandez** [comment]
Ok updated. 

screen shot 2017-05-15 at 12 36 39 pm

I used the styling that appears in the teasers for handling that first line of text. It will make the text wrap, but I think that is ok. Even playing around to make it not wrap it still wraps at smaller screen sizes anyway.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1183 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1183 |
| Installation process | http://install.openy-dev.ffwua.com/build1183/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1183/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1183/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1184 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1184 |
| Installation process | http://install.openy-dev.ffwua.com/build1184/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1184/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1184/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1188 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1188 |
| Installation process | http://install.openy-dev.ffwua.com/build1188/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1188/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1188/profiles/contrib/openy/build/reports/behat

**Pull request merged**
