### PR TITLE
Add extra checking if ids not empty.

### PR DESCRIPTION
**Pull request by Fant0m771**
Original Issue, this PR is going to https://github.com/ymcatwincities/openy/issues/1570

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by podarok** [comment]
@Fant0m771 how is it possible that $entity doesn't exist?
Looking at the code - it should be passed to function as argument
Looks like you are facing with some edge case when DB is inconsistent

**Comment by Fant0m771** [comment]
It is not clear for me how it works, but I know that our site does not use activity and maybe this is content leftovers after demo content deleted.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1575 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1575 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1575 |
| Installation process | http://install.openy.cibox.tools/build1575/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1575/

**Pull request merged**
