### PR TITLE
[OYPD-146, OYPD-168] demo programs, sub-categories

### PR DESCRIPTION
**Pull request by RoloDMonkey**
Steps for review:

- [x] drush mi --group=openy_demo_term
- [x] drush mi --group=openy_demo_nprogram
- [x] drush mi --group=openy_demo_ncategory

### CODE REVIEW

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build305

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/305/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build305/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
