### PR TITLE
[OYPD-203] Location finder paragraph test updates.

### PR DESCRIPTION
**Pull request by Kerby70**
Steps to review:
- [x] Tests must pass

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build876 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build876 |
| Installation process | http://install.openy-dev.ffwua.com/build876/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/876/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build876/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build877 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build877 |
| Installation process | http://install.openy-dev.ffwua.com/build877/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/877/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build877/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build884 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build884 |
| Installation process | http://install.openy-dev.ffwua.com/build884/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/884/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build884/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
