### PR TITLE
Mobile Branch Info for Lily, Rose, and Carnation

### LINKED ISSUE #2300: Visual Issues: Mobile Branch Info for Lily, Rose, and Carnation
Also, I created branch pages and there are some visual issues on mobiles with the 'Branch info' paragraph:
1. Carnation: the title is not seen and no 'back to all locations' link
Carnation - Branch Info

2. Rose: no 'back to all locations' link
Rose - Branch Info

3. Lily: branch hours doesn't display
Lily - Branch Info

Issue reported by Nadiia during QA for release. Original Issue archived here: https://3.basecamp.com/3608022/buckets/9444393/todos/3180624645

### PR DESCRIPTION
**Pull request by shuklina**
Issue: https://github.com/ymcatwincities/openy/issues/2300

## Steps for review
1. Rose theme
- [x] go to `/locations` and choose some location.
- [x] Make sure that there is a ` back to all locations` link
image

2. Carnation theme
- [x] go to `/locations` and choose some location.
- [x] Make sure that there is a ` back to all locations` link
image

3. Lily theme
- [x] go to `/locations` and choose some location.
- [x] Make sure that hours are displayed on mobile.
image

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2844/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2844/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2844/

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2844/

**Comment by podarok** [comment]
Thank you, @shuklina

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
