### PR TITLE
[OPENY-192] Fix nonexisting service error when unistalling packages

### PR DESCRIPTION
**Pull request by anprok**
## Steps for review

- [x] login as admin.
- [x] visit admin/openy/extend/uninstall
- [x] uninstall Camp package
- [x] visit admin/reports/dblog.
- [x] make sure that camp related modules deleted without errors
- [x] return to admin/openy/extend/uninstall
- [x] uninstall Programs package.
- [x] make sure that Programs related modules deleted without errors

### CODE REVIEW

**Review by hamrant — APPROVED** [review]

**Review by ddrozdik — APPROVED** [review]

**Review by hamrant — APPROVED** [review]

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1151 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1151 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1151 |
| Installation process | http://install.openy.cibox.tools/build1151/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1151/

**Review by podarok — APPROVED** [review]

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1152 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1152 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1152 |
| Installation process | http://install.openy.cibox.tools/build1152/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1152/

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1153 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1153 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1153 |
| Installation process | http://install.openy.cibox.tools/build1153/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1153/

**Comment by podarok** [comment]
```
[Tue Nov 13 16:43:25.947213 2018] [php7:notice] [pid 11415] [client 178.54.63.218:58785] Error: Cannot use object of type Symfony\\Component\\HttpFoundation\\RedirectResponse as array in /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-profile/modules/custom/openy_system/src/Form/OpenyModulesUninstallConfirmForm.php on line 33 #0 [internal function]: Drupal\\openy_system\\Form\\OpenyModulesUninstallConfirmForm->buildForm(Object(Symfony\\Component\\HttpFoundation\\RedirectResponse), Object(Drupal\\Core\\Form\\FormState))\n#1 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(514): call_user_func_array(Array, Array)\n#2 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(271): Drupal\\Core\\Form\\FormBuilder->retrieveForm('system_modules_...', Object(Drupal\\Core\\Form\\FormState))\n#3 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/Controller/FormController.php(74): Drupal\\Core\\Form\\FormBuilder->buildForm('system_modules_...', Object(Drupal\\Core\\Form\\FormState))\n#4 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\RouteMatch))\n#5 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)\n#6 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#7 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#8 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)\n#9 [internal function]: Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#10 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array)\n#11 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#12 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#13 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#14 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#15 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#16 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-profile/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#17 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\openy_block_date\\StackMiddleware\\BlockDateCacheInvalidator->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#18 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#19 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/core/lib/Drupal/Core/DrupalKernel.php(664): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build1152/openy-project/docroot/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#22 {main}
```

on http://openy.cibox.tools/build1152/admin/openy/extend/uninstall/confirm

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1155 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1155 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1155 |
| Installation process | http://install.openy.cibox.tools/build1155/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1155/

**Pull request merged**
