### PR TITLE
[MAINTAIN-35] changed image style for paragraph teaser display view of media image

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: [MAINTAIN-35](https://openy.atlassian.net/browse/MAINTAIN-35)

In this PR was replaced  the image style for paragraph teaser display view (from prgf_teaser (260x220) to paragraph_teaser_520_440 (520x440)) for better quality of teaser image

This one should affect all 3 themes. so needs to test on with all of them:
**Rose**:
Desktop
MAINTAIN-35NewImageStyleRose1
Tablet:
MAINTAIN-35NewImageStyleRoseTablet

**Lily**:
Desktop:
MAINTAIN-35NewImageStyleLily1
Tablet:
MAINTAIN-35NewImageStyleLilyTablet

**Carnation**:
Desktop
MAINTAIN-35NewImageStyleCarnation1
Tablet:
MAINTAIN-35NewImageStyleCarnationTablet

## Steps for review

- [ ] Log as admin.
- [ ] To create a new landing page.
- [ ] In content are please add a new teaser block with image
- [ ] Verify that this block looks good in all 2 themes (Rose. Lily, Carnation) for desktop screen
- [ ] Verify that this block looks good in all 2 themes (Rose. Lily, Carnation) for mobile screens (tablet/smartphone)

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Review by podarok — APPROVED** [review]

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3098/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3098/

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build3098/

**Comment by podarok** [comment]
Seems like all good
image

**Comment by podarok** [comment]
image
Seems like the upgrade path is failing

**Comment by podarok** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3102/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3102/

**Comment by podarok** [comment]
same, Upgrade Path is not working @aleevas

**Review by podarok — CHANGES_REQUESTED** [review]
Upgrade path needs to be working

**Comment by gundevel** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build3102/

**Comment by podarok** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3104/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3104/

**Comment by podarok** [comment]
```
13:39:46 >  [notice] Update started: openy_activity_finder_update_8401
13:39:46 >  [error]  Configuration <em class="placeholder">core.entity_view_display.media.image.prgf_teaser</em> depends on the <em class="placeholder">image.style.paragraph_teaser_520_440</em> configuration that will not exist after import. 
13:39:46 >  [error]  Update failed: openy_activity_finder_update_8401 
```
same issue after server clear caches on CI
Upgrade path is broken here

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build3104/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3111/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3111/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3111/

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
Tested on all 3 themes - http://upgrade.openy.cibox.tools/build3111/test-1

Screenshot from 2021-02-26 17-37-14

Screenshot from 2021-02-26 17-38-10

Screenshot from 2021-02-26 17-39-00

Checked all devices looks ok.

@aleevas please provide more details about the hook update fix for @podarok (force push was a bad decision in this case)

cc @podarok

**Comment by aleevas** [comment]
> @aleevas please provide more details about the hook update fix for @podarok

I've separate one hook_updates to 2:
one for import new configs and second for update existing one
And it works!
@hamrant thank you for quick review

**Review by podarok — APPROVED** [review]

**Pull request merged**
