### PR TITLE
[YP2-19] Fix errors in W3C CSS Validator.

### PR DESCRIPTION
**Pull request by manachynskyi**
This PR is going to fix some W3C css errors for Carnation theme. 
Error list: https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.ymcapkc.org%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en#errors

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2814/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2814/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2815/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2815/

**Pull request merged**
