### PR TITLE
[OYPD-489] Small Banner: Increase space between Title and Description.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution! ;))))

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-489
Drupal.org issue: https://www.drupal.org/node/2891225

# Steps to review:
- [x] login as admin
- [x] go to /blog
- [x] add description for small banner on the blog page
- [x] verify space between title and description same as in the banner on fronpage

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1770 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1770 |
| Installation process | http://install.openy-dev.ffwua.com/build1770/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1770/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1770

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1770

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1770/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1782 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1782 |
| Installation process | http://install.openy-dev.ffwua.com/build1782/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1782/

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1782

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1782

**Comment by Sanchiz** [comment]
@ivan-berezhnov needs re-roll.

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1782/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1787 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1787 |
| Installation process | http://install.openy-dev.ffwua.com/build1787/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1787/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1787

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1787

**Review by alexschedrov — APPROVED** [review]

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1787/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1789 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1789 |
| Installation process | http://install.openy-dev.ffwua.com/build1789/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1789/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1789

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1789

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1789/profiles/contrib/openy/build/reports/behat

**Pull request merged**
