### PR TITLE
[OYPD-467] Multiple links in mobile top nav read as "home".

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-467
Drupal.org issue: https://www.drupal.org/node/2888011

Needed for verification: iPad or iPhone
# Steps to review:
- [x] open build in your device
- [x] go to frontpage or any other page
- [x] enable Accessibility on your device Settings ->General -> Accessibility -> VoiceOver
Please look https://www.imore.com/how-use-voiceover-iphone-and-ipad
- [x] go to back to browser
- [x] two fingers right
- [x] verify you can lisen "Home" one or two in the nav menu

### CODE REVIEW

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1660

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1660 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1660 |
| Installation process | http://install.openy-dev.ffwua.com/build1660/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1660/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1660/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1670 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1670 |
| Installation process | http://install.openy-dev.ffwua.com/build1670/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1670/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1670

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1670/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1671 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1671 |
| Installation process | http://install.openy-dev.ffwua.com/build1671/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1671/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1671

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1671/profiles/contrib/openy/build/reports/behat

**Comment by ivan-berezhnov** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1675 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1675 |
| Installation process | http://install.openy-dev.ffwua.com/build1675/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1675/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1675

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1675/profiles/contrib/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1676 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1676 |
| Installation process | http://install.openy-dev.ffwua.com/build1676/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1676/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1676

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1676/profiles/contrib/openy/build/reports/behat

**Pull request merged**
