### PR TITLE
Schedules aligning

### PR DESCRIPTION
**Pull request by AleksandrPrykhodkoDev**
Steps for review:

Steps for review:

- [x]   turn on theme carnation
- [x]  visit page schedules
- [x]  schedules align in 1 line

Theme Carnation:
before
Снимок экрана 2019-12-18 в 16 33 25
after
Снимок экрана 2019-12-18 в 15 52 51

Theme Lily:
before 
Снимок экрана 2019-12-18 в 15 57 15
after
Снимок экрана 2019-12-18 в 15 57 25

Theme Rose:
before
Снимок экрана 2019-12-18 в 15 58 55
after
Снимок экрана 2019-12-18 в 15 59 05

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2013/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2013/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2013/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2013/

**Pull request merged**
