### PR TITLE
[OYPD-106] Configure main landing page without demo content.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-106
D.o https://www.drupal.org/node/2852216

- [x] Perform manual install
- [x] Uncheck Demo landing pages
  - image
- [x] Complete install & go to homepage
- [x] See start tutorial button link "Start guided tour" & text "This is default installation without demo content."

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build437

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/437/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build437/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build446

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/446/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build446/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
