### PR TITLE
Fix Location demo coordinates

### PR DESCRIPTION
**Pull request by yasik78**
Issue  Location demo coordinates #387 

## Steps for review

- [x]  Go to    /locations
- [x]  In listing we see 4 branches     On map we see  4

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by yasik78** [comment]
please test

**Comment by Sanchiz** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1598 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1598 |
| Installation process | http://install.openy-dev.ffwua.com/build1598/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1598/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1598/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
