### PR TITLE
[OYPD-250] Updating styles for facility sidebar

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Add a facility node and a branch node.
- [x] Associated it with a branch.
- [x] Check the display of the facility page.

screen shot 2017-02-16 at 2 49 26 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build487

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/487/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build487/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build488

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/488/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build488/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build491

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/491/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build491/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build492

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/492/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build492/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build493

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/493/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build493/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
