### PR TITLE
1543 fix svg logo

### LINKED ISSUE #1543: (Carnation) Update logo.svg
Update the themes logo.svg so we can apply the "fill" attribute on our path element when transitioning the navbar from a dark background to a light one, or vice versa.

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/1543

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [x] Log in as admin.
- [x] Go ti the appearance settings  page admin/appearance .
- [x] Set the Carnation theme as default.
- [x] Checks what path in **Path to custom logo**  is contain svg file as logo (for ex.:profiles/contrib/openy/themes/openy_themes/openy_carnation/logo.svg). If no, please set the path to svg file in theme. Save settings
- [x] Checks the main page. The logo should be displayed as inline SVG object.
- [x] You shold have ability to chnage colors of  logo via css (like on scrrenshoot)

CR-82-svgLogo

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2742/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2742/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2742/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2742/

**Comment by hamrant** [comment]
http://openy.cibox.tools/build2742/ - @aleevas logo looks not ok...

Screenshot from 2020-11-02 18-14-15

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by aleevas** [comment]
> http://openy.cibox.tools/build2742/ - @aleevas logo looks not ok...
> 
> Screenshot from 2020-11-02 18-14-15

@hamrant it should be fixed in this PR https://github.com/ymcatwincities/openy/pull/2272

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
