### PR TITLE
Add description and placeholder to Small banner

### PR DESCRIPTION
**Pull request by yasik78**
## Steps for review

- [x] login as admin
- [x] Go to /node/add/landing_page
- [x] Add paragraf block Small banner 
- [x] Check description for fields and compare with docs.  https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Content%20structure/Paragraphs/Small%20Banner.md

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by yasik78** [comment]
Pleace test this

**Comment by Sanchiz** [comment]
ok to test

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1525 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1525 |
| Installation process | http://install.openy-dev.ffwua.com/build1525/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1525/

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1532 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1532 |
| Installation process | http://install.openy-dev.ffwua.com/build1532/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1532/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1532/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
