### PR TITLE
[OYPD-110] Add facility type taxonomy migration to defaults

### PR DESCRIPTION
**Pull request by danylevskyi**
Task: OYPD-110

### How to review

1. Install the site
2. Make sure that facility type taxonomy is present

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build354

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/354/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build354/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build355

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/355/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build355/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
