### PR TITLE
Empty space at Programs page + styling of location filters on mobile

### LINKED ISSUE #1096: Improve Search filters on Locations page
URL: /locations

1) Openy sandbox has no search filters
image

ymcamn.org has filters. Which is useful. (Map is hidden but that's OK, because it could be too small.)
image

2) Also still may be there is an UX ability to add map on mobile too. In a way, that most of the map is taken by map. And only some place at the bottom by filters.

3) If some YMCA not having Camps and Facilities. But only few YMCAs - nice to hide checkbox "YMCAs".

### LINKED ISSUE #1879: Whitespace in Program Header
**[Carnation Theme]
[openy-8.x-2.3.5]**

-------

There is strange extra whitespace in the header of Program content type pages, with or without an image in the banner.  

image

This appears to be coming from the CSS on element `.layout-container`:

```
.without-banner .layout-container {
  padding-top: 140px;
}
```

I'm not sure why the body class of "without-banner" is being added to the program page, even when an image is present.  So in searching for that code, I found in openy_carnation.theme file:

```
if($node_type == 'program') {
    $variables['body_classes'][] = 'without-banner';
} elseif (in_array($node_type, [
        'class',
        'blog',
        'news',
        'camp',
        'event',
        'facility',
        'branch',
        'program_subcategory',
  ]) || (count($banner_paragraphs) > 0) || (count($any_paragraphs) == 0)) {
      $variables['body_classes'][] = 'with-banner';
  }
else {
    $variables['body_classes'][] = 'without-banner';
}
```

It looks to be assigning that class to all program pages.  Can we remove that logic, or maybe there was another purpose for this snippet?

### PR DESCRIPTION
**Pull request by anpolimus**
Fixes for:
https://github.com/ymcatwincities/openy/issues/1879
https://github.com/ymcatwincities/openy/issues/1096

## Steps for review

- [x] Open program page, expect that there are no whitespace for anonymous under menu.
- [x] Open Locations page at mobile. Expect that search and map are working.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by anpolimus** [comment]
retest me please

**Comment by anpolimus** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2092/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2092/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2092/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2092/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2092/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2092/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2092/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2093/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2093/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2093/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2093/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2093/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2093/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2093/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]
code looks good

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2092/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2093/

**Pull request merged**
