### PR TITLE
[OYPD-199] Fix images migration

### PR DESCRIPTION
**Pull request by danylevskyi**
Task: OYPD-199

### How to review

1. Go to `admin/content/media` and make sure that all media images are imported
2. Go to `/accelerator` and make sure it's working
3. Go to `/locations/downtown-ymca` and make sure it's working

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build362/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build362

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/362/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build362/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build363

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/363/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build363/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
