### PR TITLE
[OYPD-410] [#325] Mobile menu loads weird

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Drupal.org issue - https://www.drupal.org/node/2878479
Issue details here - #325

Steps for review:
- [x] go to frontpage or any another page
- [x] change your screen to mobile or tablet
- [x] click on icon menu in the top
- [x] verify icon menu and the menu loads with the animation is smooth in tablet and mobile

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1176 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1176 |
| Installation process | http://install.openy-dev.ffwua.com/build1176/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1176/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1176/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1192 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1192 |
| Installation process | http://install.openy-dev.ffwua.com/build1192/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1192/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1192/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1197 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1197 |
| Installation process | http://install.openy-dev.ffwua.com/build1197/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1197/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1197/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. It still stuck for a few seconds at the beginning. Just compare to how it works on Seattle http://seattleymca.org.

2 Can we have the same animation as on Seattle's website for hamburger menu?
image

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1248 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1248 |
| Installation process | http://install.openy-dev.ffwua.com/build1248/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1248/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1248/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
