### PR TITLE
[OYPD-529] Resolve problem with SubFormState in plugin selectors

### PR DESCRIPTION
**Pull request by alexschedrov**
## Steps for review

- [x] Open /admin/config/services/daxko
- [x] Specify credentials - [creds](https://propeople-us.atlassian.net/wiki/display/OYPD/Daxko+program+registration)
- [x] Open /admin/config/services/daxko/programs-search
- [x] Specify Daxko Client ID - [creds](https://propeople-us.atlassian.net/wiki/display/OYPD/Daxko+program+registration)
- [x] Create Landing Page /node/add/landing_page
- [x] Add "Program Registration (Daxko)" paragraph to "Content Area"
- [x] Add "Simple Content" paragraph to "Content Area"
- [x] Save node
- [x] Make sure you don't see fatal error `Fatal error: Call to a member function getFieldStorageDefinition() on string in /var/www/docroot/core/lib/Drupal/Core/Field/TypedData/FieldItemDataDefinition.php on line 66`

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1796 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1796 |
| Installation process | http://install.openy-dev.ffwua.com/build1796/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1796/

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1796

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1796

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1796/profiles/contrib/openy/build/reports/behat

**Pull request merged**
