### PR TITLE
[OPENY-277]: Avoid using custom packages with drupal-library type

### PR DESCRIPTION
**Pull request by afi13**
Added https://asset-packagist.org/ composer repo, custom repositories replaced with npm-asset packages.

Depends to https://github.com/ymcatwincities/openy-project/pull/50

## Steps for review

- [x] Install Open Y with composer.
- [x] Make sure blazy, dropzone, slick and jquery.easing installed to `docroot/libraries/{name}`.
- [x] Check Open Y for possible regressions related to these libraries.

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1489 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1489 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1489 |
| Installation process | http://install.openy.cibox.tools/build1489/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1489/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1489/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1489/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1489/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1489/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1489/blogWCAG2AAhtmlcs.txt

**Comment by hamrant** [comment]
retest this please

**Review by hamrant — APPROVED** [review]
Looks great!

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1493 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1493 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1493 |
| Installation process | http://install.openy.cibox.tools/build1493/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1493/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1493/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1493/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1493/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1493/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1493/blogWCAG2AAhtmlcs.txt

**Review by ddrozdik — APPROVED** [review]

**Comment by Sanchiz** [comment]
@afi13 keep in mind that we should do the same in https://github.com/ymcatwincities/openy-project/blob/8.1.x/composer.json#L38

**Review by podarok — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1496 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1496 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1496 |
| Installation process | http://install.openy.cibox.tools/build1496/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1496/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1498 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1498 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1498 |
| Installation process | http://install.openy.cibox.tools/build1498/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1498/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1498/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1498/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1498/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1498/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1498/blogWCAG2AAhtmlcs.txt

**Pull request merged**
