### PR TITLE
[OYPD-308] Upgrade path tools. Part 2

### PR DESCRIPTION
**Pull request by hamrant**
Previos PR - https://github.com/ymcatwincities/openy/pull/205
Jira - https://propeople-us.atlassian.net/browse/OYPD-308
d.org issue - https://www.drupal.org/node/2857614

**Steps for review:**
- [x] login as admin
- [x] go to /admin/structure/views/view/images_library
- [x] set "Use pager:Full"
- [x] save views
- [x] go to /admin/reports/dblog
- [x] check that you have warning message from openy_upgrade_tool
- [x] go to /devel/php (install this module if not exist)
- [x] execute
```
$config = drupal_get_path('module', 'openy_media_image') . '/config/install/views.view.images_library.yml';
$config_importer = \Drupal::service('openy_upgrade_tool.param_updater');
$config_importer->update($config, 'views.view.images_library', 'display.default.display_options.pager');
```
- [x] go to /admin/reports/dblog
- [x] check that you have error message from config_update with link to dashboard
- [x] go to /admin/config
- [x] check that "OpenY upgrade dashboard" exist in DEVELOPMENT section
- [x] go to /admin/config/development/openy-upgrade-dashboard
- [x] check that you have config views.view.images_library in list
- [x] Delete config from dashboard
- [x] go to /devel/php
- [x] run (it will update full file)
```
$config_dir = drupal_get_path('module', 'openy_media_image') . '/config/install';
$config_importer = \Drupal::service('openy_upgrade_tool.importer');
$config_importer->setDirectory($config_dir);
$config_importer->importConfigs(['views.view.images_library']);
```
- [x] go to /admin/structure/views/view/images_library
- [x] check that full views was reset to default state
- [x] set "Use pager:Full"
- [x] save views
- [x] go to /devel/php
- [x] run (it will update full file)
```
$config_dir = drupal_get_path('module', 'openy_media_image') . '/config/install';
$config_importer = \Drupal::service('openy_upgrade_tool.importer');
$config_importer->setDirectory($config_dir);
$config_importer->importConfigs(['views.view.images_library']);
```
- [x] go to /admin/reports/dblog
- [x] check that you have error message from config_update with link to dashboard
- [x] go to /admin/config/development/openy-upgrade-dashboard
- [x] check that you have config views.view.images_library in list with '-' param
- [x] profit

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build675 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build675 |
| Installation process | http://install.openy-dev.ffwua.com/build675/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/675/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build675/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build676 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build676 |
| Installation process | http://install.openy-dev.ffwua.com/build676/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/676/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build676/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Should it be from `openy_upgrade_tool` ?

image

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
