### PR TITLE
CodeSprint: test (Vasyl)

### PR DESCRIPTION
**Pull request by vasilyyaremchuk**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

### CODE REVIEW

**Comment by vasilyyaremchuk** [comment]
test this please

**Comment by vasilyyaremchuk** [comment]
retest this please

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by danylevskyi** [comment]
ok to test

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1413/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace@2
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5946339336244017541.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git9077602482291349382.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/490/merge^{commit} # timeout=10
 > git branch -a --contains e618de7f308c201a10162bbba409d01e3b78e1ea # timeout=10
 > git rev-parse remotes/origin/pr/490/merge^{commit} # timeout=10
Checking out Revision e618de7f308c201a10162bbba409d01e3b78e1ea (origin/pr/490/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e618de7f308c201a10162bbba409d01e3b78e1ea
First time build. Skipping changelog.
[workspace@2] $ /bin/sh -xe /tmp/hudson360814150418577493.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
/tmp/hudson360814150418577493.sh: 2: cd: can't cd to /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
Build step 'Execute shell' marked build as failure
Couldn't read comment file
java.io.FileNotFoundException: File '/var/lib/jenkins/jobs/PR_BUILDER/workspace@2/commentinfo.md' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:124)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by danylevskyi** [comment]
retest this please

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1415/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace@2
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git2978376824071107012.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/490/merge^{commit} # timeout=10
 > git branch -a --contains e618de7f308c201a10162bbba409d01e3b78e1ea # timeout=10
 > git rev-parse remotes/origin/pr/490/merge^{commit} # timeout=10
Checking out Revision e618de7f308c201a10162bbba409d01e3b78e1ea (origin/pr/490/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e618de7f308c201a10162bbba409d01e3b78e1ea
First time build. Skipping changelog.
[workspace@2] $ /bin/sh -xe /tmp/hudson2755501958496889781.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
/tmp/hudson2755501958496889781.sh: 2: cd: can't cd to /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
Build step 'Execute shell' marked build as failure
Couldn't read comment file
java.io.FileNotFoundException: File '/var/lib/jenkins/jobs/PR_BUILDER/workspace@2/commentinfo.md' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:124)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by danylevskyi** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1417/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git3124214084029395661.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git4946817316677500498.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/490/merge^{commit} # timeout=10
 > git branch -a --contains e618de7f308c201a10162bbba409d01e3b78e1ea # timeout=10
 > git rev-parse remotes/origin/pr/490/merge^{commit} # timeout=10
Checking out Revision e618de7f308c201a10162bbba409d01e3b78e1ea (origin/pr/490/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e618de7f308c201a10162bbba409d01e3b78e1ea
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson7270212403072329654.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
/tmp/hudson7270212403072329654.sh: 2: cd: can't cd to /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
Build step 'Execute shell' marked build as failure
```

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1418/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
GitHub pull request #490 of commit d9bb9db43c630b8e4740f8bd987bae7bc1a673f1 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git6283846678758841172.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/490/merge^{commit} # timeout=10
 > git branch -a --contains e618de7f308c201a10162bbba409d01e3b78e1ea # timeout=10
 > git rev-parse remotes/origin/pr/490/merge^{commit} # timeout=10
Checking out Revision e618de7f308c201a10162bbba409d01e3b78e1ea (origin/pr/490/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e618de7f308c201a10162bbba409d01e3b78e1ea
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson4011896228677192731.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace
+ cd ../vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory3414422949874422969.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1418 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local
ERROR: the playbook: /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml could not be found
FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1420 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1420 |
| Installation process | http://install.openy-dev.ffwua.com/build1420/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1420/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1420/profiles/contrib/openy/build/reports/behat

**Pull request closed without merging**
