### PR TITLE
[OYPD-144] Taxonomy creation tour

### PR DESCRIPTION
**Pull request by hamrant**
Jira - https://propeople-us.atlassian.net/browse/OYPD-144

Steps for review:
- [x] login as admin
- [x] go to /admin/structure/taxonomy?tour=1
- [x] check tour on /admin/structure/taxonomy, /admin/structure/taxonomy/manage/color/overview and /admin/structure/taxonomy/manage/color/add pages
- [x] tour steps check in task
- [x] profit

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build300

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/300/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build300/profiles/openy/build/reports/behat

**Comment by hamrant** [comment]
test this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build303

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/303/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build303/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Dependency on tour module should be added.
2. Text adjustment. Should be "taxonomy terms"
image

3. Placement - top.
image
image

4. Let's redirect here https://github.com/ymcatwincities/openy/pull/90/files#diff-f723127fe759b8e19a6e7d0185013476R62 to "/admin/content".

**Review by alexschedrov — CHANGES_REQUESTED** [review]
Fixes above are required.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build312

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/312/

**Review by alexschedrov — APPROVED** [review]

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build312/profiles/openy/build/reports/behat

**Pull request merged**
