### PR TITLE
Fix missing blocks for CLI installation

### PR DESCRIPTION
**Pull request by alexschedrov**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## Steps for review
JIRA: https://propeople-us.atlassian.net/browse/OYPD-458
drupal.org issue: https://www.drupal.org/node/2889298
- Open following pages and make sure you see rendered paragraphs instead of `This block is broken or missing. You may be missing content or you might need to enable the original module.`. You can compare with http://ci.openymca.org/demo
  - /join
  - /schedules
  - /programs/swimming/drop-swim
  - /programs/swimming/drop-swim/drop-swim/recreational-swim-3ft

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1795 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1795 |
| Installation process | http://install.openy-dev.ffwua.com/build1795/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1795/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1795

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1795

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1795/profiles/contrib/openy/build/reports/behat

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
