### PR TITLE
[OYPD-258] Rename color and add more color schemas.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-258
D.o https://www.drupal.org/node/2862921

Steps to review:
- [x] go to /admin/appearance/settings/openy_rose
- [x] See Color schema options
  - Blue sky (default)
  - Endeavor Blue
  - Vivid Violet
  - Bay Sunset
  - Purple Orchid

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build803 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build803 |
| Installation process | http://install.openy-dev.ffwua.com/build803/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/803/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build803/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build804 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build804 |
| Installation process | http://install.openy-dev.ffwua.com/build804/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/804/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build804/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build805 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build805 |
| Installation process | http://install.openy-dev.ffwua.com/build805/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/805/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build805/profiles/contrib/openy/build/reports/behat

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build810 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build810 |
| Installation process | http://install.openy-dev.ffwua.com/build810/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/810/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build810/profiles/contrib/openy/build/reports/behat

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
