### PR TITLE
Disable camp related tests to fix the sandbox

### PR DESCRIPTION
**Pull request by ygerasimov**
Avoid running tests that changes the homepage.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by podarok** [comment]
retest this please

**Review by podarok — APPROVED** [review]

**Pull request merged**
