### PR TITLE
[OYS-83] Fix openy_hours_formatter lib error in IE11

### PR DESCRIPTION
**Pull request by anprok**
Error with Luxon library from  openy_hours_formatter module in IE11.
When load branch page in Internet Explorer 11 this library causes error with message
`«Object doesn’t support property or method assign»`
And stops running other javascript scenarios on the page loaded.
Propose to replace Luxon library with Moment library that already widely used on Open Y project.

Backport for YGBW

## Steps for review

- [ ] open site in IE 11
- [ ]  visit page locations/downtown-ymca
- [ ] make sure no errors in console with message Object doesn't support property or method assign
- [ ] compare it with console errors appeared in http://sandbox.openy.org/locations/downtown-ymca (see screenshot with error)
image

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2069/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2069/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2069/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2069/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2069/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2069/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2069/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2069/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2069/

**Review by hamrant — APPROVED** [review]
@anprok code looks good, can you provide some screenshots from build with fix and without for comparing?

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
@anprok I appreciate you adding screenshots for the historical reference reasons.
Thank you

**Pull request merged**
