### PR TITLE
[8.x-1.x-exp-news] News demo data

### PR DESCRIPTION
**Pull request by dimb**
- demo content

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by ddrozdik** [comment]
retest this please

**Comment by ddrozdik** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2012 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2012 |
| Installation process | http://install.openy-dev.ffwua.com/build2012/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2012/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build2012

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2012/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2012/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2012/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2012/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2012/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2012/profiles/contrib/openy/build/reports/behat

**Comment by ddrozdik** [comment]
retest this please

**Comment by ddrozdik** [comment]
@dimb please add demo module to the installation step where we can select install demo content or not. 
See examples how to do this:
https://github.com/ymcatwincities/openy/blob/8.x-1.x/src/Form/ContentSelectForm.php#L26
https://github.com/ymcatwincities/openy/blob/8.x-1.x/openy.profile#L54

**Comment by ddrozdik** [comment]
I have checked, I see only 1 test news. 
would be great to have 5-10 news to test paragraphs with pagers.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2025 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2025 |
| Installation process | http://install.openy-dev.ffwua.com/build2025/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2025/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build2025

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2025/profiles/contrib/openy/build/reports/behat

**Pull request closed without merging**
