### PR TITLE
Denisbilchenko/1319

### PR DESCRIPTION
**Pull request by denisbilchenko**
Issue: https://github.com/ymcatwincities/openy/issues/1319
Added attribute v-cloak to elements with vuejs placeholders to hide them until vuejs complete render.

### CODE REVIEW

**Comment by kolesnikoff** [comment]
@podarok please review

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1048 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1048 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1048 |
| Installation process | http://install.openy.cibox.tools/build1048/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1048/

**Comment by AlexNetman** [comment]
retest this please

**Comment by ddrozdik** [comment]
retest this please

**Review by ddrozdik — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1054 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1054 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1054 |
| Installation process | http://install.openy.cibox.tools/build1054/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1054/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1058 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1058 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1058 |
| Installation process | http://install.openy.cibox.tools/build1058/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1058/

**Pull request merged**
