### PR TITLE
fixed an logical error in set default value for the Time Zone

### LINKED ISSUE #2344: In the openy hours formatter we always use hardcorded default values
Looks like we have some logical issue in [openy_hours_formatter.js](https://github.com/ymcatwincities/openy/blob/f06361f1f8b96aee9c1e60acc177e40cdcb70047/modules/custom/openy_hours_formatter/js/openy_hours_formatter.js#L53)

```
if (typeof drupalSettings.openy_hours_formatter != 'undefined') {

        drupalSettings.openy_hours_formatter = {};
}
```

And as result we always use default values that hardcorded in that file.
That's mean even if we use another timezone for the Open Y site, anyway for user we display works hours based on default "America/New York" timezone
todaysHoursBlock

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/2344 ( publicly available )

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Log as admin.
- [ ] Go to the **admin/config/regional/settings** page and change **Default time zone.** to **Los Angeles**
- [ ] Please change date to Sunday and time to evening of that day
- [ ] Go to the location page
- [ ] Check the **Todays hours** block. There is should be **Closed**

todaysGithub

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2903/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2903/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2903/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2903/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2904/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2904/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2904/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2904/

**Review by podarok — COMMENTED** [review]
Thank you

**Pull request merged**
