### PR TITLE
[OYPD-191] Adjusting responsive layout of teaser paragraph

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Add landing page.
- [x] Add teaser paragraph
- [x] Check responsive sizes, make sure there isn't a large gap between picture and text.

screen shot 2017-02-09 at 9 27 12 pm
screen shot 2017-02-09 at 9 27 06 pm
screen shot 2017-02-09 at 9 26 59 pm
screen shot 2017-02-09 at 9 26 47 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build414

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/414/

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build415

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/415/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build415/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
