### PR TITLE
[ROY-25] Fix half size image for Rose theme

### LINKED ISSUE #2292: Issue on Rose - half size image showing as full size
In the Rose theme, when you choose the half-size option, the image is showing as full size. This can be reviewed here: https://sandbox-rose-cus-dev.openy.org/imx-qa

### PR DESCRIPTION
**Pull request by shuklina**
Issue: https://github.com/ymcatwincities/openy/issues/2292

## Steps for review

- [x] Login as admin.
- [x] Create Landing Page and add 1 column paragraph.
- [x] Add image and choose `Half Without Blazy`
image
- [x] Save and make sure that the image, not full size.

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2853/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2853/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2853/

**Comment by podarok** [comment]
works great
image

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2853/

**Comment by podarok** [comment]
Tested on a fresh install too
image

**Pull request merged**
