### PR TITLE
OYPD-636 Removing programs from class filter if they are unpublished

### PR DESCRIPTION
**Pull request by david-hernandez**
Github issue: #913 

## Steps for review

- [x] Look at the options available for "Program" when visiting a program page with the class filter. Like /programs/child-care/after-school-child-care
- [x] Unpublish one of the programs, like "Swimming".
- [x] Go back to the filter and verify that Swimming is removed from the list of options.

### CODE REVIEW

**Comment by david-hernandez** [comment]
This surprisingly works fine with cache. If the form is holding the node context, which it should, it clears the cache for it when the node becomes unpublished.

There are better options but with the VERF module being the source, the alternative is hacking it.

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build252 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build252 |
| Installation process | http://install.openy-dev.ffwua.com/build252/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/252/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build252/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build252/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build252/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build252/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build252/blogWCAG2AAhtmlcs.txt

**Comment by AlexNetman** [comment]
**Case for programs:**
When I go to unpublish a program (example - Swimming)
Then I don't see that Program in the dropdown on subcategory page
But I still see subcategory "Swim Team"
And able to select classes that way


**Similar bug for Subcategory is reproduced**
When I unpublish a Subcategory (example: Swim Team)
Then I still see it in dropdown and able to select classes

**For activities**
When I see unpublished Activity node
Then I still see it in dropdown available for selection

This making issue #938 not fully fixed.

**Comment by gundevel** [comment]
Behat test results file URL http://ci.openymca.org/build252/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build252/profiles/contrib/openy/build/reports/behat/screenshots

**Comment by david-hernandez** [comment]
Are categories only matched to specific programs? This is where it gets annoying, because I'd have to go through each subcategory and match it to its parent program. (and doing this in the form alter which feels wrong, but is doable)

**Comment by david-hernandez** [comment]
This is why I asked when we talked about this a while ago, if unpublishing a program should unpublish all the subcategories under it. The answer was no, but I don't know why. I still don't understand why some of these are intended to stay published but not show in the filter. You would still be able to get to them by url or somewhere else.

**Comment by AlexNetman** [comment]
1) Yes, categories are matched to specific programs. 
2) I don't remember the fact that we agreed to not to unpublish subcategories after category is updated... I guess we were thinking that it's enough to update "Session Instance Entity" (they are here http://upgrade.openy-dev.ffwua.com/build252/admin/structure/session_instance)

Also only unpublishing of Subcategories will not resolve the whole issue. See my message above: 
`When I unpublish a Subcategory (example: Swim Team)
Then I still see it in dropdown and able to select classes`

**Comment by AlexNetman** [comment]
Best possible solution in the case is smart JS filters.  We are having this item in backlog for long time already.
Requirements were like this:
" When I select program Swimming
Then I should see only items related to swimming in Category dropdown
image

**Comment by david-hernandez** [comment]
If we unpublish the subcategories when the program is unpublished we can remove the subcategories easily from the filter. The same code can be used in the form alter.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build266 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build266 |
| Installation process | http://install.openy-dev.ffwua.com/build266/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/266/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build266/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build266/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build266/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build266/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build266/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL http://ci.openymca.org/build266/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build266/profiles/contrib/openy/build/reports/behat/screenshots

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
I can confirm that now unpublished nodes are not present in the list of filters. But as we discussed we need to adjust process of changing node status, to unpublish all nodes(program subcategories/activities/classes/sessions) associated with the unpublished parent. 
cc @AlexNetman

**Pull request merged**
