### PR TITLE
8.8drupal

### LINKED ISSUE #1838: Change custom code related to usr_alias table to get support for Drupal 8.8+ core
An initial branch is here https://github.com/ymcatwincities/openy/pull/1834

We have a code that does SQL query against the table which doesn't exist in 8.8 Drupal core https://www.drupal.org/project/drupal/releases/8.8.0 .

We must replace it with a new, based on the entity system. See change record https://www.drupal.org/node/3013865. 

We should use `path_alias` entity now.
Once this is resolved - we'll continue to work on getting ready for 8.8 core

### PR DESCRIPTION
**Pull request by retif**
this should fix #1838

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2002/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2002/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2002/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2002/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2002/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2002/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2002/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2002/

**Comment by podarok** [comment]
@retif Status page error 500 http://upgrade.openy.cibox.tools/build2002/admin/reports/status on upgrade path builder

**Comment by podarok** [comment]
credentials to the build https://github.com/ymcatwincities/openy-cibox-build/blob/master/devops/reinstall/vars/global_settings.yml#L3

**Comment by podarok** [comment]
```[Wed Jan 29 12:40:41.113702 2020] [php7:notice] [pid 2584] [client 178.54.63.218:50049] Uncaught PHP Exception Drupal\\Core\\Extension\\Exception\\UnknownExtensionException: "The module openy does not exist or is not installed." at /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build2002/openy-project/docroot/core/lib/Drupal/Core/Extension/ExtensionList.php line 346, referer: http://upgrade.openy.cibox.tools/build2002/user/1```
error in console

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2002/

**Comment by podarok** [comment]
@retif disregard status page error for upgrade path. Not related to this PR

**Pull request merged**
