### PR TITLE
Fix dependency string for OpenY Map.

### PR DESCRIPTION
**Pull request by danylevskyi**
I propose to use full dependency description.

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Review by ddrozdik — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build800 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build800 |
| Installation process | http://install.openy-dev.ffwua.com/build800/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/800/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build800/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build801 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build801 |
| Installation process | http://install.openy-dev.ffwua.com/build801/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/801/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build801/profiles/contrib/openy/build/reports/behat

**Pull request merged**
