### PR TITLE
Update grid column css with nth-child logic

### LINKED ISSUE #1533: Carnation theme - hardcoded color for grid columns
Carnation has hardcoded color rules for the grid columns. The logic is the following:
- 1st item - green
- 2nd item - yellow
- 3rd item - black title and green button
- Rest of the items - black title and green button
- Last item - red

image

### PR DESCRIPTION
**Pull request by froboy**
Original Issue, this PR is going to fix: #1533

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Edit the homepage
- [ ] Add more than 3 items in the Grid Content Paragraph
- [ ] Observe the colors alternate as they should.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3552/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3552/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3552/

**Comment by froboy** [comment]
The sass is ready here, but I ran into https://github.com/ymcatwincities/openy/issues/2577 and wasn't able to compile it.

**Comment by podarok** [comment]
@shelleygoetz @sarah-halby let's add to Jira Maintain board, please

**Comment by froboy** [comment]
Closing this. It's replaced by https://www.drupal.org/project/openy_carnation/issues/3254989.

**Pull request closed without merging**
