### PR TITLE
[YGBWSLA-80] Allow other modules to alter the activity finder process results.

### PR DESCRIPTION
**Pull request by hamrant**
On projects like YGBW and YGS, we have some customizations for session prices and availability statuses, so we need to display this in the same way on the Activity Finder schedule.
Let's add hook alter for the OpenyActivityFinderSolrBackend::processResults.

Example of my use case in custom hook:

```php
/**
 * Implements hook_activity_finder_program_process_results_alter().
 */
function ybw_activity_finder_activity_finder_program_process_results_alter(&$data, NodeInterface $entity) {
  // @see \Drupal\ygbw_class_page\ClassPageDataProvider
  $formatted_session = \Drupal::service('ygbw_class_page.data_provider')
    ->formatSessions([$entity], FALSE);
  $formatted_session = reset($formatted_session);

  // Fix pricing according to YGBW price customization.
  // @see themes/custom/ymca_seattle/templates/custom/class-page-other-sessions.html.twig
  $data['price'] = '';
  if (!empty($formatted_session['prices'])) {
    foreach ($formatted_session['prices'] as $price) {
      $data['price'] .= implode(' ', $price) . '<br>';
    }
  }

  // Fix availability and registration according to YGBW customization.
  // @see themes/custom/ymca_seattle/templates/custom/class-page-other-sessions.html.twig
  $link = Link::createFromRoute(t('View registration info for our next session.'), '<ygbw-reg-info>');
  $messages = [
    'begun' => t('This class has begun. <br> @link', [
      '@link' => $link->toString(),
    ]),
    'will_open' => t('Registration for this class opens shortly. Please check back. <br> @link', [
      '@link' => $link->toString(),
    ]),
    'inperson' => t('Online registration is closed. <br> Visit a YMCA branch to register.'),
    'included_in_membership' => t('Included in Membership'),
  ];

  if (isset($messages[$formatted_session['reg_state']])) {
    $data['availability_note'] = $messages[$formatted_session['reg_state']];
  }
}
```

The result on page:
Screenshot from 2019-07-23 17-41-01

### CODE REVIEW

**Comment by podarok** [comment]
@hamrant great stuff
Please, add your example to Readme of the module. And then I'lll merge it

**Comment by hamrant** [comment]
@podarok Done.

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1676 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1676 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1676 |
| Installation process | http://install.openy.cibox.tools/build1676/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1676/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1677 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1677 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1677 |
| Installation process | http://install.openy.cibox.tools/build1677/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1677/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1677/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1677/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1677/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1677/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1677/blogWCAG2AAhtmlcs.txt

**Pull request merged**
