### PR TITLE
[OYPD-523] Updating styles for input elements in chrome and the problme with focus

### PR DESCRIPTION
**Pull request by david-hernandez**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Check keyboard focus on checkbox and radio elements on chrome to make sure they get the green highlight color. See screenshots.

screen shot 2017-11-15 at 10 37 34 pm
screen shot 2017-11-15 at 10 36 54 pm
screen shot 2017-11-15 at 10 36 31 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2375 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2375 |
| Installation process | http://install.openy-dev.ffwua.com/build2375/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2375/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2375/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2375/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2375/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2375/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2375/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2375/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2377 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2377 |
| Installation process | http://install.openy-dev.ffwua.com/build2377/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2377/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2377/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2377/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2377/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2377/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2377/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2377/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Code looks good, @AlexNetman please test PR.

**Comment by AlexNetman** [comment]
Now post click effect appear only for those form elements.
So that when I click on checkbox - I see it highlighted with Green.
It looks acceptable.

**Comment by AlexNetman** [comment]
Also in IE those fields are not green.
image
Only checkboxes are green.
image
And as safari - we don't support safari in terms of tabbing at all.

**Comment by david-hernandez** [comment]
Was this the case before in IE? I didn't remove any styles, only added.

**Comment by david-hernandez** [comment]
Just checked. IE does not listen to any of the current focus styles in the current build. Should we merge this as fixing the one chrome issue and open a separate issue to go over all the IE problems?

**Comment by alexschedrov** [comment]
We can skip IE for now.

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
