### PR TITLE
[OYPD-187] PHP 7 and jquery_colorpicker

### PR DESCRIPTION
**Pull request by alexschedrov**
JIRA: https://propeople-us.atlassian.net/browse/OYPD-187

Steps for review:
- Login as admin
- Go to "/admin/structure/taxonomy/manage/color/add" and make sure you're seeing color widget.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build280

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/280/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build280/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build281

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/281/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build281/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build282

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/282/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build282/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build283

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/283/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build283/profiles/openy/build/reports/behat

**Review by podarok — APPROVED** [review]
Code looks good

**Review by hamrant — APPROVED** [review]

**Pull request merged**
