### PR TITLE
[OYPD-389] Add openy branches popup paragraphs.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-389
D.o https://www.drupal.org/node/2880752

Steps to review
- [x] Remove any preferred branch cookie

- [x] Add "Branches popup (All)" paragraph to a Landing page
- [x] Select location popup displays (should see all locations)

- [x] Add "Branches popup (All)" paragraph to a Program Subcategory page
- [x] At least one session, with a location, needs to be related to a class, related to an activity, related to this program subcategory.
- [x] Select location popup displays (should see related locations)

- [x] Add "Branches popup (Class)" paragraph to a Class
- [x] At least two sessions needs to be related to this class with at least two different locations.
- [x] Select location popup displays (should see related locations)

- [x] New test features scenarios all pass.

- [x] See demo "Branches popup (Class)" on all demo class pages.
- [x] See demo "Branches popup (All)" on all demo program subcategory pages.
- [x] See demo "Branches popup (All)" on demo schedules landing page.

- [x] "Branches popup (Class)" on class page with class sessions paragraph & class location paragraph will operate as expected.
- [x] Class location paragraph change link will appear when the "Branches popup (Class)" is on the page & the class is associated with at least 2 locations.
  - [x] When the class location change link is clicked the "Branches popup (Class)" popup opens.

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1250 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1250 |
| Installation process | http://install.openy-dev.ffwua.com/build1250/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1250/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1250/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1251 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1251 |
| Installation process | http://install.openy-dev.ffwua.com/build1251/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1251/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1251/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1256 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1256 |
| Installation process | http://install.openy-dev.ffwua.com/build1256/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1256/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1256/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Please add "Branches popup (All)" to the "Schedules" page and all "Program Subcategory" pages
2. Please add "Branches popup (Class)" to all Classes in demo content
3. When location is selected on Class page, page is not reloaded with `?location=%` in URL.

Other things that are related to logic will be added as separate ticket.

**Comment by Kerby70** [comment]
Will do.

* To be clear 1 & 2 were specifically named in the follow on tickets assigned to me https://propeople-us.atlassian.net/browse/OYPD-390 https://propeople-us.atlassian.net/browse/OYPD-391 & https://propeople-us.atlassian.net/browse/OYPD-392.
* I found the cause for 3 while working on https://propeople-us.atlassian.net/browse/OYPD-392.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1262 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1262 |
| Installation process | http://install.openy-dev.ffwua.com/build1262/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1262/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1262/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1265 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1265 |
| Installation process | http://install.openy-dev.ffwua.com/build1265/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1265/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1265/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1267 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1267 |
| Installation process | http://install.openy-dev.ffwua.com/build1267/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1267/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1267/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
