### PR TITLE
Delete forced logic that adds btn-primary class

### PR DESCRIPTION
**Pull request by anpolimus**
Hi, @podarok.
I know that this pr might produce some regression issues, but it is very weird logic when we set `btn-primary` class everywhere
FE engineers that cant work with theme file have to fight with windwheels trying to override color of the button.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3301/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3301/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3301/

**Comment by podarok** [comment]
@sarah-halby @KylieAldridge this is for discussion
Due to it could lead to a bunch of regressions on all themes.
I'm ok with improving FE Dev Experience, but we should do a visual regression testing

**Comment by podarok** [comment]
@hamrant ^^^

**Comment by anpolimus** [comment]
@podarok this fix affects Carnation only.

**Comment by anpolimus** [comment]
I've faced this issue at the old Membership calculator form.
We have `btn-primary-outline` class there, added through form array.
It cold affect all places at the frontend that render button using Drupal form api. There are a few places where it could happen.
- Old membership calculator
- Exposed filters for views.
- User login form

**Comment by sarah-halby** [comment]
@podarok agreed - I don't mind going after this for a future point release. With code freeze starting tomorrow, I don't want to rush through this given the volume of work Anastasiia has for VY & Open Y over the next two weeks. @anpolimus - this is not a launch blocker for your clients, correct?

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
This is done in decoupled theme

**Pull request closed without merging**
