### PR TITLE
[OYPD-260] Taxonomy pathauto patterns; for Area, and Facility Type.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-260
D.o https://www.drupal.org/node/2854296

Steps to review:
For Area
- [x] Go to /admin/structure/taxonomy/manage/area/overview
- [x] See listed terms url's follow the required patter /area/[term:name]
For Facility Type
- [x] Go to /admin/structure/taxonomy/manage/facility_type/overview
- [x] See listed terms url's follow the required patter /facility-type/[term:name]

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build528

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/528/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build528/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build532

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/532/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build532/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
