### PR TITLE
9.x 2.x alerts fix

### PR DESCRIPTION
**Pull request by podarok**
Backport from 8.x branch #2336

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2894/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2894/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2894/

**Comment by podarok** [comment]
image

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2894/

**Pull request merged**
