### PR TITLE
[OYS-31] Carnation mobile menu Accessibility Issue

### PR DESCRIPTION
**Pull request by AndreyMaximov**
Original Issue, this PR is going to fix the Open Y Carnation theme Accessibility issue.

Actual Results
> Screen reader users see both the mobile and desktop headers on all pages.

Expected Results
> Only one header should be detected by a screen reader at any time, depending on the screen size or device being used. The second header version should be hidden for screen reader users just as it is visually.

## Steps for review

Verify there is no regression:
- [ ] Login as admin
- [ ] Install Carnation theme and set it a default theme
- [ ] Resize the browser so that the header is switched to mobile layout
- [ ] Verify you can open, close and use the mobile menu in general
- [ ] Tab through the page content
- [ ] Verify you can navigate through the page content, open/close mobile menu using the tab key, navigate through the mobile menu

The steps to review the fix:
- [ ] Switch back to the desktop layout by resizing the browser viewport
- [ ] Verify the mobile menu contents (menu links, the search field, etc.) is not tabbable

Extended steps to review the fix:
- [ ] Install the ChromeVox plugin or use other screen readers
- [ ] Verify the change using it.

### CODE REVIEW

**Review by podarok — DISMISSED** [review]
code looks good

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1918/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1918/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1918/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1918/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1918/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1918/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1918/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1918/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build1918/

**Comment by AndreyMaximov** [comment]
@konservax please take a look at the issue and verify the fix works

**Review by hamrant — DISMISSED** [review]

**Comment by podarok** [comment]
@hamrant @AndreyMaximov let's fix conflict and I'd like this to have in today's release

**Comment by AndreyMaximov** [comment]
@podarok it's been **rebased**

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1923/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1923/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1923/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1923/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1923/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1923/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1923/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1923/

**Pull request merged**
