### PR TITLE
[OPENY-83] Social post CT decoupling

### PR DESCRIPTION
**Pull request by anprok**
## Steps for review

- [x] login as admin
- [x] go to admin/content?title=&type=social_post&status=All&langcode=All
- [x] Check that some Social post nodes exist in this list
- [x] go to /admin/modules/uninstall
- [x] uninstall "OpenY Demo Node Social Post" module
- [x] uninstall "OpenY Node - Social Post" module
- [x] go to /admin/structure/paragraphs_type
- [x] check that Social list paragraph not exist in this list
- [x] return to admin/content?title=&type=social_post&status=All&langcode=All
- [x] check that Social post nodes was removed
- [x] go to /admin/structure/types
- [x] check that "Social post" not exist in this list
- [x] go to /admin/modules
- [x] install "OpenY Node - Social Post" module
- [x] check that all components related to "OpenY Node - Social Post" module was restored

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build623 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build623 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build623 |
| Installation process | http://install.openy.cibox.tools/build623/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/623/

**Comment by ddrozdik** [comment]
@podarok merged, since this pr is simple.

**Pull request merged**
