### PR TITLE
Fix images path for import.

### PR DESCRIPTION
**Pull request by ygerasimov**
Steps to review:
- [ ] install the site and open Media files admin/content/media
- [ ] ensure that all files got displayed and there is no missing ones

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build607 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build607 |
| Installation process | http://install.openy-dev.ffwua.com/build607/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/607/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build607/profiles/openy/build/reports/behat

**Comment by AlexNetman** [comment]
Now images are missed on Drush make installation:
Fresh OpenY installation	http://openy-dev.ffwua.com/build607
Upgraded(upgrade path) installation	http://upgrade.openy-dev.ffwua.com/build607

On most probably they will be missed on Simpletest.me . 

@Sanchiz 
Can we unify placement of OpenY profile for Composer and Drush-Make installations?
So that we don't face this problem with images and so on.

Note - few behat tests are failed on the step where image is verified. So we did them in right manner, so that they Can detect missing images. :)

**Comment by alexschedrov** [comment]
@ygerasimov in there's a way to define relative path for images instead of absolute?

**Pull request merged**
