### PR TITLE
[OYPD-168] Remove corrupted migrations

### PR DESCRIPTION
**Pull request by danylevskyi**
Task: OYPD-168

### How to review

Make sure that the next pages can be edited and saved:
 - `/openy`
 - `/blog`

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build368

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/368/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build368/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build369

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/369/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build369/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build370

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/370/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build370/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build371

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/371/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build371/profiles/openy/build/reports/behat

**Pull request merged**
