### PR TITLE
[INOYI-31] - added processing the '<front>' token for the 'alert_visibility_pages' field

### LINKED ISSUE #2129: Alerts "Visibility Pages" field does not work for <front> path
When I add <front> to the Visibility Pages field I expect that alert will be displayed only on the homepage. But at the moment it does now work. 
image

Also, I noticed that the description field does not render the needed token \<front>
image

while if I open the content type field configuration I see it there 

image

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: [#2129](https://github.com/ymcatwincities/openy/issues/2129) ( publicly available )

Now we should have an ability to put the "**\<front\>**" token to the 'alert_visibility_pages' field.
INOYI-31visibilityPages

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Log as admin.
- [ ] Go to the edit node CT Alert or to create a new one.
- [ ] Specify pages by using their paths. Enter one path per line in the  **Visibility pages->Pages** field. Please use the "**\<front\>**" as one of varinats.
- [ ] Save node.
- [ ] Go to the home page, you should see this alert banner. If you remove the "**\<front\>**"  from the **Visibility pages->Pages** field, you shouldn't see this banner on home page.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by podarok — APPROVED** [review]
code looks good

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2760/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2760/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2760/

**Pull request merged**
