### PR TITLE
Fix description in the module openy_node_activity

### PR DESCRIPTION
**Pull request by anprok**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [x] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

D.org issue https://www.drupal.org/node/2885223

## Steps for review

- [x] Open openY
- [x] Login as admin
- [x] Go to _/node/add/activity_
- [x] Check Program Subcategory field description

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1443/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #513 of commit ccefe178a0915037aef349d042869b954c2d78b9 automatically merged.
GitHub pull request #513 of commit ccefe178a0915037aef349d042869b954c2d78b9 automatically merged.
GitHub pull request #513 of commit ccefe178a0915037aef349d042869b954c2d78b9 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace@2
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git1322693552172612727.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5547327130992063277.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/513/merge^{commit} # timeout=10
 > git branch -a --contains 999107d223653120d824d0470e0edf8b45a18aa0 # timeout=10
 > git rev-parse remotes/origin/pr/513/merge^{commit} # timeout=10
Checking out Revision 999107d223653120d824d0470e0edf8b45a18aa0 (origin/pr/513/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 999107d223653120d824d0470e0edf8b45a18aa0
First time build. Skipping changelog.
[workspace@2] $ /bin/sh -xe /tmp/hudson7290485925024931866.sh
+ rm -Rf /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
+ cp -R ../vm /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
+ git pull
Already up-to-date.
[workspace@2] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory65420427946033248.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace@2 -e build_number=1443 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace@2/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
failed: [localhost] => {"changed": true, "cmd": "cp -R /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm/docroot/ /var/www/build1443", "delta": "0:00:00.835549", "end": "2017-06-11 11:20:45.913670", "rc": 1, "start": "2017-06-11 11:20:45.078121", "warnings": []}
stderr: cp: cannot create directory ‘/var/www/build1443/core/modules/rdf/tests/src/Unit’: No space left on device
cp: error writing ‘/var/www/build1443/core/modules/rdf/rdf.info.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/modules/rdf/rdf.info.yml’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/rdf/config’: No space left on device
cp: error writing ‘/var/www/build1443/core/modules/rdf/rdf.api.php’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/modules/rdf/rdf.api.php’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/rdf/src’: No space left on device
cp: error writing ‘/var/www/build1443/core/modules/rdf/rdf.module’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/modules/rdf/rdf.module’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/inline_form_errors’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/migrate’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/color’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/field’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/views’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/views_ui’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/dblog’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/config’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/book’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/tour’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/datetime’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/block_content’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/shortcut’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/image’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/dynamic_page_cache’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/user’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/text’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/block_place’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/serialization’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/tracker’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/contextual’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/update’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/automated_cron’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/taxonomy’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/responsive_image’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/system’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/menu_ui’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/modules/statistics’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/tests’: No space left on device
cp: error writing ‘/var/www/build1443/core/composer.json’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/composer.json’: No space left on device
cp: error writing ‘/var/www/build1443/core/INSTALL.mysql.txt’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/INSTALL.mysql.txt’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/profiles’: No space left on device
cp: error writing ‘/var/www/build1443/core/phpunit.xml.dist’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/phpunit.xml.dist’: No space left on device
cp: error writing ‘/var/www/build1443/core/CHANGELOG.txt’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/CHANGELOG.txt’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/scripts’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/config’: No space left on device
cp: error writing ‘/var/www/build1443/core/globals.api.php’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/globals.api.php’: No space left on device
cp: error writing ‘/var/www/build1443/core/core.services.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/core.services.yml’: No space left on device
cp: error writing ‘/var/www/build1443/core/.eslintrc.json’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/.eslintrc.json’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/lib’: No space left on device
cp: error writing ‘/var/www/build1443/core/phpcs.xml.dist’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/phpcs.xml.dist’: No space left on device
cp: error writing ‘/var/www/build1443/core/authorize.php’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/authorize.php’: No space left on device
cp: error writing ‘/var/www/build1443/core/INSTALL.pgsql.txt’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/INSTALL.pgsql.txt’: No space left on device
cp: error writing ‘/var/www/build1443/core/core.link_relation_types.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/core.link_relation_types.yml’: No space left on device
cp: error writing ‘/var/www/build1443/core/.eslintignore’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/.eslintignore’: No space left on device
cp: cannot create directory ‘/var/www/build1443/core/themes’: No space left on device
cp: error writing ‘/var/www/build1443/core/core.libraries.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/core/core.libraries.yml’: No space left on device
cp: error writing ‘/var/www/build1443/LICENSE.txt’: No space left on device
cp: failed to extend ‘/var/www/build1443/LICENSE.txt’: No space left on device
cp: error writing ‘/var/www/build1443/reinstall.sh’: No space left on device
cp: failed to extend ‘/var/www/build1443/reinstall.sh’: No space left on device
cp: cannot create directory ‘/var/www/build1443/devops’: No space left on device
cp: error writing ‘/var/www/build1443/.htaccess’: No space left on device
cp: failed to extend ‘/var/www/build1443/.htaccess’: No space left on device
cp: error writing ‘/var/www/build1443/codestyleautofix.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/codestyleautofix.yml’: No space left on device
cp: cannot create directory ‘/var/www/build1443/modules’: No space left on device
cp: error writing ‘/var/www/build1443/.editorconfig’: No space left on device
cp: failed to extend ‘/var/www/build1443/.editorconfig’: No space left on device
cp: error writing ‘/var/www/build1443/.gitattributes’: No space left on device
cp: failed to extend ‘/var/www/build1443/.gitattributes’: No space left on device
cp: error writing ‘/var/www/build1443/config_clean.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/config_clean.yml’: No space left on device
cp: error writing ‘/var/www/build1443/README.windows.md’: No space left on device
cp: failed to extend ‘/var/www/build1443/README.windows.md’: No space left on device
cp: error writing ‘/var/www/build1443/.csslintrc’: No space left on device
cp: failed to extend ‘/var/www/build1443/.csslintrc’: No space left on device
cp: error writing ‘/var/www/build1443/composer.json’: No space left on device
cp: failed to extend ‘/var/www/build1443/composer.json’: No space left on device
cp: cannot create directory ‘/var/www/build1443/profiles’: No space left on device
cp: error writing ‘/var/www/build1443/runsniffers.sh’: No space left on device
cp: failed to extend ‘/var/www/build1443/runsniffers.sh’: No space left on device
cp: error writing ‘/var/www/build1443/README.txt’: No space left on device
cp: failed to extend ‘/var/www/build1443/README.txt’: No space left on device
cp: error writing ‘/var/www/build1443/reinstall.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/reinstall.yml’: No space left on device
cp: cannot create directory ‘/var/www/build1443/vendor’: No space left on device
cp: error writing ‘/var/www/build1443/.eslintrc.json’: No space left on device
cp: failed to extend ‘/var/www/build1443/.eslintrc.json’: No space left on device
cp: cannot create directory ‘/var/www/build1443/sites’: No space left on device
cp: error writing ‘/var/www/build1443/reinstall_upgrade.sh’: No space left on device
cp: failed to extend ‘/var/www/build1443/reinstall_upgrade.sh’: No space left on device
cp: error writing ‘/var/www/build1443/rundevops.sh’: No space left on device
cp: failed to extend ‘/var/www/build1443/rundevops.sh’: No space left on device
cp: error writing ‘/var/www/build1443/autoload.php’: No space left on device
cp: failed to extend ‘/var/www/build1443/autoload.php’: No space left on device
cp: error writing ‘/var/www/build1443/.eslintignore’: No space left on device
cp: failed to extend ‘/var/www/build1443/.eslintignore’: No space left on device
cp: cannot create directory ‘/var/www/build1443/themes’: No space left on device
cp: error writing ‘/var/www/build1443/.gitignore’: No space left on device
cp: failed to extend ‘/var/www/build1443/.gitignore’: No space left on device
cp: error writing ‘/var/www/build1443/config_clean.sh’: No space left on device
cp: failed to extend ‘/var/www/build1443/config_clean.sh’: No space left on device
cp: error writing ‘/var/www/build1443/web.config’: No space left on device
cp: failed to extend ‘/var/www/build1443/web.config’: No space left on device
cp: error writing ‘/var/www/build1443/README.reinstall.md’: No space left on device
cp: failed to extend ‘/var/www/build1443/README.reinstall.md’: No space left on device
cp: error writing ‘/var/www/build1443/scss-lint.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/scss-lint.yml’: No space left on device
cp: error writing ‘/var/www/build1443/sniffers.yml’: No space left on device
cp: failed to extend ‘/var/www/build1443/sniffers.yml’: No space left on device

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/deploy_code.retry

localhost                  : ok=3    changed=1    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by anprok** [comment]
retest this please

**Comment by anprok** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1444/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #513 of commit ccefe178a0915037aef349d042869b954c2d78b9 automatically merged.
GitHub pull request #513 of commit ccefe178a0915037aef349d042869b954c2d78b9 automatically merged.
GitHub pull request #513 of commit ccefe178a0915037aef349d042869b954c2d78b9 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7368663302088626804.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git8443490844130650770.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/513/merge^{commit} # timeout=10
 > git branch -a --contains 999107d223653120d824d0470e0edf8b45a18aa0 # timeout=10
 > git rev-parse remotes/origin/pr/513/merge^{commit} # timeout=10
Checking out Revision 999107d223653120d824d0470e0edf8b45a18aa0 (origin/pr/513/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 999107d223653120d824d0470e0edf8b45a18aa0
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson3937794486049636554.sh
+ rm -Rf /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ cp -R ../vm /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory8586358924721467381.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1444 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory2326859398437030990.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1444 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1444/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1444 -e drupal_folder=/var/www/build1444 -e site_url=http://openy-dev.ffwua.com/build1444 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
ok: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [localhost] => (item={'status': True, 'name': '$config["system.file"]["path.temporary"]', 'value': '/tmp'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
skipping: [localhost]

TASK: [Creating drupal database] ********************************************** 
skipping: [localhost]

TASK: [Downloading latest backup to local environment] ************************ 
skipping: [localhost]

TASK: [Removing possible abandoned dump] ************************************** 
skipping: [localhost]

TASK: [Importing from remote backup] ****************************************** 
skipping: [localhost]

TASK: [Copy latest backup to build folder] ************************************ 
skipping: [localhost]

TASK: [Importing from local backup] ******************************************* 
skipping: [localhost]

TASK: [Remove local backup from build folder] ********************************* 
skipping: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
skipping: [localhost]

TASK: [Clear Drupal cache] **************************************************** 
skipping: [localhost]

TASK: [Updating database] ***************************************************** 
skipping: [localhost]

TASK: [Apply pending entity schema updates] *********************************** 
skipping: [localhost]

TASK: [Download stage file proxy] ********************************************* 
skipping: [localhost]

TASK: [Enable stage file proxy] *********************************************** 
skipping: [localhost]

TASK: [Set configuration for stage file proxy] ******************************** 
skipping: [localhost]

TASK: [Set folder for stage file proxy] *************************************** 
skipping: [localhost]

TASK: [Updates listing] ******************************************************* 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
failed: [localhost] => {"failed": true}
msg: unable to connect, check login credentials (login_user, and login_password, which can be defined in ~/.my.cnf), check that mysql socket exists and mysql server is running

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=10   changed=3    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by anprok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1445 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1445 |
| Installation process | http://install.openy-dev.ffwua.com/build1445/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1445/

**Review by ddrozdik — APPROVED** [review]

**Pull request merged**
