### PR TITLE
[OYPD-526] Adding text decoration underline to blog teaser links

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Verify underline when hovering on blog teaser title text.
- [x] Verify there is no underline for the category text when hovering on the title.
- [x] Verify only the category text is underline when hovering on the category text.
- [x] Verify related content info on a blog page gets underline when hovering on the text.

screen shot 2017-07-07 at 4 02 28 pm
screen shot 2017-07-07 at 4 02 45 pm
screen shot 2017-07-07 at 4 02 57 pm

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1829 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1829 |
| Installation process | http://install.openy-dev.ffwua.com/build1829/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1829/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1829

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1829/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1829/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1829/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1829/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1829/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1829/profiles/contrib/openy/build/reports/behat

**Review by Kerby70 — APPROVED** [review]

**Pull request merged**
