### PR TITLE
[OYPD-161] Behat tests: blog, camp, facility, program, subcategory CTs

### PR DESCRIPTION
**Pull request by AlexNetman**

### CODE REVIEW

**Review by alexschedrov — CHANGES_REQUESTED** [review]
Changes are required.

**Comment by Sanchiz** [comment]
retest this please

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build251

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/251/

**Pull request closed without merging**
