### PR TITLE
[MAINTAIN-33] fixed icons for paragraph grid columns for Carnation theme

### LINKED ISSUE #2443: [Carnation] Icons no longer appearing in Grid Content Paragraph
Steps to Recreate:

1) In Carnation theme, add a Grid Content paragraph to any page
2) Add an icon class in the "Icon Class" field (any free FontAwesome icon class should do)
3) Save the page.

The icon does not show.  It does not print out in the code under `div.inner > span.d-block`.  I've just noticed this after updating one of our Y sites to Open Y (openy-8.x-2.7.3).  However, it behaves the same on the D8 & D9 sandbox sites.

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/2443

This one should fix issue with not displaying icons for Grid Columns Paragraph in Carnation theme.

How it looks:
With icons class only:
MAINTAIN-33GridColumnsWithIconsClassBackEnd
MAINTAIN-33GridColumnsWithIconsClass

With image and icons class:
MAINTAIN-33GridColumnsWithIconsWithImage

## Steps for review

- [ ] go to the edit landing page.
- [ ] in content area plase add **Grid Content** paragraph
- [ ] please fill the **Icon Class** field (bookmark, thumbs-up etc.)
- [ ] save node
- [ ] verify that you can see icons under column's header

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by hamrant** [comment]
@aleevas the code looks ok for me. I see that on this screenshot the picture is stretched:

MAINTAIN-33GridColumnsWithIconsWithImage 

Can we fix this in the current PR?

cc @podarok

**Review by hamrant — APPROVED** [review]

**Comment by aleevas** [comment]
> @aleevas the code looks ok for me. I see that on this screenshot the picture is stretched:
> ...
> Can we fix this in the current PR?

@hamrant I've made a new commit with fix for your notice
MAINTAIN-33ImageFixed
cc @podarok

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3192/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3192/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3192/

**Comment by hamrant** [comment]
Tested on http://upgrade.openy.cibox.tools/build3192/test - works as expected

**Pull request merged**
