### PR TITLE
[OYPD-378] Theme setting color support changes for pink and purple

### PR DESCRIPTION
**Pull request by david-hernandez**
Added color support for two new settings, primary highlight and secondary highlight. Primary is everything purple, secondary is everything pink. I also changed items in the theme that were magenta to be either pink or purple to consolidate colors down to just the two.

- [x] Pull changes
- [x] Change primary and secondary highlight colors
- [x] Check colors throughout the site.

screen shot 2017-04-15 at 8 32 24 pm
screen shot 2017-04-15 at 8 25 47 pm
screen shot 2017-04-15 at 8 25 25 pm

I did notice one or two things that won't change. For example, the open quote icon that is in some teasers. This is a background image. Its color can be changed with CSS.

### CODE REVIEW

**Comment by david-hernandez** [comment]
In this PR I also changed the branch teaser border color to grey, like the other borders. We agree to this, to reduce the number of colors.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build954 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build954 |
| Installation process | http://install.openy-dev.ffwua.com/build954/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/954/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build954/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Code looks good.

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build964 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build964 |
| Installation process | http://install.openy-dev.ffwua.com/build964/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/964/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build964/profiles/contrib/openy/build/reports/behat

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build975 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build975 |
| Installation process | http://install.openy-dev.ffwua.com/build975/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/975/

**Comment by AlexNetman** [comment]
image

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build975/profiles/contrib/openy/build/reports/behat

**Comment by david-hernandez** [comment]
@AlexNetman That is what I referring to in my original comment. The quote graphic there is a background image. The color can't be changed with CSS. The graphic would have to be implemented differently, but I'd rather not tackle that here. If we want to make that change can we do it in a follow up?

**Pull request merged**
