### PR TITLE
[RGTC-796][Backport][AF] Add container for Locations step

### PR DESCRIPTION
**Pull request by shuklina**
Issue: https://github.com/ymcatwincities/ymca/issues/4456

### How to review:
- [ ]  Make sure that there is the indent left and right for the Location step.
image

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
This is tested on YGTC, merging

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2009/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2009/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2009/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2009/

**Pull request merged**
