### PR TITLE
PEF: performance enhancement. Load classes selectively.

### PR DESCRIPTION
**Pull request by ygerasimov**
There was a problem on YMCA Brandywine with loading data for all their classes (more than 30k records). After loading them selectively performance issue was resolved.

### CODE REVIEW

**Review by podarok — APPROVED** [review]
Code looks good

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build831 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build831 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build831 |
| Installation process | http://install.openy.cibox.tools/build831/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/831/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build831/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build831/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build831/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build831/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build831/blogWCAG2AAhtmlcs.txt

**Review by alexschedrov — APPROVED** [review]
Approved. Works good on Brandywine.

**Review by podarok — APPROVED** [review]

**Pull request merged**
