### PR TITLE
[OYPD-404] Enable openy_node_alert after openy_rose theme is enabled to place blocks.

### PR DESCRIPTION
**Pull request by Kerby70**
Blocked by #342 will need to rebase after that is merged, to get built to complete.

Jira https://propeople-us.atlassian.net/browse/OYPD-404
D.o https://www.drupal.org/node/2876736

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1122/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #343 of commit 1337b79aa4bb7b40955f0366684b5128d1755086 automatically merged.
GitHub pull request #343 of commit 1337b79aa4bb7b40955f0366684b5128d1755086 automatically merged.
GitHub pull request #343 of commit 1337b79aa4bb7b40955f0366684b5128d1755086 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git148535172721199088.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git1932499339862948354.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/343/merge^{commit} # timeout=10
 > git branch -a --contains 51f6feb8b8102ae43cfe3f6febd1d269b3b8c6c6 # timeout=10
 > git rev-parse remotes/origin/pr/343/merge^{commit} # timeout=10
Checking out Revision 51f6feb8b8102ae43cfe3f6febd1d269b3b8c6c6 (origin/pr/343/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 51f6feb8b8102ae43cfe3f6febd1d269b3b8c6c6
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson3508247463129824707.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory7104339065537888389.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1122 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory2612500362336672448.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1122 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1122/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1122 -e drupal_folder=/var/www/build1122 -e site_url=http://openy-dev.ffwua.com/build1122 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
ok: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [localhost] => (item={'status': True, 'name': '$config["system.file"]["path.temporary"]', 'value': '/tmp'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
skipping: [localhost]

TASK: [Creating drupal database] ********************************************** 
skipping: [localhost]

TASK: [Downloading latest backup to local environment] ************************ 
skipping: [localhost]

TASK: [Removing possible abandoned dump] ************************************** 
skipping: [localhost]

TASK: [Importing from remote backup] ****************************************** 
skipping: [localhost]

TASK: [Copy latest backup to build folder] ************************************ 
skipping: [localhost]

TASK: [Importing from local backup] ******************************************* 
skipping: [localhost]

TASK: [Remove local backup from build folder] ********************************* 
skipping: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
skipping: [localhost]

TASK: [Clear Drupal cache] **************************************************** 
skipping: [localhost]

TASK: [Updating database] ***************************************************** 
skipping: [localhost]

TASK: [Apply pending entity schema updates] *********************************** 
skipping: [localhost]

TASK: [Download stage file proxy] ********************************************* 
skipping: [localhost]

TASK: [Enable stage file proxy] *********************************************** 
skipping: [localhost]

TASK: [Set configuration for stage file proxy] ******************************** 
skipping: [localhost]

TASK: [Set folder for stage file proxy] *************************************** 
skipping: [localhost]

TASK: [Updates listing] ******************************************************* 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
ok: [localhost]

TASK: [Creating drupal database] ********************************************** 
changed: [localhost]

TASK: [Remove settings.php] *************************************************** 
ok: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
failed: [localhost] => {"changed": true, "cmd": "cd profiles/contrib/openy && APP_ENV=dev drush make drupal-org.make -y --no-core --no-cache", "delta": "0:00:32.882907", "end": "2017-05-08 20:01:39.381338", "rc": 1, "start": "2017-05-08 20:01:06.498431", "warnings": []}
stderr: Beginning to build drupal-org.make.                                  [ok]
features-8.x-3.5 downloaded.                                         [ok]
config_update-8.x-1.3 downloaded.                                    [ok]
entity-8.x-1.0-alpha4 downloaded.                                    [ok]
datalayer-8.x-1.x-dev downloaded.                                    [ok]
datalayer patched with                                               [ok]
2857270-4-fix-entity-reference-field-using-name-property.patch.
Generated PATCHES.txt file for datalayer                             [ok]
media_entity-8.x-1.x-dev downloaded.                                 [ok]
media_entity_image-8.x-1.x-dev downloaded.                           [ok]
media_entity_document-8.x-1.x-dev downloaded.                        [ok]
address-8.x-1.0-rc3 downloaded.                                      [ok]
paragraphs-8.x-1.0 downloaded.                                       [ok]
entity_reference_revisions-8.x-1.2 downloaded.                       [ok]
pathauto-8.x-1.0-rc1 downloaded.                                     [ok]
ctools-8.x-3.0-alpha27 downloaded.                                   [ok]
token-8.x-1.0-rc1 downloaded.                                        [ok]
field_group-8.x-1.0-rc6 downloaded.                                  [ok]
video_embed_field-8.x-1.4 downloaded.                                [ok]
jquery_colorpicker-8.x-1.3 downloaded.                               [ok]
entity_browser-8.x-1.0-rc1 downloaded.                               [ok]
entity_browser patched with 2845037_15.patch.                        [ok]
Generated PATCHES.txt file for entity_browser                        [ok]
dropzonejs-8.x-1.0-alpha3 downloaded.                                [ok]
inline_entity_form-8.x-1.0-beta1 downloaded.                         [ok]
embed-8.x-1.0-rc3 downloaded.                                        [ok]
entity_embed-8.x-1.0-beta2 downloaded.                               [ok]
views_block_filter_block-8.x-1.x-dev downloaded.                     [ok]
Unable to patch views_block_filter_block with                        [error]
empty_exposed_forms-2790505-10.patch.
plugin-8.x-2.4 downloaded.                                           [ok]
plugin patched with plugin-id-2851503-8.patch.                       [ok]
Generated PATCHES.txt file for plugin                                [ok]
libraries-8.x-3.x-dev downloaded.                                    [ok]
migrate_plus-8.x-3.0-beta1 downloaded.                               [ok]
migrate_tools-8.x-3.0-beta1 downloaded.                              [ok]
optimizely-8.x-1.2 downloaded.                                       [ok]
verf-8.x-1.0-beta6 downloaded.                                       [ok]
simple_menu_icons-8.x-1.x-dev downloaded.                            [ok]
simple_menu_icons patched with                                       [ok]
clear-cache-after-simple_menu_icons_css_generate-2847964.patch.
Generated PATCHES.txt file for simple_menu_icons                     [ok]
views_infinite_scroll-8.x-1.3 downloaded.                            [ok]
slick-8.x-1.0-rc1 downloaded.                                        [ok]
slick_views-8.x-1.0-rc2 downloaded.                                  [ok]
blazy-8.x-1.0-rc1 downloaded.                                        [ok]
geolocation-8.x-1.9 downloaded.                                      [ok]
google_tag-8.x-1.x-dev downloaded.                                   [ok]
google_analytics-8.x-2.1 downloaded.                                 [ok]
redirect-8.x-1.0-alpha4 downloaded.                                  [ok]
simple_sitemap-8.x-2.8 downloaded.                                   [ok]
metatag-8.x-1.0 downloaded.                                          [ok]
confi-8.x-1.3 downloaded.                                            [ok]
confi patched with                                                   [ok]
confi-drush-call-hooks-from-disabled-2856910.patch.
Generated PATCHES.txt file for confi                                 [ok]
Drush Make failed to download all projects. See the log above for the[error]
specific errors.
stdout: Make new site in the current directory? (y/n): y
Project features contains 2 modules: features_ui, features.
Project config_update contains 2 modules: config_update_ui, config_update.
Project paragraphs contains 3 modules: paragraphs_type_permissions, paragraphs_demo, paragraphs.
Project ctools contains 3 modules: ctools_views, ctools_block, ctools.
Project field_group contains 2 modules: field_group_migrate, field_group.
Project video_embed_field contains 3 modules: video_embed_media, video_embed_wysiwyg, video_embed_field.
Project entity_browser contains 3 modules: entity_browser_example, entity_browser_entity_form, entity_browser.
Project dropzonejs contains 2 modules: dropzonejs_eb_widget, dropzonejs.
Project migrate_plus contains 5 modules: migrate_example_setup, migrate_example, migrate_example_advanced_setup, migrate_example_advanced, migrate_plus.
Project slick contains 2 modules: slick_ui, slick.
Project blazy contains 2 modules: blazy_ui, blazy.
Project geolocation contains 2 modules: geolocation_google_places_api, geolocation.
Project redirect contains 3 modules: redirect_domain, redirect_404, redirect.
Project metatag contains 14 modules: metatag_app_links, metatag_mobile, metatag_verification, metatag_open_graph_products, metatag_open_graph, metatag_favicons, metatag_dc, metatag_dc_advanced, metatag_google_cse, metatag_hreflang, metatag_google_plus, metatag_twitter_cards, metatag_facebook, metatag.
Project confi contains a module named config_import.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=13   changed=4    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1125 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1125 |
| Installation process | http://install.openy-dev.ffwua.com/build1125/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1125/

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1126/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #343 of commit 4220085c78412e26453047ce730c9eb1678e4b20 automatically merged.
GitHub pull request #343 of commit 4220085c78412e26453047ce730c9eb1678e4b20 automatically merged.
GitHub pull request #343 of commit 4220085c78412e26453047ce730c9eb1678e4b20 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git4089318102761863648.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git3916581684116856719.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/343/merge^{commit} # timeout=10
 > git branch -a --contains 9f1f17a023fd299c612978a114a71cf9f9c401b7 # timeout=10
 > git rev-parse remotes/origin/pr/343/merge^{commit} # timeout=10
Checking out Revision 9f1f17a023fd299c612978a114a71cf9f9c401b7 (origin/pr/343/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 9f1f17a023fd299c612978a114a71cf9f9c401b7
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson7571020673678493867.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory7050509849957061521.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1126 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory7617246567391427399.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1126 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1126/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1126 -e drupal_folder=/var/www/build1126 -e site_url=http://openy-dev.ffwua.com/build1126 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-qocnkdeksuwwxhwkmladautfjdvmfglr
Traceback (most recent call last):
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1494278640.56-237869039628330/file", line 2012, in <module>
    main()
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1494278640.56-237869039628330/file", line 291, in main
    changed |= recursive_set_attributes(module, file_args['path'], follow, file_args)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1494278640.56-237869039628330/file", line 132, in recursive_set_attributes
    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1494278640.56-237869039628330/file", line 1207, in set_fs_attributes_if_different
    file_args['path'], file_args['mode'], changed
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1494278640.56-237869039628330/file", line 1045, in set_mode_if_different
    path_stat = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/tmp/hudson6227839044153158614.sh'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=3    changed=0    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1125/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1127 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1127 |
| Installation process | http://install.openy-dev.ffwua.com/build1127/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1127/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1127/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1136 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1136 |
| Installation process | http://install.openy-dev.ffwua.com/build1136/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1136/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1136/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
