### PR TITLE
[OYPD-346] Adding update hook to update member calc summary image style

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Verify update with config change for the image style.

Seems to update fine with my local test.

screen shot 2017-03-30 at 3 37 40 pm

screen shot 2017-03-30 at 3 37 55 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build869 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build869 |
| Installation process | http://install.openy-dev.ffwua.com/build869/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/869/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build869/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build870 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build870 |
| Installation process | http://install.openy-dev.ffwua.com/build870/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/870/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build870/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
