### PR TITLE
[OYPD-464] Add labels to buttons for slick slider.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue: https://propeople-us.atlassian.net/browse/OYPD-464
Drupal.org issue: https://www.drupal.org/node/2884153

Steps for review:
- [x] go to page [sitename]/programs/health-and-fitness/personal-training
- [x] move cursor above arrow Next on slider
- [x] verify you can see tooltip "Next"
- [x] move cursor above dots on slider
- [x] verify you can see tooltip "Slide set X"
- [x] go to page [sitename]/schedules
- [x] move cursor above arrow Next on slider
- [x] verify you can see tooltip "Next"
- [x] move cursor above dots on slider
- [x] verify you can see tooltip "Slide set X"

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1352 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1352 |
| Installation process | http://install.openy-dev.ffwua.com/build1352/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1352/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1352/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1357 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1357 |
| Installation process | http://install.openy-dev.ffwua.com/build1357/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1357/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1357/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
