### PR TITLE
Update captcha module 8.x-1.0-beta1 -> 8.x-1.0-beta4; update composer.lock

### PR DESCRIPTION
**Pull request by duozersk**
We needed to address this issue for our client - https://www.drupal.org/project/captcha/issues/2896957

So decided to update the module here too.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2031/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2031/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2031/

**Review by podarok — APPROVED** [review]
Great

**Pull request merged**
