### PR TITLE
Schedule: add AJAX throbber to Date filter

### PR DESCRIPTION
**Pull request by alexander-danilenko**
## Problem:
It can confuse user: filter was changed, the rest of form is inactive but no throbber appeared.
For now Schedule form's Date filter just clicks on Submit button using JS: https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/custom/openy_schedules/js/openy_schedules.js#L72-L82

## Solution:
Form field with date picker should have its own AJAX callback on change event that will show throbber in needed place.

Also please have a look to video demonstration how it improves UX:
- [Current state](https://www.drupal.org/files/issues/1.%20Before.mp4)
- [After PR merge](https://www.drupal.org/files/issues/2.%20After.mp4)

Issue on Drupal.org: https://www.drupal.org/project/openy/issues/2923773

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2374 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2374 |
| Installation process | http://install.openy-dev.ffwua.com/build2374/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2374/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2374/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2374/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2374/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2374/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2374/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build2374/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2376 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2376 |
| Installation process | http://install.openy-dev.ffwua.com/build2376/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2376/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2376/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2376/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2376/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2376/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2376/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2376/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Code looks good, @AlexNetman please test PR.

**Comment by AlexNetman** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2391 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2391 |
| Installation process | http://install.openy-dev.ffwua.com/build2391/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2391/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2391/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2391/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2391/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2391/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2391/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build2391/profiles/contrib/openy/build/reports/behat

**Pull request merged**
