### PR TITLE
[OPENY-107] OpenY Session instance decoupling

### PR DESCRIPTION
**Pull request by hamrant**
## Related issues:
- https://www.drupal.org/project/drupal/issues/2876872
- https://www.drupal.org/project/drupal/issues/2862702

## Steps for review

- [x] login as admin
- [x] go to /admin/modules/uninstall
- [x] uninstall "OpenY Demo Node Alert", "OpenY Demo Node Sessions", "OpenY Demo Node Landing Page" modules
- [x] uninstall "OpenY Paragraph Schedule Search", "OpenY Paragraph Class Sessions" modules
- [x] uninstall "OpenY Schedules" module
- [x] check that on "OpenY Session instance" module you can remove all entity content by clicking on "Remove session instance entities." link
- [x] remove this entities and uninstall "OpenY Session instance" module
- [x] go to /admin/structure
- [x] check that "Session Instance settings" and "Session Instance list" not exist in this list
- [x] go to /admin/structure/views
- [x] check that session_instances_listing views not exist here
- [x] go to /admin/modules
- [x] install "OpenY Session instance" module
- [x] check that all module components was restored

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
@hamrant I see a patch within
Does it make sense to pull it into next bugfix release?

**Comment by hamrant** [comment]
@podarok I think no, this issue can happen only on module uninstall that contain content entity (even node). For now we can't disable most of this modules because decoupling not finished, so better to keep this inside decoupling branch.

**Comment by podarok** [comment]
Cool. Go ahead with review and merge within your team
Thank you!

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build596 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build596 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build596 |
| Installation process | http://install.openy.cibox.tools/build596/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/596/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build596/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build596/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build596/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build596/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build596/blogWCAG2AAhtmlcs.txt

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build605 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build605 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build605 |
| Installation process | http://install.openy.cibox.tools/build605/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/605/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build605/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build605/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build605/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build605/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build605/blogWCAG2AAhtmlcs.txt

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
@hamrant there is an issue with the module after uninstalling. I get an error when I try to uninstall module the second time. 
`
Drupal\Core\Entity\EntityStorageException: Exception thrown while performing a schema update. Cannot rename session_instance__field_si_activity to field_deleted_data_25ce6f6bf5: table field_deleted_data_25ce6f6bf5 already exists. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException() (line 1509 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build605/openy-project/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
`

Steps to reproduce: 
- Uninstall "OpenY Session instance" module
- check that all entities were deleted 
- Install "OpenY Session instance" module
- go to any Session and edit it. 
- Verify you can see newly created session instance entities 
- Try to uninstall "OpenY Session instance" module (On this stage I get the error specified above)

**Comment by hamrant** [comment]
@ddrozdik according to [comments](https://www.drupal.org/forum/support/post-installation/2011-09-12/fields-field_deleted_data_-tables-appear-in-database#comment-6817064) Those tables will eventually be cleared by `field_purge_batch` after about six hours by 10 rows of data per cron run.

**Pull request merged**
