### PR TITLE
Fix composer library names

### PR DESCRIPTION
**Pull request by alexschedrov**
[skip-ci]

Rename libraries once again, because with "/" 2nd part of the library name treated as package name.

### CODE REVIEW

**Review by ddrozdik — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build518

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/518/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build518/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build519

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/519/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build519/profiles/openy/build/reports/behat

**Pull request merged**
