### PR TITLE
OYPD-388 Add OpenY Branch Selector module, render link on branch, add behat tests.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-388
D.o https://www.drupal.org/node/2879237

Steps to review
- [x] When a user opens the Branch page
- [x] Then clicks on “Save this location as My YMCA”
- [x] System should set cookie with following parameters:
  - [x] Lifetime: 1 years (expire timestamp a year from now)
  - [x] Value: current node_id
  - [x] Domains: http + https (secure false, & httpOnly false)
- [x] Link label should be changed to "This is your preferred branch, remove as preferred branch"

- [x] When a user opens the Branch page
- [x] And the current branch is marked as “My YMCA” (the user has a cookie with the current branch_id)
- [x] Displayed "This is your preferred branch, remove as preferred branch" text

- [x] When the user clicks on "This is your preferred branch, remove as preferred branch"
- [x] We should remove the cookie
- [x] Behat test coverage should match the above

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [x] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [x] All tests are running and there are no failed tests reported by CI.
- [x] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [x] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [x] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [x] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [x] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1217 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1217 |
| Installation process | http://install.openy-dev.ffwua.com/build1217/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1217/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1217/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1218 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1218 |
| Installation process | http://install.openy-dev.ffwua.com/build1218/install.php |

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1219/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #370 of commit ec321b0af3661d6f1dded1bc66649fa3c6a774f7 automatically merged.
GitHub pull request #370 of commit ec321b0af3661d6f1dded1bc66649fa3c6a774f7 automatically merged.
GitHub pull request #370 of commit ec321b0af3661d6f1dded1bc66649fa3c6a774f7 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git8524308287459799804.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git415698376652534830.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/370/merge^{commit} # timeout=10
FATAL: Command "git rev-parse origin/pr/370/merge^{commit}" returned status code 128:
stdout: origin/pr/370/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/370/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "git rev-parse origin/pr/370/merge^{commit}" returned status code 128:
stdout: origin/pr/370/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/370/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1576)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1572)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1233)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1245)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:607)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:85)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:934)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1044)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1222 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1222 |
| Installation process | http://install.openy-dev.ffwua.com/build1222/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1222/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1222/profiles/contrib/openy/build/reports/behat

**Pull request merged**
