### PR TITLE
[OYPD-297] Add Camp tip to Tour for node add.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue https://propeople-us.atlassian.net/browse/OYPD-297

Steps to review:
- [x] log in as admin /user, login: _admin_ and pass: _openy_
- [x] go to [sitename] /node/add?tour=1
- [x] verify tip 9 is Camp
- [x] verify tip 13 is Alert

Issue in Drupal.org https://www.drupal.org/node/2869846

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build953 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build953 |
| Installation process | http://install.openy-dev.ffwua.com/build953/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/953/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build953/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build958 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build958 |
| Installation process | http://install.openy-dev.ffwua.com/build958/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/958/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build958/profiles/contrib/openy/build/reports/behat

**Review by AlexNetman — APPROVED** [review]

**Pull request merged**
