### PR TITLE
Openy 1588 gx schedule bug

### PR DESCRIPTION
**Pull request by SanyokMedved**

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1660 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1660 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1660 |
| Installation process | http://install.openy.cibox.tools/build1660/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1660/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1660/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1660/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1660/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1660/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1660/blogWCAG2AAhtmlcs.txt

**Comment by kolesnikoff** [comment]
@podarok please review.

**Comment by podarok** [comment]
@kolesnikoff how to review? No description at all

**Comment by kolesnikoff** [comment]
@podarok the code fixes the bug described into https://github.com/ymcatwincities/openy/issues/1588.
Not sure if I can provide more details...

**Comment by podarok** [comment]
It was not clear for me @kolesnikoff sorry

**Pull request merged**
