### PR TITLE
1132 Improve UX for the help blocks

### PR DESCRIPTION
**Pull request by rotator**
More info in #1132 
Provided help blocks UX like it is in the Webform module.
[https://monosnap.com/file/FySHTTKfy0OWlMKnKU8FeD1TycYQj5](https://monosnap.com/file/FySHTTKfy0OWlMKnKU8FeD1TycYQj5)
Fixed visibility for multiple pages in the textarea.

@podarok please, review.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build567 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build567 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build567 |
| Installation process | http://install.openy.cibox.tools/build567/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/567/

**Comment by kolesnikoff** [comment]
@podarok please review

**Review by podarok — APPROVED** [review]
Code looks good

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build590 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build590 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build590 |
| Installation process | http://install.openy.cibox.tools/build590/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/590/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build590/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build590/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build590/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build590/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build590/blogWCAG2AAhtmlcs.txt

**Pull request merged**
