### PR TITLE
[OPENY-246] Backport PDF Schedules bug fix

### PR DESCRIPTION
**Pull request by anprok**
## Steps for review
- [x] visit page /schedules-0?date=3%20Jan%202019&locations=&categories=
- [x] make sure January 3 2019 selected
- [x] click Weekly PDF schedule link
- [x] make sure PDF generates without errors

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1302 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1302 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1302 |
| Installation process | http://install.openy.cibox.tools/build1302/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1302/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1302/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1302/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1302/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1302/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1302/blogWCAG2AAhtmlcs.txt

**Review by ddrozdik — APPROVED** [review]

**Comment by ddrozdik** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1307 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1307 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1307 |
| Installation process | http://install.openy.cibox.tools/build1307/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1307/

**Review by podarok — APPROVED** [review]

**Pull request merged**
