### PR TITLE
[YGSSLA-121] Force home branch modal display on menu item and locatio…

### PR DESCRIPTION
**Pull request by anprok**
Fix of bug for YMCA Brandywine

Home branch functionality is not working, user can not click on home branch button on [Homepage]. Home branch pop-up is not appearing. Also button Change (home branch) for any location page is not working

image

## Steps for review

Steps to review:

- [ ]  login as admin
- [ ]  enable openy_home_branch module and back to home page
- [ ]  make sure home branch modal displayed at first opening
- [ ]  reload page and make sure that home branch modal not displayed
- [ ]  click Home branch link in top menu
- [ ]  make sure modal displayed
- [ ]  select any branch and close modal
- [ ]  make sure home branch link changed to branch name you selected
- [ ]  click on branch link at top menu
- [ ]  make sure you redirected to branch page
- [ ]  click on change location link in banner
- [ ]  make sure home branch modal displayed

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1992/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1992/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1992/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1992/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1992/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1992/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1992/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1992/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build1992/

**Review by podarok — APPROVED** [review]
Looks good code wise

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
Tested this fix on https://www.ymcagbw.org/

@podarok feel free to merge PR

**Comment by podarok** [comment]
was it tested on a build? @hamrant

**Comment by hamrant** [comment]
@podarok Yes, tested here - http://openy.cibox.tools/build1992/locations/downtown-ymca

**Pull request merged**
