### PR TITLE
[OYPD-227] Migration for blog posts listings.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-227
D.o https://www.drupal.org/node/2851627

## Steps to review:
1. Homepage LP
Content area: Latest blog posts
- [x] Go to homepage
- [x] See blog posts listed in content area.
image

2. Blog LP
Content area: Blog posts listing
- [x] Go to /blog
- [x] See blog posts listing with filters in content area.
image

3. Branches
Content area: Latest blog posts (branch)
- **Existed previously no additional changes or additions**
- [x] Go to /admin/content
- [x] Filter to content type branch
- [x] View any
- [x] See blog posts listing in content area.
image

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build422

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/422/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build422/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build438

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/438/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build438/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build444

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/444/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build444/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build445

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/445/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build445/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
