### PR TITLE
Alerts location fix

### LINKED ISSUE #2330: Alerts on location related pages are not working
On the latest version of Open Y (2.7.0 & 2.7.1), there is a problem with the Location field, which part of the Alert content type. This field has no options while branch and camps exist on the website 
image

Without options, there is no way to create an alert that will be associated with all branch or camp pages via this reference. 

**Expected Results:**
Location dropdown contains a list of branch and camp locations.

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/2330

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Login as admin.
- [ ] Verify Alert CT Location field is functional now and contains Camps and Branches 
image
.
- [ ] Create Alert node with reference to Branch and verify alert is displayed on respective Branch 
image
.
- [ ] Create Landing Page ( Blog Post, News Post ) with reference to previously referenced Branch from Alert and verify alert displayed on created node
image
image
image

.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2892/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2892/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2892/

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2893/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2893/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2892/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2893/

**Review by anpolimus — COMMENTED** [review]
@podarok I see that this code should add a location reference field to the Alert CT, but I cant find place where you are adding it to this bundle.
Can you point me to that place?

**Comment by podarok** [comment]
> @podarok I see that this code should add a location reference field to the Alert CT, but I cant find place where you are adding it to this bundle.
> Can you point me to that place?

reference added previously - but it was not added completely - this PR is a fix of badly made in the past @anpolimus

**Review by hamrant — APPROVED** [review]

**Review by anpolimus — APPROVED** [review]

**Pull request merged**
