### PR TITLE
Fixed Groupex Pro empty Sign Up link field.

### PR DESCRIPTION
**Pull request by anpolimus**
At this PR I've fixed empty groupex sign up link that were not filling during syncer Save method execution.

In addition to that I've deleted old goupexpro sync script based.
It took some time for me to understand that this is old and outdated feature. I think we could save some time for future developers if we delete it.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
@anpolimus we need to have demo content for the site. Are you sure removing old code won't break demo content?

**Comment by podarok** [comment]
ok to test

**Comment by anpolimus** [comment]
@podarok can you give me direction, where this demo content import execution is stored at codebase and I'll check it.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1682 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1682 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1682 |
| Installation process | http://install.openy.cibox.tools/build1682/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1682/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1682/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1682/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1682/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1682/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1682/blogWCAG2AAhtmlcs.txt

**Comment by podarok** [comment]
Next time let's use dedicated PRs for removing code. especially if unrelated to the main task @anpolimus 
Thank you, merging

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1683 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1683 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1683 |
| Installation process | http://install.openy.cibox.tools/build1683/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1683/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1683/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1683/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1683/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1683/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1683/blogWCAG2AAhtmlcs.txt

**Comment by anpolimus** [comment]
@podarok got it. 
Thank you.

**Pull request merged**
