### PR TITLE
[OYPD-242] Media browser fixes.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-242
D.o https://www.drupal.org/node/2852262

1. Should be "Video name"
- [x] Add or edit a blog post
- [x] Click video embed
- [x] Go to select video tab
- [x] See label for title field reads "Video name"
image

2. Should be "Document name"
- [x] Add or edit a blog post
- [x] Click document embed
- [x] Go to select documents tab
- [x] See label for title field reads "Document name"
image

2. Add filter by "Media Tags" to all media browser views
- [x] Add or edit a blog post
- [x] Click (document, video, image) embed
- [x] Go to select (documents, video, image) tab
- [x] See Media Tags field.
image

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build439

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/439/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build439/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build440

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/440/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build440/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build451

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/451/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build451/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Please add "No results found" when there's no results to display.

**Comment by Kerby70** [comment]
@Sanchiz "No results found" message added in the latest commit.

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build459

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/459/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build459/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
