### PR TITLE
[NOT PASSED] Check 8.7.0 

### PR DESCRIPTION
**Pull request by podarok**
- [x] OpenY with Drupal core 8.7.0 is pixel perfect(669 pages of the site with Demo content) in comparison to Drupal core 8.6.x
We need to spend some time for the investigation regarding https://www.drupal.org/node/3034742

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1595 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1595 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1595 |
| Installation process | http://install.openy.cibox.tools/build1595/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1595/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1596 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1596 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1596 |
| Installation process | http://install.openy.cibox.tools/build1596/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1596/

**Comment by podarok** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1597 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1597 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1597 |
| Installation process | http://install.openy.cibox.tools/build1597/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1597/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1597/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1597/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1597/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1597/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1597/blogWCAG2AAhtmlcs.txt

**Comment by podarok** [comment]
We are good to go with 8.7.0
@ddrozdik @Sanchiz @ygerasimov @AndreyMaximov @danylevskyi 
@paige-kiecker @ymcagtc

**Comment by alexschedrov** [comment]
@podarok good news 👍

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1600 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1600 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1600 |
| Installation process | http://install.openy.cibox.tools/build1600/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1600/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1600/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1600/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1600/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1600/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1600/blogWCAG2AAhtmlcs.txt

**Comment by podarok** [comment]
We need to spend some time for the investigation regarding https://www.drupal.org/node/3034742 as per @ygerasimov mentioning.
8.7 is not going into tomorrow's release. Too risky.

**Pull request closed without merging**
