### PR TITLE
[MAINTAIN-155] fixed issue with not working modal dialog on membership (/join) page on Carnation theme

### PR DESCRIPTION
**Pull request by aleevas**
Original Issue, this PR is going to fix: [MAINTAIN-155](https://openy.atlassian.net/browse/MAINTAIN-155)

This one should fix issue with a modal window on /join page that didn't closing

MAINTAIN-155closeModal

## Steps for review

- [ ] go to /join page
- [ ] please not check anything on page and click **Next**
- [ ] verify that you can see the modal window with error message
- [ ] verify that you can close it by clicking to **x** button
MAINTAIN-155closeModal

- [ ] please verify that you can close this modal window on every steps on this form
- [ ] for additional check: go to /user/login
- [ ] please fill fields with dummy credentials and click "Login"
MAINTAIN-155closeModalOnAnotherPage

- [ ] verify that you can see the modal window with error message
- [ ] verify that you can close it

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3414/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3414/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3414/

**Comment by hamrant** [comment]
Looks ok for me - http://upgrade.openy.cibox.tools/build3414/join

**Comment by AnastasiiaPys** [comment]
Tested on macOS(Chrome),Windows 10(Edge), Iphone 11, Ipad.

Works as expected.

**Pull request merged**
