### PR TITLE
[OYPD-398] Adding GroupEx Pro paragraph and block

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Verify after pulling in the change the module is enabled as well as the feature with the paragraph type.
- [x] Go to admin/config/services/groupexpro and an account id for testing. (See JIRA issue or slack for id to use.)
- [x] Add the embedded groupex pro block to a region and verify it works and the schedule appears.
- [x] Add the embedded groupex pro paragraph to a landing page and verify it works and the schedule appears.

### CODE REVIEW

**Comment by david-hernandez** [comment]
Regarding changes from the previous pull request, I removed the id setting from the block put it on a custom settings form. Both the block and paragraph get the id from there.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1129 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1129 |
| Installation process | http://install.openy-dev.ffwua.com/build1129/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1129/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1129/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Needs re-roll.

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1152/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #344 of commit b02d60f3534cf26b03efc43657007f8bec6f1b13.
GitHub pull request #344 of commit b02d60f3534cf26b03efc43657007f8bec6f1b13.
GitHub pull request #344 of commit b02d60f3534cf26b03efc43657007f8bec6f1b13.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7716128908148442346.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git1191829587085562221.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse b02d60f3534cf26b03efc43657007f8bec6f1b13^{commit} # timeout=10
 > git branch -a --contains b02d60f3534cf26b03efc43657007f8bec6f1b13 # timeout=10
 > git rev-parse remotes/origin/pr/344/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/344/merge^{commit} # timeout=10
Checking out Revision b02d60f3534cf26b03efc43657007f8bec6f1b13 (origin/pr/344/merge, origin/pr/344/head)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b02d60f3534cf26b03efc43657007f8bec6f1b13
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson7486489964363081082.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory5208350100844829280.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1152 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory7391022121556471436.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1152 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1152/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1152 -e drupal_folder=/var/www/build1152 -e site_url=http://openy-dev.ffwua.com/build1152 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
changed: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [localhost] => (item={'status': True, 'name': '$config["system.file"]["path.temporary"]', 'value': '/tmp'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
skipping: [localhost]

TASK: [Creating drupal database] ********************************************** 
skipping: [localhost]

TASK: [Downloading latest backup to local environment] ************************ 
skipping: [localhost]

TASK: [Removing possible abandoned dump] ************************************** 
skipping: [localhost]

TASK: [Importing from remote backup] ****************************************** 
skipping: [localhost]

TASK: [Copy latest backup to build folder] ************************************ 
skipping: [localhost]

TASK: [Importing from local backup] ******************************************* 
skipping: [localhost]

TASK: [Remove local backup from build folder] ********************************* 
skipping: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
skipping: [localhost]

TASK: [Clear Drupal cache] **************************************************** 
skipping: [localhost]

TASK: [Updating database] ***************************************************** 
skipping: [localhost]

TASK: [Apply pending entity schema updates] *********************************** 
skipping: [localhost]

TASK: [Download stage file proxy] ********************************************* 
skipping: [localhost]

TASK: [Enable stage file proxy] *********************************************** 
skipping: [localhost]

TASK: [Set configuration for stage file proxy] ******************************** 
skipping: [localhost]

TASK: [Set folder for stage file proxy] *************************************** 
skipping: [localhost]

TASK: [Updates listing] ******************************************************* 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
ok: [localhost]

TASK: [Creating drupal database] ********************************************** 
changed: [localhost]

TASK: [Remove settings.php] *************************************************** 
ok: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
failed: [localhost] => {"changed": true, "cmd": "cd profiles/contrib/openy && APP_ENV=dev drush make drupal-org.make -y --no-core --no-cache", "delta": "0:00:14.601541", "end": "2017-05-11 08:51:50.476824", "rc": 1, "start": "2017-05-11 08:51:35.875283", "warnings": []}
stderr: Beginning to build drupal-org.make.                                  [ok]
features-8.x-3.5 downloaded.                                         [ok]
config_update-8.x-1.3 downloaded.                                    [ok]
entity-8.x-1.0-alpha4 downloaded.                                    [ok]
datalayer-8.x-1.x-dev downloaded.                                    [ok]
datalayer patched with                                               [ok]
2857270-4-fix-entity-reference-field-using-name-property.patch.
Generated PATCHES.txt file for datalayer                             [ok]
media_entity-8.x-1.x-dev downloaded.                                 [ok]
media_entity_image-8.x-1.x-dev downloaded.                           [ok]
media_entity_document-8.x-1.x-dev downloaded.                        [ok]
address-8.x-1.0-rc3 downloaded.                                      [ok]
paragraphs-8.x-1.0 downloaded.                                       [ok]
entity_reference_revisions-8.x-1.2 downloaded.                       [ok]
pathauto-8.x-1.0-rc1 downloaded.                                     [ok]
ctools-8.x-3.0-alpha27 downloaded.                                   [ok]
token-8.x-1.0-rc1 downloaded.                                        [ok]
field_group-8.x-1.0-rc6 downloaded.                                  [ok]
video_embed_field-8.x-1.4 downloaded.                                [ok]
jquery_colorpicker-8.x-1.3 downloaded.                               [ok]
entity_browser-8.x-1.0-rc1 downloaded.                               [ok]
entity_browser patched with 2845037_15.patch.                        [ok]
Generated PATCHES.txt file for entity_browser                        [ok]
dropzonejs-8.x-1.0-alpha3 downloaded.                                [ok]
inline_entity_form-8.x-1.0-beta1 downloaded.                         [ok]
embed-8.x-1.0-rc3 downloaded.                                        [ok]
entity_embed-8.x-1.0-beta2 downloaded.                               [ok]
views_block_filter_block-8.x-1.x-dev downloaded.                     [ok]
Unable to patch views_block_filter_block with                        [error]
empty_exposed_forms-2790505-10.patch.
plugin-8.x-2.4 downloaded.                                           [ok]
plugin patched with plugin-id-2851503-8.patch.                       [ok]
Generated PATCHES.txt file for plugin                                [ok]
libraries-8.x-3.x-dev downloaded.                                    [ok]
migrate_plus-8.x-3.0-beta1 downloaded.                               [ok]
migrate_tools-8.x-3.0-beta1 downloaded.                              [ok]
optimizely-8.x-1.2 downloaded.                                       [ok]
verf-8.x-1.0-beta6 downloaded.                                       [ok]
simple_menu_icons-8.x-1.x-dev downloaded.                            [ok]
simple_menu_icons patched with                                       [ok]
clear-cache-after-simple_menu_icons_css_generate-2847964.patch.
Generated PATCHES.txt file for simple_menu_icons                     [ok]
views_infinite_scroll-8.x-1.3 downloaded.                            [ok]
slick-8.x-1.0-rc1 downloaded.                                        [ok]
slick_views-8.x-1.0-rc2 downloaded.                                  [ok]
blazy-8.x-1.0-rc1 downloaded.                                        [ok]
geolocation-8.x-1.9 downloaded.                                      [ok]
google_tag-8.x-1.x-dev downloaded.                                   [ok]
google_analytics-8.x-2.1 downloaded.                                 [ok]
redirect-8.x-1.0-alpha4 downloaded.                                  [ok]
simple_sitemap-8.x-2.8 downloaded.                                   [ok]
metatag-8.x-1.0 downloaded.                                          [ok]
confi-8.x-1.3 downloaded.                                            [ok]
confi patched with                                                   [ok]
confi-drush-call-hooks-from-disabled-2856910.patch.
Generated PATCHES.txt file for confi                                 [ok]
Drush Make failed to download all projects. See the log above for the[error]
specific errors.
stdout: Make new site in the current directory? (y/n): y
Project features contains 2 modules: features_ui, features.
Project config_update contains 2 modules: config_update_ui, config_update.
Project paragraphs contains 3 modules: paragraphs_type_permissions, paragraphs_demo, paragraphs.
Project ctools contains 3 modules: ctools_views, ctools_block, ctools.
Project field_group contains 2 modules: field_group_migrate, field_group.
Project video_embed_field contains 3 modules: video_embed_media, video_embed_wysiwyg, video_embed_field.
Project entity_browser contains 3 modules: entity_browser_example, entity_browser_entity_form, entity_browser.
Project dropzonejs contains 2 modules: dropzonejs_eb_widget, dropzonejs.
Project migrate_plus contains 5 modules: migrate_example_setup, migrate_example, migrate_example_advanced_setup, migrate_example_advanced, migrate_plus.
Project slick contains 2 modules: slick_ui, slick.
Project blazy contains 2 modules: blazy_ui, blazy.
Project geolocation contains 2 modules: geolocation_google_places_api, geolocation.
Project redirect contains 3 modules: redirect_domain, redirect_404, redirect.
Project metatag contains 14 modules: metatag_app_links, metatag_mobile, metatag_verification, metatag_open_graph_products, metatag_open_graph, metatag_favicons, metatag_dc, metatag_dc_advanced, metatag_google_cse, metatag_hreflang, metatag_google_plus, metatag_twitter_cards, metatag_facebook, metatag.
Project confi contains a module named config_import.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=13   changed=5    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1162 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1162 |
| Installation process | http://install.openy-dev.ffwua.com/build1162/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1162/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1162/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
Let's add some description what should be entered in form and link to https://www.groupexpro.com.
image

**Comment by david-hernandez** [comment]
Added help text with link.

screen shot 2017-05-12 at 10 07 43 am

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1171 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1171 |
| Installation process | http://install.openy-dev.ffwua.com/build1171/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1171/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1171/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1173 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1173 |
| Installation process | http://install.openy-dev.ffwua.com/build1173/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1173/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1173/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1178 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1178 |
| Installation process | http://install.openy-dev.ffwua.com/build1178/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1178/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1178/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
