### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by podarok**
Some readmes

Let's keep the rule of having README files everywhere in codebase

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build327

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/327/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build327/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build329

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/329/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build329/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build330

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/330/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build330/profiles/openy/build/reports/behat

**Pull request merged**
