### PR TITLE
[OYPD-344] Update media_entity & media_entity_document to use 1.x-dev each.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-344
D.o https://www.drupal.org/node/2864808

Related to #2860574: "Openy distribution requirements fail on Address module dependencies" and currently final resolution is blocked by #2849014: "Update to use packages.drupal.org", that would not prevent this pull request from being merged.

A pull request on media_entity https://github.com/drupal-media/media_entity/pull/83

Steps to review
- [x] Composer will build get dependencies appropriately, on simplytest.me after the media_entity changes have been adopted.

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build854 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build854 |
| Installation process | http://install.openy-dev.ffwua.com/build854/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/854/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build854/profiles/contrib/openy/build/reports/behat

**Comment by Kerby70** [comment]
I was unable to update composer.lock with this configuration so I closed the PR, for now.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/media_entity_document (locked at 1.1.0, required as 1.x-dev) is satisfiable by drupal/media_entity_document[1.1.0] but these conflict with your requirements or minimum-stability.
```

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build855 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build855 |
| Installation process | http://install.openy-dev.ffwua.com/build855/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/855/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build855/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build862 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build862 |
| Installation process | http://install.openy-dev.ffwua.com/build862/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/862/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build862/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build864 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build864 |
| Installation process | http://install.openy-dev.ffwua.com/build864/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/864/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build864/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
