### PR TITLE
[OYPD-199] Update blog images & fix footer

### PR DESCRIPTION
**Pull request by alexschedrov**
JIRA: https://propeople-us.atlassian.net/browse/OYPD-199

Steps for review:
- Open blog posts and make sure they have good images

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build364

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/364/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build364/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build365

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/365/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build365/profiles/openy/build/reports/behat

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build366

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/366/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build366/profiles/openy/build/reports/behat

**Pull request merged**
