### PR TITLE
[OYPD-473] swap order of the neighbourhood and the location on the locations page see screen shot attached.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue: https://propeople-us.atlassian.net/browse/OYPD-473
Drupal.org issue: https://www.drupal.org/node/2884319

Steps for review:
- [x] go to page [sitename]/locations
- [x] verify in branch content title above then field_location_area and  field_location_state
- [x] verify style, must be same space field_location_area and  field_location_state as was have title

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1365 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1365 |
| Installation process | http://install.openy-dev.ffwua.com/build1365/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1365/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1365/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1400 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1400 |
| Installation process | http://install.openy-dev.ffwua.com/build1400/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1400/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1400/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. We should do the same for Facilities

image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1498 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1498 |
| Installation process | http://install.openy-dev.ffwua.com/build1498/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1498/

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1499 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1499 |
| Installation process | http://install.openy-dev.ffwua.com/build1499/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1499/

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1502/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #458 of commit 089bcaa4d93605883eb038a5926fd5524b71d593 automatically merged.
GitHub pull request #458 of commit 089bcaa4d93605883eb038a5926fd5524b71d593 automatically merged.
GitHub pull request #458 of commit 089bcaa4d93605883eb038a5926fd5524b71d593 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace@2
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git186775379478808892.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git1188717629125617298.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/458/merge^{commit} # timeout=10
 > git branch -a --contains a1b3cd1fecdf63a39fa1854b5418eadedaa3d467 # timeout=10
 > git rev-parse remotes/origin/pr/458/merge^{commit} # timeout=10
Checking out Revision a1b3cd1fecdf63a39fa1854b5418eadedaa3d467 (origin/pr/458/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a1b3cd1fecdf63a39fa1854b5418eadedaa3d467
 > git rev-list a1b3cd1fecdf63a39fa1854b5418eadedaa3d467 # timeout=10
[workspace@2] $ /bin/sh -xe /tmp/hudson1339542577685845703.sh
+ rm -Rf /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
+ cp -R ../vm /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
+ git pull
Already up-to-date.
[workspace@2] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory8527537894346532635.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace@2 -e build_number=1502 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace@2/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace@2] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm/cibox/jobs/build.yml -i /tmp/inventory5681274647133295400.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace@2 -e build_number=1502 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace@2] $ ansible-playbook /var/www/build1502/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1502 -e drupal_folder=/var/www/build1502 -e site_url=http://openy-dev.ffwua.com/build1502 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
changed: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [localhost] => (item={'status': True, 'name': '$config["system.file"]["path.temporary"]', 'value': '/tmp'})

TASK: [Copy settings back (WINDOWS)] ****************************************** 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
skipping: [localhost]

TASK: [Creating drupal database] ********************************************** 
skipping: [localhost]

TASK: [Downloading latest backup to local environment] ************************ 
skipping: [localhost]

TASK: [Removing possible abandoned dump] ************************************** 
skipping: [localhost]

TASK: [Importing from remote backup] ****************************************** 
skipping: [localhost]

TASK: [Copy latest backup to build folder] ************************************ 
skipping: [localhost]

TASK: [Importing from local backup] ******************************************* 
skipping: [localhost]

TASK: [Remove local backup from build folder] ********************************* 
skipping: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
skipping: [localhost]

TASK: [Clear Drupal cache] **************************************************** 
skipping: [localhost]

TASK: [Updating database] ***************************************************** 
skipping: [localhost]

TASK: [Apply pending entity schema updates] *********************************** 
skipping: [localhost]

TASK: [Download stage file proxy] ********************************************* 
skipping: [localhost]

TASK: [Enable stage file proxy] *********************************************** 
skipping: [localhost]

TASK: [Set configuration for stage file proxy] ******************************** 
skipping: [localhost]

TASK: [Set folder for stage file proxy] *************************************** 
skipping: [localhost]

TASK: [Updates listing] ******************************************************* 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
ok: [localhost]

TASK: [Creating drupal database] ********************************************** 
changed: [localhost]

TASK: [Remove settings.php] *************************************************** 
ok: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
changed: [localhost]

TASK: [Installing drupal] ***************************************************** 
failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush -y si openy --db-url=mysql://root:root@127.0.0.1:/drupal1502 --account-name=admin --account-pass=openy --uri=http://openy-dev.ffwua.com/build1502", "delta": "0:08:23.827100", "end": "2017-06-12 10:58:30.941805", "rc": 1, "start": "2017-06-12 10:50:07.114705", "warnings": []}
stderr: Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
Installation complete.  User name: admin  User password: openy       [ok]
Unable to send email. Contact the site administrator if the problem  [error]
persists.
Created three snippet files based on configuration.                  [status]
Optimizely database table has been created.                          [status]
A default project / experiment entry has been created. Next, enter   [status]
your Optimizely account ID on the module's ACCOUNT INFO page. There
is also an Optimizely permission that can be set for specific roles
to access the adminstration functionality. You can access those pages
via the Optimizely module below.
The XML sitemap has been regenerated for all languages.              [status]
You can now include content into the XML sitemap by visiting the     [status]
corresponding entity type edit pages (e.g. node type edit pages)
These settings can then be overridden for single entities. Support
for additional entity types and custom links can be added on the
module's configuration pages.
Congratulations, you installed OpenY!                                [status]
stdout: You are about to create a /var/www/build1502/sites/default/settings.php file and DROP all tables in your 'drupal1502' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1503 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1503 |
| Installation process | http://install.openy-dev.ffwua.com/build1503/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1503/

**Review by alexschedrov — APPROVED** [review]

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1503/profiles/contrib/openy/build/reports/behat

**Pull request merged**
