### PR TITLE
[1078]: menu styles when there is small amount of items

### PR DESCRIPTION
**Pull request by taras-tsiuper**
## Steps for review
- [x] Open admin/structure/menu/manage/main page.
- [x] Disable all menu items except "Programs" and save it.
- [x] Open front page and click on menu item if it looks good now.

See #1078 for more information

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build473 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build473 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build473 |
| Installation process | http://install.openy.cibox.tools/build473/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/473/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build473/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build473/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build473/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build473/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build473/blogWCAG2AAhtmlcs.txt

**Review by podarok — APPROVED** [review]

**Pull request merged**
