### PR TITLE
Remove dependency to openy_node_mbrsh from openy_prgf

### PR DESCRIPTION
**Pull request by yasik78**
Remove dependency to openy_node_mbrshp from openy_loc_branch #440

## Steps for review

- [x] Check this https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml#L19

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Sanchiz** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1703 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1703 |
| Installation process | http://install.openy-dev.ffwua.com/build1703/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1703/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1703

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1703/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
