### PR TITLE
[OYPD-182] Full width image for subcategory list below 480px

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Create a program page that can list subprograms using the program list paragraph type.
- [x] Look at the program list on smaller screen sizes.
- [x] See the image is full width on screens below 480px.

We may want to center the image between 480 and 760, but I wouldnt make the image max width. It will expand a 270px image to fit 700+ width which will look bad.

screen shot 2017-02-10 at 12 34 17 pm

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build421

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/421/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build421/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build427

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/427/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build427/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@david-hernandez let's center image on screen 480px-768px without max-width.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build434

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/434/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build434/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build443

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/443/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build443/profiles/openy/build/reports/behat

**Pull request merged**
