### PR TITLE
[MAINTAIN-161] Make alert full height.

### PR DESCRIPTION
**Pull request by manachynskyi**
[Original Issue](https://openy.atlassian.net/browse/MAINTAIN-161), this PR is going to improve alert styles, for case when one alert takes more lines than another one for Lily and Rose themes.

Before: https://i.imgur.com/WgIBYK4.png
After: https://i.imgur.com/jrx1m8h.png

## Steps for review

- [x] log in as admin and edit any alert
- [x] fill some long text in the description field -> save
- [x] open any page and make sure all alerts have the same height (go through all alerts on both sides) https://www.loom.com/share/96dabf2a41c74364a7341ee4cf3a0abc

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by podarok** [comment]
ok to test

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3549/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3549/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3549/

**Comment by podarok** [comment]
image

Looks great, thank you

**Pull request merged**
