### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by podarok**

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build323

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/323/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build323/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build324

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/324/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build324/profiles/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build326

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/326/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build326/profiles/openy/build/reports/behat

**Pull request merged**
