### PR TITLE
[CR-32] Fix grid content col on ipad

### PR DESCRIPTION
**Pull request by hamrant**
Original Issue: grid columns looks too big on iPad, we can use two cols

**Steps for review:**

- [ ] Find grid columns paragraph on the front page
- [ ] Check that buttons looks better

Before fix:

Screenshot from 2020-08-28 17-11-14

After fix:

Screenshot from 2020-08-28 17-32-46

- [ ] Open this page on iPad
- [ ] Check that we have 2 grid cols per row (on mobile should be one row)

Before fix:

Screenshot from 2020-08-28 17-34-25

After fix:

Screenshot from 2020-08-28 17-33-11

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2453/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2453/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2453/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2453/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2453/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2453/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2453/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2453/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2453/

**Pull request merged**
