### PR TITLE
fix(deps): decouple upgrade tool

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: https://openy.atlassian.net/browse/MAINTAIN-159
Extends: https://github.com/ymcatwincities/openy/wiki/Decoupled-(-external-)-projects-of-OpenY#drupalorg-hosted

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Ensure Open Y Upgrade Tool is in place.
image
image

- [ ] Check https://www.drupal.org/project/upgrade_tool/releases/2.0.0

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3410/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3410/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3410/

**Review by hamrant — APPROVED** [review]
@podarok there was a small difference in configuration, for contrib module we were able to select features for subscribing. In Open Y we subscribed on features with the `openy_` prefix. I can't find this change in https://git.drupalcode.org/project/upgrade_tool/-/commit/d2bc07d5eace11e90d6441e28848e7d792149eee but looks like this was fixed in https://git.drupalcode.org/project/upgrade_tool/-/blob/9.x-2.x/src/OpenyUpgradeLogManager.php#L261

**Comment by podarok** [comment]
> @podarok there was a small difference in configuration, for contrib module we were able to select features for subscribing. In Open Y we subscribed on features with the `openy_` prefix. I can't find this change in https://git.drupalcode.org/project/upgrade_tool/-/commit/d2bc07d5eace11e90d6441e28848e7d792149eee but looks like this was fixed in https://git.drupalcode.org/project/upgrade_tool/-/blob/9.x-2.x/src/OpenyUpgradeLogManager.php#L261

Does it mean we have a regression for whoever try to upgrade from old contrib module?
Old module is not supported, no any stats data for it to be used, so I'm pretty confident we will introduce 0 regressions for those "hidden" users of it

**Comment by hamrant** [comment]
> Does it mean we have a regression for whoever try to upgrade from old contrib module?
Old module is not supported, no any stats data for it to be used, so I'm pretty confident we will introduce 0 regressions for those "hidden" users of it

Agree 😁

**Pull request merged**
