### PR TITLE
[OYS-12] Update header logo image paddings for Lily

### PR DESCRIPTION
**Pull request by anprok**
https://fivejars.atlassian.net/browse/OYS-12
## Steps for review

- [ ] open Fresh OpenY installation - Lily theme link.
- [ ] check logo in the header.
- [ ] make sure it looks according to requirements below.
-
image
 
image

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
@anprok 
I see header is broken now for Lily when registered user
image
We have no such issue in Sandbox and current dev
So looks like needs fix 
image

**Review by podarok — CHANGES_REQUESTED** [review]
Registered user header fix needed

**Comment by gundevel** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1643 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1643 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1643 |
| Installation process | http://install.openy.cibox.tools/build1643/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1643/

**Comment by gundevel** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1643/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1643/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1643/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1643/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1643/blogWCAG2AAhtmlcs.txt

**Comment by AndreyMaximov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1644 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1644 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1644 |
| Installation process | http://install.openy.cibox.tools/build1644/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1644/

**Comment by AndreyMaximov** [comment]
@podarok 
I've just compared the sandbox and the build. I can't see any difference but the logo adjustments.

The top of the page:

[build](http://lily.openy.cibox.tools/build1644) | [sandbox](http://sandbox.openymca.org/)
------------ | -------------
build-top-alert | sandbox-top-alert
build-top | sandbox-top

The scrolled page:

build | sandbox
------------ | -------------
build-scrolled | sandbox-scrolled
build-scrolled-2 | sandbox-scrolled-2

It seems the bugs are not being introduced in this PR. I'd recommend checking #1626

We can work on fixing the broken header in another PR.

**Review by AndreyMaximov — APPROVED** [review]

**Comment by AndreyMaximov** [comment]
Kindly reminder. @podarok please review this PR.

**Comment by podarok** [comment]
Thank you @AndreyMaximov 
Looks like it was by browser...

**Pull request merged**
