### PR TITLE
Carnation: Gallery fixes and improvements

### PR DESCRIPTION
**Pull request by dchubar-fj**
Original Issue, this PR is going to fix: Broken gallery https://i.imgur.com/wJJu9Ea.png https://sandbox-carnation-cus.openy.org/locations/downtown-ymca

## Steps for review

- [ ] Login as admin
- [ ] Enable Carnation theme (if is not enabled)
- [ ] Create a landing page
- [ ] Add a gallery paragraph with the only one image to the header area section
- [ ] Verify the gallery looks similar to banner, without any prev/next button and thumbnails https://i.imgur.com/RIE8wAM.jpg
- [ ] Make sure it looks ok on mobiles.
- [ ] Edit the node and add more images to the gallery
- [ ] Verify the gallery has the prev/next button now https://i.imgur.com/cAo5l7m.jpg
- [ ] Make sure it looks ok on mobiles.
- [ ] Edit the node one more time and add a new gallery paragraph with several images to the content area section
- [ ] Verify the gallery has the prev/next button and thumbnails https://i.imgur.com/zOWtTAq.jpg
- [ ] Make sure the active slide can be changed by click on the corresponding thumbnail.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2390/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2390/

**Comment by bjwilkins** [comment]
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2390/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2390/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2390/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2390/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2390/blogWCAG2AAhtmlcs.txt

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2390/

**Comment by bjwilkins** [comment]
Open Y Complete profile installed at http://openy.cibox.tools/build2390/

**Review by podarok — APPROVED** [review]

**Review by hamrant — APPROVED** [review]

**Pull request merged**
