### PR TITLE
Fix warning on the theme settings page

### PR DESCRIPTION
**Pull request by ddrozdik**
Issue is described here: https://github.com/ymcatwincities/openy/issues/610
### Steps for review
- [x] Review code changes

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1707 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1707 |
| Installation process | http://install.openy-dev.ffwua.com/build1707/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1707/

**Comment by gundevel** [comment]
Decoupling report http://ci.openymca.org/build1707

**Comment by gundevel** [comment]
Accessibility report http://ci.openymca.org/build1707

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1707/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1716 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1716 |
| Installation process | http://install.openy-dev.ffwua.com/build1716/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1716/

**Comment by bjwilkins** [comment]
Decoupling report http://ci.openymca.org/build1716

**Comment by bjwilkins** [comment]
Accessibility report http://ci.openymca.org/build1716

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1716/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]

**Pull request merged**
