### PR TITLE
CodeSprint: test (Oleg Sabadash)

### PR DESCRIPTION
**Pull request by osab**
Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/>CI code sniffer errors
- [ ] All tests are running and there are no failed tests reported by CI. <br/>Behat test results
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

### CODE REVIEW

**Comment by osab** [comment]
test this please

**Comment by danylevskyi** [comment]
ok to test

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1414/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
GitHub pull request #489 of commit 32d5b4bca79f0b3b07a02001a59b89547b856d07 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace@2
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5030341462014478833.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/489/merge^{commit} # timeout=10
 > git branch -a --contains 67591c2e273249ece6b632ec5de383a282407f57 # timeout=10
 > git rev-parse remotes/origin/pr/489/merge^{commit} # timeout=10
Checking out Revision 67591c2e273249ece6b632ec5de383a282407f57 (origin/pr/489/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 67591c2e273249ece6b632ec5de383a282407f57
First time build. Skipping changelog.
[workspace@2] $ /bin/sh -xe /tmp/hudson7397310825373775812.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
/tmp/hudson7397310825373775812.sh: 2: cd: can't cd to /var/lib/jenkins/jobs/PR_BUILDER/workspace@2/vm
Build step 'Execute shell' marked build as failure
Couldn't read comment file
java.io.FileNotFoundException: File '/var/lib/jenkins/jobs/PR_BUILDER/workspace@2/commentinfo.md' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:124)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by Sanchiz** [comment]
retest this please

**Comment by osab** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1424 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1424 |
| Installation process | http://install.openy-dev.ffwua.com/build1424/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1424/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1424/profiles/contrib/openy/build/reports/behat

**Comment by osab** [comment]
retest this please

**Comment by osab** [comment]
retest this please

**Comment by alexschedrov** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1446 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1446 |
| Installation process | http://install.openy-dev.ffwua.com/build1446/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1446/

**Pull request closed without merging**
