### PR TITLE
[OYPD-349] Update about menu items to link to /about.

### PR DESCRIPTION
**Pull request by Kerby70**
Jira https://propeople-us.atlassian.net/browse/OYPD-349
D.o https://www.drupal.org/node/2861675

Steps to review
- [x] Visit homepage
- [x] See About link in menus (path is /about)
- [x] Click About link
- [x] See About page

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build768 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build768 |
| Installation process | http://install.openy-dev.ffwua.com/build768/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/768/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build768/profiles/contrib/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build779 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build779 |
| Installation process | http://install.openy-dev.ffwua.com/build779/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/779/

**Review by alexschedrov — APPROVED** [review]
Approved.

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build779/profiles/contrib/openy/build/reports/behat

**Pull request merged**
