### PR TITLE
[CIYMCA-112] Schedules: Error on filtering by category

### PR DESCRIPTION
**Pull request by manachynskyi**
## Steps for reproduce
- [ ] Edit title of some activity, add '/' to title (f.e. http://i.imgur.com/hwW2fQ1.png)
- [ ] Visit schedules page 
- [ ] Set any date with big number of sessions 
- [ ] Choose some category with no result.
- [ ] Choose our modified category (f.e. http://i.imgur.com/O44aUsm.png)

AR: the results table is broken.
ER: Results items or 'no results' message is displayed.

### CODE REVIEW

**Comment by bjwilkins** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by hamrant** [comment]
ok to test

**Review by hamrant — APPROVED** [review]

**Comment by bjwilkins** [comment]
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1939/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1939/

**Comment by bjwilkins** [comment]
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1939/

**Review by afi13 — APPROVED** [review]

**Pull request merged**
