### PR TITLE
[OYPD-280] Color adjustments for camp customizations

### PR DESCRIPTION
**Pull request by david-hernandez**
- [x] Add a camp and landing page associated with the camp.
- [x] Go to Appearance page and change the color settings for camp header color and camp header text color. 
- [x] View camp pages and verify that header background color and text color changes.

screen shot 2017-03-01 at 11 32 08 pm
screen shot 2017-03-01 at 11 31 47 pm

### CODE REVIEW

**Comment by david-hernandez** [comment]
So the color module settings are still a bit of an issue but I realized that I could use the short syntax for the text color so it wouldn't interface with the other items set to be white. Seems to work ok.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build635 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build635 |
| Installation process | http://install.openy-dev.ffwua.com/build635/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/635/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build635/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
@david-hernandez unfortunately this is not something that we need. We should be able to override all items that we have for usual schema.

image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build643 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build643 |
| Installation process | http://install.openy-dev.ffwua.com/build643/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/643/

**Comment by david-hernandez** [comment]
The last commit has some big changes. This largely works and allows the non-camp pages to have separate color overrides. There will be things in some places that don't work out correctly. For example, some buttons don't get overridden correctly, and link text, because their colors are set directly on that element.

This is more a problem with how the theme works than the color module support. This theme is not really componetized, with colors defined in one place. There are colors specified in paragrpahs, blogs, landing pages, etc. We'd have to refactor it to make this work well. I think if we used a custom solution we'd still have the same problem and would have to write a giant css file that overrides everything, which would have to constantly be maintained anytime something was added or changed.

screen shot 2017-03-02 at 10 42 44 am
screen shot 2017-03-02 at 10 42 32 am
screen shot 2017-03-02 at 10 42 52 am
screen shot 2017-03-02 at 10 42 59 am
screen shot 2017-03-02 at 10 42 19 am

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build643/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build651 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build651 |
| Installation process | http://install.openy-dev.ffwua.com/build651/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/651/

**Comment by Sanchiz** [comment]
retest this pleaes

**Comment by Sanchiz** [comment]
retest this please

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build652 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build652 |
| Installation process | http://install.openy-dev.ffwua.com/build652/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/652/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build652/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Regression in camp menu
image

2. Let's add new color options:
- Camp menu background color
- Camp menu text color
image


3. Let's add new color options
- "Branch subheader" - applied to branch page
- "Camp subheader" - applied only on Camp + Camp related LP
image


4. Please set this color schema as default for Lochmara preset
image

**Comment by david-hernandez** [comment]
The last commit should fix all of those. The regression is fixed with the update to include the camp menu settings.

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build656 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build656 |
| Installation process | http://install.openy-dev.ffwua.com/build656/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/656/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build656/profiles/openy/build/reports/behat

**Comment by david-hernandez** [comment]
To add, I did not add the camp colors for the other color profiles. Endeavor and Vivid Violet. Should I copy the same colors as used for Lochmara?

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build665 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build665 |
| Installation process | http://install.openy-dev.ffwua.com/build665/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/665/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build665/profiles/openy/build/reports/behat

**Comment by alexschedrov** [comment]
1. Make sure Camp menu top border has the same color as highlighted item(red on screenshot)
image

2. Make sure the same border also visible on LP page
image

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build678 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build678 |
| Installation process | http://install.openy-dev.ffwua.com/build678/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/678/

**Comment by gundevel** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build678/profiles/openy/build/reports/behat

**Comment by Sanchiz** [comment]
retest this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build682 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build682 |
| Installation process | http://install.openy-dev.ffwua.com/build682/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/682/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build682/profiles/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
