### PR TITLE
[OYPD-474] alt text field needs to be required for all images added to the site.

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
Issue: https://propeople-us.atlassian.net/browse/OYPD-474
Drupal.org issue: https://www.drupal.org/node/2884035

Steps to review:
- [ ] login as admin
- [ ] add image (go to [sitename]/media/add/image)
- [ ] find field Image and click on "Choose File"
- [ ] select any file
- [ ] verify "Alternative text" is required with red star
Please look https://monosnap.com/file/AeOxZz6kWxU53XUZYcPciSG1dzYtHr

### CODE REVIEW

**Comment by gundevel** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1347 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1347 |
| Installation process | http://install.openy-dev.ffwua.com/build1347/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1347/

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1347/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1348 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1348 |
| Installation process | http://install.openy-dev.ffwua.com/build1348/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1348/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://ci.openymca.org/build1348/profiles/contrib/openy/build/reports/behat

**Comment by alexschedrov** [comment]
We can't just make this fields required. Content Editor will never use this form `[sitename]/media/add/image`. Instead of this form, they are using Entity Browser that may be triggered from WYSIWYG or Image field.

image

We have drag & drop there, so, no way to specify Alt field. Let's explore solutions:
1. Somehow add alt field to the drag & drop form
2. Add alt field to the Embed Media form step
image

**Pull request closed without merging**
