### PR TITLE
Fix description in the module openy_node_mbrshp

### PR DESCRIPTION
**Pull request by yasik78**
Issue - https://github.com/ymcatwincities/openy/issues/515

## Steps for review
- [x] Login as admin
- [x] Go to  admin/structure/types/manage/membership/fields/
- [x] check  description for fields and compare with docs. [ https://github.com/ymcatwincities/openy/blob/8.x- 1.x/docs/Content%20structure/Content%20Types/Membership.md ]

### CODE REVIEW

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by yasik78** [comment]
Please test this

**Comment by hamrant** [comment]
test this please

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1516 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1516 |
| Installation process | http://install.openy-dev.ffwua.com/build1516/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1516/

**Review by hamrant — APPROVED** [review]

**Comment by gundevel** [comment]
Behat test results file URL: http://ci.openymca.org/build1516/profiles/contrib/openy/build/reports/behat

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by gundevel** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Pull request merged**
