### PR TITLE
Create Server Requirements.md

### PR DESCRIPTION
**Pull request by podarok**
Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build815 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build815 |
| Installation process | http://install.openy-dev.ffwua.com/build815/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/815/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build815/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build816 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build816 |
| Installation process | http://install.openy-dev.ffwua.com/build816/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/816/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build816/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build817 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build817 |
| Installation process | http://install.openy-dev.ffwua.com/build817/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/817/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build817/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build818 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build818 |
| Installation process | http://install.openy-dev.ffwua.com/build818/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/818/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build818/profiles/contrib/openy/build/reports/behat

**Comment by bjwilkins** [comment]
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build819 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build819 |
| Installation process | http://install.openy-dev.ffwua.com/build819/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/819/

**Comment by bjwilkins** [comment]
Behat test results file URL: http://openy-dev.ffwua.com/build819/profiles/contrib/openy/build/reports/behat

**Review by alexschedrov — APPROVED** [review]
Approved.

**Pull request merged**
